### ISSUE TITLE
Glitch in SMART error log UI

### ISSUE THREAD

**Issue by haoto** [rockstor/rockstor-core#1001]
Another small glitch in the Web UI. The SMART error log is not sorted correctly. I have a failing disk whose error log shows:

Error # Lifetime hours  State   Type    Details
99  3652    active or idle. UNCorrectable Error in Data at LBA = 0x0e606b00 = 241199872
103 3652    active or idle. UNCorrectable Error in Data at LBA = 0x0e606b00 = 241199872
102 3652    active or idle. UNCorrectable Error in Data at LBA = 0x0e606b00 = 241199872
101 3652    active or idle. UNCorrectable Error in Data at LBA = 0x0e606b00 = 241199872
100 3652    active or idle. UNCorrectable Error in Data at LBA = 0x0e606bb8 = 241200056

**Comment by phillxnet** [comment]
@haoto I had a quick look at this but I'm afraid I would need an exact sample of the output you have given in order to test a fix.
Could you execute the following command on a Rockstor console and email the output file to support@rockstor.com.
N.B. the "sda" part must match the current device name for the error log order problem drive.
```
/usr/sbin/smartctl -l error /dev/sda > smart-l-error-order-problem.out
```
so what we need is the "smart-l-error-order-problem.out" file that results. This way any patch to address this ordering can be tested on your rather poorly drives output.

Please also include a link to this issue in your email.

Thanks.

**Comment by phillxnet** [comment]
Having a quick look at this issue by first generating some test data via the script just developed in #1507 as the requested command output from the original reporter was not submitted.

Planning to modify an existing faulty drive's error report to reproduce the observed sorting anomaly locally via the test-mode of src/rockstor/system/smart.py.

**Comment by phillxnet** [comment]
Addressing as part of Looney Bean Milestone.

**Comment by phillxnet** [comment]
OK, I have recreated this issue using a fabricated smartctl -l error output based on a real drive that had over 100 errors logged, the numbers of these errors were then edited to duplicate those of the original posters example, ie 99-103:
```
Error #	Lifetime hours	State	Type	Details
99	1953	active or idle.	UNCorrectable Error in Data	5 sectors at LBA = 0x0078744b = 7894091
103	1953	active or idle.	UNCorrectable Error in Data	5 sectors at LBA = 0x0078744b = 7894091
102	1953	active or idle.	UNCorrectable Error in Data	5 sectors at LBA = 0x0078744b = 7894091
101	1953	active or idle.	UNCorrectable Error in Data	5 sectors at LBA = 0x0078744b = 7894091
100	1953	active or idle.	UNCorrectable Error in Data	5 sectors at LBA = 0x0078744b = 7894091
```

**Comment by phillxnet** [comment]
By switching from lexical to integer sort we have the following ordering for the same test error log data:
```
Error #	Lifetime hours	State	Type	Details
103	1953	active or idle.	UNCorrectable Error in Data	5 sectors at LBA = 0x0078744b = 7894091
102	1953	active or idle.	UNCorrectable Error in Data	5 sectors at LBA = 0x0078744b = 7894091
101	1953	active or idle.	UNCorrectable Error in Data	5 sectors at LBA = 0x0078744b = 7894091
100	1953	active or idle.	UNCorrectable Error in Data	5 sectors at LBA = 0x0078744b = 7894091
99	1953	active or idle.	UNCorrectable Error in Data	5 sectors at LBA = 0x0078744b = 7894091
```
