### ISSUE TITLE
No response from IP address

### ISSUE THREAD

**Issue by huskywulf** [rockstor/rockstor-core#1006]
I am running 3.8-9 on a HP Gen 8 Microserver. I installed the update through the stable update channel.

I added a third disk to my pool last night, ran a balance which failed. Now whenever the server had been running for a short period of time (less than 2hrs) the IP address that the server has fails to respond to anything. I cannot browse to it through a browser and I cannot ping it. Only way to get it back up again is to reboot the server. 

Attached is the error from the failed balance. 
![error](https://cloud.githubusercontent.com/assets/11057740/11014669/a9685f08-8538-11e5-8cea-3ca07b49fc1b.jpg)

**Comment by schakrava** [comment]
Do you have terminal access to the system? If so, please login and see if there are any errors. But it sounds more like a kernel panic may have happened. Either way, the terminal window should have some helpful information.

**Comment by FroggyFlox** [comment]
Closing as this required user feedback but has now remained opened for quite some time. Due to its age, we can safely assume that this issue no longer applies.
