### ISSUE TITLE
Samba service doesn’t start automatically after reboot

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-core#1007]
http://forum.rockstor.com/t/samba-service-doesnt-start-automatically-after-reboot/670

**Comment by phillxnet** [comment]
I wonder if the recent problems with service status could be related to the following commit:-
https://github.com/schakrava/rockstor-core/commit/7b41872d69a9d1421386a27a36cfd5bf87790683
haven't looked into it but saw this commit go in and remembered when the service status reports came in.
ie in src/rockstor/system/services.py we translate these service names for their related system service name.
prep_db.py looks to be good for the previously hardcoded "services" list minus some depricated ones.

Also the name change / mix from winbind to active-directory re:- http://forum.rockstor.com/t/why-are-sftp-and-active-directory-enabled-now/658
In the previously hardcoded list in data_collector.py there was no wins or active-directory but now there will be via prep_db.py.
Also "return init_service_op(service_name, 'status', throw=False)" as return of service_status in services.py checks against another hardcoded list:-
supported_services = ('nfs', 'smb', 'sshd', 'ypbind', 'rpcbind', 'ntpd',
                          'nslcd', 'netatalk', 'snmpd', 'docker',
                          'smartd', 'nut-server')
and from what I can tell we silence the exception that might tell us of missing services in our catch all call at the end of service_status in services.

Sorry this is probably mostly noise but I thinks there's something here.

**Comment by phillxnet** [comment]
Although this issue seems to have been fixed as apparently confirmed by
@Yoshi in the following forum post:-
http://forum.rockstor.com/t/samba-service-doesnt-start-automatically-after-reboot/670/5
I think at least some of the symptoms have an unrelated additional cause.
I have opened another issue #1043 to more specifically state the rare additional cause of the symptoms in this issue.

**Comment by schakrava** [comment]
Just spent some time investigating this issue. The original issue as described in the title is fixed by #1026 . Samba was failing because of a failed dependency(rockstor-bootstrap unit).

@phillxnet the other observations you raised in your comment are either addressed already or not valid anymore as confirmed by my testing today. I'll close this issue.

**Comment by phillxnet** [comment]
@schakrava Yes I agree, hence my opening #1043 which only shares some of the symptoms and yes not down to samba not starting (as in title) but failed mounts. My mistake.
