### ISSUE TITLE
Improve El Capitan compatibility

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#1009]
During the preparation of https://github.com/rockstor/rockstor-doc/issues/100 I discovered difficulties re Time Capsule backups to Rockstor from El Capitan (OSX 10.11.1) I believe I have a fix for this and am working on a pull request under this issue. Testing of the fix is underway but I have not yet prepared the patch set.
I am now working on this pull request.

**Comment by phillxnet** [comment]
I will have to back burner this one for the time being as more pressing matters and my supposed "fix" turned out to be a bit of superstitious learning. Also outstanding issues with multiple NAS technologies re El Capitan:-
https://discussions.apple.com/thread/7255721?start=30&tstart=0
Some older NAS systems suffer from an authentication issue but from netatalk logging I see we are getting successful DHX2 (Diffy-Hellman Key Exchange 2) so that isn't the problem.
logging was increased to see this via the following line in /etc/netatalk/afp.conf

log level = default:debug6

Successful connection was only semi reliable achieved via the Command+K then afp://user@rockstor
then authenticating; however this would only work if Finder had not first been used to browse to rockstor, and if this was the first attempt from a boot. This is consistent behaviour with that found in the  linked apple hosted discussion forum.

**Comment by iFloris** [comment]
We have this problem with other NAS devices as well. From my testing, I have found that using the auto browser ._afpovertcp._tcp.local will try to use IPv6 but will sometimes switch to v4, even mid transfer. Using connect to servers and a FQDN works much better. On my macs, I have been using an app (Mountain by Appgineers) to manage the mounts and this seems to help. To me, it does not seem to be a Rockstor related problem but rather zeroconf weirdness.

**Comment by phillxnet** [comment]
@iFloris Thanks for chipping in here. I think now as you suggest this isn't really actionable on Rockstor's part. Thanks for the work around suggestion, it may well help others who stumble across this.

Closing as no specifically Rockstor related.
