### ISSUE TITLE
GitLab RockOn should be added

### ISSUE THREAD

**Issue by devonwarren** [rockstor/rockstor-core#1025]
I think it would be great to have gitlab running on my NAS keeping all my working source code safe.

Docker instructions are available at: http://doc.gitlab.com/omnibus/docker/

**Comment by devonwarren** [comment]
I added the following code to the storageadmin/views/rockon_json.py file which follows the other rockons formats to my knowledge however it is still not showing up in the webui as an option. Wondering if anyone would know what I need to do to refresh that?

```
gitlab = {'ui': {'slug': 'web',
                   'https': True,},
            'containers': {'gitlab': {'image': 'gitlab/gitlab-ce',
                                        'ports': {
                                                '80': {
                                                   'ui': True,
                                                   'host_default': 8080,
                                                   'protocol': 'tcp',
                                                   'label': 'HTTP WebUI port',
                                                   'description': 'GitLab WebUI port. Suggested default: 8080',},
                                                '443': {
                                                   'ui': True,
                                                   'host_default': 8443,
                                                   'protocol': 'tcp',
                                                   'label': 'HTTPS WebUI port',
                                                   'description': 'GitLab WebUI port. Suggested default: 8443',},
                                                '22': {
                                                   'ui': True,
                                                   'host_default': 2222,
                                                   'protocol': 'tcp',
                                                   'label': 'SSH Gitlab port',
                                                   'description': 'GitLab SSH port. Suggested default: 2222',}
                                                },
                                        'volumes': {
                                                  '/var/opt/gitlab': {
                                                     'description': 'Choose a Share for GitLab repositories. Eg: create a Share called gitlab-repos for this purpose alone.',
                                                     'label': 'Repository Storage',
                                                     'min_size': 1073741824,},
                                                  '/etc/gitlab': {
                                                     'description': 'Choose a Share for GitLab configuration. Eg: create a Share called gitlab-config for this purpose alone.',
                                                     'label': 'Config Storage',},
                                                  },
                                        'launch_order': 1,},
                              },
            'description': 'Git repository hosting and collaboration',
            'website': 'https://about.gitlab.com/',
            'icon': 'https://about.gitlab.com/images/wordmark.png',
            'more_info': '<p>Default username for your GitLab UI is<code>root</code>and password is<code>5iveL!fe</code></p>',}
```

**Comment by phillxnet** [comment]
@devonwarren Thanks, yes I too would like this and have added it to a Rock-on requests thread in the Rockstor forum, prompted by your issue opening:-
http://forum.rockstor.com/t/rock-on-requests/41/51
I have referenced this issue to tie the two together.

Sorry but I'm just not familiar enough with this side of things to help with why your above implementation doesn't work but I do know there are plans to make running generic / possibly docker hub images work via a re-working of what is currently Rockstor's first draft of docker image support via the current Rock-on system.

The plans / RFC thread for the next implementation of Rock-ons is detailed in a wiki post ["Next phase of Rock-on framework improvements"](http://forum.rockstor.com/t/next-phase-of-rock-on-framework-improvements/417) in the Rockstor forum.

Please also contribute to these threads with any further ideas.

Thanks again for making a start on this one. Hopefully someone else can chip in with something more concrete to get GitLab available as a Rockstor's  Rock-on. Great idea.

**Comment by schakrava** [comment]
Thanks for the comment @phillxnet and @devonwarren , this is definitely happening and hopefully by 3.8-11 release. I'll circle back when things are ready for you to make Rock-on contributions.

**Comment by phillxnet** [comment]
@devonwarren As per @schakrava self fulfilling prophecy it is now considerably easier to contribute Rock-ons. As of 3.8.11 there is now a rockstor-registry:-
https://github.com/rockstor/rockon-registry
This is the location for official Rockstor Rock-on json definition files and systems pick up their definitions from this repo.
The README.md there has good instructions on creating a Rock-on and there is also a facility to pop  the proposed json file into a local directory to have it show up in the installable Rock-ons list.
/opt/rockstor/rockons-metastore/[app].json
This is a very new feature but all the better to have more people testing it out.

Just to let you know given that you have almost done all that is required already for the GitLab Rock-on.

@schakrava Not sure if I've covered everything there?

**Comment by rcastberg** [comment]
Installed this json
[gitlab-rc.json.txt](https://github.com/rockstor/rockstor-core/files/121906/gitlab-rc.json.txt)
 and tested, seems to be working fine, based on template posted above.

**Comment by schakrava** [comment]
@devonwarren and @rcastberg you rock! This is definitely happening. I want to use gitlab in production as a Rock-on. Would you be interested in opening a pull request for this issue? I'll get to it myself eventually, but would love to give you credit for it. If interested, please open the pr here: https://github.com/rockstor/rockon-registry

@rcastberg I tried your json and have some minor feedback.

1. comma missing at the end of line 12.
2. Is there a reason for not adding port 443? seems like a good idea to do so.
3. official docs suggest a separate volume for logs, which seems like a good idea as well.

**Comment by rcastbergw** [comment]
Submitted a pull request. 
Port 443 isn't enabled by default but added it anyway.
Added a logs volume.

**Comment by schakrava** [comment]
Thanks to @rcastbergw and everyone that participated in this issue. I just pushed gitlab rock-on for everyone. Looking forward to using it!
