### ISSUE TITLE
Support Jumbo frames(larger MTU) in network config

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-core#1031]

**Comment by MFlyer** [comment]
@schakrava #1044 dupe and that one already on Pinnacles roadmap, can we remove this? :)

M.

**Comment by phillxnet** [comment]
I second the closure of this issue as a duplicate given #1044, as @MFlyer states it's already in a more recent milestone and has a link to a relevant forum post, rendering this issue redundant with less info.
