### ISSUE TITLE
Email Alert New Install (Postfix Issue)

### ISSUE THREAD

**Issue by djeraseit** [rockstor/rockstor-core#1038]
exception: Error running a command. cmd = ['/usr/bin/systemctl', 'restart', 'postfix']. rc = 1. stdout = ['']. stderr = ["Job for postfix.service failed. See 'systemctl status postfix.service' and 'journalctl -xn' for details.", '']
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/rest_framework_custom/generic_view.py", line 40, in _handle_exception
    yield
  File "/opt/rockstor/src/rockstor/storageadmin/views/email_client.py", line 150, in post
    systemctl('postfix', 'restart')
  File "/opt/rockstor/src/rockstor/system/services.py", line 62, in systemctl
    return run_command([SYSTEMCTL_BIN, switch, service_name])
  File "/opt/rockstor/src/rockstor/system/osi.py", line 84, in run_command
    raise CommandException(cmd, out, err, rc)
CommandException: Error running a command. cmd = ['/usr/bin/systemctl', 'restart', 'postfix']. rc = 1. stdout = ['']. stderr = ["Job for postfix.service failed. See 'systemctl status postfix.service' and 'journalctl -xn' for details.", '']

**Comment by phillxnet** [comment]
Thanks for reporting, could you try updating on our testing channel to see if this still occurs for you. Also please give the steps that led to this.
Also please check that the configuration is valid ie as documented in http://rockstor.com/docs/email_setup.html 

If still no joy then please paste here the output of the following commands:-
systemctl status postfix.service
and
journalctl -xn
executed in a ssh terminal logged in as root.

Thanks.

**Comment by djeraseit** [comment]
I see this in the gunicorn.log file:

ImproperlyConfigured: Error importing module django.core.mail.backends.smtp: "No module named backends.smtp"

**Comment by schakrava** [comment]
I am unable to reproduce this problem. If you are able to, please also provide the output of journalctl -xn and systemctl status -l postfix as requested by @phillxnet above. Feel free to reopen with reproducible steps.
