### ISSUE TITLE
update problems

### ISSUE THREAD

**Issue by bitchecker** [rockstor/rockstor-core#1053]
I've installed Rockstor succesfully but when i try to update it i receive the following error:
```
Error: Package: 4: netatalk-3.1.7-0.1.el7.centos.x86_64 (@ anaconda / 3)
             Requires: libtracker-SPARQL-0.16.so.0 () (64bit)
             Cleanup in progress: tracker-0.16.2-11.el7.x86_64 (@ anaconda / 3)
                 libtracker-SPARQL-0.16.so.0 () (64bit)
             Updated by: tracker-1.2.6-3.el7.x86_64 (basic)
                ~ libtracker-SPARQL-1.0.so.0 () (64bit)
  You can try using --skip-broken to work around the problem
  Try running: rpm -Va --nofiles --nodigest
```

Running version: 
```
Linux rockstor 4.2.5-1.el7.elrepo.x86_64 #1 SMP Tue Oct 27 12:32:38 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by phillxnet** [comment]
@bitchecker Thanks for reporting this and yes sorry about that, a very recent issue and I am hoping for it to be sorted later in the US day or very soon there after.

Could you state if you are on the stable or testing channel of updates.

There is also a forum post that highlights this exact issue by @herbert :-
http://forum.rockstor.com/t/dev-log-for-upcoming-3-8-11/792

**Comment by bitchecker** [comment]
@phillxnet i've updated from CLI so i think (and hope) that i'm on stable channel

**Comment by phillxnet** [comment]
@bitchecker  Thanks for the quick response, the update channel selection is done via the Web-UI on the System - Software Update page. There is documentation about the available channels "Update Channels" in the docs:-
http://rockstor.com/docs/update-channels/update_channels.html
Currently I don't think the testing channel suffers from the problem you reported in this issue which has occurred just in the last few hours. However I'm confident this is just a blip and will be sorted in the next few hours as it looks like a dependency issue where 2 repos have fallen out of kilter momentarily.

**Comment by bitchecker** [comment]
@phillxnet on WebUI you can choose the channel but if you click on "update now", system will ask you subscription so i've run it via CLI as usual for unix systems.

**Comment by phillxnet** [comment]
@bitchecker If you first select which channel subscription you would prefer then you may well be away. Rockstor is aiming to be an appliance type system based on CentOS so is not typical of linux command line only server systems as it tries to make things more accessible via the WebUI. However there is effort to try and maintain all that we can of CentOS. I would suggest that you for the time being select the testing channel subscription and see how you get on. The doc I referenced explains the difference and hopefully helps to establish what we are trying to do via the channels.

Note that there is also an active forum where there are many experience and knowledgeable Rockstor users / contributors that may well be able to help with issues that you may have.

http://forum.rockstor.com/

This issue has been linked to from the forums to cover the very recent dependency issue.

Hope this helps.

**Comment by bitchecker** [comment]
so the only available channel without subscription is testing?

**Comment by phillxnet** [comment]
@bitchecker This issue was as hoped and expected fixed a few hours after our last communication. The cause and fix are detailed by @schakrava in the above linked forum post repeated here for convenience:-
http://forum.rockstor.com/t/dev-log-for-upcoming-3-8-11/792/6
Fix also confirmed by @herbert on the forum in the same thread.

@schakrava I take it this issue is now due for closure. @bitchecker Thanks again for you prompt reporting.
