### ISSUE TITLE
rockstor web interface accesses insecure (non-SSL) file

### ISSUE THREAD

**Issue by roweryan** [rockstor/rockstor-core#1055]
This non-SSL favicon file is accessed:

    http://rockstor.com/media/images/ico/favicon.ico

**Comment by roweryan** [comment]
Gives a warning on Firefox about mixed content being blocked.

**Comment by roweryan** [comment]
Could this be fixed? Thanks!

**Comment by schakrava** [comment]
Fixed by #1244
