### ISSUE TITLE
rockstor-bootstrap.service: OauthApp matching query does not exist

### ISSUE THREAD

**Issue by sfranzen** [rockstor/rockstor-core#1066]
After a recent upgrade to rockstor v3.8-10.07, I'm now left with a failing rockstor-bootstrap.service as well as an inaccessible web interface ("Internal Server Error"); both may be related of course but I'm not sure. I only have SSH access at the moment.

The systemctl status for the bootstrap service mentions the following (14 other identical errors not shown):
```
Dec 26 19:17:15 rockstor bootstrap[4523]: Exception occured while bootstrapping. This could be because rockstor.service is still starting up. will wait 2 seconds and try again. Exception: OauthApp matching query does not exist.
Dec 26 19:17:15 rockstor bootstrap[4523]: Max attempts(15) reached. Connection errors persist. Failed to bootstrap. Error: OauthApp matching query does not exist.
```
Note that rockstor.service itself is active and running at this point.

Nginx appears to be running normally as well, but serves an error page instead of the UI.
```
[root@rockstor ~]# pgrep -a nginx
4533 nginx: master process /usr/sbin/nginx -c /opt/rockstor/etc/nginx/nginx.conf
4537 nginx: worker process
4538 nginx: worker process
```

Any ideas on how to resolve this? Please let me know if I can supply more detailed logs to assist.

**Comment by schakrava** [comment]
The error in bootstrap is strange becuase it's only expected prior to initial setup. None of the screens in the UI are functional? My wild guess at this point is that something is wrong with the db. We can investigate more if you send logs(/opt/rockstor/var/log) to support@rockstor.com

I'd also be curious to see the output of "systemctl status -l postgresql rockstor-pre rockstor rockstor-bootstrap"

**Comment by sfranzen** [comment]
Thank you for the response. After upgrading to rockstor 3.8-10.10 and restarting rockstor.service, the web interface thankfully works again, but rockstor-bootstrap and any dependent services do not. I forgot to note in my original post that this issue started occurring after a failed system upgrade (from the UI), which left behind a set of duplicate packages I cleaned up by hand.

I will shortly send the requested logs and systemctl output to support@rockstor.com.

**Comment by K0r4nd** [comment]
Hello,

are there any updates regarding this problem? I think I've a similar issue with a blank new installation of rockstar 3.8-11. After successful installation, I can access the webpage for the initial setup for user credentials but when accessing the setup page there are already error messages in the rockstar.log. (after setup the Web-UI always responds with 500 errors, with similar errorMessages)

`[25/Feb/2016 23:42:49] DEBUG [smart_manager.data_collector:395] Listening on port http://127.0.0.1:8080 and on port 10843 (flash policy server)
[25/Feb/2016 23:44:56] ERROR [smart_manager.data_collector:340] Failed to update disk state.. exception: OauthApp matching query does not exist.
[25/Feb/2016 23:44:56] ERROR [smart_manager.data_collector:340] Failed to update pool state.. exception: OauthApp matching query does not exist.
[25/Feb/2016 23:44:56] ERROR [smart_manager.data_collector:340] Failed to update share state.. exception: OauthApp matching query does not exist.
[25/Feb/2016 23:44:56] ERROR [smart_manager.data_collector:340] Failed to update snapshot state.. exception: OauthApp matching query does not exist.
[25/Feb/2016 23:44:56] ERROR [smart_manager.data_collector:320] failed to update Rock-on metadata. low-level exception: OauthApp matching query does not exist.`

I've checked the db and both (smartdb and storageadmin) exist. (including tables)

Do you have an idea what could be the problem? I've already retried the initrock script but this throws an error during db creation.

**Comment by sfranzen** [comment]
I've also inspected the tables more carefully, using `/opt/rockstor/bin/django dbshell`. There seem to be no entries in the storageadmin_oauthapp table:

```
storageadmin=# TABLE storageadmin_oauthapp;
 id | application_id | name | user_id
----+----------------+------+---------
(0 rows)
```

How to repair this?

**Comment by sfranzen** [comment]
One more test result: after re-initialising Rockstor with `/opt/rockstor/bin/initrock`, the oauthapp table has one entry and things appear to be in working order again:
```
storageadmin=# TABLE storageadmin_oauthapp;
 id | application_id |  name  | user_id
----+----------------+--------+---------
  1 |              1 | cliapp |       1
(1 row)
```
After stopping a stuck ztask process, I am now also again able to install the docker add-ons.

**Comment by sfranzen** [comment]
A further note: upon updating to version 3.8-13.07, the Oauthapp issue cropped up again, with services being unable to start and also messages identical to @K0r4nd's in rockstor.log. I'm not sure how the update process manages to remove cliapp from the table, but I did figure out that it is accessible through System > Access Keys in the web interface. Using this to add a new key for "cliapp" resolves the issue again, so @K0r4nd you could try this as a workaround.

**Comment by schakrava** [comment]
cliapp getting deleted by Rockstor is too hard to believe. But your workaround is spot on @sfranzen . I am unable to reproduce this problem. We can go about fixing it if we have reproducible steps. Please feel free to re-open it with reproducible steps.
