### ISSUE TITLE
SSL certificate length

### ISSUE THREAD

**Issue by corna** [rockstor/rockstor-core#1067]
If I try to use a SSL certificate longer than 2048 characters this error appears:

     Error!

     value too long for type character varying(2048)

Unfortunately my certificate (intermediate chained with my certificate) is ~4000 bytes, so I can't use it.
Can you please increase the maximum certificate length? Intermediate certificates are very common with trusted CAs.

**Comment by schakrava** [comment]
Thanks @corna . It's a minor change, I'll try to push the change soon.

**Comment by corna** [comment]
Thanks
