### ISSUE TITLE
Too many kernels?

### ISSUE THREAD

**Issue by roweryan** [rockstor/rockstor-core#1068]
I have a lot of kernels in my grub list. How many should there be?

**Comment by roweryan** [comment]
````
# rpm -q kernel-ml
kernel-ml-4.1.0-1.el7.elrepo.x86_64
kernel-ml-4.2.2-1.el7.elrepo.x86_64
kernel-ml-4.2.5-1.el7.elrepo.x86_64
kernel-ml-4.3.3-1.el7.elrepo.x86_64
````

**Comment by phillxnet** [comment]
@roweryan This is normal as updated kernels get added, this shouldn't be a problem though. If you really don't want some earlier ones there then you can always uninstall them like you would any other rpm.

**Comment by roweryan** [comment]
How many kernels does rockstor keep?

**Comment by schakrava** [comment]
Currently, we don't delete any old kernels from the system. Perhaps we should cap it at 10 or something?

**Comment by k0nsl** [comment]
@schakrava:
I think a cap at five excess kernels would be fine. That's just my opinion ;)

**Comment by roweryan** [comment]
kernels are big. /boot is normally too small. kernels installed via yum can be limited to a number you choose, maybe we could use that mechanism. More than 5 is too many I think.

**Comment by phillxnet** [comment]
@roweryan Yes, I was forgetting the /boot partition being separate for some reason.
The default install makes a 477 MB /boot (ext4).
From a quick look it appears each kernel is taking an additional 30MB or so on /boot and with the 4 listed kernels installed we have:-
```
df -h /boot/
Filesystem      Size  Used Avail Use% Mounted on
/dev/sdd1       477M  223M  225M  50% /boot
```
So as an estimate there is room for another 6 kernels (ie 10 total) so I think we should definitely limit the total kernel count to no more than 10 and I personally think 5 is about right for total maximum installed kernels for this /boot size. There is then a good bit of head room as well.

**Comment by schakrava** [comment]
Nice work gentlemen. Looks like 5 it is! I'll get to this soon'ish, unless @phillxnet or someone else beats me to it!

**Comment by ygd2013520** [comment]
@schakrava  i download the Rockstor 3.8-10.ios, when i complete it ,i find in /usr/src/kernel/ do not have source code ? normally ,it have a source code name "4.2.5-1.el7.elrepo.x86_64" , right????

**Comment by phillxnet** [comment]
@ygd2013520 Hello and welcome. I am linking to your forum post as that is a more appropriate place to address this query:-
http://forum.rockstor.com/t/rockstor-kernel-problem/946/1
