### ISSUE TITLE
Unbootable since update to 3.8-10.07

### ISSUE THREAD

**Issue by roweryan** [rockstor/rockstor-core#1069]
rockstor-3.8-10.07.x86_64 kernel-ml-4.3.3-1.el7.elrepo.x86_64

More info soon.

**Comment by roweryan** [comment]
![rockstor-crash](https://cloud.githubusercontent.com/assets/14888564/12011801/08e896b0-acde-11e5-894c-242126057450.jpg)

**Comment by phillxnet** [comment]
@roweryan All I can suggest is for you to select the last working kernel until Rockstor updates again. I know the 4.4 is due out soon and so presumably @schakrava will adopt that as soon as is practical.
And to avoid Rockstor's mechanism of re-setting to the newest kernel on each boot I'l take a look at the following forum post:-
http://forum.rockstor.com/t/override-kernel-autoboot/798

**Comment by roweryan** [comment]
I removed the non-working kernel for now.

**Comment by roweryan** [comment]
Any timeline for a new kernel?

**Comment by schakrava** [comment]
3.8-11 is now out and it uses 4.3.3. We'll move to 4.4 no sooner than 3.8-13 IMO. Please stay tuned and keep using the kernel that works for you in the meantime.

**Comment by roweryan** [comment]
4.3.3 doesn't work for me either.

**Comment by roweryan** [comment]
The problem is present in all kernels greater than kernel-ml-4.2.5-1.el7, less than 4.5.0-0.rc1.el7.elrepo.x86_64 and affects users booting from a usb stick.

See the kernel.org change for this bug here: https://git.kernel.org/cgit/linux/kernel/git/mkp/scsi.git/commit/?h=4.5/scsi-queue&id=221255aee67ec1c752001080aafec0c4e9390d95

The elrepo people are great. https://github.com/elrepo/packages/issues/135

**Comment by roweryan** [comment]
Please could you reopen this bug since the problem is still present in the current version of the kernel shipped with rockstor. Thanks!

**Comment by schakrava** [comment]
Really nice catch @roweryan, love the thorough comments on the elrepo repo.

We need to pause and think if we should fall back to 4.2.x kernel given there are some users using Rockstor with usb as a boot drive. Thanks for your testing.

**Comment by roweryan** [comment]
or upgrade to 4.5.x asap :)

**Comment by MFlyer** [comment]
To @schakrava and @phillxnet : IMO this issue can be closed and reopened (if necessary) because now we're on kernel 4.5.x-4.6.x and Rockstor in 3.8-14 (no more 3.8-10)

**Comment by schakrava** [comment]
Agreed @MFlyer. Thanks!
