### ISSUE TITLE
Service Docker: docker wrapper not working as expected

### ISSUE THREAD

**Issue by pecigonzalo** [rockstor/rockstor-core#1081]
The docker wrapper scripts seems to exits before docker daemon finishes starting causing issues with services depending on docker.service.

I also think using the wrapper is not correct and breaks the plug n play nature of docker/linux in general. It might be easier to store config variables in /etc/systemd/system/docker.service.d to pass environment variables.

The docker.service should look like 

```
[Unit]
Description=Docker Application Container Engine
Documentation=http://docs.docker.com
After=network.target docker.socket rockstor-bootstrap.service
Requires=docker.socket rockstor-bootstrap.service

[Service]
ExecStartPre=mount -t btrfs -o subvol=Docker /dev/sda /mnt2/Docker
ExecStart=/usr/bin/docker daemon -s btrfs -g /mnt2/Docker
MountFlags=slave
LimitNOFILE=1048576
LimitNPROC=1048576
LimitCORE=infinity

[Install]
WantedBy=multi-user.target

```

given:
- /dev/sda is the first device of the BTRFS system 
- Docker is the name of the subvolume to be used by docker
- /mnt2/Docker is the mount path ( i dont understand why we are even using mnt2 and not just mnt )

Alternatively have a ExecStartPre in docker.service.d that collects this parameters from rockstor.
Another option would be to have the rockstor.service file do the mounting etc and setting the parameter Before= on it . This way we can have rockstor mount docker no a pre known location so we dont need to pass variables to docker.service

The alternative (IMHO not correct way) would be to continue to use the wrapper but ensure its running properly.

**Comment by schakrava** [comment]
Thanks for adding very useful content @pecigonzalo! I've assigned this issue to the next milestone.

**Comment by FroggyFlox** [comment]
@phillxnet , I believe we can close this issue now that we no longer use a docker-wrapper since #2090.

**Comment by phillxnet** [comment]
@FroggyFlox Cheers for the house keeping hint. Closing as suggested.
