### ISSUE TITLE
raw smart error logs missing

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#1084]
Minor regression in 3.8-10.15. In 3.8-10.12 the raw smart error log was displayed as a section below the summary of errors in the "Error Logs" tab. This is important as it is the only place where some smart errors are currently visible ie some scsi style reporting such as that from the lsi controller output used to address issue #997 which was previously fixed by pr #1076.

**Comment by phillxnet** [comment]
I'm having a quick look into this now.

**Comment by phillxnet** [comment]
Temporarily addressing a more important fix, should be back on this one soon.

**Comment by phillxnet** [comment]
I will try and continue with this one tomorrow (UK). Mainly disadvantages scsi type reports that require the raw error log to be visible as the current summary does not parse the output due to there being few standards in it's presentation, unlike that found on SATA drives.

**Comment by phillxnet** [comment]
Looking at this again today.

**Comment by phillxnet** [comment]
With above patches to 3.8-10.15 the function seen in 3.8-10.12 is restored.
ie:-
scsi smart Error Log displays as follows (screen grab):-
( N.B. this is using the internal testmode to read from submitted smart dumps from an lsi9207-8i )
![scsi-style-errorlog-reporting](https://cloud.githubusercontent.com/assets/2521585/12242594/f4e93fd8-b891-11e5-9010-7bb55dcfd504.png)

sata smart Error Logs tab displays as follows (screen grab):-
( From a rather sickly drive that has something to report here )
![sata-style-errorlog-reporting](https://cloud.githubusercontent.com/assets/2521585/12242602/fc5d1ee2-b891-11e5-84b2-a44f9c3c45f1.png)

**Comment by schakrava** [comment]
Fixed by #1091
