### ISSUE TITLE
minor regression in fake serial ui logic

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#1086]
Prior to 3.8-10.15 we tested for our internal fake-serial drive flag and indicated it to be unreliable as we also do with null, empty, or serial == diskName however as of merge (pr) #1045 we also have to test for serial.length == 48 to catch our new flag mechanism of a 48 char fake-serial-uuid-derived-char-string.

See commit in above referenced pr:-
https://github.com/phillxnet/rockstor-core/commit/ce733be859141d32954b2af88f543b8ec601fe9a

From an initial look this seems like a minor change to line 208 in file :-
/src/rockstor/storageadmin/static/storageadmin/js/views/disks.js
is required as the display logic is now handled by a handlebar helper "display_disks_tbody".

**Comment by phillxnet** [comment]
I am about to address this issue and should have a pull / merge request ready shortly.

**Comment by phillxnet** [comment]
Before and after above minor changes:-
![fake-serial-displayed](https://cloud.githubusercontent.com/assets/2521585/12223054/9542383c-b7c4-11e5-8b87-6fe8be0035f5.png)

![warning-message-displayed](https://cloud.githubusercontent.com/assets/2521585/12223057/9a8eeb28-b7c4-11e5-9664-901cfb64510d.png)

**Comment by schakrava** [comment]
Thank you @phillxnet! Really admire your ownership and quick turnaround on this one.

**Comment by phillxnet** [comment]
@schakrava Cheers.
