### ISSUE TITLE
Installed Rockstor with custom partition-table - can not scan for disks

### ISSUE THREAD

**Issue by joafri** [rockstor/rockstor-core#1089]
Hi,

Installed rockstor with below partition table to be able to extend /var and so on manually just as we do at work with LVM. Thou now I cannot add new disks/storagepools in the webgui.

> [root@fekete ~]# df -h
> Filsystem      Storlek Använt Ledigt Anv% Monterat på
> devtmpfs          4,8G      0   4,8G   0% /dev
> tmpfs             4,8G      0   4,8G   0% /dev/shm
> tmpfs             4,8G    49M   4,8G   1% /run
> tmpfs             4,8G      0   4,8G   0% /sys/fs/cgroup
> /dev/sda2         9,4G   184M   8,3G   3% /
> /dev/sda5         9,4G   1,5G   7,1G  17% /usr
> /dev/sda3         9,4G    17M   8,4G   1% /home
> /dev/sda8          28G   274M    26G   2% /var
> /dev/sda7        1008M   113M   845M  12% /boot
> tmpfs             975M   4,0K   975M   1% /run/user/0
> /dev/sda5         9,4G   1,5G   7,1G  17% /mnt2/rockstor_rockstor
> [root@fekete ~]# cat /etc/fstab 
> UUID=919c448b-48a7-4061-8e9b-416c927b99a6 /                       btrfs   subvol=root     0 0
> UUID=5692ac4d-99fc-4504-bbb3-f094f2632ff0 /boot                   ext2    defaults        1 2
> UUID=d2e9993e-956b-43ce-b9f3-7174dd697692 /home                   btrfs   subvol=home     0 0
> UUID=3a754201-7f2d-4ab8-b08c-b7062b65b189 /usr                    btrfs   subvol=usr      0 0
> UUID=88f6ea01-7fff-49aa-bf7d-f8323ed8bb50 /var                    btrfs   subvol=var      0 0
> UUID=5de03f12-9c3c-4afa-af7f-da2f3f67bc48 swap                    swap    defaults        0 0
> [root@fekete ~]# cat /etc/mtab
> sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
> proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
> devtmpfs /dev devtmpfs rw,nosuid,size=4978616k,nr_inodes=1244654,mode=755 0 0
> securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
> tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
> devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
> tmpfs /run tmpfs rw,nosuid,nodev,mode=755 0 0
> tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,mode=755 0 0
> cgroup /sys/fs/cgroup/systemd cgroup >rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups->agent,name=systemd 0 0
> pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
> cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
> cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
> cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
> cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
> cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids 0 0
> cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
> cgroup /sys/fs/cgroup/hugetlb cgroup rw,nosuid,nodev,noexec,relatime,hugetlb 0 0
> cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
> cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset 0 0
> cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
> configfs /sys/kernel/config configfs rw,relatime 0 0
> /dev/sda2 / btrfs rw,relatime,space_cache,subvolid=257,subvol=/root 0 0
> /dev/sda5 /usr btrfs rw,relatime,space_cache,subvolid=257,subvol=/usr 0 0
> systemd-1 /proc/sys/fs/binfmt_misc autofs >rw,relatime,fd=29,pgrp=1,timeout=300,minproto=5,maxproto=5,direct 0 0
> mqueue /dev/mqueue mqueue rw,relatime 0 0
> debugfs /sys/kernel/debug debugfs rw,relatime 0 0
> hugetlbfs /dev/hugepages hugetlbfs rw,relatime 0 0
> nfsd /proc/fs/nfsd nfsd rw,relatime 0 0
> /dev/sda3 /home btrfs rw,relatime,space_cache,subvolid=257,subvol=/home 0 0
> /dev/sda8 /var btrfs rw,relatime,space_cache,subvolid=257,subvol=/var 0 0
> sunrpc /var/lib/nfs/rpc_pipefs rpc_pipefs rw,relatime 0 0
> /dev/sda7 /boot ext2 rw,relatime 0 0
> tmpfs /run/user/0 tmpfs rw,nosuid,nodev,relatime,size=997896k,mode=700 0 0
> /dev/sda5 /mnt2/rockstor_rockstor btrfs rw,relatime,space_cache,subvolid=5,subvol=/ 0 0

Errormessage:

> duplicate key value violates unique constraint "storageadmin_pool_name_key" DETAIL: Key (name)=(rockstor_rockstor) already exists.

**Comment by phillxnet** [comment]
@joafri and @schakrava 
I propose this issue be closed as "LVM not supported".

**Comment by phillxnet** [comment]
Closing as LVM not supported.
