### ISSUE TITLE
Share Access control issue found on latest unstable/test updates

### ISSUE THREAD

**Issue by parker1c** [rockstor/rockstor-core#1100]
I believe I found some bug with "Access control" in a share a user makes and then edits.  I can repeat the issue as I wasn't sure what broke until after some testing.
 
Symptoms:  When editing a created share's permissions,(in the webgui) for example: enabling read/write/execute for all 3, owner/group/other (for example 777). Upon saving, it then goes to read only for owner/group/other (444), despite selecting other options.

Default install of 3.8-10(Linux: 4.2.5-1.el7.elrepo.x86_64) ISO does not exhibit this behaviour.  Upon activating Testing updates, and installing/rebooting (Rockstor 3.8-10.17) (Linux: 4.3.3-1.el7.elrepo.x86_64), the above symptoms now arrive.

Installing updates after clean install are only things done.  New or old shares created and then edited now present the "read only" option despite selecting other options for access control.

**Comment by phillxnet** [comment]
@parker1c Thanks for reporting this and your diligence in the details. I haven't had a chance to look into this myself just yet but hopefully I or someone can sort this pretty soon.

Any progress on this issue will be logged here.
Cheers.

**Comment by phillxnet** [comment]
@schakrava  I am having a quick look at this currently. Do let me know if this is inappropriate. I'm hoping its another simple fix akin to my recent run. I will report here how it goes. I have confirmed @parker1c findings in a simple share creation.

**Comment by phillxnet** [comment]
@parker1c Thanks again for bringing attention to this issue. A patch has now been submitted, referenced in this issue thread, and if it passes review then it should be available soon via an update.

Cheers for contributing your time and testing talent.

**Comment by Mazo** [comment]
After updating to the latest version of Rockstor (testing branch) it appears to have reset all my shares to the default permissions (oddly). Once the patch is merged and released I'll try reassigning permissions and see if it's working.

**Comment by phillxnet** [comment]
@parker1c As of the just released 3.8-10.18 (testing channel) the referenced patch for this issue should now be included, and it appears from the dev log that the next stable channel update is just around the corner.
http://forum.rockstor.com/t/dev-log-for-upcoming-3-8-11-latest-3-8-10-18/792/32

 Thanks for you help with this matter.
