### ISSUE TITLE
unable to delete rock-ons-root share when rock-ons service off

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#1111]
When attempting to delete this share (the one used by rock-ons) the message suggests that turning off the rock-ons service is sufficient but this is not the case. A work around is to first reconfigure the rock-ons service to use another share first; even if the rock-ons service is not enabled. This allows the deletion of the original rock-ons-root share.

**Comment by schakrava** [comment]
Nicely defined issue, but unfortunately I went unnoticed to the point where I filed another issue and fixed it, making this a duplicate. The other issue is #1125
