### ISSUE TITLE
test email sent dialog no longer appears

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#1117]
The dialog that normally appears after sending a test email such as is illustrated in the docs (http://rockstor.com/docs/email_setup.html#testing-email) no longer appears.
Version 3.8-11 fresh install.

**Comment by schakrava** [comment]
Thanks for reporting this @phillxnet. This was fixed in https://github.com/rockstor/rockstor-core/commit/04290111fa7119c924d92455ac48196bc3898369
