### ISSUE TITLE
Error after installation bad tree block start

### ISSUE THREAD

**Issue by redecs** [rockstor/rockstor-core#1118]
Hello,

I'm getting the following error just after install Rockstor 3.8-11:
`[    9.794930] BTRFS (device sdc3): bad tree block start 405340160 405307392`
The installation was on a USB stick and the machine is HP Microserver Gen 8.
I tried installing to and from various USB sticks and even a SD card without any luck.

Any suggestions?

**Comment by redecs** [comment]
More details:
![btrfs_fail](https://cloud.githubusercontent.com/assets/153277/12535937/78fb590e-c29d-11e5-8162-7e403fc66c30.png)

**Comment by phillxnet** [comment]
@redecs Just as a quick suggestion I would try installing on an hdd or ssd first. I am assuming that is not what you want to hear but usb / sd card performance with Rockstor is not currently very gratifying. Especially in your case by the looks of it :). I think there are members of the Rockstor forum that have done gen8 installs though so it might be worth asking there.
http://forum.rockstor.com/
and search for gen8 or microserver, there are a number of threads / posts for each search.

Hope that helps a little.

**Comment by Hooverdan96** [comment]
@phillxnet, @FroggyFlox, suggesting to close this, as it's 7 years old and referring to 3.9x
