### ISSUE TITLE
rockstor version not always visible

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#1119]
Thanks to @grizzly on the forum for highlighting. It is often the case that the Rockstor version is not displayed in the top right of the WebUI as intended. It would be good to make this more reliable. Workaround is to visit the System - Software Update page and if there is a pending update it sometimes provokes the WebUI into displaying the current Rockstor version.

Please update the following forum thread with development on this issue.
http://forum.rockstor.com/t/how-to-tell-current-version/963

**Comment by Mazo** [comment]
Believe this is likely down to line 310 in /smart_manager/data_collector.py

If the refresh timer hasn't expired update_check() never runs, which means displayUpdate() never gets called by the socket listener on line 974 in /storageadmin/static/storageadmin/js/router.js

**Comment by schakrava** [comment]
Thanks for the tip @Mazo. We'll get to it soon, but feel free to open a pull request if you like. greatly appreciate it!

**Comment by phillxnet** [comment]
This is now much improved for me as from 3.8-11.02; if the view is wide enought to display the individual menus then within a minute or so of a broswer refresh I get the version displayed.

@schakrava Is this now fixed by #1133 then?
