### ISSUE TITLE
Active Directory Join not working

### ISSUE THREAD

**Issue by ChristianKueppers** [rockstor/rockstor-core#1122]
Version 3.8.11
Ad Join not working. Tries to take the administrator instead of given account. But Administrator is on Windows 2012 deactivated. Domain controller shows the same in his logs.
![rockstor](https://cloud.githubusercontent.com/assets/16869118/12539121/b7b7d070-c2eb-11e5-9dfb-c1fcbe38c4ca.JPG)

**Comment by schakrava** [comment]
Fixed by #1174

**Comment by ChristianKueppers** [comment]
Hi. 
.12 release dies not work. In which release it's fixed?

Christian
