### ISSUE TITLE
Rockon OpenVPN default port issue

### ISSUE THREAD

**Issue by timmjr** [rockstor/rockstor-core#1127]
Changing the default port (from 1194) has not effect. The OpenVPN rockon will run on 1194 rather than the specified port.
![image](https://cloud.githubusercontent.com/assets/16880749/12553134/54a1b594-c37e-11e5-97b4-5d5563d8f383.png)

**Comment by schakrava** [comment]
@timmjr can you provide more info please? What's on screenshot is correct. port 1198 on the host is mapped to 1194 of the container running openvpn. What's the problem here?

**Comment by FroggyFlox** [comment]
Closing as has been waiting for feedback for a long time.
