### ISSUE TITLE
task history: columns of start/end time are inverted

### ISSUE THREAD

**Issue by jakieu** [rockstor/rockstor-core#1129]
The columns of start time and end time are inverted in the task history.
![scrub_log](https://cloud.githubusercontent.com/assets/8632220/12592869/9eea640c-c46e-11e5-8b40-6d35d8171160.png)

**Comment by phillxnet** [comment]
@Mchakravartula Could this be a duplicate of #968 
ie note the comment on 20th October.

**Comment by Mchakravartula** [comment]
@phillxnet  Yep, this is duplicate of #968

**Comment by schakrava** [comment]
Fixed by #1156
