### ISSUE TITLE
reverting network role selection

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#1139]
@parker1c in the following forum thread:- http://forum.rockstor.com/t/network-interface-role-info-and-quirks/997/1 details an inability to revert an interface back to the io role having first selected and saved another role.

**Comment by phillxnet** [comment]
This issue may now be redundant as there has recently been a major re-working of the network interface.

**Comment by Hooverdan96** [comment]
And since then probably some more work (6 years later) and a platform change ... @phillxnet, proposing to close this one.
