### ISSUE TITLE
Windows not seeing NAS or any shares

### ISSUE THREAD

**Issue by Damianjsmith** [rockstor/rockstor-core#1141]
Hi,

As per my forum thread, I have a new install and both My Windows 10 laptop can not see the drive.  have tried all the usual advice from Google ect. 

But when I run Ubuntu OS it finds it straight away with no issues at all. 

Please can you assist. 

Kind Regards 

Damian

**Comment by phillxnet** [comment]
@Damianjsmith I'll just link to the forum thread to help tie the two together.
http://forum.rockstor.com/t/new-install-all-set-up-windows-cant-find-it/961

I take it you have ensured that the "Workgroup" setting is identical in both the Rockstor Samba configuration and on the windows clients?

**Comment by Damianjsmith** [comment]
I will double check tonight , but I followed the guide and I have re done a fresh install as well. 

Thanks for the link in , I new to all this .

**Comment by MFlyer** [comment]
hi @Damianjsmith , any update on your issue??

**Comment by MFlyer** [comment]
@schakrava can we close this? It seems a dead thread
M.

**Comment by phillxnet** [comment]
Closing as old and no further interaction. For any new instance of this please open a new issue with all relevant info.
