### ISSUE TITLE
Create simple Docker Web-Interface

### ISSUE THREAD

**Issue by henfri** [rockstor/rockstor-core#1143]
The Synology software (DS) has a limited Interface to Docker and Docker Hub.
This enables any user to select any (!) Docker Image from the Docker Hub and run it on the NAS.

This feature is documented here:
http://blog.pavelsklenar.com/how-to-install-and-use-docker-on-synology/

Compare this Thread: 
http://forum.rockstor.com/t/next-phase-of-rock-on-framework-improvements/417/7

**Comment by henfri** [comment]
Hello,

I did some research on existing Docker-UIs:

- Docker-UI https://github.com/crosbymichael/dockerui

Comes as a Docker-Container itself and aims to provide all Feature that the Docker-API provides.
Appears slim and lightweight.

- Shipyard http://shipyard-project.com/
Appears more feature rich, also for Docker-Swarms

-mist.io http://blog.mist.io/post/96542374356/one-ui-to-rule-them-all-manage-your-docker
Seems also very feature rich; integrating also other containters than docker

Do you think it would be useful to assess these for a potential integration into Rockstor?

Greetings,
Hendrik

**Comment by doenietzomoeilijk** [comment]
To add to your list: at work we use [Portainer](https://portainer.io/), which works well enough.

**Comment by FroggyFlox** [comment]
@doenietzomoeilijk based on your suggestions, you may be interested to know that a Rock-on for Portainer has been created, alongside a PR:
[https://github.com/rockstor/rockon-registry/pull/128](https://github.com/rockstor/rockon-registry/pull/128)

**Comment by Hooverdan96** [comment]
@FroggyFlox what do we do with this one? I think the official strategy (good/bad/indifferent) is to continue with the Rockon framework, while advanced users can obviously still use things like portainer, etc.?

**Comment by phillxnet** [comment]
@Hooverdan96 Thanks again for the triage here.

Re

> I think the official strategy (good/bad/indifferent) is to continue with the Rockon framework, while advanced users can obviously still use things like portainer, etc.?

Agreed. Closing as insufficient community or core developer interest/contribution.
