### ISSUE TITLE
sqlite_insert_client: insert statement prepare failed: table clients has 2 columns but 3 values were supplied

### ISSUE THREAD

**Issue by roweryan** [rockstor/rockstor-core#1145]
Feb  2 20:14:05 rockstor nfsdcltrack[2891]: sqlite_insert_client: insert statement prepare failed: table clients has 2 columns but 3 values were supplied

rockstor-3.8-11.05.x86_64

**Comment by roweryan** [comment]
Also:

    Feb  2 20:06:23 rockstor nfsdcltrack[2608]: sqlite_query_reclaiming: unable to prepare select statement: no such column: has_session

**Comment by schakrava** [comment]
I don't understand what the problem here is. and how do we reproduce?

**Comment by MFlyer** [comment]
@schakrava to be closed/not really an issue??

Flyer

**Comment by schakrava** [comment]
Yup, I think so. @roweryan please feel free to reopen with reproducible steps.
