### ISSUE TITLE
"io" type for network interface has no tooltip

### ISSUE THREAD

**Issue by roweryan** [rockstor/rockstor-core#1146]

**Comment by phillxnet** [comment]
@roweryan Cheers, I meant to add this to #1139 but now it's here it can stand as a separate issue, probably best to split them anyway. I'll link to the earlier report on the forum so as to keep that thread informed of progress here as well.

Please update the following forum thread on development with this issue:-
http://forum.rockstor.com/t/network-interface-role-info-and-quirks/997

**Comment by schakrava** [comment]
This is no longer relevant as we redesigned various services to network connections as part of respective service configurations.
