### ISSUE TITLE
New rockon - Crashplan

### ISSUE THREAD

**Issue by joshiegy** [rockstor/rockstor-core#1147]
Looking for a crashplan rockon.

**Comment by joshiegy** [comment]
A fix for this has been presented by me:
https://github.com/joshiegy/rockon-registry

A pull-request have been made to merge with:
https://github.com/rockstor/rockon-registry

**Comment by Hooverdan96** [comment]
@FroggyFlox since crashplan was added to the Rockon registry back then, we should close this issue over here.
