### ISSUE TITLE
New rockon - Symform

### ISSUE THREAD

**Issue by joshiegy** [rockstor/rockstor-core#1148]
Looking for new rockon - Symform.

**Comment by joshiegy** [comment]
A fix for this has been presented by me:
https://github.com/joshiegy/rockon-registry

A pull-request have been made to merge with:
https://github.com/rockstor/rockon-registry

**Comment by Hooverdan96** [comment]
Since symform was shut down, after this Rockon was added to the registry it was also subsequently removed. 
https://github.com/rockstor/rockon-registry/issues/56
@FroggyFlox let's close this issue over here as well.
