### ISSUE TITLE
Add "sensors".

### ISSUE THREAD

**Issue by k0nsl** [rockstor/rockstor-core#1150]
**Suggestion:** include temperature sensors (mainly for CPU) on the overview/dashboard, similar to those disk/memory/cpu usage/network widgets.

**Comment by phillxnet** [comment]
@k0nsl Thanks, this is a good suggestion, but given that these values are obtained via the lm-sensors package I think it's a duplicate of our existing issue #582 "lm-sensors support". We also have another issue that is related ie "hdd temp and sensors graphs on dashboard view" which I think mainly relates to hdd sensors but linking here just in case #980 .

**Comment by k0nsl** [comment]
Ah, thanks! Yes those issues do seem related / duplicates (particularly this one: https://github.com/rockstor/rockstor-core/issues/980).

I will search harder next time. It was just something that I had to note in case I forgot about it.

**Comment by phillxnet** [comment]
@k0nsl Great, thank. I've noted that this was closed as a duplicate on the #980 issue to indicate the additional interest. It would be nice but it's not without it's difficulties as not all motherboards are known to lm-sensor and not all manufacturers publish their sensor scaling factors etc so there is a great reliance on individuals attempting to 'guess' by trial and error on the various factors for each boards various readings. I've submitted one myself for the Asus-Z87M-PLUS board. Haven't checked on if it's included or not now though.
Thanks again for chipping in. There is also a pretty active Rockstor forum that may be of interest:-
http://forum.rockstor.com/ many of these issues come from discussions there.

**Comment by kanecko** [comment]
I'll just leave a +1 here, in order to show interest for this feature.

Use-cases: 
1. in case of unexpected reboot, I will check the history temperatures, to see if that was the cause
2. to monitor the max temperature, when PC is doing an intensive task
3. to compare a year's worth of temperature, to see whether I need to change the paste or blow out the PC
