### ISSUE TITLE
Kernel panic on booting VMWare VM with current kernel

### ISSUE THREAD

**Issue by dizzi90** [rockstor/rockstor-core#1155]
The host is the free license version of the ESXi 6.0 hypervisor.

As I boot the VM, GRUB presents me with the default choice of the current kernel:
`Rockstor (4.3.3-1.el7.elrepo.x86_64) 3 (core) with debugging`
Attempting to boot with this kernel gives the following result:
![rockstor_vmware](https://cloud.githubusercontent.com/assets/3081351/12869441/13d3cf92-cd20-11e5-92fa-77a693bdd31f.JPG)

Booting with the other option works:
`Rockstor 3 (Core), with Linux 4.2.5-1.elrepo.x86_64`

Once it is up there are no issues, but it is a bit of a drag when rebooting having to open the console every time.

I have switched from unstable to stable, but I am unsure if there is a downgrade I have to make to get the stability of running a kernel which works.

I have not forced VMWare to expose UUIDs for the disks, but I have not seen any indications that Rockstor is confused as to which disk is which. The volumes work fine.

I'm not sure what other info you need.

**Comment by jhdulaney** [comment]
It is, for some reason, not seeing the block device your root filesystem lives on.  It may be that, since the other kernel boots, this kernel rpm was corrupted during download.  If you reinstall that particular kernel package, it should take care of you.

**Comment by dizzi90** [comment]
So, console as root, 
`rpm -qa | grep kernel | sort`
Find 4.2.5-1.elrepo.x86_64
`yum remove $kernelPackage`
`yum install $kernelPackage`
Does that seem like the correct way to do it? Want to make sure, as I am not very familiar with CentOS.

**Comment by dizzi90** [comment]
Yep. Worked. Thanks.
