### ISSUE TITLE
Cannot login with github login to forum.rockstor.com

### ISSUE THREAD

**Issue by roweryan** [rockstor/rockstor-core#1160]
Related to the SSL change?

**Comment by roweryan** [comment]
Also the favicon is loaded over non-SSL, and so is the logo. The same favicon problem exists in the rockstor nas web gui. It causes a warning in Firefox.

**Comment by roweryan** [comment]
It works now.

**Comment by schakrava** [comment]
Thanks for checking back again @roweryan and reporting in the first place. The social logins needed to be reconfigured after the change to https last night.
