### ISSUE TITLE
GID is ignored when creating group

### ISSUE THREAD

**Issue by TheFluffyOne** [rockstor/rockstor-core#1161]
When creating a group via the web UI, if I enter a specific GID it is ignored. For example, I create a group called "accesstest", putting 10099 into the GID field and submit. The group is created with the next sequentially-available GID, for example "10016" in the case of a test I just ran.

It appears that the GID field is being ignored. Doesn't seem to make a difference whether I choose to put the group under "Rockstor management" or not.

**Comment by TheFluffyOne** [comment]
Tested on Rockstor version 3.8-11.09.

**Comment by TheFluffyOne** [comment]
Just had a quick poke around (pretty crudely, I'm afraid, as I'm not familiar with your codebase or NGINX). The issue appears to be that the GID is not being included in the POST. Added the request body to the NGINX logging config, and the POST request for a new group was like this:

192.168.137.1 - - [10/Feb/2016:17:41:05 +0000] "POST /api/groups HTTP/1.1" 200 311 "https://192.168.137.185/?domain=&server=" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.103 Safari/537.36" "-""{\x22groupname\x22:\x22aatest5\x22}"

If I get some more time later I'll see if I can figure out the UI templates to see what's wrong...

**Comment by schakrava** [comment]
Thanks for reporting this issue @TheFluffyOne! It's fixed now and released in 3.8-11.12
