### ISSUE TITLE
Samba share page not displaying correct information for existing shares

### ISSUE THREAD

**Issue by nicolaslt** [rockstor/rockstor-core#1176]
Hi,

After creating a share, when going back to it via the 'edit' button, some -if not most- of the inputs do not display the correct data. Example: Read Only always stays on yes.

I was on my way to make a pull request for this but it seems to me this page needs more work. I'm happy to do that extra work if we agree it's needed.

There are many duplications in the .jst as follow:
```handlebars
{{#if sambaShareIdNotNull}}
    <input type="text" id="comment" class="form-control" name="comment" value="{{smbShareComment}}" title="Comment string to associate with the new share">
{{else}}
    <input type="text" id="comment" class="form-control" name="comment" value="Samba-Export" title="Comment string to associate with the new share">
{{/if}}
```

which IMHO should be:
```handlebars
<input type="text" id="comment" class="form-control" name="comment" value="{{smbShareComment}}" title="Comment string to associate with the new share" placeholder="Samba-Export">
```

And the javascript defines 5 handlebar helpers to render 3 yes/no radio buttons and 2 selects. Couple of bullets for this:
  - I guess the yes/no radios should be checkboxes
  - Those helpers defeat the purpose of having a templating engine. Why not use a handlebar partial instead ? Especially as the helpers duplicate the code by quite a bit. Each yes/no helper has 4 lines of html. (1 per permutation between `checked` and the option `name` and `value`)
  - This is where the original issue comes from; there's a few `this` and scope confusion in the building of the yes/no radios.

**Comment by schakrava** [comment]
@nicolaslt thanks for opening this issue and nicely articulating the shortcomings for current handlebar-code and suggesting improvements. Totally agree with you.

I've fixed up the functional bugs in the commits referred above. But @priyaganti is owning the templating improvements and so I am keeping this issue open for a part2 pull request from her.

Btw, thanks for becoming a code contributor. We welcome pull requests and would greatly appreciate your time and collaboration. Please don't be shy to get more involved.

**Comment by nicolaslt** [comment]
Thanks @schakrava. I'll test this fix on my setup sometime next week I think.

About contributing: For now I'm only taking care of issues I encounter on my own setup. I might get more involved in a bit. Got other priorities right now. :-)

**Comment by schakrava** [comment]
Totally understandable. Feel free to get involved as and when you are ready.

**Comment by nicolaslt** [comment]
Finally found the time to test, it works fine. Thank @schakrava.
