### ISSUE TITLE
e-mail alert enhancements

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-core#1184]
Please refer to comments by @baggar11 and @phillxnet in

https://github.com/rockstor/rockstor-core/issues/837

**Comment by MFlyer** [comment]
hi @schakrava do we still need this issue ? Reading #837 current email alerts system, except for secondary recipient address, seems good

Flyer

**Comment by MFlyer** [comment]
Post-it - to be closed @schakrava

**Comment by MFlyer** [comment]
To be closed, fixed with last PRs @schakrava

**Comment by phillxnet** [comment]
@MFlyer and @schakrava  I agree, we can always open more specific issues individually as they come up given the number of changes already implemented it's probably better to start again on issues in this area.

**Comment by schakrava** [comment]
Thanks for your comments, totally agreed.
