### ISSUE TITLE
Expose Docker socket in rockons

### ISSUE THREAD

**Issue by qooplmao** [rockstor/rockstor-core#1189]
Would it be possible to expose the `/var/run/docker.sock` (I assume by default being the easiest) in Rockon containers to stop the issues surrounding ["Docker in Docker"](https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/). The need for this is because I am wanting to run a Jenkins slave container so pretty much the exact thing the guy is going on about in his blog post. 

I assume it would just mean adding a default volume share of `/var/run/docker.sock:/var/run/docker.sock` somewhere but I can't for the life me work out where it would go.

My thinking was just adding a default volume in each docker instance. Something in `rockstor-core/src/rockstor/storageadmin/views/rockon_helpers.py` like...

``` python
def vol_ops(container):
    ops_list = []
    for v in DVolume.objects.filter(container=container):
        share_mnt = ('%s%s' % (settings.MNT_PT, v.share.name))
        mount_share(v.share, share_mnt)
        ops_list.extend(['-v', '%s:%s' % (share_mnt, v.dest_dir)])
    # expose Docker socket to container to spawn "sibling" rather than "child" containers
    ops_list.extend(['-v', '/var/run/docker.sock:/var/run/docker.sock'])
    return ops_list
```

If this would be the correct approach then I can happily create a PR.

**Comment by schakrava** [comment]
We'd love pull requests in general. Please don't be shy.

I do have one question on this one. What are the security concerns of doing this? Looks like the container will have full access? to the host docker. Is that good? especially if done by default for every container?

**Comment by qooplmao** [comment]
To be honest I hadn't even thought about security.

From a Google search it does look like there would be security issues around sharing the socket (see [this blog post](https://www.ctl.io/developers/blog/post/tutorial-understanding-the-security-risks-of-running-docker-containers)) although this **may** be sorted in 1.10 with the [user namespaces](https://blog.docker.com/2016/02/docker-engine-1-10-security/). I say **may** as I'm not entirely sure what's going on .

**Comment by FroggyFlox** [comment]
This should be entirely doable using the "opts" object in a Rock-On definition json. Closing this issue as a result.
