### ISSUE TITLE
Resize UI bug

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-core#1194]
reported by a user. [video demo](https://192.195.81.156:22080/index.php/s/NkvZJqkpqPPd6vN)

I’m allowed to resize a pool and choose change raid level but continue without selecting a raid level leading to balance errors. I should get a warning or mandate to choose before continuing forward, and if I go forward but then click back my selections should be sticky.

Error running a command. cmd = ['btrfs', 'balance', 'start', u'-mconvert=', u'-dconvert=', u'/mnt2/Testpool1']. rc = 1. stdout = ['']. stderr = ['the convert option requires an argument', '']

**Comment by ChristianKueppers** [comment]
when resizing a non raid pool with a new disk i get the error "pool migration from single to single is not supported". 
Is it a bug or a limitation?

**Comment by schakrava** [comment]
It's more of a feature than a bug :)

If you like to use multiple drives in single profile, you can use some kind of hardware raid or mdraid underneath.

**Comment by schakrava** [comment]
Fixed by #1558
