### ISSUE TITLE
Improve Pool delete UX

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-core#1195]
Requested by a user:

Deleting a pool is really tedious. If I have a pool, with a share defined, and a samba export… If I try to delete the pool I get a warning that I can’t because a share exists… so I go to the share and try deleting it only to get an error that a samba export exists… so I then have to go to samba, then back to shares, then back to pool. That’s a lot of steps. Streamlining this would help ease of use. I.E. at that confirmation window for the pool show and list all shares & exports with a checkbox to select all associated shares/exports at the same time.

**Comment by gkadillak** [comment]
@schakrava @priyaganti is this currently being worked on? If not, can I pick it up?

**Comment by schakrava** [comment]
Please go ahead @gkadillak . You are more than welcome to!

**Comment by gkadillak** [comment]
Awesome!

**Comment by schakrava** [comment]
Fixed by #1436
