### ISSUE TITLE
Latest update error on 3.8-11.20: You are running an unsupported kernel

### ISSUE THREAD

**Issue by tastyratz** [rockstor/rockstor-core#1197]
Error message on boot after applying 3.8-11.20.

You are running an unsupported kernel(4.4.3-1.el7.elrepo.x86_64). Some features may not work properly. Please reboot and the system will automatically boot using the supported kernel(4.3.3-1.el7.elrepo.x86_64)

**Comment by MFlyer** [comment]
@schakrava can we consider this "solved" or at least "to be closed"??

**Comment by schakrava** [comment]
You are right @mflyer, this is no longer an issue.
