### ISSUE TITLE
enable pool compression tooltip chopped off top of screen

### ISSUE THREAD

**Issue by tastyratz** [rockstor/rockstor-core#1198]
When enabling compression the yellow dialog box comes up but does not opt to display below the field instead of above when text will be cut off. This may be a general handling issue that presents from the selection up high.
I suspect extra mount options is the same thing but I don't know if additional text is actually missing from view..

**Comment by phillxnet** [comment]
@priyaganti I think another instance of this happening is evident in #1134 where the top of the yellow mouse over popup is obscured on the top field of the NUT config page.

**Comment by schakrava** [comment]
Fixed by #1251
