### ISSUE TITLE
Transmission rock-on is not starting

### ISSUE THREAD

**Issue by oivanenko** [rockstor/rockstor-core#1200]
Hi!

Today transmission rock-on was stopped suddenly and not starts even after reboot. I have Plex rock-on that working fine.

When I trying to start transmission rock-on any information not shows in /var/log/messages, but plex rock-on generated info like this:

Mar  3 12:17:21 gandalf systemd: Starting Docker Application Container Engine...
Mar  3 12:17:23 gandalf systemd: Scope libcontainer-13041-systemd-test-default-dependencies.scope has no PIDs. Refusing.
Mar  3 12:17:23 gandalf systemd: Started docker container a324af7cac78cb5279784fb818a6ba1e1d816632a12b444e58b2cd2f7908c53f.
Mar  3 12:17:23 gandalf systemd: Starting docker container a324af7cac78cb5279784fb818a6ba1e1d816632a12b444e58b2cd2f7908c53f.
Mar  3 12:17:23 gandalf docker/a324af7cac78[13041]: + GROUP=plextmp
Mar  3 12:17:23 gandalf docker/a324af7cac78[13041]: + mkdir -p /config/logs/supervisor
Mar  3 12:17:23 gandalf docker/a324af7cac78[13041]: + touch /supervisord.log
Mar  3 12:17:23 gandalf docker/a324af7cac78[13041]: + touch /supervisord.pid
Mar  3 12:17:23 gandalf docker/a324af7cac78[13041]: + chown plex: /supervisord.log /supervisord.pid
Mar  3 12:17:23 gandalf docker/a324af7cac78[13041]: ++ stat -c %g /data
Mar  3 12:17:23 gandalf docker/a324af7cac78[13041]: + TARGET_GID=110
Mar  3 12:17:23 gandalf docker/a324af7cac78[13041]: ++ grep 110
Mar  3 12:17:23 gandalf docker/a324af7cac78[13041]: ++ wc -l
Mar  3 12:17:23 gandalf docker/a324af7cac78[13041]: ++ cat /etc/group
Mar  3 12:17:23 gandalf docker/a324af7cac78[13041]: + EXISTS=1
Mar  3 12:17:23 gandalf docker/a324af7cac78[13041]: + '[' 1 = 0 ']'
Mar  3 12:17:23 gandalf docker/a324af7cac78[13041]: ++ getent group 110
Mar  3 12:17:23 gandalf docker/a324af7cac78[13041]: ++ cut -d: -f1
Mar  3 12:17:23 gandalf docker/a324af7cac78[13041]: + GROUP=plex
Mar  3 12:17:23 gandalf docker/a324af7cac78[13041]: + usermod -a -G plex plex
Mar  3 12:17:23 gandalf docker/a324af7cac78[13041]: + usermod -a -G plex plex
Mar  3 12:17:23 gandalf docker/a324af7cac78[13041]: + [[ -n '' ]]
Mar  3 12:17:23 gandalf docker/a324af7cac78[13041]: + '[' true = true ']'
Mar  3 12:17:23 gandalf docker/a324af7cac78[13041]: + find /config '!' -user plex -print0
Mar  3 12:17:23 gandalf docker/a324af7cac78[13041]: + xargs -0 '-I{}' chown -R plex: '{}'
Mar  3 12:17:26 gandalf docker/a324af7cac78[13041]: + '[' false = true ']'
Mar  3 12:17:26 gandalf docker/a324af7cac78[13041]: + '[' '' ']'
Mar  3 12:17:26 gandalf docker/a324af7cac78[13041]: + '[' true = true ']'
Mar  3 12:17:26 gandalf docker/a324af7cac78[13041]: + /usr/sbin/start_pms
Mar  3 12:17:26 gandalf docker/a324af7cac78[13041]: 6 3000 /config/Library/Application Support
Mar  3 12:17:26 gandalf docker/a324af7cac78[13041]: 8192

What kind of information I can provide to solve this issue? Rockstor version is 3.8-11

**Comment by Hooverdan96** [comment]
@FroggyFlox since we unfortunately don't seem to have ever responded to this request and this was more than 7 years ago, I'd suggest to close this one.

**Comment by FroggyFlox** [comment]
Agreed... Base OS, Docker, and the image all have evolved a lot since the original report so closing now.
