### ISSUE TITLE
enhancement: Cannot start without configuration. dialog should link to configuration

### ISSUE THREAD

**Issue by tastyratz** [rockstor/rockstor-core#1202]
If for example I go to the rock ons tab and click enable it does not enable but prompts me to first go configure it through another menu option. Why not allow this to be more fluid?
It could:

- Automatically redirect to the configuration page required
- Present the error with a link to the configuration page instead of short instruction
- just take me to configuration first before allowing me to enable. Maybe even replace the on/off toggle with the configure button until it's sufficient.

**Comment by schakrava** [comment]
Fixed by #1280
