### ISSUE TITLE
Check only installed AND active rock-ons for port-conflicts. NOT available Rock-Ons.

### ISSUE THREAD

**Issue by henfri** [rockstor/rockstor-core#1204]
(from https://forum.rockstor.com/t/bug-check-of-used-ports-for-rock-ons-should-be-done-for-active-rock-ons-only/1183)
Hello,

I have tried to update the plex Rock-On by adding a plex_new.json to /opt/rockstor/rockon-metastore.
Unfortunately, the fact that there are now two Plex Rock-Ons causes this problem:
`Rock-on port(32400) is dedicated to another Rock-On(Plex) and cannot be changed. Choose a different name`. This happens when trying to install the new Rock-On.

I don't see the problem here. This check is not needed my view. Instead of checking whether another *available* (but not neccessarily installed AND active) Rock-On does use this a port already, it should only be checked if an active Rock-On is using (i.e. mapping to the Host) the port of the Rock-On that is currently being installed.

Proposal:
Check only installed AND active rock-ons for port-conflicts. NOT available Rock-Ons.

**Comment by schakrava** [comment]
Thanks for the proposal @henfri, completely agreed. Turns out I've actually implemented this exact fix in https://github.com/rockstor/rockstor-core/commit/a6d47c4707a002deb673d0587adba326c822a70d

**Comment by henfri** [comment]
Thanks!
Am 14.07.2016 22:49 schrieb Suman Chakravartula <notifications@github.com>:Thanks for the proposal @henfri, completely agreed. Turns out I've actually implemented this exact fix in a6d47c4
