### ISSUE TITLE
plex RockOn without net=host

### ISSUE THREAD

**Issue by henfri** [rockstor/rockstor-core#1209]
Hello,

from: https://hub.docker.com/r/linuxserver/plex/

Special note - If you'd like to run Plex without requiring --net=host then you will need the following ports in your docker create command:

  -p 32400:32400 \
  -p 32400:32400/udp \
  -p 32469:32469 \
  -p 32469:32469/udp \
  -p 5353:5353/udp \
  -p 1900:1900/udp

Greetings,
Hendrik

**Comment by bskrtich** [comment]
I will make this change and see if they will merge it in.

**Comment by Hooverdan96** [comment]
@FroggyFlox since this post was opened various plex iterations have been merged into the corresponding Rockon repo, so I think we can close this one. If new suggestions, etc. are raised, a new issue should probably be opened over there.

**Comment by FroggyFlox** [comment]
Agreed... @phillxnet's comment in the linked and merged PR provides a very explanation on why this could be problematic so I'll close now.
