### ISSUE TITLE
Rock-Ons: It should be possible to fix ports in Rock-Ons

### ISSUE THREAD

**Issue by henfri** [rockstor/rockstor-core#1210]
Hello,

for some Rock-Ons having different ports for the host and container does not make sense.
Furthermore, for some it does not make sense to change the ports at all.

It should be possible to fix these ports in the json, i.e. to make them not user-configurable.

Greetings,
Hendrik

**Comment by qooplmao** [comment]
Which Rock-ons do you mean?
As the server can be used for more than just Rockstor (and the available Rock-ons) and people, including me, can run their own custom docker containers how would you deal with already set-up containers that have conflicting ports if they are fixed?

**Comment by henfri** [comment]
E.g. BTSync. BTSync will always try to connect to Port 55555.

**Comment by qooplmao** [comment]
Not necessarily.
BTSync can have the known hosts for linked devices added using a custom port like `1.1.1.1:12345`.
With editable ports the Rock-On may have port 55555 exposed while a user could use a non-standard port on their server and forward it through to port 55555 on the container.

Disabling user configuration on fields could make those Rock-Ons unusable for a portion of users.
I would say a better option would be something like a `use default ports []` checkbox (checked by default) that would allow for configuration where necessary but simplify setup for the majority of users.

**Comment by FroggyFlox** [comment]
@phillxnet, fixing ports is possible by using the `"options"` object in a rock-on json definition file if one needs it. We could thus close this issue if needed.



> I would say a better option would be something like a `use default ports []` checkbox (checked by default) that would allow for configuration where necessary but simplify setup for the majority of users.

I really like this suggestion / idea, which would fit the concept of "easy install" you and others have discussed / brought up several times in the forum and here...
Linking here for reference: 
https://forum.rockstor.com/t/next-phase-of-rock-on-framework-improvements/417/4?u=flox

**Comment by phillxnet** [comment]
@henfri Thanks for bringing this up. Doing a little tidy so closing this as per @FroggyFlox 's suggestion. @qooplmao Thanks for you import, all good stuff.
