### ISSUE TITLE
Fibre Channel Support 

### ISSUE THREAD

**Issue by kevin02345** [rockstor/rockstor-core#1211]
Would like to see support for Fibre Channel support out of the box.  That way when using fibre channel for storage to hosts we can do this within the system.

**Comment by ScarabMonkey** [comment]
Installing the relevant vendor-specific drivers should accomplish this. 
I don't think a distribution (such as Rockstor) could be expected to ship every vendor's drivers - and in fact may not be able to, due to licensing restrictions.

**Comment by Hooverdan96** [comment]
@phillxnet , @FroggyFlox I tend to agree with ScarabMonkey on this, and I believe we had a few forum posts on "special" network interfaces already ... so, might be ok to close this issue/enhancement request, unless you want to support this in some form or another (e.g. provide an additional explainer in the rockstor-installer repo for people to roll their own ...).
