### ISSUE TITLE
mdraid member status not updated

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#1214]
Once a disk is labelled by Rockstor as an mdraid member that status is not properly updated even if the disk is manually wiped by for example *mdadm --zero-superblock /dev/sdX*. Thank's to @elmcrest and @Spectre694 in the following forum post for rooting out this issue.
https://forum.rockstor.com/t/disks-failing-with-badge-disk-is-a-mdraid-member/1210/7?u=phillxnet

Please update the referenced forum post with any development on this issue.

@schakrava Since this was my fault I'd welcome the assignment. I haven't had the chance to reproduce locally but pretty sure I neglected proper raid member updates as I was assuming system drive only md id however in this case the label was established on a non system drive from a drives prior mdraid membership: pre rockstor. This required a re-install after manual --zero-superblock to clear the db "mdraid member" flag.

**Comment by phillxnet** [comment]
Another forum thread that appears to have run into the same issue is:
https://forum.rockstor.com/t/formatting-old-raid-hdds/1337
Please also update this thread with development on this issue.

**Comment by phillxnet** [comment]
The initial fix for this need only be updating the db drive entry of mdraid member in the role field on disk re-scan. That would then not necessitate the need for a re-install at least. This would still leave users having to manually execute the --zero-superblock command but would make for a much better arrangement than having to re-install.

**Comment by phillxnet** [comment]
A less long winded workaround than re-installing would be to run the --zero-superblock via command line on the prior mdraid members then disconnect those same drives and perform a Rescan on the Disks page. Then remove the entries pertaining to the removed drives. This way a fresh db entry will be made upon the drives re-connection, and given they no longer have mdraid superblock info their db entries should be clear of this flag; there by circumventing this bug where a Disks page Rescan fails to update a drives mdraid member status.

**Comment by phillxnet** [comment]
This is now mostly done bar final testing and debug log removal. Ie it resolves this issue and transitions the disks role field to json format as suggested by @schakrava .
I intend to have a quick look at extending things a little further to allow for additional roles in the future, but the base functions are now in place.

**Comment by cron410** [comment]
Phil you are awesome, but does this bring up a larger feature need? Should we start thinking about a "factory reset" option to remove all settings and disks from the DB? This could replace the requirement to reinstall the entire system when weird things happen. A copy of the default DB could be kept as a skel so the factory reset option could just delete the currently running DB and replace it with the factory default one. Just a thought.

**Comment by phillxnet** [comment]
@cron410 Thanks. This issue does address an error (in my own code) that needed fixing and there was upgrades to be done on the role field so popped them in while I was here.

However your Idea re factory reset is definitely an interesting one and as you say may address these, 'works one way but not the other' type of bugs that require people to re-install, or work around some how, or worse still fiddle with the db directly. I did provide a less long winded work around in my 8th of May comment here but I digress. Factory reset of db is definitely an idea with merit and I like it myself.

Would you like to open an issue on this indicating it as a feature request and how you think it might be implemented from the user perspective at least. Then hopefully a few people can chip in and get the idea flushed out? This might also help with development as it goes since then it would be easier to test a new feature or bug fix on a fresh database such as is experienced directly after install.
