### ISSUE TITLE
Catch-22 with failed Rock-ons

### ISSUE THREAD

**Issue by peterdenhaan** [rockstor/rockstor-core#1216]
It's possible to end up in nasty catch-22s when rock-ons fail.

I was trying to rig an alternative `btsync-peter` rock-on (the official BTSync is broken at the moment), but made a typo in the port definition. My json file attempted to map port 88888 rather than 8888. Installation obviously fell over because no such port was exposed. So far, so good.

When I corrected my json, Rockstor would not refresh because I wasn't allowed to change the port mappings of installed rock-ons and told me to uninstall first. But there was nothing to uninstall. After all, installation had failed. There seems to be no way offered out of this catch-22.

I only got myself unstuck by firing up `psql` and deleting all the records for my rock-on from the `storageadmin` tables.

The simplest way to fix this would probably be to suppress these port consistency checks when Rock-on installation (as opposed to start-up) has failed. However, there may be more edge cases like this. Given the data duplication between Rockstor's state recorded in `storageadmin` and Docker's own internal state, there is always scope for inconsistencies to arise.

**Comment by IamDH4** [comment]
I too had an issue with how Rockstor handles the port verification. In my case, if another rockon has a recommended port value, you cannot assign that port to your rockon. I think the user should be able to use any port regardless of recommendations (as long as the port actually exists/does not have an existing service binding to it).

**Comment by schakrava** [comment]
Fixed by #1232
