### ISSUE TITLE
Rockstor hangs on boot

### ISSUE THREAD

**Issue by HTPC-Schrauber** [rockstor/rockstor-core#1218]
After some time, Rockstore leaves me alone with a blinking cursor on boot.
The system does not start.

The problem does not seem to be hardware related. I have tried out 4 completely different hardware setups. Alway the same.
Only in a VM this does not seem to happen.

It seems the problem exists for a longer time.

Look at this Thread for the complete desciption:
https://forum.rockstor.com/t/rockstor-fails-to-boot-with-kernel-3-18-1/77/18

**Comment by skrzepto** [comment]
I have the same problem. 3 installs and it hangs on boot.


What I have noticed on my firewall logs is that during boot its recursively trying to connect to a ntp server which I blocked since I prefer my nas was only accessible inside my network.

**Comment by HTPC-Schrauber** [comment]
The NTP access does not seem to be the reason. In my case, this is not blocked.

**Comment by skrzepto** [comment]
Yea the NTP access wasn't the main culprit but it can at least pinpoint at what part of the boot sequence its good up to.

**Comment by Kollode** [comment]
I had the same problem. After a fresh install the system would not reboot. 
Most of the time i could get it to boot, if i removed the network cable. 

With the following commands from https://forum.rockstor.com/t/rockstor-fails-to-boot-with-kernel-3-18-1/77/14 i could see that it would hang after "Preprocess NFS Configuration"

> edit /etc/default/grub
> change
> GRUB_CMDLINE_LINUX="rhgb quiet crashkernel=auto"
> to
> GRUB_CMDLINE_LINUX="crashkernel=auto"
> Then run
> grub2-mkconfig -o /boot/grub2/grub.cfg

With http://unix.stackexchange.com/questions/211688/cannot-start-nfs-in-centos-7 i could get one step further but then the system stoped at "Init NFSv4 id mapper". 

Today i did a fresh Install and after the command "dracut --no-hostonly --force /boot/initramfs-4.4.5-1.el7.elrepo.x86_64.img 4.4.5-1.el7.elrepo.x86_64" i could finally reboot the system more then once. I found the command here: https://ask.fedoraproject.org/en/question/62676/f21-kernel-update-3183-201-not-booting/

I will test the system the following days and hope it remains that way.

**Comment by HTPC-Schrauber** [comment]
I found another solution for this:
I modified the /usr/lib/systemd/system/nfs-config.service.

I changed this line:
After=local-fs.target

Into this:
After=local-fs.target network.target

This now works for me.

I am unclear, what the reason is, why it hangs. I tried this because booting without network cable connected worked all the time.

**Comment by strahinjakupusinac** [comment]
I have the same problem as @skrzepto. Tried several reboots, unplugged lan cable, tried booting into recovery, nothing worked. Then i left it with blinking cursor until I got this error screen, rebooted it again and now it works but who knows what will happen on the next boot...

![img_3528](https://cloud.githubusercontent.com/assets/1199412/18284400/0b9f31b2-746a-11e6-8c41-c630cafd1ff8.JPG)

**Comment by Hooverdan96** [comment]
@phillxnet , @FroggyFlox I believe this qualifies as a legacy issue that can be closed, since we're off CentOS and moved on to OpenSUSE and this was also opened over 7 years ago.
