### ISSUE TITLE
Email Alerts Setting Missing Username

### ISSUE THREAD

**Issue by wingrunr21** [rockstor/rockstor-core#1228]
Hi,

It would be great if there was an option to specify a specific username in Email Alerts vs assuming it is the same as the "From" address. My specific case is that I use SparkPost for transactional emails and they require a username of 'SMTP_Injection' for SMTP connections (this is the same for all SparkPost accounts).

Thanks!

**Comment by MFlyer** [comment]
Hi @wingrunr21, working on it :wink:

**Comment by wingrunr21** [comment]
Great!

**Comment by MFlyer** [comment]
Hi again @wingrunr21, here is a little preview on frontend side - working and testing on backend, hope to pull request tomorrow
[https://youtu.be/zLgH3D6lNm4](https://youtu.be/zLgH3D6lNm4)

**Comment by schakrava** [comment]
Fixed by #1262
