### ISSUE TITLE
Duplicati support

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-core#1238]
Forum thread: https://forum.rockstor.com/t/running-duplicati-2-x-on-rockstor/742/10

Two possible approaches to add [duplicati](http://www.duplicati.com/home) to Rockstor to backup Rockstor Shares.
1. As a service
2. As a Rock-on.

I prefer (2). But would like to hear feedback from the community.

**Comment by phillxnet** [comment]
I vote for 2 As a Rock-on.

I have put my comments in the associated forum threat:
https://forum.rockstor.com/t/running-duplicati-2-x-on-rockstor/742/11?u=phillxnet

**Comment by MFlyer** [comment]
2 for me too. Samba is native, nfs is native, RSYNC and so on

**Comment by tronder88** [comment]
voting for 2. since it is not native, and if it was to crash, then it is good to just restart docker instead of whole server

**Comment by MFlyer** [comment]
Hi @glenngould82,
thinking about you "playing" with rock-ons, would you like to pick this and have a Rock-on? :wink:

Mirko

**Comment by MFlyer** [comment]
@schakrava can we close it?? we have Duplicati 2 Rock-on

M.

**Comment by schakrava** [comment]
Yup, let's close this!
