### ISSUE TITLE
Scrub feedback feature

### ISSUE THREAD

**Issue by tronder88** [rockstor/rockstor-core#1243]
Hello,

Is it possible to add status of scrub when it is finished? I.e. output is the following "status - errors fixed/not fixed"
Today the status columns has only running or finished as result.

**Comment by phillxnet** [comment]
As of:
issue: #1786 "improve scrub status reporting resolution"
and it's associated pr: "improve scrub status reporting resolution. Fixes #1786"
we have the additional states of 'halted' (interrupted), 'cancelled' (aborted), and 'conn-reset' (connection reset by peer).
Scheduled jobs already had an additional 'error' as possible end state.

However I read this issue as an indicator to additionally surface the full results of each scrub performed. This info is something we already capture but fail to provide a UI link to.

I propose that this issue can be finalised by providing a link to the already captured results of each scrub by way of making each Status column entry in the Pool details Scrub tab table and the scrub 'Task history' table into links that present a 'Scrub end state' page with a single table containing the stored output of that scrub command upon termination.

**Comment by phillxnet** [comment]
I am currently working on this issue.

**Comment by phillxnet** [comment]
In development Scrub Details page:

![scrub-details-page](https://user-images.githubusercontent.com/2521585/30129426-c6bb6fea-933d-11e7-81fa-c1f947b845e3.png)

**Comment by phillxnet** [comment]
Improved scrub details page (note errors in red):
![improved-scrub-details-page](https://user-images.githubusercontent.com/2521585/30188034-40c876a2-9424-11e7-9ab7-1bd14789ec1b.png)
and link from overview table now indicates errors:
![improved-pool-scrub-status-link](https://user-images.githubusercontent.com/2521585/30188063-591ca3c2-9424-11e7-94f1-ce7a1db3205a.png)

**Comment by phillxnet** [comment]
The commits against this issue are in final testing: I will prepare a pull request for review shortly.
All commits are on current master.

**Comment by phillxnet** [comment]
Please update the following forum thread with this issues resolution:
https://forum.rockstor.com/t/btrfs-scrub-scheduled-task-got-cancelled-no-reason-being-displayed/3638

**Comment by phillxnet** [comment]
Related fixes have been made to master since this issues branch was created. To avoid duplicate commit messages, and to aid merging, I am shortly to re-base locally on current master, delete the GitHub instance of this issue's branch, and re-push to GitHub the newly re-based code.

**Comment by phillxnet** [comment]
Successfully re-based on current master.
