### ISSUE TITLE
Unsupported Compression Algorithm Error when no option is selected

### ISSUE THREAD

**Issue by priyaganti** [rockstor/rockstor-core#1245]
In the shares detail view, under the Edit compression Algorithm section, if Submit button is clicked with the default text option saying "Don't enable compression", the following error is shown. 
  
![image](https://cloud.githubusercontent.com/assets/1999710/14301905/53062576-fb50-11e5-831c-8e12df7609de.png)

**Comment by MFlyer** [comment]
@priyaganti Got solved

**Comment by priyaganti** [comment]
Thanks @MFlyer. I have noticed the same thing today and fixed. Should have checked your comment earlier.

**Comment by schakrava** [comment]
fixed by #1248 and #1247
