### ISSUE TITLE
Windows previous version tab: Time offset

### ISSUE THREAD

**Issue by fkurth** [rockstor/rockstor-core#1252]
You decided to save the automatic share snapshots in a format like

`.share_201604091525`

The timestamp format is local time, as configured during the installation.
By default, samba is set to expect UTC here, as described in the doc here:

https://www.samba.org/samba/docs/man/manpages/vfs_shadow_copy2.8.html

This leads to an time offset in the windows prevous version tab by the differnce of the user local time including DST.

Adding 
`shadow:localtime = yes`
to each share entry in smb.conf fixes this. Please add this entry.

Anyway i would recommend to use the default naming "@GMT-%Y.%m.%d-%H.%M.%S"
for the snapshots and  do the formatting in the GUI, with timestamp timezone translation.
Having timestamps in local time will lead to further problems if the user changes the machine timezone and so on. Thats probably the reason for v_shadow_copy's default settings.

**Comment by fkurth** [comment]
Using the default format `@GMT-` would also eliminate the need for the error-prone "snapshot-prefix"

**Comment by schakrava** [comment]
Thanks for filing this issue and nicely articulating the details.
