### ISSUE TITLE
VMWare Raw Mapped LUN disks not working in 3.8-12.10

### ISSUE THREAD

**Issue by ScarabMonkey** [rockstor/rockstor-core#1264]
I installed a fresh Rockstor 3.8-12 into an ESXi 6.0 VM yesterday and it installed just fine (kernel 4.3.3)
I then added a SAN disk to the VM using 'Mapped Raw LUN' and this was found in Rockstor happily - I created a pool and a share and it all seemed fine.
Then I updated the system using the GUI by joining the Testing channel which took me to kernel 4.4.5.

Now Rockstor cannot see my disk.

I have successfully now changed this disk to be a 'Virtual Disk' in VMWare and I can use it.
I have tried adding a third disk using Mapped Raw LUN - but Rockstor does not see it.

I have installed the open-vm-tools into Rockstor using yum and also enabled Disk.UUID in VMWare (though as a point of fact, this wasn't needed for the LUN as Rockstor was seeing the UUID as created by my SAN hardware - an HP P2000 G3)

**Comment by MFlyer** [comment]
@phillxnet

**Comment by ScarabMonkey** [comment]
Well, I just built a second VM on the same host and this is not showing-up on a fresh install either ... most confusing.

**Comment by MFlyer** [comment]
So you're having issues directly on host and not related to Rockstor?!?

**Comment by ScarabMonkey** [comment]
Next I'll try doing the same for a plain CentOS 7 installation on the same host...

**Comment by ScarabMonkey** [comment]
Having updated my Hypervisor (and therefore restarted the host), I can now see the LUNs properly in rockstor - it returns the type, vendor and model correctly. Will try some other combinations of adding LUNs and not rebooting the host with CentOS and Rockstor VMs. But basically I expect this was a bug in 6.0.0 VMware.
