### ISSUE TITLE
Change chosen plugin to bootstrap-select or select2 plugin

### ISSUE THREAD

**Issue by priyaganti** [rockstor/rockstor-core#1270]
1. **Bootstrap-select** https://silviomoreto.github.io/bootstrap-select/ (Not sure if we can combine search and multiple select together)
2. *_Select2 *_  https://select2.github.io/ (Multiple select and Search available)

**Comment by priyaganti** [comment]
Choosing Select2 plugin mainly for the multi-select feature and how it's css goes well with the bootstrap we use. Other reasons why Select2 is a better option when compared to Chosen plugin can be seen here: https://www.sitepoint.com/jquery-select-box-components-chosen-vs-select2/

**Comment by schakrava** [comment]
Fixed by #1794
