### ISSUE TITLE
Error in Rock-ons gui

### ISSUE THREAD

**Issue by tronder88** [rockstor/rockstor-core#1272]
This error shows up in GUI when turning on rock-ons service:
I have 8 rock-ons running:

Unknown internal error doing a GET to /api/rockons?page=1&format=json&page_size=5000&count="

I hope logs are correctly attached
[opt 2.zip](https://github.com/rockstor/rockstor-core/files/222580/opt.2.zip)

**Comment by schakrava** [comment]
The logs show that you have a syntax error in duplicati json file. Please look at them and you'll see what I am referring to here.
