### ISSUE TITLE
Unable to build from source in a secured subnet

### ISSUE THREAD

**Issue by ScarabMonkey** [rockstor/rockstor-core#1273]
I am attempting to build a fork for testing purposes and am unable to complete the build due to it seeming to require Internet access. I always perform testing from a subnet which does not have access to the Internet for security reasons. In case it matters, this is a build of the master source as at today with the patch from pull-request 1265 applied. 

There are may good reasons for software to be buildable while not attached to the Internet - and I would think that an exec from a urlopen is rather bad practice (there is no way to be sure their server hasn't been hacked).

Here is the output:

[root@milan rockstor-testing]# python bootstrap.py -c buildout.cfg 
Traceback (most recent call last):
  File "bootstrap.py", line 78, in <module>
    exec(urlopen('https://bootstrap.pypa.io/ez_setup.py').read(), ez)
  File "/usr/lib64/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1224, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib64/python2.7/urllib2.py", line 1186, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 110] Connection timed out>

**Comment by MFlyer** [comment]
Hi @ScarabMonkey , reporting my experience under Watchguard firewall blocking zips too:

build need internet access and if I'm right some lines try to get a zip too

Flyer/Mirko

**Comment by MFlyer** [comment]
Hi @ScarabMonkey do you think we can close this issue??

Tks
Flyer/Mirko

**Comment by ScarabMonkey** [comment]
I must be old fashioned I guess, I expect to be able to get the dependencies myself rather than the build script doing that for me - at least having an option to get them manually would be nice :)

**Comment by schakrava** [comment]
It is possible to build without internet access using the following steps.

1. familiarize yourself with [buildout](http://www.buildout.org/en/latest/)
2. update buildout.cfg to use your own hosted pypi or use a different/custom buildout part to pull eggs from.
3. change the js-libs part in buildout.cfg to pull the libs from your own hosted location.

I personally don't see a need to do this for the project as a whole, but if you are up for the challenge please feel free to share your buildout recipes via another config file, eg: local-buildout.cfg or something like that.
