### ISSUE TITLE
Cleanup handlebar helpers and move to .jst files (handlebars-part2)

### ISSUE THREAD

**Issue by priyaganti** [rockstor/rockstor-core#1275]

**Comment by phillxnet** [comment]
@priyaganti I've added a couple of columns to the disks table in the referenced issue so just linking here to remind me to keep an eye on your changes so that I might try and ease merging later.

**Comment by MFlyer** [comment]
@priyaganti - @schakrava this to be closed after last PR merged

**Comment by schakrava** [comment]
Fixed by #1287
