### ISSUE TITLE
Edit AFP share must be disabled or be similar to Samba Edit. Make all export features consistent.

### ISSUE THREAD

**Issue by priyaganti** [rockstor/rockstor-core#1277]
1. Edit AFP export displays the chosen share to export. In addition to that it allows users to click and add more shares.
2. But the dropdown to choose a share is empty.

Suggestion: Remove the Share field completely and move it to the heading area (or) disable the shares field.

**Comment by Hooverdan96** [comment]
@phillxnet since we're not supporting AFP anymore, probably should close this issue ...
