### ISSUE TITLE
Make services configure forms as modals

### ISSUE THREAD

**Issue by priyaganti** [rockstor/rockstor-core#1278]
1. When clicked on the wrench icon (configure option) on some services in the services view, configure form open up in another page. Instead make it open a modal and ask the user to submit form inside the modal.

**Comment by ScarabMonkey** [comment]
It's worth noting that some service pages currently enable the service once it is configured, whereas others don't.
With a switch to modal configuration dialogues, I would propose that all services require explicit enabling after configuration.
