### ISSUE TITLE
Failed after upgrade from 3.8-12.11 to 3.8-12.13 

### ISSUE THREAD

**Issue by ScarabMonkey** [rockstor/rockstor-core#1281]
I have tried this update from the GUI on both my Rockstor VMs (one has non-mission-critical data, the other is for testing). In both cases, the service refused to start after the upgrade - in the console I see a systemd error and in /var/log/messages I see many kernel errors.

At the command-line I can perform a 'yum history undo' to go back to the older version  - which then also fails with a different error. But then I can do a yum update to get back to 3.8-12.13 and then all is well.

**Comment by phillxnet** [comment]
@ScarabMonkey Thanks for reporting this, but I can't reproduce it here I'm afraid, could you post some of the relevant log entries as that may help pin it down a tad.
I just done a 3.8-12.11 to 13 upgrade here with no issues so not much to go on just yet.

Nice find on the work around though.

As a potentially relevant point what kind of network setup did you have in these installs as I know there was a bunch of network changes that may be playing up with you type of install.

**Comment by ScarabMonkey** [comment]
Interesting... My VMs are both on the same physical hardware, which is in a 192.168 network (requiring manual proxy configuration to get internet access). I have added my proxy manually to yum.conf.

**Comment by ScarabMonkey** [comment]
And the networking is all manual.

**Comment by phillxnet** [comment]
@ScarabMonkey My upgrade earlier was with a vanilla DHCP install. Just trying to narrow it down really. The upgrades are usually pretty smooth but yes may be network config related in this case given the very recent changes there. I'm afraid I haven't had a chance to look at them properly just yet.

@schakrava ? any ideas.

**Comment by schakrava** [comment]
It doesn't sound like an issue with Rockstor bits, but probably the new 4.4.5 kernel that is the latest defaul doesn't like the setup. I'd first confirm a working kernel and then update to latest and see if that reproduces the problem. If you can isolate that Rockstor rpm package is triggering the problem, then we'll have something to debug. I seriously doubt it, but /opt/rockstor/var/log may have some clues.

Regarding network related changes, the new changes don't change any settings. But try to parse the system config and construct Rockstor level state which is then presented in the UI. If there's a problem with this, you'll see errors in the System -> Network of the UI. They should be localized. There is a low chance that rockstor-pre may be erroring out, but now I am just rambling...

**Comment by ScarabMonkey** [comment]
From what I can tell, there isn't a kernel upgrade from 3.8-11 to 3.8-13 ... 

```
[root@milan ~]# yum history list 
Loaded plugins: changelog, fastestmirror
ID     | Login user               | Date and time    | Action(s)      | Altered
-------------------------------------------------------------------------------
     5 | root <root>              | 2016-04-21 17:00 | Update         |    1 EE
     4 | root <root>              | 2016-04-21 16:59 | Downgrade      |    1 EE
     3 | root <root>              | 2016-04-21 16:39 | Update         |    1 EE
     2 | root <root>              | 2016-04-20 11:13 | I, U           |   61 EE
     1 | System <unset>           | 2016-04-20 10:45 | Install        |  484   
history list
```
```
[root@milan ~]# yum history package kernel-ml rockstor
Loaded plugins: changelog, fastestmirror
ID     | Action(s)      | Package                                              
-------------------------------------------------------------------------------
     5 | Updated        | rockstor-3.8-12.11.x86_64                          EE
     5 | Update         |          3.8-12.13.x86_64                          EE
     4 | Downgrade      | rockstor-3.8-12.11.x86_64                          EE
     4 | Downgraded     |          3.8-12.13.x86_64                          EE
     3 | Updated        | rockstor-3.8-12.11.x86_64                          EE
     3 | Update         |          3.8-12.13.x86_64                          EE
     2 | Install        | kernel-ml-4.4.5-1.el7.elrepo.x86_64                EE
     2 | Updated        | rockstor-3.8-12.x86_64                             EE
     2 | Update         |          3.8-12.11.x86_64                          EE
     1 | Install        | kernel-ml-4.3.3-1.el7.elrepo.x86_64                  
     1 | Install        | rockstor-3.8-12.x86_64                               
history package
[root@milan ~]#

**Comment by ScarabMonkey** [comment]
I have attached a portion of /var/log/messages from the time of installing the new rockstor to installing the old one again...
[cropped_messages.txt](https://github.com/rockstor/rockstor-core/files/231517/cropped_messages.txt)

**Comment by phillxnet** [comment]
@ScarabMonkey This is all quite curios, also have a look at the /opt/rockstor/var/log/rockstor.log for Rockstor specific logging.
When you say "the service refused to start after the upgrade" which service are you referring to, presumably the rockstor service, in which case maybe the following command when the rockstor service has failed to start.
```
systemctl status rockstor
```

Take care with the version numbers as I see from you're last post you have used 3.8-11 to 3.8-13 but I suspect from the title and info given of course they were meant to be:-
3.8-12.11 to 3.8-12.13. Because we did also have a 3.8-11 (http://rockstor.com/blog/news/3-8-11-rock-on-and-ui-improvements/) 

I've just done an example upgrade from and to the same versions in a KVM and you're /var/log/messages entries look pretty identical:- up until your realm and samba stuff:-
Obviously this is on testing channel updates:-
My logs stop at that point with a working 3.8-12.13 UI.
[3.8-12.11_to_3.8-12.13_messages.log.txt](https://github.com/rockstor/rockstor-core/files/231682/3.8-12.11_to_3.8-12.13_messages.log.txt)

Copying here to try and help with more info.

I say next look should be at the rockstor.log.

**Comment by ScarabMonkey** [comment]
(Versions amended in my earlier post)
Okay, I'm going to revert one of my VM's to the 3.8-12.11 snapshot and try this again - are there any useful extra logging things I could enable before trying the update?
Incidentally, why am I not offered 3.8-13 in the GUI for the Testing branch; is this only on the stable branch?

**Comment by phillxnet** [comment]
@ScarabMonkey Thanks, Can't think of any extra log things; normal logging should be enough hopefully.
Yes 3.8-13 is stable release version name of what for a short time will be the same code as testing. In this case 3.8-12.13. Testing version number will then move on as it takes more commits while stable version stays put for a bit.

**Comment by phillxnet** [comment]
@ScarabMonkey From a quick look your rockstor log does show errors relating to internet access to the repos:-
```
'Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock error was', '14: curl#7 - "Failed to connect to 2a01:c0:2:4:0:acff:fe1e:1e52: Network is unreachable"',
```
And (unrelated) you have a disk without serial which is tricky as Rockstor tracks drives by their serial number. 
There is also a time out for retrieving the root.json from rockstor.com, again network access related.

**Comment by ScarabMonkey** [comment]
Well, that's a bit embarrassing - I just reverted my 'milan' VM to the snapshot with 3.8-12.11 and then successfully updated it to 3.8-12.13 with no problems. 
This snapshot was before configuring Active Directory or even any shares - will now try reverting to 11 then configuring a test share and AD then trying a 13 update.

**Comment by phillxnet** [comment]
@ScarabMonkey No no this is all good as you are routing out a few things here and narrowing it down. And when in doubt 'more info' is mostly a good thing.

**Comment by ScarabMonkey** [comment]
Those network errors will be from before configuring yum.conf with our proxy - this machine is in a private subnet with no direct access to the Internet.
I think the disk without serial in the log will be from before I added disk.enableUUID into the VM configuration.

**Comment by ScarabMonkey** [comment]
I have just successfully upgraded from a configured v11 to v13 again with no problem. No idea why this failed for me on 2 different VMs earlier in the week. I am going to update my hypervisor in case there was some weird bug in that (6.0 to 6.0U2).
