### ISSUE TITLE
Active Directory info popup slightly misleading

### ISSUE THREAD

**Issue by ScarabMonkey** [rockstor/rockstor-core#1284]
It mentions the enumerate configuration option - which isn't an option.

**Comment by ScarabMonkey** [comment]
I have submitted a pull request for it :)

Though the file I had to modify seemed like an odd place for this info - perhaps there would be a more generic way for services to put an info thingy onto the services page?

**Comment by phillxnet** [comment]
Linking to the said pull request for ease #1285

**Comment by schakrava** [comment]
You have a good point @ScarabMonkey . @priyaganti is looking into that. It will also make translations easy, we are shamefully behind on that front.

Thanks for the pull request, btw!.

Fixed by #1285
