### ISSUE TITLE
RFE: allow a scheduled task to run only once at a time

### ISSUE THREAD

**Issue by roweryan** [rockstor/rockstor-core#1300]
I have a scrub that takes some time to run, I'd like the assurance that two scrubs won't run at once I guess :)

**Comment by MFlyer** [comment]
Hi @roweryan , actually when running scheduled scrubs there's a check for scrub state, so if old task is still running no new scrub get executed.

Can you close this one? thanks

**Comment by roweryan** [comment]
@MFlyer my rfe isn't for scrubs, it's for scheduled tasks in general

**Comment by MFlyer** [comment]
Ho @roweryan , actually scheduled tasks under Rockstor are scrubs and snapshots:
- scrubs scheduled task is ok (see previous post)
- snapshots scheduled task should be ok too (it's so fast to take a snapshot that it would be really strange to have same scheduled task overlapping with previous one)

Do you agree on that?

Other option: are you running 2 different tasks on same data so they can overlap? (this is the only case i can think about)

Thanks
Flyer

**Comment by roweryan** [comment]
ok
