### ISSUE TITLE
Active Directory service complains too much about NTP

### ISSUE THREAD

**Issue by ScarabMonkey** [rockstor/rockstor-core#1301]
The Active Directory service will not allow you to configure it while NTP is disabled.

Since the service is not enabled until it is explicitly turned on - there is no need to nag the user about NTP configuration until the time that the service is actually enabled.

Note that this behaviour is somewhat different from most services which automatically become enabled when they are configured.

**Comment by ScarabMonkey** [comment]
https://github.com/rockstor/rockstor-core/pull/1298

**Comment by schakrava** [comment]
Fixed by #1298
