### ISSUE TITLE
Yum $releasever is not resolved

### ISSUE THREAD

**Issue by greghensley** [rockstor/rockstor-core#1303]
In repo URLs, `$releasever` is resolved based on the version of the package assigned to the `distroverpkg` setting in `/etc/yum.conf`.  By default, this is `centos-release` which, in RockStor, is replaced by `rockstor-release`.  Since `centos-release` is not present, Yum does not resolve `$releasever`, breaking compatibility with third-party repos which use this variable in their URLs as well as giving us cache paths like `/var/lib/yum/repos/x86_64/$releasever/`.

Since `rockstor-release` version numbers do not track CentOS releases, it cannot be used for `distroverpkg` and maintain compatibility with third-party CentOS repositories.  I propose adding a new package (such as `rockstor-upstream-release`) as a dependency of `rockstor-release` which tracks the version of CentOS upon which each RockStor release is based.  Then `/etc/yum.conf` can be updated to use this package for version resolution: `distroverpkg=rockstor-upsteam-release`.

**Comment by Hooverdan96** [comment]
@phillxnet I assume, this is still relevant?

**Comment by phillxnet** [comment]
@Hooverdan96 Re:

> I assume, this is still relevant?

Not so much, we pretty much leave the os-release file alone with regard to critical versioning and upstream info. We are obliged to change some things and we have done mostly now we are openSUSE only. So closing as resolved give we have had not reports for some years of this sort, i.e. unregognised OS essentially.
