### ISSUE TITLE
Replication task creation only displays shares from first page of shares.

### ISSUE THREAD

**Issue by williamstlr** [rockstor/rockstor-core#1305]
I'm attempting to create a new replication task and I've noticed that I can't select any share that is on page 2 from my shares list. When I compare the shares that are available to select from for the replication task, the range of shares matches exactly what I see when I'm looking on page 1 of System > Shares. I've never created an issue so I'm hoping that I've done this correctly.

**Comment by phillxnet** [comment]
@williamstlr Thanks for reporting this, very succinctly and clearly put. That's a nice find. I'm afraid I'm not up on the mechanisms involved just yet and it may take a little while to track down but this is a good start.

**Comment by priyaganti** [comment]
@williamstlr Thanks a lot for pointing this out. I guess this issue has always been there but I have never noticed. I I was able to understand how inconvenient it was when trying to test replication task with a share on the 2nd page.

**Comment by williamstlr** [comment]
@priyaganti That's fantastic, thanks for taking your time to fix this one up.
