### ISSUE TITLE
Revise internal use and format of device names

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#1320]
In order to increase the flexibility and utility of the db Disk.name field it is proposed that it be re-deployed to hold by-id device names as opposed to the current ‘sd’ type names. This in combination with the Disk.role field is intended to aid in supporting additional storage options such as LUKS full disk encryption.

Ie change:
/dev/sdX derived from a db entry of sdX
to:
/dev/disk/by-id/wwid-for-device derived from a db entry of wwid-for-device.

A World Wide Identifier (WWID) is a persistent and system independent identifier required of all SCSI standards compliant devices.
Reference:-
https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Storage_Administration_Guide/persistent_naming.html

**Comment by phillxnet** [comment]
I am currently working on this issue.

**Comment by phillxnet** [comment]
- [ ] convert btrfs import mechanism to by-id name use.
- [ ] convert APM level reporting to by-id name use.
- [ ] convert Power State / spin down config and reporting to by-id name use.
- [ ] convert SMART subsystem to by-id name use.
- [ ] revise fake dev name for missing devices mechanism as now legitimate device name (by-id) and fake dev name collision is far more likely than before.

**Comment by phillxnet** [comment]
From fs/btrfs/scan_disks we have:
# 12 chars (fake-serial-) + 36 chars (uuid4) = 48 chars
Given our move to much long by-id type names we should no longer just use the length of this serial as a flag for a device with no original serial number.
Checked by handlebar helper checkSerialStatus storageadmin/static/storageadmin/js/views/disks.js

**Comment by phillxnet** [comment]
get_dev_byid_name looks for:-
DEVLINKS=/dev/disk/by-id/virtio-test-serial22222
in for example (for a virtio of vdd):-
udevadm info --query=property --name vdd
This is created by udev from the model "virtio" and the serial "test-serial22222"
In the case of a virtio without a serial ascribed to it we have no DEVLINKS  as there is no serial for it to be drawn from!
This causes get_dev_byid_name to return None (by design) which has created the "violates not-null constraint" on Disk.name field. Previously we used the vdd device name but due to this missing DEVLINKS entry in the output of at least virtio devices without serial we need a graceful and meaningful failover.
I am leaning towards failing back, in this circumstance, to the original name.
Will pick this up again soon.

**Comment by phillxnet** [comment]
Disk.name by-id conversion mostly done and all disk and pool functions appear to be working, bar dealing with corner case serial issues.
I now just need to debugging (see above) and clean a few things up.

**Comment by holmesb** [comment]
This will be a great improvement.  For one thing it will make installing in a XenServer VM possible using the normal method possible.  Xen uses /dev/xvdx rather /dev/sdx device names, so currently have to use a [workaround](https://forum.rockstor.com/t/installation-in-a-xen-vm/427/20?u=grizzly).

**Comment by phillxnet** [comment]
@holmesb Thanks for chipping in more info on this one; but I'm afraid this won't have any effect on the actual install, sorry. But I'm hoping it will have other 'good' effects. At least that's my aim.

**Comment by phillxnet** [comment]
Almost there now I think, just need to address re-arrangement todo's and maybe slip a few more clean-ups in and a fair bit more testing then this should be ready for review. Currently working as expected but with loads of logging.

**Comment by phillxnet** [comment]
- [ ] Investigate apparent anomaly in current logging which suggests a blank base name returned in SMART query, yet no malfunction!

**Comment by phillxnet** [comment]
Disk's and Pools pages with by-id type names:-
![disks_by-id](https://cloud.githubusercontent.com/assets/2521585/15759489/b5b3ecb0-2906-11e6-9681-6489a585f4c8.png)

![pools_by-id](https://cloud.githubusercontent.com/assets/2521585/15759497/bb4b0d02-2906-11e6-9126-741c297c4bb6.png)
