### ISSUE TITLE
Field validation in e-mail setup

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-core#1340]
Here's an e-mail bug report

Hi,

when entering a wrong formated relayhost adress fort the email alerts, the email alert functionality can become unconfigurable over the web ui.

i accidently copied a relayhost with leading blanks. This resulted in an entry in the main.cf of postfix that blocks further config tries by the web ui.

If the malformed relayhost is corrected with SSH, everything works fine again.

I suggest a better validation of this field.

Haven't found any issues regarding this.

**Comment by MFlyer** [comment]
To @schakrava, not told on these 2 PR : obviously I had some tests before PR eheh :)
