### ISSUE TITLE
Issues with afp share name

### ISSUE THREAD

**Issue by djevo1** [rockstor/rockstor-core#1347]
It would be useful to be able to change the share name so it doesn't contain any space. This is the case when it adds on rockstor at the end of the share name. It is currently only fixable if the netatalk conf file is edited to remove the name of the share.

**Comment by timorjim** [comment]
I agree, having share names with "on rockstor" attached is awful IMO.

**Comment by phillxnet** [comment]
Linking to forum member fva.taimyr recent post on a potential solution to this long standing issue:
https://forum.rockstor.com/t/chnage-share-name-on-afp/1597/3

**Comment by FroggyFlox** [comment]
Closing as we no longer use AFP so this issue is now irrelevant.
