### ISSUE TITLE
Make Appliance UUID persistent

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-core#1348]
Currently, appliance UUID is dynamically generated during setup time using a combination of hostid and uuid generated by python's uuid library. Because it's generated purely by Rockstor code during setup time, it's not persistent across reinstalls.

If we make the uuid persistent, by using a hardware generated one, it would eliminate the pain of having to generate a new stable subscription activation code every time Rockstor is installed on the same hardware. Luckily, someone in the community told us exactly [how to get](https://forum.rockstor.com/t/reinstall-activation/1234/4) this uuid from /sys/class/dmi/id/product_uuid.

**Comment by williamstlr** [comment]
I'm just curious to see if you know, but run my Rockstor appliances as virtual machines, how would using the product_uuid work in that case with Rockstor? Looking at the values of two VM's on the same hypervisor (ESXi) I get two different UUID's.

**Comment by schakrava** [comment]
I verified that in case of Virtualbox and KVM they are unique. Glad to get your confirmation that it's the case on ESXi as well. Not sure if I understand your question correctly, but the expectation is that 2 VMs on the same hypervisor each get a UUID.

**Comment by williamstlr** [comment]
Sorry, I didn't explain that too well there. If I end up rebuilding my Rockstor appliance on a VM, say I end up deleting the old VM to rebuild, how will activation by UUID work there? I guess ideally you would keep the same VM, wipe the VHDs or add new ones, but if a VM is deleted and a new one is created it will have a new UUID, how would activation be handled in that case?
