### ISSUE TITLE
missing header package for 4.6 kernel

### ISSUE THREAD

**Issue by ERFier** [rockstor/rockstor-core#1355]
I updated to the new rockstor 3.8-14 which uses the new 4.6 kernel. I use some dkms modules to make e.g. my sas controller working under linux. The new version lacks a kernel-header package which makes it imposible for dkms to compile the module for the new kernel. Please add the corresponding header package to the repo.

**Comment by phillxnet** [comment]
@ERFier Thanks for the report, may just have got missed some how in some recent repo changes. @schakrava  another one for you I'm afraid.

**Comment by schakrava** [comment]
Sorry about that and thanks for filing the issue @ERFier . It should be available now.

**Comment by ERFier** [comment]
The issue isn’t solved. The package is available but its contents are stored in the wrong directory. DKMS uses the /lib/modules/$(uname -r)/build dir that links to /usr/src/kernel/$(uname -r). For the 4.4 kernel there is a dir containing the kernel source tree with makefiles in each dir but no sourcecode. The Include folder contains the header files. Your package on the otherhand installs only the include dir to  /usr/include. The rest of the sourcetree and especially the Makefiles are missing. A simple link to the right destination didn’t solved the problem cause of the missing Makefiles.
