### ISSUE TITLE
Add local/current time on the UI

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-core#1362]
Here's a user report

What i find a little annoying is that there is no current time shown on the Dashboard. I can see uptime, but how can i tell if my system is running on the right local time? Yes, i have this set at the Installation, but to know if time is correct and to maybe set another timeserver it would be nice to have this in the Dashboard or under System Menu to control and set.

How can i check the current time and timeserver? Should i go to the Terminal and try the right commands for centOS?

**Comment by MFlyer** [comment]
Suggestion: always avoid getting time and refresh via a js `setInterval`, because it's a really destructive method (common reason for RAM abuse by browser)
Better to grab ex. via sysinfo websocket and just update a div text

Flyer
