### ISSUE TITLE
Rockstor disappears from network and requires reboot

### ISSUE THREAD

**Issue by djevo1** [rockstor/rockstor-core#1363]
I have rockstor setup with a static ip and am having issues of keeping it visible on the network. At random intervals it will disappear and can only be accessed via ssh.

**Comment by MFlyer** [comment]
Good morning @djevo1 , can you provide some Rockstor logs??

Thanks
Flyer

**Comment by djevo1** [comment]
Where can I get the logs from

**Comment by MFlyer** [comment]
Hi @djevo1 , from shell `/opt/rockstor/var/log/` where you can find rockstor.log and other useful logs

You can access logs via web ui too (if you have access to web ui)

BR
Flyer/Mirko

**Comment by djevo1** [comment]
[log.zip](https://github.com/rockstor/rockstor-core/files/343738/log.zip)

**Comment by MFlyer** [comment]
I'll look to your logs asap and i think other contributors will do the same :smiley:

**Comment by phillxnet** [comment]
@MFlyer and @djevo1 the smartctl errors are harmless (apart from log volume) and result from a lack of default smartmontools compatibility hence the "Unknown USB bridge" and originate from the Sony MicroVault Flash Drive. They may be silenced by adding a custom smart option of either  "-d sat" and if that doesn't work you could try "-d scsi" via the pen icon in the Disk page for this device. The SMART on this device may then appear to be available but in the case of many flash drives may well not provide full SMART capabilities and consequently may result in Web-UI presented error messages when trying to gain more SMART info. But given one of these custom SMART options may circumvent the "Unknown USB bridge" the log entries issue at least, may be addressed.

**Comment by MFlyer** [comment]
Ok, so reading @phillxnet last post and back to logs i think this is related to some Rock-ons problems.
@djevo1 pls check if without Rock-ons it's ok or not

**Comment by djevo1** [comment]
So I disabled rockons and I rebooted, and then I received this error 
which may have something to do with the issue.

             Traceback (most recent call last):
   File "/opt/rockstor/src/rockstor/rest_framework_custom/generic_view.py", line 40, in _handle_exception
     yield
   File "/opt/rockstor/src/rockstor/storageadmin/views/network.py", line 353, in post
     network.toggle_connection(nco.uuid, switch)
   File "/opt/rockstor/src/rockstor/system/network.py", line 170, in toggle_connection
     return run_command([NMCLI, 'c', switch, uuid])
   File "/opt/rockstor/src/rockstor/system/osi.py", line 98, in run_command
     raise CommandException(cmd, out, err, rc)
CommandException: Error running a command. cmd = ['/usr/bin/nmcli', 'c', 'up', 'a0a1d9fb-1dc6-43b5-a681-bc1fc24d9df0']. rc = 4. stdout = ['']. stderr = ['Error: Connection activation failed.', '']

**Comment by djevo1** [comment]
Update: I can no longer access the shares on my network or the web-ui. I 
may need to perform a fresh install; what is the process to do this 
without loosing the current RAID?

**Comment by MFlyer** [comment]
I think - considering network errors - now we need @schakrava help too :)

**Comment by djevo1** [comment]
After some troubleshooting it appears a portion of the problem was due 
to a faulty network switch. The unit does appear on the network but I 
still have rock-ons disabled.

**Comment by MFlyer** [comment]
Hi @djevo1 , try to turn on again rock-ons so we can check :wink:

**Comment by djevo1** [comment]
I turned on Rock-ons and it was working fine but then it became 
unresponsive and I had to reboot and it no longer appears on the network 
again.

**Comment by MFlyer** [comment]
Hi @djevo1, i supposed this is related to Rock-ons / a specific Rock-on, can you please list currently running Rock-ons. Asking for @phillxnet and @schakrava help on Rock-ons

**Comment by djevo1** [comment]
I can no longer disable rock-ons and am getting this error when 
attempting to get rockstor to start:

Traceback (most recent call last):
   File "/opt/rockstor/bin/initrock", line 44, in <module>
     sys.exit(scripts.initrock.main())
   File "/opt/rockstor/src/rockstor/scripts/initrock.py", line 418, in main
     run_command([PREP_DB, ])
   File "/opt/rockstor/src/rockstor/system/osi.py", line 98, in run_command
     raise CommandException(cmd, out, err, rc)
system.exceptions.CommandException: Error running a command. cmd = 
['/opt/rockstor/bin/prep_db']. rc = 1. stdout = ['']. stderr = 
['Traceback (most recent call last):', '  File 
"/opt/rockstor/bin/prep_db", line 44, in <module>', '    
sys.exit(scripts.prep_db.main())', '  File 
"/opt/rockstor/src/rockstor/scripts/prep_db.py", line 63, in main', '    
create_setup()', '  File 
"/opt/rockstor/src/rockstor/scripts/prep_db.py", line 57, in 
create_setup', '    if len(setup) == 0:', '  File 
"/opt/rockstor/eggs/Django-1.6.11-py2.7.egg/django/db/models/query.py", 
line 77, in __len__', '    self._fetch_all()', '  File 
"/opt/rockstor/eggs/Django-1.6.11-py2.7.egg/django/db/models/query.py", 
line 857, in _fetch_all', '    self._result_cache = 
list(self.iterator())', '  File 
"/opt/rockstor/eggs/Django-1.6.11-py2.7.egg/django/db/models/query.py", 
line 220, in iterator', '    for row in compiler.results_iter():', '  
File 
"/opt/rockstor/eggs/Django-1.6.11-py2.7.egg/django/db/models/sql/compiler.py", 
line 713, in results_iter', '    for rows in self.execute_sql(MULTI):', 
'  File 
"/opt/rockstor/eggs/Django-1.6.11-py2.7.egg/django/db/models/sql/compiler.py", 
line 785, in execute_sql', '    cursor = self.connection.cursor()', '  
File 
"/opt/rockstor/eggs/Django-1.6.11-py2.7.egg/django/db/backends/__init__.py", 
line 162, in cursor', '    cursor = util.CursorWrapper(self._cursor(), 
self)', '  File 
"/opt/rockstor/eggs/Django-1.6.11-py2.7.egg/django/db/backends/__init__.py", 
line 132, in _cursor', '    self.ensure_connection()', '  File 
"/opt/rockstor/eggs/Django-1.6.11-py2.7.egg/django/db/backends/__init__.py", 
line 127, in ensure_connection', '    self.connect()', '  File 
"/opt/rockstor/eggs/Django-1.6.11-py2.7.egg/django/db/utils.py", line 
99, in __exit__', '    six.reraise(dj_exc_type, dj_exc_value, 
traceback)', '  File 
"/opt/rockstor/eggs/Django-1.6.11-py2.7.egg/django/db/backends/__init__.py", 
line 127, in ensure_connection', '    self.connect()', '  File 
"/opt/rockstor/eggs/Django-1.6.11-py2.7.egg/django/db/backends/__init__.py", 
line 115, in connect', '    self.connection = 
self.get_new_connection(conn_params)', '  File 
"/opt/rockstor/eggs/Django-1.6.11-py2.7.egg/django/db/backends/postgresql_psycopg2/base.py", 
line 115, in get_new_connection', '    return 
Database.connect(**conn_params)', '  File 
"/opt/rockstor/eggs/psycopg2-2.6-py2.7-linux-x86_64.egg/psycopg2/__init__.py", 
line 164, in connect', '    conn = _connect(dsn, 
connection_factory=connection_factory, async=async)', 
'django.db.utils.OperationalError: could not connect to server: No such 
file or directory', '\tIs the server running locally and accepting', 
'\tconnections on Unix domain socket 
"/var/run/postgresql/.s.PGSQL.5432"?', '', '']

**Comment by djevo1** [comment]
Is there a way to re-install rockstor without loosing the settings or 
drive pools?

**Comment by phillxnet** [comment]
@djevo1 The following sections in the official docs may be of interest:
http://rockstor.com/docs/config_backup.html#config-backup
and
http://rockstor.com/docs/reinstall/reinstall.html
with regard to your: "Is there a way to re-install rockstor without loosing the settings or
drive pools?"
This of course assumes you have no data stored on the system disk and that the UI is working for the config backup section anyway.
Hope that helps.
Sorry not that up on the Rock-on side of things though.

**Comment by djevo1** [comment]
Ok i can no longer access the the ui and I sent the error that is 
generated when I try to initialize it manually. I reinstalled rockstor 
using yum and am still getting the error I sent.

**Comment by Hooverdan96** [comment]
@phillxnet is still an issue (7 years ago) or can we assume this resolved for now (along with partner issue #1381)

**Comment by FroggyFlox** [comment]
Agreed. Given how much everything has evolved dive then, this unfortunately no longer applies.
