### ISSUE TITLE
Active Directory password in clear text in config backup

### ISSUE THREAD

**Issue by ScarabMonkey** [rockstor/rockstor-core#1373]
I just noticed that the Active Directory password is stored in clear text in the 'config backups' output.

I propose that this should be at least hashed in some way. 

Also, to mitigate the risk, the GUI could advise against using an AD admin account for this purpose - merely an account with the permission to 'add workstation to the domain' - which in many AD implementations is any standard user.

**Comment by MFlyer** [comment]
Hi @ScarabMonkey , agree with you and found the same thing times ago in domain join too, but i think it can't be any different (domain join in linux done with clear text password)

My suggestion: create a not admin user able to join machines to domain and instead use that one, so if someone find that pass you won't give any admin access (except for adding machines)

Flyer

**Comment by MFlyer** [comment]
Hi @ScarabMonkey do you think we can solve this just by adding a tooltip suggesting a non admin user with less privileges??

Flyer

**Comment by MFlyer** [comment]
@schakrava my opinion:
we can close this
- AD Admin pass is under Rockstor db
- Rockstor db has pass access
- Rockstor db avail only with root shell

M.

**Comment by MFlyer** [comment]
To @schakrava : we can close this
M.

**Comment by schakrava** [comment]
Thanks @MFlyer and @ScarabMonkey
