### ISSUE TITLE
Scheduling of pause/resume of btrfs scrubs

### ISSUE THREAD

**Issue by zhongfu** [rockstor/rockstor-core#1374]
Right now, the ioprio switch on `btrfs scrub` doesn't seem to have much effect (even if the priority of the `btrfs scrub` processes is reported as "idle", as expected). Running any scrubs murders I/O performance, and often brings many things to a crawl.

In lieu of an actual solution (perhaps something similar to ZFS scrub tuning), btrfs scrubs could perhaps be paused/resumed according to a schedule, so any scrubs can be automatically paused when responsive I/O is desired, and resumed at other times (e.g. scrubbing during nighttime).

**Comment by tfiskgul** [comment]
The ionice has little effect on btrfs as you have stated, but I have found something else that is a nice workaround; using cgroups blk io controller.

Using [systemd resource control](https://www.freedesktop.org/software/systemd/man/systemd.resource-control.html), I have created a slice called ``background.slice``, which has ``BlockIOReadBandwidth`` set for slower devices. This is using cgroups v1. For cgroups v2, use the ``IOReadBandwidthMax`` option.

I then use the following command to start / resume the scrub:
``sudo systemd-run --slice background.slice --scope btrfs scrub resume /path/to/mount``

**Comment by phillxnet** [comment]
@tfiskgul This is a nice find, thanks for sharing. I would like to suggest that you post the same on our forum:

https://forum.rockstor.com/

as I think it may reach more folks that way.

Thanks again for sharing your findings and after a little discussion on the forum we may very well be able to bake this approach into our scrub initialisation code as a configurable option via the Web-UI.

**Comment by tfiskgul** [comment]
@phillxnet Thanks for the quick feedback =)

I've created the post in the [rockstor forums](https://forum.rockstor.com/t/reducing-scrub-io-impact/4815).
