### ISSUE TITLE
Snapshot exclusive size erroneously reported

### ISSUE THREAD

**Issue by zhongfu** [rockstor/rockstor-core#1376]
On the snapshots screen (and in the per-share snapshot listing), the exclusive size of each snapshot seems to be the total size of the snapshotted subvolume. When deleting snapshots, this can lead to scary warnings (e.g. deleting a snapshot with no changed data reports that it will "permanently delete [amount] of data").

`btrfs qgroup show` reports the correct (or at least, a seemingly correct) exclusive size of each snapshot/subvolume.

**Comment by MFlyer** [comment]
Cross ref to #1412, checking shares and snapshots usage and now all seem fine

M.
