### ISSUE TITLE
smb.conf overwritten when workgroup name is set

### ISSUE THREAD

**Issue by zhongfu** [rockstor/rockstor-core#1378]
When the workgroup name for samba is set (in System -> Services -> Samba), `smb.conf` is overwritten with just the `global` section along with the configuration for any shares exported with samba:

```
[global]
    workgroup = WORKGROUP
    log file = /var/log/samba/log.%m
    log level = 3
    load printers = no
    cups options = raw
    printcap name = /dev/null

####BEGIN: Rockstor SAMBA CONFIG####
[media]
    comment =
    path = /mnt2/media
    browseable = yes
    read only = no
    guest ok = no
    admin users = zhongfu
[public]
    comment =
    path = /mnt2/public
    browseable = yes
    read only = no
    guest ok = no
    admin users = zhongfu
####END: Rockstor SAMBA CONFIG####
```

 Any other lines are removed, including comments and configuration directives that were present in the original configuration file.

**Comment by MFlyer** [comment]
Hi @zhongfu , had some time so checked your issue:

Rockstor simply missing customs params on global section of samba, so every direct edit on smb.conf get lost if you change smb workgroup (there's a full smb.conf rewrite).

Customization possible only on single shares and I quite agree with current Rockstor policy: under Linux samba usually works fine without particular settings (not the same on bsd systems)

Flyer

**Comment by schakrava** [comment]
@zhongfu please test this on the latest update(3.8-14.05 or later). You can now see and edit the global section of samba config in the UI. I'll close this issue for now. But please feel free to re-open/comment.

**Comment by MFlyer** [comment]
To @schakrava sorry, currently latest update not running on my dev env so didn't realize we can edit global smb.conf xD
