### ISSUE TITLE
Allow scheduling of read-only snapshot creation

### ISSUE THREAD

**Issue by zhongfu** [rockstor/rockstor-core#1379]
In the snapshot creation scheduling screen in the Scheduled Tasks menu, there's no option to allow the creation of read-only snapshots. As a result, all snapshots made are writable, which may not be desirable in some cases:

- When snapshots are visible to the user, they'll be able to modify the contents within
- When snapshots are exposed through samba as shadow copies, users can delete/modify copies of files. Disabling that can possibly solve #1230, preventing ransomware (and users) from deleting the snapshots' contents.

**Comment by LIvewire18** [comment]
I agree, this should be a very easy fix and being a NAS administrator for a Fortune 50 company, I agree this is VERY important to have.

**Comment by tomtom13** [comment]
Just created a pull request for being able to set "writable" in the GUI.

**Comment by schakrava** [comment]
Fixed by #1446
