### ISSUE TITLE
add cli initiated config backup

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#1382]
In cases where Rockstor's Web-UI has failed catastrophically a cli initiated config-backup could play a valuable part in disaster recovery scenarios as it would then be possible to archive the current config and retrieve the resulting file via scp and then execute a pool / share import and config restore procedure.

The file could be stored identically to the current Web-UI backups and in the same format, ie zipped json in /opt/rockstor/static/config-backups. Obviously some cli feedback indicating the success or otherwise of the command should also be incorporated. And given the use of the same location and format, if the cli command fails at least the user would be led to finding previous config backups if they exist.

A related function here could be an automated config-backup just prior to every Rockstor update procedure.

**Comment by daniel-illi** [comment]
I'm interested to work on this feature. As I don't have much experience with python (coming from ruby/java world), I need some pointers where to start.

I see that the config backup functionality is implemented in [ConfigBackupListView#post](https://github.com/rockstor/rockstor-core/blob/master/src/rockstor/storageadmin/views/config_backup.py#L186).
I suppose the backup code should get extracted in its own stand-alone service class which can be used from the view and from the cli script.
Where should such service classes be placed in the project tree?

**Comment by schakrava** [comment]
@daniel-illi great to hear you like to contribute! python should be super easy coming from java. You should read up on console scripts in python. and take a look at [setup.py](https://github.com/rockstor/rockstor-core/blob/master/setup.py). You can also look at src/rockstor/scripts directory for various scripts that become binaries via console scripts mechanism.

You are right about extracting the view logic out into it's own callable. I haven't looked at the code recently, but sounds about right. I wouldn't call it "service" though. It can just be a function that's imported in your script as well as the view. This code can go under system/

Feel free to be bold with your changes.

**Comment by daniel-illi** [comment]
@schakrava thanks for the pointers.
I'll implement a first version and will open a pull request for you to comment.

**Comment by schakrava** [comment]
Fixed by #1576
