### ISSUE TITLE
Let Rockstor open modules pages in a pop up window

### ISSUE THREAD

**Issue by MFlyer** [rockstor/rockstor-core#1387]
Will working on #518 I realized it can be useful to have some Rockstor pages able to open in a detached window too (ex. having shell access inside Rockstor is ok, but it becomes really useful if you can move to other pages while having your shell open! )

What do you think about this @phillxnet @schakrava @priyaganti ?
Flyer

**Comment by phillxnet** [comment]
@MFlyer This seems like a good idea but I'm not sure how it would affect the complexity of the UI code and if it does negatively impact there it may not be worth it. As one could always open another tab / page and achieve similar results. So not really up enough on the ramifications to say one way or the other at the moment.

**Comment by MFlyer** [comment]
Hi @phillxnet , going to provide an example over shell (actually only page i really find useful to have on a "modal/detached" page).
My idea was to have detached pages like an option for some pages, not like a default, and so is going to be for shell page (via configuration page :wink: )

**Comment by MFlyer** [comment]
Hi @phillxnet , I'd like to have your opinion about this "on the fly" solution for Rockstor shell :smiley: 

This is how i modified rendering func on router.js

```javascript
 	showShell: function() {
 -		this.renderSidebar('system', 'shell');
 -		this.cleanup();
 -		this.currentLayout = new ShellView();
 -		$('#maincontent').empty();
 -		$('#maincontent').append(this.currentLayout.render().el);
 +		//Special router function for shell
 +		//We fetch shellinaboxd service model and check for detach option
 +		//If not present or false we go with normal layout to maincontent
 +		//otherwhise (popup enabled) we open it in a new detached window
 +		var _this = this;
 +		_this.shell_service = new Service({name: 'shellinaboxd'});
 +		_this.shell_service.fetch({
 +		success: function(collection){
 +			var config = JSON.parse(collection.get('config'));
 +			if ('detach' in config && config.detach){
 +					window.open('/shell', '', 'width=800, height=600');
 +			} else {
 +				_this.renderSidebar('system', 'shell');
 +				_this.cleanup();
 +				_this.currentLayout = new ShellView();
 +				$('#maincontent').empty();
 +				$('#maincontent').append(_this.currentLayout.render().el);				
 +			}
 +		}});
```
Fetch data from Service model for shellinaboxd service, check the ad hoc field "detach".
If not set or false normally render shell inside rockstor, otherwise if detach true open a new window

Obviously this can be extended to other pages (actually not thinking about which pages really need this, but we can have it :wink: )

Before develop probably we could choose pages needing this option @schakrava - @priyaganti too

**Comment by phillxnet** [comment]
@MFlyer Sorry but I'm a little weak on the web programming side so can't really comment on if this is a good idea / approach or not. However @schakrava and @priyaganti are much stronger in these areas so would have to go with their judgement on this one. But looks straight forward enough to me; if it's viable.

Have you trialled it as presented?

**Comment by MFlyer** [comment]
Addendum: Diving into Rockstor i realized currently detached pages make sense just for shell, not sure for other modules.
Issue left open to have a bookmark on it, but with priority equal nearly to zero :)
