### ISSUE TITLE
Changing hostname does not update postfix config

### ISSUE THREAD

**Issue by greghensley** [rockstor/rockstor-core#1392]
After changing the hostname via the WebUI, the file `/etc/postfix/generic` still contains re-mapping directives for the old hostname.  As a result, mail is sent to the configured SMTP forwarder without remapping the sender.  Since the default sender is `<user>@<hostname>.localdomain`, most ISPs' SMTP forwarders will reject the message as the `.localdomain` TLD is not resolvable.

This should be considered silent failure, since users will simply stop receiving notifications.  The only ways for users to detect that a problem exists is by either sending a test email from the WebUI, or accessing the root account from a shell and checking its mail spool (postfix returns the undeliverable mail).

Removing and re-adding the email configuration in the Rockstor WebUI correctly updates the postfix config.

**Comment by MFlyer** [comment]
Hi @greghensley working on it, probably going to solve it today

Flyer
