### ISSUE TITLE
Headless Mode

### ISSUE THREAD

**Issue by junland** [rockstor/rockstor-core#1396]
I would like to propose a headless mode for Rockstor, this headless mode would deactivate the web gui but still expose the REST API. By doing this, it would accomplish:

* Make it better for better for developers to write / test there own front-ends with the REST API (Which is a feature, but I haven't seen in documentation on it yet).
* Reduce overhead of other machines which have Rockstor on them that you want to connect to one machine with it's web gui enabled.

Keep up the good work!

**Comment by MFlyer** [comment]
Hi @junland , this obviously is my personal opinion: 
Rockstor is a full nas solution (backend + web UI) and not just a framework of rest apis (you can google and find some btrfs tools doing this).

Flyer

**Comment by schakrava** [comment]
Rockstor is already headless. When you access the web-ui, it runs in your browser. REST API exists, and if you know DRF, you can figure it out. but it's not documented :(

Having said that, we have to do a lot of work to make Rockstor APIs consumable by other developers. I invite you to work with us in making that happen! Hope you'll consider it.

**Comment by MFlyer** [comment]
@schakrava can we close this?
M.
