### ISSUE TITLE
boot usb is labled as floppy disk

### ISSUE THREAD

**Issue by BlakeMccon27** [rockstor/rockstor-core#1403]
After the recent updates to rockstor my NAS now recognizes my boot USB as a floppy disk. When I select it to boot nothing happens and it only automatically recognizes it about one quarter on the time. I do not have a floppy drive installed or ever have had one installed.

**Comment by phillxnet** [comment]
@BlakeMccon27 Rockstor itself has no concept of a floppy disk as such so I think your issue revolves around bios settings. Until this can be narrowed down more I suggest you open a forum thread where you are likely to receive more eyes on this. I haven't seen this myself but maybe other forum members have and can advise.

https://forum.rockstor.com/

My assessment is based on the selection and recognition of boot device as a bios level thing which happens before any installed system, such as Rockstor. However during some updates new kernels are installed but the basic boot loader remains unchanged, and that is the part of the boot device that the bios uses to recognise the nature and viability of a boot medium. Sounds like a failing USB key to me.

**Comment by FroggyFlox** [comment]
Closing this as we assume this has been resolved or has been waiting for feedback for a long time.

**Comment by BlakeMccon27** [comment]
I haven't used rockstor in years. XD Yes please close this issue. I have to
commend you guys for checking in on this issue however.
