### ISSUE TITLE
single pool metadata level is single not dup

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#1409]
The current default of a single pool metadata level appears to be single also. My understanding was that in the case of single pool creation we intended metadata to default to dup, not single:
https://forum.rockstor.com/t/internal-implementation-of-pools-shares-snapshots-and-clones/453

```
btrfs fi df /mnt2/single-pool/
Data, single: total=8.00MiB, used=64.00KiB
System, single: total=4.00MiB, used=16.00KiB
Metadata, single: total=248.00MiB, used=128.00KiB
GlobalReserve, single: total=16.00MiB, used=0.00B
```

Tested on current master branch.

This would also bring our single data pools in line with the rockstor_rockstor single pool profile ie:

```
btrfs fi df /mnt2/rockstor_rockstor/
Data, single: total=3.37GiB, used=2.71GiB
System, DUP: total=8.00MiB, used=16.00KiB
System, single: total=4.00MiB, used=0.00B
Metadata, DUP: total=471.50MiB, used=165.94MiB
Metadata, single: total=8.00MiB, used=0.00B
GlobalReserve, single: total=64.00MiB, used=0.00B
```

so single data and dup metadata. It would also provide a more robust default without sacrificing much in the way of space.

Comments?

**Comment by schakrava** [comment]
Hi @phillxnet. dup metadata profile for single pools is a good idea and also recommended by BTRFS. Something we should've changed a while ago. Many thanks for digging it up!
