### ISSUE TITLE
Wrong shares size on Total Capacity, Allocation and Usage Widget

### ISSUE THREAD

**Issue by MFlyer** [rockstor/rockstor-core#1441]
While coding on #998 - Total Capacity, Allocation and Usage Widget finally I found out why my "shares" total size is wrong.
Looking to these 2 images
![widget](https://cloud.githubusercontent.com/assets/17988902/18750031/b8ac3ba4-80d9-11e6-90b8-b6a683af0cdb.jpg)
![shares](https://cloud.githubusercontent.com/assets/17988902/18750037/bd9f5a4c-80d9-11e6-9343-8a3dc915fee9.jpg)

shares capacity = sum of each share size without taking care of single share sizesare overlapping on same pool.
From storage_metrics.js view
```javascript
this.share = this.shares.reduce(function(sum, share) {
    sum += share.get('size');
    return sum;
}, 0);
```
Installation time shares home & root both have pool size as max size, but that doesn't mean every share can be full size (home+root = pool size max, shared space)

Going to solve it (client side) on next Widgets PR

**Comment by MFlyer** [comment]
On f1bd52a we hack total shares size:
group shares by pool, get pool size, get shares under current pool total size (conditional _.reduce) and if greater than pool size this means current shares have shared space, so we assume shares size = pool size.

Don't like it at all (btrfs quota with reserved space shares would be the right way), but this commit fits well regardless of btrfs quota or not.

Flyer

**Comment by sfranzen** [comment]
@MFlyer re quota:
Yes, I have also made this suggestion in a forum post, but I think I've read that enforcing limits can currently lead to large btrfs overhead. I'll do some more reading about it tomorrow.
