### ISSUE TITLE
Adding codeclimate on Rockstor repository

### ISSUE THREAD

**Issue by MFlyer** [rockstor/rockstor-core#1447]
Hi @rockstor/developers while coding over #998 (Part 6 by this evening / tomorrow :grin: ) had also some times over codeclimate and created this:

https://codeclimate.com/github/rockstor/rockstor-core

What do you think about adding it over our repo / checking it?

Flyer

**Comment by gkadillak** [comment]
Why not just use a CI server via a Rockon?

**Comment by sfranzen** [comment]
Haha, that's a big list of big red Fs :stuck_out_tongue:

**Comment by MFlyer** [comment]
To @sfranzen : know that, codeclimate config file missing to (part of those big red blinking baloons are because of this :grin: )
To @gkadillak : ??? I didn't mean a CI server over Rockstor, but a CI tool for Rockstor developers over github

**Comment by sfranzen** [comment]
I think it's pretty cool, it pays attention to far more stuff than my IDE does. So all you have to do is put a config file in the repo and one of those badges in the readme?

**Comment by MFlyer** [comment]
> I think it's pretty cool, it pays attention to far more stuff than my IDE does. So all you have to do is put a config file in the repo and one of those badges in the readme?

Not so easy, I just glanced it quickly and like every CI tool some config is required, but i really appreciated some nice features like redundant code, etc

**Comment by gkadillak** [comment]
@sfranzen why do you say that?

**Comment by sfranzen** [comment]
@gkadillak because that's how I figured it would work; MFlyer wants to configure it on this repository to analyse our code and PRs.

**Comment by MFlyer** [comment]
It's not only to "monitor" our coding, but to provide some all others good open source projects have

**Comment by MFlyer** [comment]
Closing issue, found we're moving to Travis :+1:
