### ISSUE TITLE
Rockstor js libs md5 mismatch

### ISSUE THREAD

**Issue by MFlyer** [rockstor/rockstor-core#1451]
Hi @schakrava, found this out while building on Rockstor:

new js libs file now has bootstrap-editable, but buildout.cfg hasn't been updated

To @rockstor/developers : new md5 is `c28902888396a702e06518507f8ceae8`

Copy&paste it over buildout.cfg or merge my buildout branch :wink:

**Comment by gkadillak** [comment]
👍

**Comment by schakrava** [comment]
I can't slack at all around you guys. It was a bit late last night when I broke it and I left to pick it up today.. not fast enough. Should be fixed once I get home shortly. Sorry @MFlyer and @gkadillak

**Comment by MFlyer** [comment]
Hi @schakrava this is not required anymore, already solved over @priyaganti PR merged (js lib file was updated before PR merge causing md5 mismatch, but now md5 is ok)

Closing issue & PR too
