### ISSUE TITLE
auto update copyright years using a buildout part

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-core#1468]

**Comment by sfranzen** [comment]
Personally I think it's not that important to meticulously update these things; the copyright exists automatically regardless of this and the history of each file is already recorded by git. However, suppose I soon file a pull request introducing some new files, it would definitely be incorrect to list any year other than 2016. Is there an elegant solution to this?

**Comment by FroggyFlox** [comment]
Closing this as not longer applicable to our build system.
