### ISSUE TITLE
"Share is owned by root"

### ISSUE THREAD

**Issue by k0nsl** [rockstor/rockstor-core#1473]
I tried to add a sFTP share on my Rockstor instance and it wasn't possible. As per:
![screenshot from 2016-10-12 16-31-35](https://cloud.githubusercontent.com/assets/2517921/19314168/75e6ece0-9099-11e6-81e1-101a772ca509.png)

**Comment by phillxnet** [comment]
@k0nsl There are some limitations on sftp shares in Rockstor and this error is consistent with those limitations.
Please see the official docs for information on acceptable share ownership for sftp access:
Secure File Transport Protocol (SFTP) section at:
http://rockstor.com/docs/sftp/sftp.html
If your problem persists within those limitations can you report back here.

Thanks for the report.
