### ISSUE TITLE
Dashboard TOP10 share usage does go out of borders on mini view

### ISSUE THREAD

**Issue by tomtom13** [rockstor/rockstor-core#1476]
Hi,
As in title, the dash board item for TOP10 share usage seems to drop through the bottom of the rectangle and draw on unused page. 

ps. when there is a widget under it it will draw under or over depending on mood :)

![fireshot screen capture 006 - rockstor - tevva-server_ home](https://cloud.githubusercontent.com/assets/22304458/19318742/c97afb00-90a1-11e6-9d55-1a6b01431b47.png)

**Comment by MFlyer** [comment]
Hi @tomtom13 , thanks for this.
Had lot of testing with other widgets, less with this one (same over pool widget, #1477 fixes that too)

Mirko

**Comment by tomtom13** [comment]
Cheers guys !
