### ISSUE TITLE
Required locale to US conversion / code to avoid time comparison failing

### ISSUE THREAD

**Issue by MFlyer** [rockstor/rockstor-core#1479]
Reference to [this](https://forum.rockstor.com/t/unable-to-check-update-due-to-a-system-error-time-data-mo-20-jun-2016-does-not-match-format-a-d-b-y/2178) forum thread:

user Uwe_Ganswig (German locale) reported Rockstor failing over update process
rpm_build_info fails [here](https://github.com/rockstor/rockstor-core/blob/master/src/rockstor/system/pkg_mgmt.py#L99) expecting a US/UK abbreviated weekday.

Requires patching

**Comment by sfranzen** [comment]
Heh, opened an issue for this just seconds after you did. There is also a number format issue (comma as decimal separator) at [this place](https://github.com/rockstor/rockstor-core/blob/master/src/rockstor/system/osi.py#L318).

**Comment by MFlyer** [comment]
Update: check latest messages on Rockstor forum thread
