### ISSUE TITLE
Linked to #1379 - writable snapshots

### ISSUE THREAD

**Issue by MFlyer** [rockstor/rockstor-core#1482]
Reference to recently closed #1379

Manual snapshots from shares/[sharename]/snapshots label don't work: @tomtom13 do you wanna care about this? :) it's a wrong control over radio button writable

Mirko

**Comment by tomtom13** [comment]
Me no speak Americano :) Had you fixed that in 1482 ? or is it for me to fix ?

**Comment by MFlyer** [comment]
xD eheh
Hi @tomtom13, first I had this new issue then, having some free time and thinking about next Rockstor stable, decided to code it over #1483

**Comment by tomtom13** [comment]
Cool :)
