### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by djevo1** [rockstor/rockstor-core#1485]
In order to get rockstor to show up as a server in AFP shares I modified the netatalk conf to add the following line.

https://forum.rockstor.com/t/simple-afp-setting-request/2201/6

```
[Global]
; Global server settings
 mimic model = RackMac (G)
```

![screen shot 2016-10-17 at 8 56 56 am](https://cloud.githubusercontent.com/assets/16768999/19438553/8dd24888-9448-11e6-9dcc-71e77d533680.png)

**Comment by MFlyer** [comment]
Hi @djevo1,
I'm not an "Apple guy" so just one question: can we consider this as our default for all Mac users??
If yes, going to code it (if you don't do it :) )

**Comment by djevo1** [comment]
Yes this can be the default for all mac users. I am new to github, I would add it myself but not sure how to do so.

**Comment by MFlyer** [comment]
Do you have a Rockstor Development environment? If no you can start here:
http://rockstor.com/docs/contribute.html#developers

**Important**: **Never** try to build over a production env, Rockstor building will clean your `/opt/rockstor` folder

**Comment by djevo1** [comment]
I will check that out, you can add the change for now.

**Comment by MFlyer** [comment]
Ok, if you need help building your development environment please ask on our forum and we'll help you :wink:

**Comment by megema** [comment]
Could you change it from RackMac to Xserve? RackMac seems not to working in more recent macOS versions.
