### ISSUE TITLE
Systemd warns that "rockstor-hdparm.service is marked world-inaccessible"

### ISSUE THREAD

**Issue by maxhq** [rockstor/rockstor-core#1493]
As already mentioned [before](https://github.com/rockstor/rockstor-core/issues/885#issuecomment-216206193), systemd keeps logging this:

> Oct 21 01:14:20 Sigurd systemd[1]: Configuration file /etc/systemd/system/rockstor-hdparm.service is marked world-inaccessible. This has no effect as configuration data is accessible via APIs without restrictions. Proceeding anyway.

It can easily be fixed manually by executing:

```
chmod 0644 /etc/systemd/system/rockstor-hdparm.service
```

And it makes me feel much better :D

**Comment by phillxnet** [comment]
@maxhq Thanks for bringing this up again and nice to have it in an issue of it's own.

From a quick look I think where the rockstor-hdparm.service file is concerned we can apply the required chmod directly after moving the edited temp file over the live file with the following line:
```
run_command([CHMOD, '644', '/etc/systemd/system/rockstor-hdparm.service'])
```
along with a definition for CHMOD at the head of the file.
```
CHMOD = '/usr/bin/chmod'
```
Previously (in your linked reference) I had thought that this systemd overly restrictive rights warning affected many systemd files but upon looking just now it seems to only affect this one Rockstor created systemd file. Only had a quick look though so if you could confirm this that would be a help.

Do you fancy changing this issue's title to reference this one file if that is also your finding as then I can commit these changes against your issue and have the branch name used be more specific:
ie "hdparm systemd wrong rights warning" or some such thing.

Cheers. And yes this would also make me feel at least a little better :D.

**Comment by maxhq** [comment]
Hi @phillxnet, yes it only affects this one file. Of course you are right and I should have put in a more concrete title in the first place :-)
I guess that the problem might be the function [update_hdparm_service](https://github.com/rockstor/rockstor-core/blob/de82a836763f6acaf23ea880e7ca734d9e6211f2/src/rockstor/system/osi.py#L1471) where a new file is created without changing the access rights.

**Comment by phillxnet** [comment]
@maxhq Do you fancy having a go at this one, since we have pretty much sorted it already in this issue. I can add it to my queue otherwise. Given the relatively harmless nature I don't think we need account for existing file permissions only the newly created. Users can always trivially adjust spin-down times and get the new perms that way.

No worries otherwise as it was my code and my omission so more than happy to get to it but must finish my current run before that.

**Comment by phillxnet** [comment]
@maxhq Just noticed @schakrava has assigned himself on this one so if you start on it do make a note here just in case.

**Comment by phillxnet** [comment]
@maxhq No worries, it looks like @schakrava has now fixed this in indicated pr. Sorry for noise folks.
