### ISSUE TITLE
enhance disk role/management subsystem

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#1494]
In order to enhance the capability and flexibility of Rockstor's disk management a disk 'role' field was introduced in https://github.com/rockstor/rockstor-core/commit/cc7cfc1750cafa43b3a7c8192faa1bdce5c22f10 . This field was initially used to identify mdraid disk members in #1164 . In pr #1314 this role field was moved to a json format, as advised by @schakrava , enhancing it's general purpose use, (see commit https://github.com/rockstor/rockstor-core/commit/4935f06c99bb41976a0836390b4eb5f67c575328 ).

Given the requirements presented by  #550 (Support full disk LUKS) and #1157 (Support backup to USB devices) it is proposed that we move the existing disk identification system fully over to using the 'role' db field. Currently there is still an 'overloading' of the "parted" flag in storageadmin/views/disk.py DiskMixin _update_disk_state() to signify 'unusable' or unsupported devices or file-systems. This potentially complicates support of extended role devices such as may be used in for example external USB 'import' / 'export' type roles which may very well be partitioned. Moving over to using the role field exclusively should therefor centralise and simplify device management and classification and aid in this subsystems utility.

It is therefor proposed that the 'overloading' of the parted flag be removed and superseded by the disk role field to allow for enhanced device support. ~~In later pull requests~~ this role field could be user assigned via links within the disk page that take the place of the "Click to wipe it clean" cog that instead ascribes one or more compatible roles to a device as well as the existing option to wipe the device prior to the usual default whole disk btrfs device role.

**Comment by phillxnet** [comment]
My intention is to address this issue next; given time constraints.

**Comment by phillxnet** [comment]
The initial overloading of the parted flag starts in scan_disks()
```
disks item = Disk(name='sda3', model='QEMU HARDDISK', serial='QM00005', size=7025459, transport='sata', vendor='ATA', hctl='2:0:0:0', type='part', fstype='btrfs', label='rockstor_rockstor', btrfs_uuid='ef6737b7-6e81-4902-80a2-e450935d3031', parted=False, root=True)
```
Here we have a system partition that has parted=False as partitioned drives are historically disqualified drives; but in this case we flip this flag to not disqualify our root=True drive. So partially redundant flags given as of #1166 "improve root not in partition behaviour and mdraid member labeling" we can handle root not in a partition but the overloading of the parted flag here is confusing: hence the move to disk roles. This in turn should help with supporting external drives for export / import / sync roles that are likely to be partitioned.

**Comment by phillxnet** [comment]
We also overload the parted flag within scan_disks() caller disk.py _update_disk_state():
```
            # If attached disk has an fs and it isn't btrfs
            if (d.fstype is not None and d.fstype != 'btrfs'):
                dob.btrfs_uuid = None
                dob.parted = True  # overload use of parted as non btrfs flag.
                # N.B. this overload use may become redundant with the addition
                # of the Disk.role field.
```

**Comment by phillxnet** [comment]
Role subsystem re-write in progress: appetiser for Rockstor root drive identification:
![system-drive-identification-via-role](https://cloud.githubusercontent.com/assets/2521585/20072502/97f44da0-a520-11e6-9831-744fa5ceef91.png)
Note the 'R' logo.

Role code should be much improved and more in keeping with the rest of _update_disk_state()

A little more time and testing and we should have an extensible disk role system in place.

**Comment by phillxnet** [comment]
We can now use a disk's role field to reject or accept it's viability as a pool member.
From the last commit and associated console logs:
```
add_pool ACCEPTING ROLE OF null
add_pool ACCEPTING ROLE OF openLUKS json = {"openLUKS": "dm-name-luks-8f0bfeb8-d5c2-4846-a604-ae8846217ba1"}
add_pool ACCEPTING ROLE OF null
add_pool REJECTING ROLE with json = {"LUKS": "8f0bfeb8-d5c2-4846-a604-ae8846217ba1"}
add_pool ACCEPTING ROLE OF null
add_pool REJECTING ROLE with json = {"mdraid": "linux_raid_member", "backup-task": "syncthing-backup-task"}
add_pool REJECTING ROLE with json = {"mdraid": "linux_raid_member"}
```

**Comment by phillxnet** [comment]
Some progress on roles, initially to accommodate full disk LUKS containers, openLUKS mapped disks and pool use of openLUKS mapped devices:

Container:
![luks-container](https://cloud.githubusercontent.com/assets/2521585/20324522/d42f766a-ab78-11e6-9e7e-03125d8156cf.png)

Mapped open container:
![open-luks-disk](https://cloud.githubusercontent.com/assets/2521585/20324552/eef8ed46-ab78-11e6-88a6-7ebe39454193.png)

Pool using above disk:
![luks-pool-teaser](https://cloud.githubusercontent.com/assets/2521585/20324604/03d9deaa-ab79-11e6-9f2c-7cd685da7d56.png)

Pretty incomplete and mid development but in progress.

**Comment by phillxnet** [comment]
The following is the role system flagging 2 bcache backing devices and a single bcache caching device (double link) and the consequent virtual block devices (from their respective backing devices) are used to create a bcache-test-pool.
![bcache-caching-dev-with-2-backing-devs](https://cloud.githubusercontent.com/assets/2521585/20642812/428cf542-b411-11e6-8ae3-f4f0e36021f1.png)

Thanks to forum member ghensley ( @greghensley on GitHub ) for schooling me on bcache and developing and providing the required udev rules to test bcache role capabilities.

This is not an indication of pending official bcache support just a test case to help inform the development of the disk role subsystem in this issue.

**Comment by phillxnet** [comment]
Test of pool on full disk LUKS on virtual bcache devices:
![luks-pool-on-bcache](https://cloud.githubusercontent.com/assets/2521585/20649192/fb97cefa-b4b0-11e6-9da4-d932444a510d.png)
Only the open LUKS volumes are presented as pool member options once the bcache virtual block devices are make into LUKS containers(padlock). Prior to that the bcache backing devices (link icon) are not available for pool creation, only their consequent virtual devices.

In the above example the raw devices were make into bcache backing devices (single link icon) and associated with a caching device (double link icon). At this point the backing devices become unavailable for pool creation. This results in the bcache-<backing device-model-serial> devices appearing which can then be used as the backing device's 'cached' proxies. These devices were then luksFormatted which in turn made them unavailable for pool creation as, once opened, their consequent dm-name-luks devices are their consequent mapped device. These openLUKS volumes were then used as the virtual drives for the "luks-pool-on-bcache" pool.

**Comment by phillxnet** [comment]
Successfully re-based on current master branch after first having removed existing GitHub branch to help preserve clean history. GitHub branch by the same name has now been re-established.

**Comment by phillxnet** [comment]
Hopefully just a little more debugging / refining to go on this one and and it should be ready for pr. Aiming at early next testing channel updates.

**Comment by phillxnet** [comment]
Currently extending this issue a little more to include a rudimentary UI component to set and remove 'redirect' roles as this will help with testing the behaviour of this non scan_disks managed role. The only role of this type currently implemented.

**Comment by phillxnet** [comment]
My next task here is to complete the back-end wipe / redirect interplay to ensure we don't do both at the same time. Front end already has 2 layers of constraint on this but back-end should also be made aware.

- [ ] Add back-end wipe capability / role interplay awareness and constraint.
- [ ] Add user indicators of drive redirect (partition use) in pool resize and pool create disk tables.
- [ ] Testing of combined front and back end functionality re redirect role assignment and removal.
- [ ] Testing of new delete mechanism embedded in role config form.
- [ ] Code tidy.
- [ ] Comments tidy.

**Comment by phillxnet** [comment]
This issue is dependant on pr #1607 as it contains generic device add improvements.

**Comment by phillxnet** [comment]
I have again successfully re-based on current master branch after first having removed the existing GitHub branch to help preserve clean history. GitHub branch by the same name has now been re-established. This is to accommodate upstream fixes and help to ease merging as this issue is approaching a pull request soon.

N.B. as there has now been 2 re-bases this issue lists each commit multiple times.

**Comment by phillxnet** [comment]
I have again re-based on master to account for changes in #1615.

To avoid complex merging I have replaced existing master files with my own variants as the referenced pr predominantly involved Flake8 compliance (code formatting). I will endeavour to re-assert those code formatting changes in this pr as there has been significant code / logic change here so I have favoured these changes over the formatting changes in #1615.

**Comment by phillxnet** [comment]
Almost there folks, pr should be just around the corner.

**Comment by dbivolaru** [comment]
For the backup support I propose the following:
- Backup role for a subvolume (native, ie `btrfs send | btrfs receive` from snapshot or a higher level of abstraction like `btrbk` which can take a schedule and creates appropriate timestamp folders and manages snapshots and backup retention levels)
- Archive role for a disk (native, see above, just doing a recursive subvolume copy 1:1, ie `btrbk archive`)
- Non-native Backup role for a subvolume/disk (non-Btrfs target like USB device, implements any `rsync -av` like system)
- Add a new section under Storage called Backup to manage btrbk.conf schedules.
