### ISSUE TITLE
Backup question

### ISSUE THREAD

**Issue by k0nsl** [rockstor/rockstor-core#1497]
Hello,

I was wondering about backup since I need to replace the disk where Rockstor is installed. Can I do a "clean installation" and then simply restore the backup generated in the browser based interface of Rockstor, and then all my pools and such will be back to the previous stage?

...that would have been ideal!

If that's not possible, I suppose I'll have to generate an image of the current disk which hosts the operating system, then restore that image on the new disk. A bit more cumbersome and time-consuming as I would need to also shrink the disk image because the target disk is smaller.

Thanks in advance for any suggestions.

**Comment by k0nsl** [comment]
I suppose I've already got the answer by reading the documentation, which states:

> Since Rockstor can dynamically detects Pool, Share and Snapshot information after an external change like a reinstall, there is no need to save this information. While the above list covers the essentials of the whole state, the following state information is not currently saved to a backup. There are plans to add these states to the list of saved states in the future.

However, I wanted to be absolutely certain that there would be no issue affecting my pools when I decide to perform a clean installation.

**Comment by phillxnet** [comment]
@k0nsl I think this question would be best asked on the rockstor forum:
https://forum.rockstor.com/
As you are likely to get more feedback that way, given that it's a general usability question.

But I would say that the config backup and the data (pools / shares) import are 2 different mechanisms.

You have already referenced the "Configuration Backup and Restore" section of the docs:
http://rockstor.com/docs/config_backup.html#configuration-backup-and-restore
But it is in turn referenced by the more directly relevant "Reinstalling Rockstor" page:
http://rockstor.com/docs/reinstall/reinstall.html#reinstalling-rockstor
Which goes through the procedure for re-installation and specifically the subsection of "Data Import"
http://rockstor.com/docs/reinstall/reinstall.html#data-import section. 

I have created an issue in the doc repository to address the lack of a reciprocal link between these pages:
https://github.com/rockstor/rockstor-doc/issues/156
Thanks for bringing this to light with your question.

Hope the above pointers helps.

**Comment by phillxnet** [comment]
@k0nsl @schakrava I propose that this issue has been address by my last response here and is more appropriate as a forum / support topic anyway so can be closed. @k0nsl Hope you are OK and please go ahead and close this if your are in agreement as there is little more that is actionable.
