### ISSUE TITLE
[Maintenance issue] Rockstor code cleaning

### ISSUE THREAD

**Issue by MFlyer** [rockstor/rockstor-core#1505]
Hi all,
while coding on #1503 had a 20-30 minute "playing" with gunicorn.conf.in when - while having no results - I said "wait, we use buildout" and finally got my gunicorn running with desired worker (python-socketio integration over Rockstor Django...really not having fun :/ ) by coding on buildout files.
Not starting with buildout -> my fault, but I realized once again we have tons of garbage.
I can check over it, and @phillxnet could do too, but IMO our best "Garbage Collector" candidate is @schakrava 
Reason: you had initial Rockstor code 4-5 years ago and you probably know what's not required anymore better then anyone else.

Why asking for garbage collection?
- easier coding for current contributors
- easier learning / better Rockstor skeleton understanding for future contributors

@schakrava obviously I'll help on cleaning everytime I'll find something no more required and i think @phillxnet 'll do same :)

**Comment by schakrava** [comment]
I believe we cleaned up most of the dead code in the 3.9.0 cycle.

**Comment by MFlyer** [comment]
@schakrava agree on closing this after big cleaning on 3.9.0 cycle, although I think we still have some redundant code (quite sure I've seen some dupe funcs, ex. file compression with tar)
