### ISSUE TITLE
[Feature enhancement - 3.8-16] Disks widget upgrades

### ISSUE THREAD

**Issue by MFlyer** [rockstor/rockstor-core#1506]
Forum user KarstenV asking for some improvements on Disks widget (ref. https://forum.rockstor.com/t/the-new-disk-activity-widget-possible-enhancements/2275):

- Disks having always same color (already planned while coding, skipped to close all widgets PR)
- Disks detail chart for all disks

**Comment by phillxnet** [comment]
Closing as no further interest.
