### ISSUE TITLE
WebUI user has cripeled path

### ISSUE THREAD

**Issue by BuritoSlinger** [rockstor/rockstor-core#1511]
As of 3.8.15-0  the webui admin user I used suddenly is missing /usr/local/sbin and /usr/sbin in path when logging in via SSH.  The account is not usable for administration this way, as not even 'ls' works. 

When I ssh into the system via the 'root' user, and then 'su into my webui user, then the path is set correclty and the account usable.  

Sorry but my linux knowhow is not sufficient to find place where bash sets the path.

**Comment by MFlyer** [comment]
Hi @BuritoSlinger ,
had some tests over Rockstor ShellinaBox and it seems ok with root user.

Can you please provide more infos?
Mirko

**Comment by BuritoSlinger** [comment]
Correct,  but I have to use ssl as login does not work,  and it says ssl is not so secure with root,  so I wanted to use the administrative user for the web interface,  which is possible,  but with crippled path
Regards
Paul

Am 7. November 2016 09:26:49 MEZ, schrieb Mirko Arena <notifications@github.com>:
>Hi @BuritoSlinger ,
>had some tests over Rockstor ShellinaBox and it seems ok with root
>user.
>
>Can you please provide more infos?
>Mirko
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/rockstor/rockstor-core/issues/1511#issuecomment-258773532

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by MFlyer** [comment]
How to connect to shellinabox
LOGIN: no direct root access, that's normal
SSH: root access allowed (if you didn't disable it)

LOGIN auth: use your rockstor user then su to root

**Comment by BuritoSlinger** [comment]
OK,  then maybe I have another bug.  When I first used the shellinabox the screen showed an ngix error 'bad gateway'.  The I switched to ssh and it worked...  For root.. The I switched back to login,  and now the screen opens and it immediate shows connect button in the middle.   Press that,  and the screen flicker and shows the connect button again. I presume it takes to let the user log in,  but something kills the connection.  
I would post a log,  if I knew which one
Regards Paul

Am 7. November 2016 10:14:02 MEZ, schrieb Mirko Arena <notifications@github.com>:
>How to connect to shellinabox
>LOGIN: no direct root access, that's normal
>SSH: root access allowed (if you didn't disable it)
>
>LOGIN auth: use your rockstor user then su to root
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/rockstor/rockstor-core/issues/1511#issuecomment-258782902

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by MFlyer** [comment]
Hi @BuritoSlinger , you can start with nginx log files

**Comment by BuritoSlinger** [comment]
I configured the shell in a box to use login, and went to the "System Shell" menu, the window poped up and showed "Session Closed" and a "connect" button in the middle.  I then went to the "Logs manager" and exported all NGINX logs, but nginx stderr and stdout showed nothing meaningful ("package upgarde", three times) but the access log did have "shell in a box" entries. Hope that helps.

[var.zip](https://github.com/rockstor/rockstor-core/files/576401/var.zip)

**Comment by BuritoSlinger** [comment]
Then I switcht the shellinbox service back to ssh and went to "System Shell", logged in as the webui user and tried "ls" which did not work,  exited with "exit" and reconnected via the "connect" button in the middle of the screen and logged in a root.  Then "ls" worked.  Then I went to the logging section again and got: 
[Req02_ssh.zip](https://github.com/rockstor/rockstor-core/files/576426/Req02_ssh.zip)

Don't know if that helps ... sorry.

**Comment by MFlyer** [comment]
Hi @BuritoSlinger , that access log doesn't help us

What happens if you query with `journalctl -u shellinaboxd.service` ?

**Comment by BuritoSlinger** [comment]
Hi @MFlyer, 
first, thanks for helping me with this!

thats what the terminal looks like...  

[root@rocky ~]# journalctl -u shellinabox.service                                     
-- Logs begin at Sun 2016-11-06 13:17:50 CET, end at Tue 2016-11-08 07:01:52 CET. --  
[root@rocky ~]# 

probably does not help much. 

I did a fresh virtual box installation and tried the shell without touching the configuration at all, and I got what I got initially on my production system:
![shell_err01](https://cloud.githubusercontent.com/assets/17932230/20088927/c6a6aef0-a583-11e6-8b02-3799c5e43a09.png)

Looked at the nginxwebui log but it looked the same as on my production machine... not helpful.

What is required to actually try to debug this?  Do i have to get pycharm?

**Comment by BuritoSlinger** [comment]
OK played around with the VM and went to the connfig of the shellinabox service.  Selected "login" although it was already selected and went to system shell, and it worked!  Changed the config to all combinations [login/ssh][Popup yes/popup no] can only log in to "login" with webui user, and with "ssh" only with root.  So I presume it works as designed.

So I guess something is messed up with my production environment... is there a config file I can manually copy over to my prod environment to fix this?

**Comment by BuritoSlinger** [comment]
Whoops just realized my VM is on 3.8.14-22 and my prod is on 3.8.15-0 ....

**Comment by MFlyer** [comment]
So finally is that working or not?!?
It should be ok as 3.8.14-22 equals 3.8.15
M.

**Comment by BuritoSlinger** [comment]
Well, I was hoping the problem was due to the higher version I'm my prod env.  But is they are the same,  then I have something quirky in prod, which would be good if fixed.  

Am 8. November 2016 09:12:47 MEZ, schrieb Mirko Arena <notifications@github.com>:
>So finally is that working or not?!?
>It should be ok as 3.8.14-22 equals 3.8.15
>M.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/rockstor/rockstor-core/issues/1511#issuecomment-259072362

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by MFlyer** [comment]
Hi @BuritoSlinger ,
I'm here not forgetting this, can you provide a feedback with last updates on 3.8.15-* ?
Can we have this closed? (one of your last messages having it working) or not? :)
M.

**Comment by BuritoSlinger** [comment]
Updated to 3.8.15-9 and with that to the new Kernel 4.8.7
Still the "login" version will not allow me to log in, as the "session closed" ist the only thing the shell shows.
If I use the "ssh" version login will only work with root, as all other users (which are able to log in) seem to have no drive mounted ('ls' is an unknown command, only 'pwd' works and that shows only '/' and cd in any other directory leads to "no such file or directory"

**Comment by MFlyer** [comment]
Hi @BuritoSlinger ,
reading your last post I can say shellinabox is working as expected, let me explain:
- ssh with root enabled is ok
- login with no root login is ok (you need to login with your rockstor user then `su` to root)

Having session closed is quite normal, shellinabox is a running service and sometimes goes on timeout, so don't worry about that.

Talking about ssh with access only on root user: that's normal, check this `cat /etc/ssh/sshd_config`
```shell
Subsystem       sftp    internal-sftp
###BEGIN: Rockstor SFTP CONFIG. DO NOT EDIT BELOW THIS LINE###
AllowUsers root
```

Rockstor default has only root able to ssh :)

M.

**Comment by MFlyer** [comment]
As far as I'm concerned we can close this @schakrava @BuritoSlinger 

M.

**Comment by BuritoSlinger** [comment]
sorry for the late reply, yes lets close it
