### ISSUE TITLE
network stack overhaul

### ISSUE THREAD

**Issue by tomtom13** [rockstor/rockstor-core#1517]
I would like to use this issue to fix a lot of stuff in networking stack:
- manual settings sometimes don't work
- manual setting can magically suck in additional setting from dhcp and populate it magically inside of gui (yeah, scary ... init)
- related to previous, when trying to fix this problem by going to edit page again and removing ALL dhcp aquired setting leaving only manual IP address that one would wish to have ... after hitting submit all manual setting disappear and you only get left with dhcp ones (checked with ifconfig to be true on interface as well). After togling interface OFF then back ON problem seems tobe fixed.
- bonding only works on initial setup, after reboot it's bonkers
- after setting up a bonding in 802.3ad for 4 interfaces and rebooting in VMware, this made interfaces go into crazy loop and get rockstor stuck. Forced reboot and removal of interfaces just to get to logon screen made rockstor forget my log on detail (possible config corruption ?)
- teaming is just plainly defunct
- manual setting forces to put in a random gateway that makes it put route with higher priority than dhcp one resulting in rockstor not being able to access internet. 
- Clicking a pencil (for edit) button on network connection sometimes takes you to 100% unpopulated network page ... but if you stick on the network page for longer than 30 seconds and click the pencil button it then takes you to a properly populated page.

ps. guy could you please pile on any problems you see with networking setup ? I can join it here.

**Comment by tomtom13** [comment]
Just adding more stuff :/
- manual setting forces to put in a random gateway that maker it hit route with higher priority than dhcp one resulting in rocstor not being able to access internet.

**Comment by tomtom13** [comment]
- Clicking a pencil (for edit) button on network connection sometimes takes you to 100% unpopulated network page ... but if you stick on the network page for longer than 30 seconds and click the pencil button it then takes you to a properly populated page.

![fireshot capture 1 - rockstor - https___192 168 44 129_ network_edit_6](https://cloud.githubusercontent.com/assets/22304458/20243257/f0c7a60e-a947-11e6-97e9-8a690ebc6a82.png)
![fireshot capture 2 - rockstor - https___192 168 44 129_ network_edit_6](https://cloud.githubusercontent.com/assets/22304458/20243259/f2d0b206-a947-11e6-9181-ca3bac0e2681.png)

**Comment by tomtom13** [comment]
- after setting up a bonding in 802.3ad for 4 interfaces and rebooting in VMware, this made interfaces go into crazy loop and get rockstor stuck. Forced reboot and removal of interfaces just to get to logon screen made rockstor forget my log on detail (possible config corruption ?)

**Comment by Hooverdan96** [comment]
We have not made many changes in the underlying area (judging by the PRs related to `network.py` view. Do we consider this still being an issue at this time, though (since both base OS, UI libraries, etc. have gone through all kinds of changes and upgrades)?

**Comment by phillxnet** [comment]
@Hooverdan96 Lets close this as we have changed the entire underlying OS and @FroggyFlox has redone some network stuff in the interim. Plus it is easier to action less large scoped issues: without dedicated outside contributions as I believe this one started out as.
