### ISSUE TITLE
owncloud official - adding caching to accelerate performance x10

### ISSUE THREAD

**Issue by tomtom13** [rockstor/rockstor-core#1519]
Hi,

on every instalation of owncloud official I have to manually add this to the config:

'memcache.local' => '\OC\Memcache\APCu',

would it be better just to patch the original install to have it in ? most of users will already do it anyway.

**Comment by MFlyer** [comment]
Hi @tomtom13 ,
probably better have this under rockstor/rockon-registry : can you code this ? :)

**Comment by tomtom13** [comment]
I can try :smile_cat: , I just put bugs on queue to get solved in future. If somebody is desperate before I finish my network fun - be my guest

**Comment by Hooverdan96** [comment]
@FroggyFlox any recollection whether something on this was done over in the rockon repo? I don't recall, and I am not sure whether this goes into the json itself as an environment variable.
In any case, if this is still open, we should close this and move it over to the Rockon registry to be dispositioned.

**Comment by FroggyFlox** [comment]
Agreed... I thought we already deprecated the owncloud Rock-On, to be honest. It's no longer maintained and too old a version.

**Comment by Hooverdan96** [comment]
It's still in the repo, but yes, we talked about removing it.

**Comment by phillxnet** [comment]
> It's still in the repo, but yes, we talked about removing it.

Linking to @FroggyFlox issue re this Rock-ons removal: https://github.com/rockstor/rockon-registry/issues/357
