### ISSUE TITLE
Add "dup" target for pool.

### ISSUE THREAD

**Issue by tomtom13** [rockstor/rockstor-core#1521]
I just realized that there is no duplication target for pool. 

Shouldn't be that much of a hassle to add.

(and yes I can add code it.... just populating the queue for the future)

**Comment by dbivolaru** [comment]
Just realized it's also missing for resize. There are multiple places where that would need to be updated. Did you get to work on it yet?

The use cases not covered in the UI are:
- new dup
- single -> dup
- dup -> single
- raidN -> single (requires additional input which drive to keep)
- raidN -> dup (requires additoinal input which drive to keeep)
- dup -> raidN

**Comment by tom-vixake** [comment]
Since nobody wanted it I did not moved with it.

**Comment by Hooverdan96** [comment]
@phillxnet is this still relevant, or superseded with the addition of various RAID profiles, etc.?

**Comment by phillxnet** [comment]
@Hooverdan96 Thanks for the legacy issue triag here.

As we now support mixed raid profiles, closing as:
Fixed by #2524

See: "Add mixed raid levels #2520" #2524

Where we expand our options regarding target btrfs-raid profiles to a common subset, where some dup additions were made.
