### ISSUE TITLE
[Major bug] Endless loops over data_collector.py

### ISSUE THREAD

**Issue by MFlyer** [rockstor/rockstor-core#1522]
While investigating a glitch over modal views #1500 had a check over data_collector.py too and luckily had an important find:

from data_collector.py services status emitter:
```python
class ServicesNamespace(BaseNamespace, BroadcastMixin):

    def recv_connect(self):
        self.emit('services:connected', {
            'key': 'services:connected', 'data': 'connected'
        })
        self.spawn(self.send_service_statuses)

    def recv_disconnect(self):
        self.disconnect()

    def send_service_statuses(self):
        while True:
            data = {}
            for service in Service.objects.all():
                config = None
                if (service.config is not None):
                    try:
                        config = json.loads(service.config)
                    except Exception, e:
                        logger.error('Exception while loading config of '
                                     'Service(%s): %s' %
                                     (service.name, e.__str__()))
                data[service.name] = {}
                output, error, return_code = service_status(service.name, config=config)
                data[service.name]['running'] = return_code

            self.emit('services:get_services', {
                'data': data, 'key': 'services:get_services'
            })
            gevent.sleep(15)
```
Check this
```
def send_service_statuses(self): 
        while True: # <- Bad boy!
```
this is a serie of endless loops because on every connection to services pages system starts a new emitter that never dies

Going to solve this inside #1510 

Mirko

**Comment by schakrava** [comment]
@MFlyer that's a good question but those loops do die when recv_disconnect is called. This happens as part of cleanup as user navigates away from the services page, for example.

**Comment by MFlyer** [comment]
Hi @schakrava you're right about that, but having some tests had also found that our cleanup strategy doesn't seem good at all, let me explain:

Using Rockstor "normally": it's all fine
Having a refresh over ex. services page: sockets get duplicated / it seems there's not a complete cleanup over views.
Had some reading over our cleanup func but probably I need help on this by @priyaganti & you too, because my suspicion is we have some "zombies" view (not closing att all)

M.

**Comment by MFlyer** [comment]
Hi @schakrava , got a new test changing some code over data_collector / services (tracking socket id).
Check this:
34400242ce5a48c98ed3edd50fc33d3 is our first client (first time I load page)
then i performe an F5 and we get c2f6dfff69d14f11a193bf8ccf5942a4 (second client): first one should be dead, but it's alive
after another F5 first client get killed, but second is alive and so on 

```
[14/Nov/2016 16:14:22] DEBUG [smart_manager.data_collector:661] sending to 34400242ce5a48c98ed3edd50fc33d35
[14/Nov/2016 16:14:38] DEBUG [smart_manager.data_collector:661] sending to 34400242ce5a48c98ed3edd50fc33d35
[14/Nov/2016 16:14:54] DEBUG [smart_manager.data_collector:661] sending to 34400242ce5a48c98ed3edd50fc33d35
[14/Nov/2016 16:15:01] DEBUG [smart_manager.data_collector:661] sending to c2f6dfff69d14f11a193bf8ccf5942a4
[14/Nov/2016 16:15:10] DEBUG [smart_manager.data_collector:661] sending to 34400242ce5a48c98ed3edd50fc33d35
[14/Nov/2016 16:15:17] DEBUG [smart_manager.data_collector:661] sending to c2f6dfff69d14f11a193bf8ccf5942a4
[14/Nov/2016 16:15:27] DEBUG [smart_manager.data_collector:661] sending to 34400242ce5a48c98ed3edd50fc33d35
[14/Nov/2016 16:15:33] DEBUG [smart_manager.data_collector:661] sending to c2f6dfff69d14f11a193bf8ccf5942a4
[14/Nov/2016 16:15:43] DEBUG [smart_manager.data_collector:661] sending to 34400242ce5a48c98ed3edd50fc33d35
```
Going to check this too

**Comment by MFlyer** [comment]
Another update:
forcing `emit(namespace, data, room = sid)` where sid is connected client we avoid data duplicating and this is ok, but we still get emitting on old client

Added disconnect(sid, namespace) seems not working too, had to understand (client doesn't get disconnected), so have to understand if Rockstor related, gevent related (maybe?) or python-socketio related
@schakrava sorry for getting the "glitch issue" slower, but before getting that updated need to get emitting ok (probably you didn't notice that, but when closing a modal services listener is broken)

M.

**Comment by MFlyer** [comment]
@schakrava : https://github.com/miguelgrinberg/python-socketio/issues/58#issuecomment-260429303

Now I've got my confirmation :smiley: ....and some more coding required before merging #1510 
#1500 will procede together to avoid having some code not working on new socketio server, do you agree on that?
M.
