### ISSUE TITLE
[GUI inconsistency - lack of warning] Samba service config still missbehaving. 

### ISSUE THREAD

**Issue by tomtom13** [rockstor/rockstor-core#1523]
Hi, so most recently @MFlyer fixed the workgroup bug that made samba useless. Unfortunatelly there is still a problem with this config page. Typing setting into a global config results in a fault. 

Example settings:
'
write cache size = 33554432 # 32MB
read cache size = 33554432 # 32MB
socket options = IPTOS_LOWDELAY TCP_NODELAY SO_SNDBUF = 131072 SO_RCVBUF  = 131072 
strict allocate = no
aio write size = 16384
aio read size = 16384
'

return error code
'
            Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/smart_manager/views/samba_service.py", line 83, in post
    update_global_config(global_config, adconfig)
  File "/opt/rockstor/src/rockstor/system/samba.py", line 181, in update_global_config
    test_parm(npath)
  File "/opt/rockstor/src/rockstor/system/samba.py", line 50, in test_parm
    raise Exception('Syntax error while checking the temporary '
Exception: Syntax error while checking the temporary samba config file
'

@MFlyer - I'll let you take care of it, since you're doing some stuff around it. Just please next time test this page ... fresh setup would be very beneficial as well.

There is another regression there, quite minor in fact - if one starts fresh and types in a workgroup name it will not show up on page reload (after hitting submit) so even my self I ended up punching the value several times before just checking smb.cfg so setting. The value of workgroup will show in this field after system reboot - from this point all workgroup updates will behave in a valid fashion.

**Comment by MFlyer** [comment]
This is going to be a bug day, but not on this round @tomtom13 :

from a console, create a  `testing_samba` file, add your code testparam your conf:
```
[global]
    log level = 3
    map to guest = Bad User
    cups options = raw
    log file = /var/log/samba/log.%m
    printcap name = /dev/null
    load printers = no
    write cache size = 33554432 # 32MB
    read cache size = 33554432 # 32MB
    socket options = IPTOS_LOWDELAY TCP_NODELAY SO_SNDBUF = 131072 SO_RCVBUF = 131072
    strict allocate = no
    aio write size = 16384
    aio read size = 16384
```
then try a `testparm -v ./testing_samba` to have a verbose output

then edit your `testing_samba` and remove those `#` having a clean
```
[global]
    log level = 3
    map to guest = Bad User
    cups options = raw
    log file = /var/log/samba/log.%m
    printcap name = /dev/null
    load printers = no
    write cache size = 33554432
    read cache size = 33554432
    socket options = IPTOS_LOWDELAY TCP_NODELAY SO_SNDBUF = 131072 SO_RCVBUF = 131072
    strict allocate = no
    aio write size = 16384
    aio read size = 16384
```
try a `testparm -v ./testing_samba` and...et voilà

samba testparm -> **no** inline comments

Obviously had same config via Rockstor too and it was ok (because is not Rockstor code refusing those params with hashes, but testparam)
My suggestion about write/read cache aio etc : those confs usually come useful over bsd like systems (freenas/nas4free) having a poor samba porting - had that nice adventure too... -, but on linux distros samba acts well on its own 99%
M.

P.S.: going to check other issue asa i can get a clean env without samba

**Comment by tomtom13** [comment]
FYI, at least samba does **work** you only can not apply global settings.

**Comment by MFlyer** [comment]
O_o ?? @tomtom13  that's not code related, it's `testparam` not accepting inline comments xD

Nice find of the day checking your config:
currently we handle samba config params check = sign, but socket options lets have some_param=value inside it

**Comment by tomtom13** [comment]
Sorry for previous comment, it was stall in browser and waiting for me to hit reply. Anyway if we not allow # comments we should at least let user know about it.

So maybe we can smash this into "need comment"

**Comment by MFlyer** [comment]
Hey guy that's ok, no problem! ;)
Comments: reading samba documentation comments expected to be at the beggining of line, but nothing telling them not allowed after params (although I've never had them knowing samba like a willful kid!)
Important: that socket options is a good find (some samba params, very few, have `param = something something something=value` <- please note missing space on last equal sign, that should be the right way by smb.conf docu), we need a dictionary with these params like socket options having equal sign inside - we can check later

**Comment by tomtom13** [comment]
So, "paper rock scissors" on who takes one updating GUI to give some warning ?

**Comment by MFlyer** [comment]
Good morning @tomtom13 , here my idea:
we can close this issue and split it in 2/3:

1. Warning about inline comments
2. Allow Rockstor having "not standard" params like `socket options` (more then 1 equal sign per line, params having this should be few and well known - going to check over samba documentation)
3. empty/new workgroup taking too much time to render on new install

What do you thing about these? All of these issues are not blocking (maybe except for n. 2, but only for a really small group of users having lot of customization)

M.

**Comment by tomtom13** [comment]
3 It is. Fancy taking a second one ? I had no idea about that script - which proves that you've got a head start :P

**Comment by MFlyer** [comment]
Going to get second one 👍
