### ISSUE TITLE
New workgroup setting does not render on new instalation

### ISSUE THREAD

**Issue by tomtom13** [rockstor/rockstor-core#1526]
Hi, with @MFlyer we're splitting issue #1523 into 3 separate ones.
"
There is another regression there, quite minor in fact - if one starts fresh and types in a workgroup name it will not show up on page reload (after hitting submit) so even my self I ended up punching the value several times before just checking smb.cfg so setting. The value of workgroup will show in this field after system reboot - from this point all workgroup updates will behave in a valid fashion.
"

**Comment by MFlyer** [comment]
Can we close this @tomtom13 - @schakrava ?? Ref to #1540 already merged

**Comment by tomtom13** [comment]
it works on .15-14
