### ISSUE TITLE
Allow having "not standard" samba params like socket options - more then 1 equal sign per line

### ISSUE THREAD

**Issue by tomtom13** [rockstor/rockstor-core#1527]
Hi, with @MFlyer we're splitting issue #1523 into 3 separate ones.
So this one is:
"
Allow Rockstor having "not standard" params like socket options (more then 1 equal sign per line, params having this should be few and well known - going to check over samba documentation)
"
essentially having a line like this one:
socket options = IPTOS_LOWDELAY TCP_NODELAY SO_SNDBUF = 131072 SO_RCVBUF = 131072
and passing it through
testparm -v ./testing_samba
will strip this line because it has to many "=" signs inside of it

**Comment by phillxnet** [comment]
@tomtom13 and @MFlyer I am unsure of the utility and wisdom in ignoring or circumventing testparm's tests, config file verification is it's ball park / primary purpose. Is this fixed in an upstream version of samba maybe?

**Comment by MFlyer** [comment]
> Is this fixed in an upstream version of samba maybe?
Yesterday had a really quick check and didn't find anything about that, will take care about this reading changelog from our samba (`4.2.10 on my dev env`) to latest
M.
