### ISSUE TITLE
Upgrade to 3.8.15-6 dashboard widgets dont work

### ISSUE THREAD

**Issue by barnhill** [rockstor/rockstor-core#1534]
![capture](https://cloud.githubusercontent.com/assets/3878158/20375164/f1ff4d08-ac42-11e6-8a98-16760a97e72f.PNG)

Even the current version stopped showing on the dashboard

**Comment by MFlyer** [comment]
Good morning @barnhill ,
you're the first one reporting this
Can you please provide more infos?
OS, browser and some console logs (over Chrome ctrl+shift+I, over Firefox ctrl+shift+K)

Thanks
Mirko

**Comment by barnhill** [comment]
At surgery center right now but it was chrome, browser on a Windows 10 box with anniversary update

**Comment by MFlyer** [comment]
> At surgery center
O_o hope you're ok

**Comment by barnhill** [comment]
Oh yea ... Kid had to have tubes put in her ears.  Doing great!!! Thanks!!!

**Comment by MFlyer** [comment]
Ok, stating it's all ok, back to our issue:
that's a really strange one, can you please provide some console log??
First idea: a missing dependency on new socket.io library (widgets not using socket.io like top shares work fine)

Mirko

**Comment by barnhill** [comment]
This seems to be fixed in the .7 release. I just installed it this morning and the dashboard is back to its former glory :)  You can close this if you like.
