### ISSUE TITLE
UI lacks logout

### ISSUE THREAD

**Issue by alanlaird** [rockstor/rockstor-core#1542]
Cannot figure out how to logout from the web interface.

**Comment by MFlyer** [comment]
Hi @alanlaird ,
probably we could better docu it:
Right side of WebUI you'll find a clickable username (your Rockstor username) that opens a small panel with logout option too

![logout](https://cloud.githubusercontent.com/assets/17988902/20591686/433f62e2-b22a-11e6-8a33-004135a96b0a.jpg)

Please close this issue, thanks
M.
