### ISSUE TITLE
Adding new Appliance hangs and fails without proper error display

### ISSUE THREAD

**Issue by priyaganti** [rockstor/rockstor-core#1572]
Steps to Reproduce:

1. System->Appliances->Add new Appliance->Start filling the form with a valid host name and invalid Access key ID and invalid Access Key Secret.
2. No error is displayed instead ajax loader appears and finally nothing happens. Had to hit cancel or refresh to go back. No errors in the console too.

If you enter an invalid host name, then error is shown. Which means the validation on Access Key ID and Secret are not being performed I guess.

Attaching the screenshot for reference.

![wrongapplianceid](https://cloud.githubusercontent.com/assets/1999710/20996148/52e6d500-bcb0-11e6-919f-ea6ca889da66.png)

After waiting for some time finally the following error shows up.
![appliancewaiterror](https://cloud.githubusercontent.com/assets/1999710/20996386/1655bd16-bcb2-11e6-8e0d-44f605fce7b3.png)

**Comment by schakrava** [comment]
This is no longer reproducible.
