### ISSUE TITLE
Samba integrated path modification

### ISSUE THREAD

**Issue by LarsNowak** [rockstor/rockstor-core#1575]
follow issue, it is possible modify the path in the frontend to better use SAMBA functions?

    root preexec = "/opt/rockstor/bin/mnt-share homes"
    root preexec close = yes
    comment = homedrive
    **;path = /mnt2/homes**
    browseable = no
    read only = no
    guest ok = no
    valid users = %S
    **path = /mnt2/homes/%S**

To use variable I must be use external modification in smb.conf and after rebuilds some configuration will be overwrite.

Thank you for your project rockstor, it is great solution!!! Regards Lars

**Comment by MFlyer** [comment]
Hi @LarsNowak ,
why do you need manually edit of smb.conf?? Having problems with `%` char?
M.

**Comment by LarsNowak** [comment]
Hi @MFlyer ,
thk for fast question, right, the standard path will be set by select item, but to use functions for users or groups I need to edit the "custom configuration" field - the standard path is also in the configuration file smb.conf (the marked lines) - easier was to override path information with new settings or insert a line (modified) path setup.
Regards Lars

**Comment by MFlyer** [comment]
Hi @LarsNowak ,
will check it asap (actually performing final tests for Rockstor 3.8.16 release with other contributors) :+1: 

Meanwhile, if you need custom configuration over samba `[global]` with samba variables:

create an ad hoc `smb_extra.conf` file (choose name you prefare) and include it in samba global configuration via Rockstor WebUI with `include = /your/path/to/samba/extra/config/smb_extra.conf`

Put inside that `smb_extra.conf` al required variables/funcs, so you can have samba conf via Rockstor WebUI + adding anything currently not supported without losing conf on every samba service restart

Documentation:
https://www.samba.org/samba/docs/man/manpages-3/smb.conf.5.html#INCLUDE

Please note I'm not leaving this in a corner, will come back soon ;)

**Comment by MFlyer** [comment]
EDIT: checked `%` and working fine both on samba global & shares params, actually going to test it with a new `[homes]` share
M.

**Comment by MFlyer** [comment]
Hi @LarsNowak , working on it let me better understand:

when creating a new samba share we always define its `path` and you cannot change it with share custom params (results 2 path).

Homes share is a special one, so we can think about an ad hoc solution.

Important: having something like `path=mnt2/homes/%U` works, but folders have to be manually created

**Comment by LarsNowak** [comment]
Hi MFlyer,
thanks for the workaround it is ok for me, sorry that I wrote so late, a had other problems to fix, cron integration and problems with trim ssd as boot device, some Rockstore wakeup (WOL) are fine other system hold - other issue ;-) (CENTOS7 and RHEL7) - my samba case can close
