### ISSUE TITLE
UI improvement on initial Rock-ons config

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#1582]
On first visiting the Rock-ons page and switching the switch on the left hand side ON as prompted by the: "Warning! Rock-on service is not running. Please turn it on to use features on this screen" we are correctly prompted with a modal dialog, selecting an appropriate share (pre-configured) and then submit button results in returning to the same message but the button is gone and replaced with the normal side menu. A browser refresh brings up the services page.

I would have expected for the switch to now be ON and to be looking at the 'enabled' Rock-ons page.

Revisiting the Rock-ons page after the config dialog sequence detailed above and we have the switch in the OFF position. Upon switching it ON for a second time we are sorted.

**Comment by Hooverdan96** [comment]
@FroggyFlox, @phillxnet I think this can still be an issue, just want to check in whether you've observed it still in recent releases? I think I have.

**Comment by FroggyFlox** [comment]
I do, but slightly different:

1. Go to Rock-Ons page
2. Toggle ON -> presented with Service config modal (normal). Upon submission, I'm automatically redirected to the "System > Services" page. This should not happen.
3. Upon visiting the Rock-Ons page again, I still see the "warning, the service is OFF" as expected. Toggling it ON again this time proceeds normally and the Rock-Ons page is now displaying normally.

I believe the behavior is step 2 above is an indirect (unforeseen by me, at least) consequence of how configuring a service does not trigger its "starting" (which is the correct behavior in my opinion when on the "System > Services" page). When toggled ON from an "endpoint" page, though (such as the Rock-Ons) page, the service should be started, however.

**Comment by phillxnet** [comment]
@Hooverdan96 & @FroggyFlox Since the behaviour I detailed is now changed, lets close this one once & @FroggyFlox can opened a new issue when time allows. We have after all improved things here: but it would be good to have the newer into as the header text.
