### ISSUE TITLE
Samba 4.4.4 slow and error in log

### ISSUE THREAD

**Issue by PhilippeAB** [rockstor/rockstor-core#1586]
Hi
With samba 4.4.4 in Rockstor 3.8.15 and 3.8.16-0 we have a lots of error in samba server logs

` pid_to_procid: messaging_dgm_get_unique failed: No such file or directory`

Files transfer is slow and there is freeze and disconnection for users

**Comment by MFlyer** [comment]
Hi @PhilippeAB 
had some tests after upgrading to samba 4.4.4 from a win7 machine, here some stats on a Gigabit lan:
Writing last ubuntu iso (1,48 GB) -> ~160 MB/s till half size, then moved down to worst 90MB/s 
Writing clonezilla iso (180 MB) -> ~1 sec writing 

So actually it seems ok
My current samba `[global]` config has only `local master = no` to avoid nmbd winning master election

`pid_to_procid: messaging_dgm_get_unique failed: No such file or directory` <- investigating on it
M.

**Comment by MFlyer** [comment]
https://bugzilla.samba.org/show_bug.cgi?id=11775

@schakrava - @phillxnet having same problems , ntp service seems dead & no ping :(

**Comment by PhilippeAB** [comment]
We hit this one too, it was a missing config in ldconfig
echo '/usr/lib64/samba' > /etc/ld.so.conf.d/samba-x86_64.conf
ldconfig

and it's ok

**Comment by MFlyer** [comment]
Hi @PhilippeAB ,
pls avoid manual pacthing.
Had your way and it solves ntp not running, but pit_to_procid always there
Check this : https://forum.rockstor.com/t/3-8-16-upgrade-killed-rockstor/2530/6
It's Centos related :disappointed:

**Comment by PhilippeAB** [comment]
Yes It's a bug in centos packet and it's because the ldconfig does not find the samba library
It's not a patch it's just the missing config

**Comment by MFlyer** [comment]
Can we close this not being Rockstor related??
Unfortunately we can only wait

M.

**Comment by PhilippeAB** [comment]
As you wish but it's a bug in one of a core functionality of rockstor

**Comment by MFlyer** [comment]
Not in Rockstor itself @PhilippeAB , it was fine with last 3.8.16 till I updated with yum

**Comment by MFlyer** [comment]
Hi @PhilippeAB , just to update you : 

samba has gethostbyname function not working on 4.4.4 and fixed over [4.4.7](https://www.samba.org/samba/history/samba-4.4.7.html), @schakrava can we consider an ad hoc rpm under Rockstor with an updated samba??
M.

P.S.: if i've time will check building from source like on btrfs-progs :)

**Comment by MFlyer** [comment]
Hi @PhilippeAB , just had latest samba 4.4.4-12 from CentOS, this fixed segmentation fault, name resolutions, ntpd and others.
Can we close this?? Yes on my side,

**Comment by MFlyer** [comment]
@schakrava : on my side we can close this, recent samba update solved samba - nss - ntp issues

Mirko

**Comment by schakrava** [comment]
Thanks @MFlyer and @PhilippeAB
