### ISSUE TITLE
Rockon install fails but no log entries written

### ISSUE THREAD

**Issue by daniel-illi** [rockstor/rockstor-core#1594]
I'm trying to install a rockon, but I always get the message
```
Failed to install in the previous attempt. Here's how you can proceed.
Check logs in /opt/rockstor/var/log for clues.
Install again.
If the problem persists, post on the Forum or email support@rockstor.com
```
As advised, I checked the logfiles but no entries whatsoever get logged when I try to install the rockon.

**Comment by daniel-illi** [comment]
I just realized that not only installing a new rockon fails silently, so does stopping a running rockon.
It seems I have to manage my rockons with the docker cli for now :(

**Comment by daniel-illi** [comment]
After the rockstor 3.9 update I had another look.
For testing I tried to install the uhttp-2 rockon. Now I get the following errors in the rockstor.log:
```
[27/Mar/2017 04:30:11] ERROR [storageadmin.views.rockon:81] Rockon(uhttpd-2) is in pending state but there is no pending or failed task for it. 
```

**Comment by maclm** [comment]
Nearly two years after your last post, I get the exact same error message 
`is in pending state but there is no pending or failed task for it.`
for any rock-on I try to install.

Have you got around this?

**Comment by daniel-illi** [comment]
Unfortunately I never got it to work again.
I have since migrated away from rockstor altogether, so I won't be able to verify any solution to this problem.

**Comment by FroggyFlox** [comment]
Hi @maclm,

Thank you for looking through our forums and reaching there as well. As the forums is the preferred medium for this sort of things, I'll [answer you there](https://forum.rockstor.com/t/rock-ons-issues/3375/3?u=flox).

**Comment by phillxnet** [comment]
@maclm and @daniel-illi Linking to the known work around by way of a reply to @maclm in the forum. Though in this case although @maclm appears to be OK again the work around was not the issue.

N.B. @maclm report pertains to our now depricated CentOS testing channel version 3.9.1-16 which uses an older version of docker. Our Stable channel updates have for some time moved to using docker-ce. Noting to add context to this issue.

@daniel-illi You might like to give us another look once we have released our openSUSE based offering where we now use the distro provided docker-ce and stick more strictly to their docker config.

**Comment by phillxnet** [comment]
Link to recent forum post with known workaround:
https://forum.rockstor.com/t/rock-ons-issues/3375/4

**Comment by FroggyFlox** [comment]
Closing as this issue appears to have been resolved in the linked forum thread.
