### ISSUE TITLE
[Feature Request] Implementation of sensors in dashboard

### ISSUE THREAD

**Issue by ghost** [rockstor/rockstor-core#1595]
Hi Rockstor Team,
it is possible to integrated sensors and/or ACPI information in the dashboard view to get better system information and health status? 
Thanks a lot and kind regards!

**Comment by MFlyer** [comment]
Hi @LarsNowak,
there's another issue related to sensors on dashboard (it's an old one, so it's quite normal not to find it ;) )

Mirko

**Comment by Hooverdan96** [comment]
Should we consolidate this request, #582 and #980 into a single feature request? Or is the Netdata Rockon we already have the way to go? Considering that we do have a dashboard with a couple of widgets that monitor memory, disks, etc. it would make sense to at least have some basic views on some of the other hardware related facts, at least for real-time monitoring.
Netdata could (if configured appropriately) be the framework that keeps track of historical data.
The benefit of outsourcing that aspect for things like post-mortems is that we don't have to develop a whole data facility management capability and can take advantage of upstream improvements, changes.
Alternatively, what would it take to do something like an iView of netdata into the dashboard ...
As a side note, we already have a SMART historical tracking Rockon ...

**Comment by phillxnet** [comment]
@Hooverdan96 Yes, lest consolidate: if just to cut down on the forest of issues. Not as feature reqeust though, given, as you say, there are Rock-ons that provide this. Although I suspect our netdata rock-on would need more capabilities granted to get temps.

If we do add, I think we keep it very simple. I.e. pre-install lm-sensors and surface cpu-temp only say. Leaving specialist Rock-ons for hdd. The configuration sometimes needed for lm-sensors is hardware specific and can be quite involved. So a little out-of-our-realm give the work we have on currently.

**Comment by Hooverdan96** [comment]
in my case Netdata does provide at least CPU temp, I believe. And there's some additional config that might still allow it, which we could then document in a how-to for "historical data capture" or something to the likes. But you are correct, we would have to look at simplest option like you said.

You prefer a new issue for consolidation or picking one for it? If just picking one, then let's use this newest (relative term, I know) one and close the other two. Otherwise, I can open a new one and do the references before you close the other ones.

**Comment by phillxnet** [comment]
@Hooverdan96 How about we start out fresh. We can reference others, and interesting netdata reports OK, that's good to know. But there are many other temps available that are often only enabled by specific config, sometimes by hand. I submitted some missing onces way back for a Haswell board one time. So often only available if the board is recognised and has it's custom config available already: i.e. for ram temp/ fan-speed / etc. But our main priority is CPU and storage. All else could be addressed by specific projects that we may be able to suggest and offer via a docker.

**Comment by Hooverdan96** [comment]
I created a new issue (title can be adjusted of course). If that works, then we could close this and the other 2 related Issues.
