### ISSUE TITLE
Sysctl.conf optimizations should go into separate file

### ISSUE THREAD

**Issue by maxhq** [rockstor/rockstor-core#1598]
Modifying `/etc/sysctl.conf` as done in [flash_optimize.py](https://github.com/rockstor/rockstor-core/blob/2c6e1ad9d2c955b9e1b2ccb297fa7c81e76b3c1c/src/rockstor/scripts/flash_optimize.py#L111) leads to upgrade warnings and is hard to maintain.
The script should follow the official recommendations and create a separate file (e.g. `/etc/sysctl.d/99-rockstor`) which can easily be deleted and re-created on updates.

**Comment by schakrava** [comment]
Thanks for reporting this @maxhq
