### ISSUE TITLE
[Bug] Wrong pool usage

### ISSUE THREAD

**Issue by MFlyer** [rockstor/rockstor-core#1600]
To @schakrava & @phillxnet  : do you agree having this on Pinnacles too, hopefully going to work on this like on shares

Summary:
- had a new Pool
- had a new share & played with it and finally deleted snapshots and share

After share & snapshots deletion Pool lists usage "correctly" reports a huge amount of data greater then share original size, a balance is required on share deletion

Add: Pools list can be improved on "Usage" column

Ref to #1412

**Comment by schakrava** [comment]
Agreed @MFlyer, go for it!

**Comment by Hooverdan96** [comment]
@phillxnet, I am not sure that this is still an issue/bug, but I might be misunderstanding what we have as of today vs. what was there 6 years ago.
