### ISSUE TITLE
ISO grub menu kernel options for "Troubleshooting" menu

### ISSUE THREAD

**Issue by firkin-gadabout** [rockstor/rockstor-core#1621]
When trying to install from ISO I was forced to use the basic graphics option in the troubleshooting menu. I discovered that the kernel options appended in the isolinux.cfg specify the wrong disk label.

See here the correct append parameter. Specifically the \x203\x20 in the label
```
label linux
  menu label ^Install Rockstor
  menu default
  kernel vmlinuz
  append initrd=initrd.img inst.stage2=hd:LABEL=Rockstor\x203\x20x86_64 quiet ip=dhcp ks=hd:LABEL=Rockstor\x203\x20x86_64:/ks.cfg
```

Then in grub troubleshooting menu both the vesa plus the rescue install have \x203.0\x20 and the correct label is simply 3 not 3.0
```
label vesa
  menu indent count 5
  menu label Install Rockstor 3.0 in ^basic graphics mode
  text help
	Try this option out if you're having trouble installing
	Rockstor 3.0.
  endtext
  kernel vmlinuz
  append initrd=initrd.img inst.stage2=hd:LABEL=Rockstor\x203.0\x20x86_64 xdriver=vesa nomodeset quiet
```

**Comment by phillxnet** [comment]
@firkin-gadabout Thanks for this report, nice find from an initial look.

Would you mind re-creating it in the rockstor-iso repo:
https://github.com/rockstor/rockstor-iso
and closing it here as that is where it belongs as this directly concerns the iso build and nothing can be done in the Rockstor code (rockstor-core repository) to affect this.

Thanks again for sharing your findings.

**Comment by firkin-gadabout** [comment]
Understood. Thanks for the reply!

https://github.com/rockstor/rockstor-iso/issues/15

**Comment by phillxnet** [comment]
@firkin-gadabout Thanks.
