### ISSUE TITLE
GUI Shows 100 for Network Devices when system is using 1000

### ISSUE THREAD

**Issue by magicalyak** [rockstor/rockstor-core#1630]
The main GUI shows 100 (connected) yet ifconfig reveals the connection to be using 1000 (if you run cat /sys/class/net/{interface}/speed it shows 2000 for my bond0 (it's a LACP bond yet the GUI shows 100).  I suspect it's using something like mii-tool or something old that doesn't have fast ethernet (so it never goes above 100).  If the network GUI could leverage running cat on /sys/class/net/{interface}/speed it should be perfect.

Or...someone forgot to add a 0

**Comment by phillxnet** [comment]
Having a quick look into this now:
From initial investigation the relevant base network info is parsed in src/rockstor/system/network.py in devices() via the following commands:
```
nmcli -t -f device device
```
to first get a list of the devices, and then each of these devices is fed into:
```
nmcli d show devname
```
In an example on real hw where ifconfig shows 1000 on a dev named enp3s0 in this instance we have the output here as:
```
nmcli d show enp3s0 | grep 'GENERAL.STATE:'
GENERAL.STATE:                          100 (connected)
...
So we are parsing nmcli's output correctly.

What is shown is not connection speed but a status code (condition) report.
ie in the following we have the state code of 20 (unavailable):

![network-state-code-report](https://cloud.githubusercontent.com/assets/2521585/22405410/0b41e60a-e63a-11e6-84e0-52ef3cce6335.png)

So to address this issue I have opened an additional issue to specifically address the observed miscommunication of the 'State' title as the column header: #1633 .

@magicalyak An additional feature request issue could be opened to request that interfaces and or connections speeds be reported in an addition column to the existing tables. Please feel free to open such an issue and then link back to this issue if you think that is appropriate. I think this issue can now be closed given the specificity of #1633 which attributes you and the associated forum thread with this lake of clarity finding.

Linking back to the forum thread that initialted this issue:
https://forum.rockstor.com/t/jumbo-packets-possibility/2706/3

**Comment by phillxnet** [comment]
@magicalyak As pr #1634 (for spin off issue #1633)  has now been merged I think this issue can be closed. Please do so if you agree and do open a feature request issue re network device speed if you think that is appropriate.

**Comment by phillxnet** [comment]
@magicalyak and @schakrava I think this one can now be close re my last comment here.

**Comment by schakrava** [comment]
Thanks for your input @phillxnet
