### ISSUE TITLE
Cant roll back snapshot does not exist

### ISSUE THREAD

**Issue by alazare619** [rockstor/rockstor-core#1631]
Snapshot(/mnt2//rockstor_rockstor/.snapshots/rockon_share/25c10691b487dd3ea7bd4347bc886e371cec73069a24a7040980ee872660b121) does not exist. Rollback is not possible

**Comment by schakrava** [comment]
Can you provide more context and steps to reproduce here? I don't think rock-on snapshots would be rollback friendly as they are managed by docker internally.
