### ISSUE TITLE
[Major Feature] Nagios integration

### ISSUE THREAD

**Issue by MFlyer** [rockstor/rockstor-core#1638]
Adding Nagios support over Rockstor (not Nagios Core over Rockstor, but Rockstor monitored by a Nagios Env)

Mirko

**Comment by schakrava** [comment]
You  might want to explain this with more details @MFlyer :)

**Comment by MFlyer** [comment]
Hi @schakrava ,
I'm looking all your updates and telling the whole truth about this...I had to read my starting post 3-4 times and try to recap eheh

Finally got it: my idea was to install/enable/setup a Nagios monitoring agent via our WebUI (ex. NRPE)

Useful reference about Nagios monitoring agents
https://exchange.nagios.org/directory/Addons/Monitoring-Agents

Probably @phillxnet & @magicalyak will provide good suggestions about this :)

**Comment by magicalyak** [comment]
How about a rockon? I have one for both zabbix server and one I didn't pr for the agent. It can't be that hard to make one for nagios. Would that be a solution?

**Comment by magicalyak** [comment]
We have been working a lot with sensu in assuming it makes sense to publish that agent also ;) let me know I'm sure it can't be too hard to get up and running

**Comment by magicalyak** [comment]
By we I mean my company not rockstor. Sorry should have specified that.

**Comment by Hooverdan96** [comment]
I propose this to be closed/moved to the Rockon repo instead, unless we want to consider this as a native solution ...

**Comment by phillxnet** [comment]
@Hooverdan96 Thanks again, and agreed:

Re:

> I propose this to be closed/moved to the Rockon repo instead

Sorted:

https://github.com/rockstor/rockon-registry/issues/358
