### ISSUE TITLE
"Comment" field not filled when editing Samba share

### ISSUE THREAD

**Issue by maxhq** [rockstor/rockstor-core#1647]
When I go to "File Sharing" - "Samba" and edit an existing share the "Comment" field is not filled with the previously entered comment (which is corrently shown in the overview table).

**Comment by MFlyer** [comment]
Thanks @maxhq , solved over #1649

Mirko

**Comment by maxhq** [comment]
Wow, that is fast!
Take care that you do not solve problems before I report them or we'll end up in a time loop ;-P
Thanks a lot!

**Comment by MFlyer** [comment]
Hi @maxhq next time don't close issues, PR for this and other need to be merged by @schakrava (on our commits we always have one "Fixes #issuenumber" and this auto-close issues :wink: )

Mirko

**Comment by maxhq** [comment]
Oh OK sorry, shall I reopen it?

**Comment by MFlyer** [comment]
No problem Max, don't worry :)
