### ISSUE TITLE
[Bug] Share/Volume usage - issues on some production environments

### ISSUE THREAD

**Issue by MFlyer** [rockstor/rockstor-core#1654]
After #1625 some users experienced issues.
PR working on dev env & confirmed working on production env (@schakrava) too.
Building a new production env trying to reproduce issues

Adding ref to forum threads:

https://forum.rockstor.com/t/after-upgrading-to-3-8-16-11-rock-on-wont-start/2842
https://forum.rockstor.com/t/column-storageadmin-share-pqgroup-rusage-does-not-existline-1-n-share-rusage-storageadmin-share-eusage-storagead/2847
https://forum.rockstor.com/t/null-value-in-column-pqgroup-eusage-violates-not-null-constraintdetail-failing-row-contains-6-4-0-259-data1-null-4831838208-root-root-755-2017-02-14-17-12-34-201143-00-data1-f-no-0-0-2015-4-null-null/2841
~https://forum.rockstor.com/t/unable-to-access-web-ui-and-shares-not-mounted-to-file-system-after-reboot/3029/~ <- ref removed on 11 apr 2017, not shares related

**Comment by MFlyer** [comment]
Updates on [this](https://forum.rockstor.com/t/null-value-in-column-pqgroup-eusage-violates-not-null-constraintdetail-failing-row-contains-6-4-0-259-data1-null-4831838208-root-root-755-2017-02-14-17-12-34-201143-00-data1-f-no-0-0-2015-4-null-null/2841/5), new production environment running without issues, performed tests, thinking about a corrupted update task ( aka had reboot or similar before update ending )

Mirko

**Comment by MFlyer** [comment]
Considerations after some recent forum posts:
@schakrava & @phillxnet reading some posts like [this one](https://forum.rockstor.com/t/unable-to-access-web-ui-and-shares-not-mounted-to-file-system-after-reboot/3029/12?u=flyer) made me thing about this related to a "major" issue (ex. no shares -> no pools -> no disks), so I'm not sure it's related to wrong migrations at all

Mirko

**Comment by MFlyer** [comment]
Today asked forum users for feedbacks/updates after last @schakrava  Rockstor release consolidating db migrations

**Comment by MFlyer** [comment]
@schakrava any news on your side? There's a recent feedback after last testing channel update reporting same issue

Mirko

**Comment by MFlyer** [comment]
@phillxnet & @schakrava can we close this?
M.

**Comment by phillxnet** [comment]
@MFlyer I think that this can be closed as I believe it references 2 different issues anyway. With regard to the quoted forum threads I have just submitted a pr #1770 that addresses the first of your references:
https://forum.rockstor.com/t/after-upgrading-to-3-8-16-11-rock-on-wont-start/2842
more specifically:
https://forum.rockstor.com/t/after-upgrading-to-3-8-16-11-rock-on-wont-start/2842/5
The other references given I believe are old code still in play directly after update or flaky db migration events that @schakrava has since made much more robust.

**Comment by MFlyer** [comment]
Closing this @phillxnet :)
