### ISSUE TITLE
[Feature Request] CRON over UI

### ISSUE THREAD

**Issue by ghost** [rockstor/rockstor-core#1655]
Hi at all,

is it possible to get CRON TAB integration in schedule tasks board? 

Thanks a lot.

**Comment by MFlyer** [comment]
Hi @LarsNowak ,
what do you mean with "CRONTAB integration"?? custom tasks??
We already have #735 + #1306 and parent #1036 : currently working on those :)

Mirko

**Comment by FroggyFlox** [comment]
Closing as this issue has been waiting for feedback for quite some time.
