### ISSUE TITLE
Small UI bug while installing rock-ons

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-core#1660]
https://forum.rockstor.com/t/small-ui-bug-while-installing-rock-ons/2905

**Comment by tobiashochguertel** [comment]
Thanks.

 

Mit freundlichen Grüßen,

Tobias Hochgürtel

 

 

 

Tobias Hochgürtel

Gewerbestraße 9

38550 Isenbüttel

 

Telefon 05374 9349-994

Mobil   01768 674-5374

E-Mail   <mailto:tobias.hochguertel@googlemail.com> tobias.hochguertel@googlemail.com

 

 

 

Von: Suman Chakravartula [mailto:notifications@github.com] 
Gesendet: Samstag, 4. März 2017 02:11
An: rockstor/rockstor-core <rockstor-core@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [rockstor/rockstor-core] Small UI bug while installing rock-ons (#1660)

 

https://forum.rockstor.com/t/small-ui-bug-while-installing-rock-ons/2905
