### ISSUE TITLE
Comment field not retained when editing Samba share in UI

### ISSUE THREAD

**Issue by t3kka** [rockstor/rockstor-core#1661]
For a Samba share that already has text in the comment section, if you click the EDIT button the comment field is not populated with the existing value in the edit screen.  It is simply blank and any comment is lost if it is not re-entered before submitting.

**Comment by MFlyer** [comment]
Hi @t3kka ,
testing this on latest Rockstor and no issues.
Which Rockstor version are you using?

Mirko

**Comment by MFlyer** [comment]
Add: this is a dupe for #1647 , already solved and merged

Issue can be closed
Mirko

**Comment by schakrava** [comment]
Thanks @MFlyer
