### ISSUE TITLE
UI Shares view incorrect sort on size

### ISSUE THREAD

**Issue by magicalyak** [rockstor/rockstor-core#1673]
The sort on the UI for shares by size incorrectly uses the numeric values and ignores the TB,GB,MB values.  So a 1TB usage will be ranked lower than a 9MB usage on the share.  
What happens:
90.0 MB
8 TB
4 GB
2 MB
1 TB

What should happen:
8 TB
1 TB
4 GB
90.0 MB
2 MB

**Comment by MFlyer** [comment]
Hi @magicalyak ,
you're right about that - noticed while working on new share usage with btrfs "real" used space too.

Hopefully will stop over yum manager via WebUI #1619 and fix this before 3.9.0 release (@suman can you wait? Going to code this today/tomorrow :) )

Mirko

**Comment by magicalyak** [comment]
If you do end up just grabbing the text and parsing, make sure to include KB (I didn't list it but it's used).  Hopefully you can get the value from a common denominator though.  Size also has the same issue on the shares UI view (Size and Usage)

**Comment by MFlyer** [comment]
Every size value over Rockstor views is byte and we get it KB, MB, etc via humanize js funcs, had an ad hoc function on another page fixing same issue :wink:

**Comment by MFlyer** [comment]
DataTables has a builtin file size sorting function, so going to use it without rewrite it :)
