### ISSUE TITLE
Shares UI show incorrect Usage when there is a snapshot

### ISSUE THREAD

**Issue by Ormak** [rockstor/rockstor-core#1675]
Create a share and place files in it.  Take a snapshot and wait for the UI to refresh or open a command line and check the "btrfs subvolume list <mount point>" and "btrfs qgroup show <mount point>" to see the usage and exclusive amounts.  The UI will show the exclusive amount which will be 0 at this point.  It should show the rfer (Total) amount instead.

**Comment by MFlyer** [comment]
Hi @Ormak,
on testing branch this already solved over shares page (current size + "real size" considering snapshots too)

Mirko

**Comment by Ormak** [comment]
Ok, thanks.  I'll get a VM setup with test branch so I can check a few other things I've noticed.

**Comment by MFlyer** [comment]
Thanks @Ormak :)
