### ISSUE TITLE
Install fails with VirtIO drives

### ISSUE THREAD

**Issue by f-r-e-e-s-k-y** [rockstor/rockstor-core#1676]
A new vm from the RHEL 7 template is created on the KVM host with Virtual Machine Manager and booted via ISO. No setup UI is shown, output in console:

> The following problem occured on line 13 of the kickstart file:
> Disk "sda" given in ignoredisk command does not exist.
> Exception AttribureError: "´NoneType´ object has no attribute ´udev_unref´" in blablabla...

Is the disktype hardcoded to sda in some hidden kickstart file? RedHat supports VirtIO diskc. Setting the disktype to **sata** for the vm/hdd image allows me to start the installer.

**Comment by f-r-e-e-s-k-y** [comment]
Update: shutting the system down and manually changing the hdd type from sata back to virtio in Virtual Machine Manager: system boots from virtio hdd without issues.

**Comment by schakrava** [comment]
Thanks for the update @f-r-e-e-s-k-y . I guess we can close this?
