### ISSUE TITLE
Connect to rockstor web gui fails if host has more than one nic

### ISSUE THREAD

**Issue by f-r-e-e-s-k-y** [rockstor/rockstor-core#1677]
A new vm from the RHEL 7 template is created on the KVM host with Virtual Machine Manager and booted via ISO. The vm is configured with 4 ethernet nic´s to be used with bonding after the initial setup/configuration.

The installer configures the nic´s to use dhcp during setup and each nic get a different IP adress after installation. However you can not access the rockstor web gui over any of those IP adresses - ssh and ping working without issues. If you manually set _ONBOOT=no_ to three of the four nic´s in _/etc/sysconfig/networking-scripts/ifcfg-eth*_ and run _systemctl restart network_, the remaining nic with the one IP becomes reachable via a browser and the post setup wizard is shown. Without digging any further I guess this is a binding issue somewhere.

**Comment by MFlyer** [comment]
Hi @f-r-e-e-s-k-y ,
thanks for reporting this, guessing: when we first create nginx conf with initrock task we don't have a configured Rockstor management interface ( ex. from #1686 issue ), so your/our nginx conf file under /opt/rockstor/etc/nginx/nginx.conf will have ip address from initrock.py [init_update_issue task](https://github.com/rockstor/rockstor-core/blob/master/src/rockstor/scripts/initrock.py#L79), but if it fails you don't have a management ip & WebUI access.
How to check this? `cat /etc/issue` should provide further infos and confirmation about Rockstor failing on management & nginx ip.
Next step/question: why are we failing? Well, during initrock.py (Rockstor machine start) we roll the dice 30 times trying to get a default interface to use with Rockstor (same initrock.py code, line 425) via linux ip command (`ip route` to get `default via` line and grab nic name - ex. eth0 on my dev env -, then another ip command, `ip address show YOURNIC` where mine is `ip address show eth0` returning multiple lines with nic ip address too)

Can you try having `ip route` over your ssh shell? If ip route is ok we should have at least 1 nic!
Mirko

**Comment by Hooverdan96** [comment]
@phillxnet, @FroggyFlox is this considered an issue still? Again, quite a bit of time has passed and we're on OpenSUSE now ...
I have not seen that problem on some VMs (under VirtualBox) where I configured multiple NICs, which doesn't mean it doesn't exist, but I have not seen other posts on the forum either in that regards.

**Comment by Hooverdan96** [comment]
@BigBlueHat thanks for reporting this behavior. Did the WebUI survive a reboot after you re-enabled the second NIC via the WebUI? Or did you end up in the same place as before (no UI access, etc.)?

If yes, great. If not, did you set the Management Interface to a particular NIC in `System --> Services --> Rockstor`?
As per:

https://rockstor.com/docs/interface/system/services.html#rockstor

While this might address it so after reboots you can access the UI (albeit only on the NIC specified in the setting), this can obviously only be accessed after the initial UI set up.

I think, it might be related to this:

https://github.com/rockstor/rockstor-core/blob/f7732ac65ad8e40d16490a73cf3ef1a1ce745524/src/rockstor/scripts/initrock.py#L150-L172

where it first checks whether a management ip/interface has already been defined in the services screen, and if not (as @MFlyer mentioned above in his analogy of rolling the dice 30 times) it will try to pick one from the list of interfaces it has. I am not sure what that then looks like with multiple NICs, apparently in some cases, it doesn't find the "right" one).
