### ISSUE TITLE
Autopartitioning during initial setup results in unusable system

### ISSUE THREAD

**Issue by f-r-e-e-s-k-y** [rockstor/rockstor-core#1678]
A new vm from the RHEL 7 template is created on the KVM host with Virtual Machine Manager and booted via ISO. The vm is configured to automatically partition the boot drive during the setup. The vm has only one hdd connected during setup. 

The installation runs through without any further warning and boots without issues, however running the setup wizard in the browser rusults in:

> Houston, we've had a problem.
> 'root filesystem is not BTRFS. During Rockstor installation, you must select BTRFS instead of LVM and other options for root filesystem. Please re-install Rockstor properly.' 
> 
> Traceback (most recent call last):
>   File "/opt/rockstor/src/rockstor/rest_framework_custom/generic_view.py", line 40, in _handle_exception
>     yield
>   File "/opt/rockstor/src/rockstor/storageadmin/views/disk.py", line 272, in post
>     return self._update_disk_state()
>   File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/utils/decorators.py", line 145, in inner
>     return func(*args, **kwargs)
>   File "/opt/rockstor/src/rockstor/storageadmin/views/disk.py", line 62, in _update_disk_state
>     disks = scan_disks(settings.MIN_DISK_SIZE)
>   File "/opt/rockstor/src/rockstor/system/osi.py", line 125, in scan_disks
>     base_root_disk = root_disk()
>   File "/opt/rockstor/src/rockstor/system/osi.py", line 782, in root_disk
>     raise NonBTRFSRootException(msg)
> NonBTRFSRootException: 'root filesystem is not BTRFS. During Rockstor installation, you must select BTRFS instead of LVM and other options for root filesystem. Please re-install Rockstor properly.'

So actually you have to manually partition and reinstall again. If you try to ignore the error and close the popup + just click submit again, django gets really confused and reports:

> Houston, we've had a problem.
> Unknown internal error doing a POST to /setup_user 

It still however is adding users to the system in the background (checked via /etc/passwd).

**Comment by mkeith83** [comment]
This might be related to what I was seeing on VMWare
https://forum.rockstor.com/t/vmware-giving-error-not-a-valid-btrfs-filesystem-dev-disk-by-id-sda3/2543/2

For me it just randomly worked after subsequent installs, but I have since turned this flag on myself. Does KVM has something similar you can try?

**Comment by phillxnet** [comment]
@f-r-e-e-s-k-y Thanks for reporting this. I haven't seen this myself and do almost all my development on KVM with SATA drives. The installer here defaults to the btrfs scheme. We need to improve the documentation / tweak the kickstart file to avoid this happening but not sure whats going on as I have never had to manually partition myself. The install steps I use are documented in our:
"Rockstor in Virtual Machine Manager guide"
http://rockstor.com/docs/kvm_setup.html
How do your steps differ to trigger this ext4 or whatever on root install? I wonder if you are installing to a pre LVM partitioned device and that is triggering a slightly different auto partitioning path.

@mkeith83 Thanks for chipping in on this one but this issue actually covers a different situation. That of our CentOS upstream installer, under certain circumstances, failing to choose the kickstart configured btrfs scheme and falling back to an ext4 root, or something different anyway. Your situation was that of no serial attribution to the block device passed through. KVM does pass a serial through when using SATA bus emulation.

**Comment by Hooverdan96** [comment]
@phillxnet are there any actions left here, since we're not on CentOS anymore, and the installer has been certainly changed a lot (maybe not in this area though) do you see any remaining action for the above issue?

**Comment by phillxnet** [comment]
@Hooverdan96 Thanks for the house cleaning here, much apprecaited.

We are now openSUSE based and use latest kiwi-ng OEM targets for our installer image builds.

Closing as legacy related.
