### ISSUE TITLE
Rockstor volumes not mounting on boot, rockstor boot-strap not starting, and Web ui not accessible.

### ISSUE THREAD

**Issue by djevo1** [rockstor/rockstor-core#1679]
I believe these issues are all related. AFter rockstor version 3.7 I have had nothing but issues in regards to accessing the web ui and getting shares to mount. First it appears rockstor-boostrap will not start. Below is the output of systemctl list dependencies that will not start.

rockstor-bootstrap.service
```

●   ├─rhel-autorelabel-mark.service
●   ├─rhel-autorelabel.service
●   ├─rhel-configure.service
●   ├─rhel-dmesg.service
●   ├─rhel-loadmodules.service
●   ├─selinux-policy-migrate-local-changes@targeted.service
●   │ ├─plymouth-read-write.service
●   │ ├─plymouth-start.service
```

Attempting to access shares also does not work. I have two shares and neither appear to be mounted properly so none of my files are accessible.

Even creating a new initrock does not solve the problem.

**Comment by phillxnet** [comment]
@djevo1 Hello.
Just linking to your current forum post where we can try and narrow this down first.
Also please note that the Rockstor versions you give here and in the forum differ:
Here Rockstor 3.7 (very old), forum post 3.8. I'm assuming 3.8 (forum post) but it would help to know the exact version:
https://forum.rockstor.com/t/unable-to-access-web-ui-and-shares-not-mounted-to-file-system-after-reboot/3029
I see that the forum post already has some engagement from @MFlyer .

**Comment by djevo1** [comment]
I believe I made a mistake on the typing. I originally thought it was 3.7, but it may have been 3.8

**Comment by schakrava** [comment]
This issue description is too broad. Unless reproducible steps are provided, it's hard to make sense of it as a bug. I am closing it. Feel free to reopen with reproducible steps.
