### ISSUE TITLE
Samba Custom configuration UI glitch

### ISSUE THREAD

**Issue by ralphys** [rockstor/rockstor-core#1691]
This is not a serious bug but I want to report it anyways.

The Custom configuration text box in Samba Shares has annoying blank spaces all around... I had to actually SSH into the box and look at the the smb.conf to make sure nothing was messy there. 

Fortunately, this does not seem to affect usability and all parameters are set properly in the configuration.

![3](https://cloud.githubusercontent.com/assets/15816320/24693974/171ea466-19ae-11e7-80cc-61157b1235e5.png)
![4](https://cloud.githubusercontent.com/assets/15816320/24693973/171d526e-19ae-11e7-9449-07bcc134391a.png)

**Comment by MFlyer** [comment]
Hi @ralphys ,
thanks for this, can you please tell us your current Rockstor version?
I had lot of code over Rockstor Samba and I remember I had some code over this too :)

If not an old version related issue, will check it asap
Mirko

**Comment by ralphys** [comment]
I'm on 3.9.0-0; stable updates... so not sure if it was pushed to testing and that's why I don't see it.

**Comment by MFlyer** [comment]
Samba related code was on 3.8.16 cycle, so 3.9.0 has it
Will check it again :)

**Comment by MFlyer** [comment]
Hi @ralphys , got it: I fixed those glitches over Samba global config (under services), but not on share custom config, will fix it!
Mirko

**Comment by MFlyer** [comment]
Thanks @ralphys , it was because of textarea element behaviours ( on textareas tabs, carriage returns and spaces always rendered) plus a minor javascript code fix

PR on its way
Mirko
