### ISSUE TITLE
Please fix the forum

### ISSUE THREAD

**Issue by dragon2611** [rockstor/rockstor-core#1693]
Not really a Rockstor-core issue but the twitter auth is broken on the forum (Http 500 error) did try emailing support/tweeting but didn't get a reply (Maybe it got binned by a filter)

**Comment by MFlyer** [comment]
@schakrava

**Comment by MFlyer** [comment]
Hi @dragon2611 ,
can you close this (not rockstor code related) and have it via Rockstor Forum or with a mail to support@rockstor.com ?

Thanks :)

**Comment by dragon2611** [comment]
@MFlyer well not really as I couldn't login to the forum (I use twitter auth) and I did email support and tweeting the rockstor account but didn't get a reply/acknowledgement from either so this was the only way I could find to contact someone from the team to get it sorted.

Anyway looks like it's been fixed
