### ISSUE TITLE
[Feature enhancement] Enhance output of SMART email reports

### ISSUE THREAD

**Issue by coleberhorst** [rockstor/rockstor-core#1712]
The current emails recieved when we get drive SMART errors only reference /dev/sda type file paths to id the drives. Could we include more identifying information such as Serial, Size, etc?

Sample from recent SMART email
`Device: /dev/sda [SAT], 16 Offline uncorrectable sectors`

@phillxnet suggested modifying this email would be easier and better than say modifing the Storage -> Disks UI on the webui to include the /dev/sda type file path for each disk.

We discussed this in this forum post:
https://forum.rockstor.com/t/minor-disk-ui-improvement-device-dev-path-and-or-smart-email-tweaks/3240/3

**Comment by phillxnet** [comment]
@coleberhorst Had another quick look at this issue.

I suspect the emails where only the short temp-name for drives is given, such as in your example, are those that come directly from smartmontools as Rockstor's own S.M.A.R.T related emails are of the form:

    Drive [u'/dev/disk/by-id/usb-ST950032_5AS_5E1EC8888888-0:0'] has logged S.M.A.R.T errors.
    Please view the Error logs tab for this device.

As we now tend to only use by-id names that already contain the drive's bus, model number, and serial number. In which case this may be an upstream issue to address the smartmontools folks on?

We do have plans to add scheduled S.M.A.R.T tests via an easy to use UI page, beyond those performed by smartmontools by default, and hopefully those can return similarly more useful device names.

**Comment by coleberhorst** [comment]
Awesome, glad to have this clarified. Anything to make identifying failing drives a bit easier and I'm glad to see we can get a solution directly into rockstor eventually.
