### ISSUE TITLE
[Feature] Add UI support for SMB Guest only shares

### ISSUE THREAD

**Issue by ghost** [rockstor/rockstor-core#1720]
Please add GUI level support to create a cifs share as guest only. This will require specifying the guest account and specifying guest only. The following three should work:
guest account = nobody
public = yes
guest only = yes

Note that I was not able to get my guest only share to actually be read/write and I don't know what the issue is yet, but with these three lines I was able to create a share that does not have a password requirement.

**Comment by Hooverdan96** [comment]
Since we have the share level "custom config" section for SMB exports where parameters can be added I am not sure that any additional work would need to be done to reflect these settings above? Unless we consider a one-click version of the above scenario, I would suggest we close this issue.
