### ISSUE TITLE
Drive usage numbers inconsistent 

### ISSUE THREAD

**Issue by barnhill** [rockstor/rockstor-core#1727]
The total space left and used between the two widgets do not match.  This should be consistent.

![capture](https://user-images.githubusercontent.com/3878158/26912562-ead22b44-4bda-11e7-82b9-b58168870a30.PNG)

**Comment by MFlyer** [comment]
Thanks for having this @barnhill, partially related to #1600: shares usage was fixed having "btrfs usage" too (real usage + snapshots usage), pools need coding after shares usage update

M.

**Comment by Hooverdan96** [comment]
I think this can be closed, some fixes have been applied and it was tracked through the above issue ...
