### ISSUE TITLE
Freezed Rockstor after Scheduling hourly Root snapshot

### ISSUE THREAD

**Issue by Daxten** [rockstor/rockstor-core#1730]
Yesterday I setuped an hourly snapshot of the root directory.

Today I came back and rockstor was completly froze, display on it only showed a black screen an no ssh was available (timeout)

after a hard reset everything booted fine, and there was no root snapshot available, so I bet this happened while creating the snapshot.

Which debug info can I provide?

Best regards

**Comment by MFlyer** [comment]
Hi @Daxten,
can you collect some logs from Rockstor Logs Manager? dmesg and rockstor log itself

Mirko

**Comment by Daxten** [comment]
https://recordbayg-my.sharepoint.com/personal/alexej_recordbay_de/_layouts/15/guestaccess.aspx?docid=031b1abda49c84345be86df95a781744f&authkey=AYxuQVk5ESEz34A2lEEaMII

**Comment by Daxten** [comment]
Anything to see there?

**Comment by MFlyer** [comment]
Hi @Daxten ,
here we are:

From your logs:
```

Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/storageadmin/views/disk.py", line 301, in _update_disk_state
    do.name, do.smart_options)
  File "/opt/rockstor/src/rockstor/system/smart.py", line 316, in available
    [SMART, '--info'] + get_dev_options(device, custom_options))
  File "/opt/rockstor/src/rockstor/system/osi.py", line 110, in run_command
    raise CommandException(cmd, out, err, rc)
CommandException: Error running a command. cmd = /usr/sbin/smartctl --info /dev/disk/by-id/usb-SanDisk_Cruzer_Fit_4C530002010412104593-0:0. rc = 1. stdout = ['smartctl 6.2 2013-07-26 r3841 [x86_64-linux-4.8.7-1.el7.elrepo.x86_64] (local build)', 'Copyright (C) 2002-13, Bruce Allen, Christian Franke, www.smartmontools.org', '', '/dev/disk/by-id/usb-SanDisk_Cruzer_Fit_4C530002010412104593-0:0: Unknown USB bridge [0x0781:0x5571 (0x100)]', 'Please specify device type with the -d option.', '', 'Use smartctl -h to get a usage summary', '', '']. stderr = ['']
```

@phillxnet any suggestion with that disk?
M.

**Comment by Daxten** [comment]
Hey, that's the usb stick I installed it from, I've removed it but since the log is spammed with this error I think it's hard to believe that it really freezed the machine

**Comment by Daxten** [comment]
Happened again without the usb-stick, we will reinstall a different OS now and hope this is not hardware related (it's a brand new machine)

**Comment by Hooverdan96** [comment]
This can seemingly be closed, due to age and no report back (assuming that all went well, of course :) ).
