### ISSUE TITLE
Rockstor System Shell = 502 Bad Gateway nginx/1.10.2

### ISSUE THREAD

**Issue by MichaelBiddulph** [rockstor/rockstor-core#1739]
New User of Rockstor version ROCKSTOR 3.8.15-0 - seems to be working fine but System Shell option gives = 502 Bad Gateway nginx/1.10.2

Hardware is HP Microserver n40l
Software is ROCKSTOR 3.8.15-0   Linux: 4.6.0-1.el7.elrepo.x86_64

nginx log gives:
/api/sm/services/shellinaboxd HTTP/1.1" 200 231 "https://192.168.1.116/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"

Help with fixing this would be greatly appreciated.

**Comment by MFlyer** [comment]
Hi @MichaelBiddulph ,
did you try to start/stop system shell service from services page? System Shell off on default, so you have to turn it on

Mirko

**Comment by MichaelBiddulph** [comment]
Mirko
Thanks for the pointer.  It was turned ON but set to us LOGIN - changed it to use SSH and it worked first click.
Cheers, Michael

**Comment by MFlyer** [comment]
Can we close this @MichaelBiddulph ?
Thanks :)
Mirko

**Comment by KaiRo-at** [comment]
Why was this closed? The default setting of the service is LOGIN so by default, it doesn't work for people out there. If the solution is to change the default setting, then that should actually be done in an issue (this one?), I would think...

**Comment by mozzbozz** [comment]
@MFlyer I agree with @KaiRo-at - you should reopen this issue, same problem for me with the standard setting. Also tooltip suggests that the SSH-option is less secure.

**Comment by computergeek125** [comment]
I found this today shortly after messing about with Active Directory.  I discovered that changing to `SSH` worked to restore the shell, but that it also continued working when I switched it back to `LOGIN`

**Comment by Jip-Hop** [comment]
This issue is still relevant for a fresh install of RockStor 3.9.1-16. I didn't have this issue on the RockStor 4 beta.

**Comment by phillxnet** [comment]
@Jip-Hop Liking to a recent post on the forum re release dates:
https://forum.rockstor.com/t/luks-full-disk-encryption-on-rockstor-4-system-drive/7770/5
3.9.1-16 released Nov 2017 (last testing on CentOS)
Stable updates only then on CentOS until 3.9.2-57 (April 2020)
Now we are only working on the 'Built on openSUSE' 4 variant, last released March 2021 as version 4.0.6.

**Comment by gabrielxfx** [comment]
> New User of Rockstor version ROCKSTOR 3.8.15-0 - seems to be working fine but System Shell option gives = 502 Bad Gateway nginx/1.10.2
> 
> Hardware is HP Microserver n40l Software is ROCKSTOR 3.8.15-0 Linux: 4.6.0-1.el7.elrepo.x86_64
> 
> nginx log gives: /api/sm/services/shellinaboxd HTTP/1.1" 200 231 "https://192.168.1.116/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"
> 
> Help with fixing this would be greatly appreciated.

Hi , I come from the future, just installed it on my  N40L latest version , got the bad gateway error , you know what I did, just wait a while like 10 mins , and then I could browse onto the GUI and could finish install process. So if this helps someone else.... just wait....
