### ISSUE TITLE
failed to start rockstor hdparm settings

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#1752]
An as yet unidentified system package update seems to have broken (on some systems) the rockstor-hdparm.service that enacts custom Web-UI configured drive spin down time and APM levels during boot.
```
journalctl -u rockstor-hdparm.service
hpp systemd[1]: Starting Rockstor hdparm settings...
hpp hdparm[1727]: /dev/disk/by-id/ata-SAMSUNG_HM160HI_S1WWJ9BZ408430: No such file or directory
hpp systemd[1]: rockstor-hdparm.service: main process exited, code=exited, status=2/INVALIDARGUMENT
hpp systemd[1]: Failed to start Rockstor hdparm settings.
hpp systemd[1]: Unit rockstor-hdparm.service entered failed state.
hpp systemd[1]: rockstor-hdparm.service failed.
```

It was found that if the same rockstor-hdparm.service file was executed later in the boot process it would succeed:
```
journalctl -u rockstor-hdparm.service
...
hpp systemd[1]: Starting Rockstor hdparm settings...
hpp systemd[1]: Started Rockstor hdparm settings.
```

A pull request to address this issue is under development.

**Comment by eliasmagn** [comment]
```
[root@nas ~]# systemctl restart rockstor-hdparm
[root@nas ~]#

```
journalctl:
```
[root@nas ~]# journalctl -u rockstor-hdparm.service
-- Logs begin at Di 2017-07-11 10:39:50 CEST, end at Di 2017-07-11 11:08:18 CEST
Jul 11 10:39:57 nas systemd[1]: Starting Rockstor hdparm settings...
Jul 11 10:39:58 nas systemd[1]: Started Rockstor hdparm settings.
Jul 11 11:07:41 nas systemd[1]: Starting Rockstor hdparm settings...
Jul 11 11:07:50 nas systemd[1]: Started Rockstor hdparm settings.
lines 1-5/5 (END)
```
rockstore 3.9.1-0 latest (non stable updates)
```
[root@nas ~]# uname -a
Linux nas 4.10.6-1.el7.elrepo.x86_64 #1 SMP Sun Mar 26 12:19:32 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by phillxnet** [comment]
@eliasmagn Thanks for the feedback, much appreciated. Yes I've found that it is only affecting some systems so still trying to work out why. As a note on your test, on all the test systems affected here a restart wouldn't show the failure, however from the looks of your journalctl it also worked on boot (the 10:39) entry.
Could you state some info on your systems nature, ie number of cores / threads, ssd or hdd system disk, RAM for example. It would just be nice to be able to announce more than "(on some systems)" when releasing the fix, if I can.

Pretty sure I have a proper fix for all systems in the works however so we are good to go soon but just need a little more time to make sure my fix (improved rockstor-hdparm.service template) is not going to adversely affect currently working systems. Will do some more testing hopefully later today and would appreciate your trialling my fix once I've got it ready for commit (should appear against this issue), if your game? By way of further regression testing that is (in your case at least). No worries otherwise.

Thanks again for helping out on this one.

**Comment by phillxnet** [comment]
@eliasmagn I've made a commit against this issue that indicates the changes made to ensure our deployed rockstor-hdparm.service file is executed after the by-id names become available. If you make those same changes to your installed version (after making a copy by a different name of the existing version):

    /opt/rockstor/conf/rockstor-hdparm.service

taking care to keep the exact line count (hence my re-wording of the comments) as that way the transition from old to new should be smoother. You will then need to remove all your spin down and apm settings from all of your drives (simply select "Remove config" from the drop down). This will end up removing the existing /etc/systemd/system/rockstor-hdparm.service file. Then when you re-add your settings the new template file will come into play along with its new line. There after a reboot should prove if we have any regression on your system. None were observed here except maybe an additional second on some system boot times.

No worries if you don't fancy trialling this fix (for any regressions) as it looks good to me here, fix and regression wise. Especially if you are not familiar with the linux command line: but I'm assuming you are.

We have nano pre-installed so that might help as it's only a single line change: but do make sure you don't change the actual line count of that file.

**Comment by eliasmagn** [comment]
I will test it soon. i am just home from work.

**Comment by phillxnet** [comment]
Thanks for the system info, nice. I have an Asus N3700 ITX low power build here that looks similar (also didn't exhibit this issue). Do you fancy doing a forum post on your system. I expect it will draw some interest / discussion as there are many more eyes there: plus easier to discus without flooding this issue. Just a though.

Re the issue commit: Are yes, sorry (silly me) this is a direct link:
:
https://github.com/phillxnet/rockstor-core/commit/cd2721c8e5e568d1f478f4263e2ca344a9206292

Essentially you just need to replace the first line of comments in the template file with:

Requires=systemd-udev-settle.service

In order to keep the line count the same. Then follow the previous instructions re enabling it's use over the existing one.

I'll try and create a pull request tomorrow if it continues to check out and if it ends up being merged then your system, in time, will receive the edited comments etc via the rpm but be functionally the same.

Cheers.

**Comment by eliasmagn** [comment]
Still no issue !  And it should be enough to read the code, like you mentioned, to see that this shouldnt delay the execution of hdparm.service too much. XD

**Comment by phillxnet** [comment]
@eliasmagn OK, so no regression on your system then. Great thanks.
I used the following bash alias:

    echo "alias bp='systemd-analyze plot > boot.svg'" >> ~/.bashrc

To get a "bp" boot picture of how the boot up changes and sure enough it sets up a type of watch dog service that allows us to fire off our rockstor-hdparm.service only once all the udev stuff is in place. Only really added an addition second or two on boot times (due to greater constraints on ordering I expect) so I think that's OK for greater robustness.

So can I add that you have tested for regression on your prior and still working system to the pr? I.e you have confirmed that you are running an /etc/systemd/system/rockstor-hdparm.service file based on the new template (that is containing the new Requires line) and have successfully booted multiple times with no hdparm failures such as are sighted in the original issue post?

**Comment by eliasmagn** [comment]
Yes you can. 

```
[root@nas ~]# journalctl -u rockstor-hdparm.service; echo "####"; date; echo "#####"; grep "Requires" < /opt/rockstor/conf/rockstor-hdparm.service
-- Logs begin at Mi 2017-07-12 19:05:13 CEST, end at Mi 2017-07-12 20:27:01 CEST. --
Jul 12 19:05:20 nas systemd[1]: Starting Rockstor hdparm settings...
Jul 12 19:05:20 nas systemd[1]: Started Rockstor hdparm settings.
####
Mi 12. Jul 20:27:57 CEST 2017
#####
Requires=systemd-udev-settle.service
```
