### ISSUE TITLE
Bootloader UEFI wrong directory for grubx64.efi in UEFI entry. V.3.9.1

### ISSUE THREAD

**Issue by eliasmagn** [rockstor/rockstor-core#1753]
**The issue:  the grubx64.efi resides under EFI/centos/ but installer configures uefi on EFI/fedora/shim.efi**
On my system gigabyte j1900n d3v, it is possible to boot via usb3.0 and it works fine when configuring uefi after installation via efibootmgr. I have to chroot into /mnt/sysimage 
`efibootmgr -v -c -L"Rockstor" -d /dev/sdc -p1 -l "EFI/centos/grubx64.efi"`
Although i have to grub2-mkconfig -o /boot/efi/EFI/centos/grub.cfg
The Rockstor-Installer configures efibootmgr as: 
EFI/fedora/shim.efi 
which is not existing and failes to write grub config.
/EFI/BOOT/BOOTX64.EFI is existing as well but ignored by my board, dont know wy! The reason could be in booting from usb3.0. Debian/Centos/Gentoo/Arch isos are booting fine on USB3.0
_I only wanted to tell you about the fedora bootentry which is not correct._

**Comment by phillxnet** [comment]
@eliasmagn This is a great find and thanks for opening this issue. However would you mind opening it in our rockstor-iso repo:
https://github.com/rockstor/rockstor-iso
as I think it belong there. You could just cut and paste this one's contents there and close this as "moved to rockstor-iso repo".
That way it can stay under you name and hopefully be addressed ready for our next iso release.

Thanks again for reporting your findings.

**Comment by eliasmagn** [comment]
Yep ill do so thnks
