### ISSUE TITLE
jquery map file missing

### ISSUE THREAD

**Issue by eliasmagn** [rockstor/rockstor-core#1754]
fixed it by wget-ing https://code.jquery.com/jquery-3.2.1.min.map
mv jquery-3.2.1.min.map /opt/rockstor/static/js/lib/jquery.min.map
```
/var/log/nginx/error.log
2017/07/10 21:31:09 [error] 12002#0: *372 open() "/opt/rockstor/static/js/lib/jquery.min.map" failed (2: No such file or directory), client: 192.168.1.219, server: ~^(?<myhost>.+)$, request: "GET /static/js/lib/jquery.min.map HTTP/1.1", host: "192.168.1.183"
2017/07/10 21:42:15 [error] 12002#0: *610 open() "/opt/rockstor/static/js/lib/jquery.min.map" failed (2: No such file or directory), client: 192.168.1.219, server: ~^(?<myhost>.+)$, request: "GET /static/js/lib/jquery.min.map HTTP/1.1", host: "192.168.1.183"
2017/07/10 21:43:01 [error] 12002#0: *631 open() "/opt/rockstor/static/js/lib/jquery.min.map" failed (2: No such file or directory), client: 192.168.1.219, server: ~^(?<myhost>.+)$, request: "GET /static/js/lib/jquery.min.map HTTP/1.1", host: "192.168.1.183"
2017/07/10 21:44:43 [error] 12002#0: *652 open() "/opt/rockstor/static/js/lib/jquery.min.map" failed (2: No such file or directory), client: 192.168.1.219, server: ~^(?<myhost>.+)$, request: "GET /static/js/lib/jquery.min.map HTTP/1.1", host: "192.168.1.183"

```

**Comment by phillxnet** [comment]
@eliasmagn Thanks for another nice find. Can you say how you reproduced this nginx error log entry as that should help to pin down how we best address it and also help with proving the fix we settle on.

@MFlyer This is more in your area, could you advise on what we might be missing and where here. Does this issue for instance belong in our rockstor-jslibs repo? Thanks.

**Comment by eliasmagn** [comment]
@phillxnet 
I really dont know how i produced this error, just was looking for a possibility to proxy 
```
 location /some/path/ {
    proxy_pass http://www.example.com/link/;
} 
```
gunicorn with nginx for https/http2 and was looking in nginx log for the shell bug mentioned here [https://github.com/rockstor/rockstor-core/issues/1739](url) which encountered me, fixed like they described in the issue, by de/re/activating shell service twice.

The log stays clean now! I wasnt digging into your jquery scripts! 
As the log file mentioned jquery.min.map was just missing. I think it has not made its way in the 3.9.1 iso.
OFFTOPIC -->

> By the way: do you need someone for German translations? As you probably noticed i'm not a native English speaker. I see that the text on storageadmin is static which makes it not easy to have multiple languages installed. I will test to set up some variables inside. Perhaps its better to write a feature thread, than talk about that here. 

Regards eliasmagn

**Comment by phillxnet** [comment]
@eliasmagn Thanks for the update. So bit of a strange one then. We do need a reproducer to proceed really. Maybe @MFlyer will have some insight on this when he next gets time.

As you are now not seeing this maybe we should leave it open for a bit to see if any more info comes along and then if nothing further turns up we could close it as 'no reproducer found'.

As for digging; no worries there as all our stuff is open source (various licences on the js but it's all open) so the more digging the better.

On your translation note please see issue #821, I believe @MFlyer (Italian) has made some inroads there. Do please comment there (ideas / efforts wise) and thanks for your generous offer re German, once we get fully setup translation wise this would be great. Also note the links back to our forum in that issue for other discussions re translation.

Cheers.

**Comment by MFlyer** [comment]
Hi all,
sorry cos' I'm late.
Short answer: we don't care about map files
Long answer: you need map files to debug minified js files - like our jquery js -, but your code will run although a missing map file 😉 

Mirko

**Comment by phillxnet** [comment]
@MFlyer Thanks, figured you'd know.

@eliasmagn Given @MFlyer's last statement here are you happy to close this issue as "js map file irrelevant in production" or what ever you think best sums this up. Thanks.

**Comment by eliasmagn** [comment]
@MFlyer An accedantly pressed F12 produced this issue XD.
You are totally right.
