### ISSUE TITLE
Config backup restore error: exception: isdir() takes exactly 1 argument (0 given)

### ISSUE THREAD

**Issue by FroggyFlox** [rockstor/rockstor-core#1765]
The following error is encountered on 3.9.1 when trying to upload a 3.9.1 config backup.
```
[19/Jul/2017 08:39:16] ERROR [storageadmin.util:44] exception: isdir() takes exactly 1 argument (0 given)
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/rest_framework_custom/generic_view.py", line 41, in _handle_exception
    yield
  File "/opt/rockstor/src/rockstor/storageadmin/views/config_backup.py", line 255, in post
    if (not os.path.isdir()):
TypeError: isdir() takes exactly 1 argument (0 given)
```
Full details can be found in the forum topic:
https://forum.rockstor.com/t/config-backup-upload-error/3537

1. Create Rockstor VM (VirtualBox in Windows): Rockstor1:
  - virtual drive (let's call it "A") for system install
  - virtual drive for pool (SATA1) with Rockons-root configured and two additional shares for a test rockon (Syncthing)

2. Backup config for Rockstor1 and download the .json.gz file on local HDD.

3. Create a second Rockstor VM: Rockstor2:
   - 1 (new) virtual drive (let's call it "B") for system install

4. Boot Rockstor2 and run yum updates.

5. Shutdown Rockstor2

6. Attach SATA1 drive to VM

7. Boot Rockstor2

8. Import pool in webUI for SATA1 (was successful)

9. Try to upload previous config backup file and receive the error pasted above when clicking on the "Upload file" button.

**Comment by phillxnet** [comment]
I am currently working on this issue.

**Comment by phillxnet** [comment]
This issue's cause may simply be a missing cb_dir parameter on line:

https://github.com/rockstor/rockstor-core/blob/master/src/rockstor/storageadmin/views/config_backup.py#L255

Further testing is underway, if all looks OK I will submit a pr shortly.
