### ISSUE TITLE
Block role-wipe-luks page for fake serial drives

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#1767]
Thanks to forum member roswitina for highlighting this behaviour in the following forum thread. When encountering a drive with no or non-unique serial we attribute it a fake-serial and display a warning indicating that it can not form part of a pool. However we do not block it's role/wipe/luks page link which leads to a confusing user experience as the code errors out as the non stable drive names / id (multiple non unique serial instances) move under us. The solution is to block access to the role/wipe/luks page as we already explain that these drives are not supported so we should not offer the role/wipe/luks features on 'no or non-unique' (fake-serial) drives.

Please update the following forum thread with the resolution of this issue:
https://forum.rockstor.com/t/configure-drive-role-failure/3563

**Comment by Hooverdan96** [comment]
@phillxnet, is this still an issue?

**Comment by phillxnet** [comment]
@Hooverdan96 Re our current issues backlog, and this having had no attention. Lets close it. I'm also fairly sure this has now been tended to. We would need a cleaner reproducer also to ease follow-up anyway.

Plus you activity re LUKS and our pending LUKS2 move may re-surface this. But importantly in a modern code context.

Closing as suspected legacy with no community interest there-after.
