### ISSUE TITLE
System shell doesn't work

### ISSUE THREAD

**Issue by sirio81** [rockstor/rockstor-core#1823]
Rockstor 3.9.1-0.

Clicking on System Shell (url: https://<ip>/#shell), I get the error

502 Bad Gateway
nginx/1.10.2

**Comment by phillxnet** [comment]
@sirio81 Could you take a look at the following forum thread and report back here on your experience with this issue. Definitely something that needs fixing and I suspect we have a race condition of sorts where we depend on a program to install in the background that is failing to do so 'in time'.

https://forum.rockstor.com/t/system-shell-error/3738

Calling on @MFlyer who coded this feature a little while ago.

**Comment by MFlyer** [comment]
Hi @phillxnet ,
hope to check it asap

M.

**Comment by martinbehrens** [comment]
I can confirm the issue. Reproducible as well is that the shell suddenly presents a login prompt instead of a 502 response code after 30 minutes or so.

**Comment by thunfischbrot** [comment]
Same here, expect it is 502 immediately after boot up.

**Comment by Hooverdan96** [comment]
Now on 4.x and provisioning our own version of Shellinabox, is this still an issue that needs to be tracked or can it be closed for now?
