### ISSUE TITLE
Network card not active after installation

### ISSUE THREAD

**Issue by sirio81** [rockstor/rockstor-core#1824]
I installed rockstore 3.9.1-0 on a pc with 2 ssd and automatic partitioning.
I dind't change netwrok settings so it set to use dhcp.
At first boot the network card is not configured and in state down.
I have to add an ip by console.
This is what I see in Network section:

![immagine](https://user-images.githubusercontent.com/2992550/30629804-16ba7c3e-9dde-11e7-99a2-722afa713d96.png)

I checked
  ps aux | grep dhc
and there are no dhclient processes running.

**Comment by sirio81** [comment]
I confirm that choosing 'Open shell in a popup window' in the service option works.
After disabling the option, it works also inside the window.
So this is a work around.

**Comment by FroggyFlox** [comment]
Closing this issue as legacy due to the fact that it relates to our older installer and older OS base.
