### ISSUE TITLE
Rockstore installer doens't work well with virtio driver

### ISSUE THREAD

**Issue by sirio81** [rockstor/rockstor-core#1825]
The guest is run by Virtaul Machine Manager on a debian 9 host.

![immagine](https://user-images.githubusercontent.com/2992550/30647376-8b0d565a-9e1b-11e7-8eef-75bdc5867648.png)

This is the qemu process with its options:

`qemu-system-x86_64 -enable-kvm -name guest=rockstore,debug-threads=on -S -object secret,id=masterKey0,format=raw,file=/var/lib/libvirt/qemu/domain-3-rockstore/master-key.aes -machine pc-i440fx-2.8,accel=kvm,usb=off,vmport=off,dump-guest-core=off -cpu Westmere,+vme,+ds,+acpi,+ss,+ht,+tm,+pbe,+pclmuldq,+dtes64,+monitor,+ds_cpl,+vmx,+est,+tm2,+fma,+xtpr,+pdcm,+pcid,+movbe,+tsc-deadline,+xsave,+osxsave,+avx,+f16c,+rdrand,+arat,+fsgsbase,+tsc_adjust,+bmi1,+avx2,+smep,+bmi2,+erms,+invpcid,+xsaveopt,+pdpe1gb,+rdtscp,+abm -m 1024 -realtime mlock=off -smp 2,sockets=2,cores=1,threads=1 -uuid e0131c53-1c35-4abb-952a-e8b99ca8af40 -no-user-config -nodefaults -chardev socket,id=charmonitor,path=/var/lib/libvirt/qemu/domain-3-rockstore/monitor.sock,server,nowait -mon chardev=charmonitor,id=monitor,mode=control -rtc base=utc,driftfix=slew -global kvm-pit.lost_tick_policy=delay -no-hpet -no-shutdown -global PIIX4_PM.disable_s3=1 -global PIIX4_PM.disable_s4=1 -boot menu=off,strict=on -device ich9-usb-ehci1,id=usb,bus=pci.0,addr=0x5.0x7 -device ich9-usb-uhci1,masterbus=usb.0,firstport=0,bus=pci.0,multifunction=on,addr=0x5 -device ich9-usb-uhci2,masterbus=usb.0,firstport=2,bus=pci.0,addr=0x5.0x1 -device ich9-usb-uhci3,masterbus=usb.0,firstport=4,bus=pci.0,addr=0x5.0x2 -device ahci,id=sata0,bus=pci.0,addr=0x6 -device virtio-serial-pci,id=virtio-serial0,bus=pci.0,addr=0x7 -drive file=/home/valerio/iso/Rockstor-3.9.1.iso,format=raw,if=none,id=drive-ide0-0-1,readonly=on -device ide-cd,bus=ide.0,unit=1,drive=drive-ide0-0-1,id=ide0-0-1,bootindex=1 -drive file=/home/valerio/vm/disks/rockstore_test1.qcow2,format=qcow2,if=none,id=drive-virtio-disk0 -device virtio-blk-pci,scsi=off,bus=pci.0,addr=0x9,drive=drive-virtio-disk0,id=virtio-disk0,bootindex=2 -drive file=/home/valerio/vm/disks/rockstore_test2.qcow2,format=qcow2,if=none,id=drive-virtio-disk1 -device virtio-blk-pci,scsi=off,bus=pci.0,addr=0xa,drive=drive-virtio-disk1,id=virtio-disk1,bootindex=3 -drive file=/home/valerio/vm/disks/rockstore_test3.qcow2,format=qcow2,if=none,id=drive-virtio-disk2 -device virtio-blk-pci,scsi=off,bus=pci.0,addr=0xb,drive=drive-virtio-disk2,id=virtio-disk2,bootindex=4 -drive file=/home/valerio/vm/disks/rockstore_test4.qcow2,format=qcow2,if=none,id=drive-virtio-disk3 -device virtio-blk-pci,scsi=off,bus=pci.0,addr=0xc,drive=drive-virtio-disk3,id=virtio-disk3,bootindex=5 -netdev tap,fd=25,id=hostnet0 -device e1000,netdev=hostnet0,id=net0,mac=52:54:00:f0:dd:ea,bus=pci.0,addr=0x3 -chardev pty,id=charserial0 -device isa-serial,chardev=charserial0,id=serial0 -chardev spicevmc,id=charchannel0,name=vdagent -device virtserialport,bus=virtio-serial0.0,nr=1,chardev=charchannel0,id=channel0,name=com.redhat.spice.0 -spice port=5900,addr=127.0.0.1,disable-ticketing,image-compression=off,seamless-migration=on -k it -device qxl-vga,id=video0,ram_size=67108864,vram_size=67108864,vram64_size_mb=0,vgamem_mb=16,max_outputs=1,bus=pci.0,addr=0x2 -device intel-hda,id=sound0,bus=pci.0,addr=0x4 -device hda-duplex,id=sound0-codec0,bus=sound0.0,cad=0 -device virtio-balloon-pci,id=balloon0,bus=pci.0,addr=0x8 -msg timestamp=on
`

**Comment by MFlyer** [comment]
Hi @sirio81,
going to help you, had same issues when testing Rockstor over Proxmox virtualization:

you just need to add a "fake sata disk" cos' Rockstor installer requires a sata disk, but you can install it over your virtios.
Ex.: rockstor VM with 1 or more virtios + 1 1GB sata disk, installer will run fine, you'll install over your virtio disk, shutdown rockstor, remove sata disk and et voilà

M.

**Comment by sirio81** [comment]
Ok, nice to know about the workaround.

**Comment by MFlyer** [comment]
Hi @sirio81 ,
can you close this? thx
M.
