### ISSUE TITLE
Give a visual indication that an update is running in the background

### ISSUE THREAD

**Issue by doenietzomoeilijk** [rockstor/rockstor-core#1827]
This issue came out of [this thread](https://forum.rockstor.com/t/samba-service-broken-after-update-11/3780).

It is possible to start an update from the web UI, or by having automatic updates enabled. Shutting down or rebooting during those updates is, of course, a recipy for disaster, but currently it's hard to tell if an update is in progress. Also, it might give the idea that nothing happened after starting the update in the web UI.

**Proposal**: add a notification that shows up when an update is in progress, similar to the "please don't shutdown your console, I'm doing important stuff" messages you see on game consoles.

To detect a background update, we could poll for the existance of `/var/run/yum.pid` (and maybe check for the actual process if we're being thorough).

There's already a bit of scaffolding in the HTML we could use (currently in router.js, the check for updates is a bit coarse ("did the user just click the button"), but that can be built upon.

**Comment by phillxnet** [comment]
Linking to other potentially related forum threads concerning failed / interrupted os updates:
forum member kysdaddy https://forum.rockstor.com/t/samba-stops-working-after-activation/5117

**Comment by Hooverdan96** [comment]
While this was on 3.x, I and we do have the small blinking radio icon during a running update, should we consider more blatant warnings/indicators in case the user tries to shut down/reboot? If not, is this issue then still considered open?

**Comment by phillxnet** [comment]
@doenietzomoeilijk @Hooverdan96 we do have the blinking (wifi like) icon now re updates. But yes we do have to improve things here. However we are now zypper based  on an different OS base (openSUSE) and it would be good to have a fresh issue detailing a proposed improvement re back-end/front-end ideally using our planed HTMX mechanisms.

As we do now have 400+ issues as backlog, I'm closing this as having received no community contribution attention/code wise. But it does remain a weak point for us and we do need to up-our-game on this specific user-feedback element. But with a view to our current zypper base.

So in light of recent confusion re old issues leading folks a-stray this one counts as a candidate for closure.

@doenietzomoeilijk if you are still interested in contributing do take a look at our current openSUSE leap / TW based offering in testing to suggest other OS flags/files we could use to indicate these back-ground updates. We also have the issue that during our own update, users end-up with an nginx errror: this could instead be redirected to the zypper history file content with a "Refresh for status update" header. Via a custom nginx error handler. So what we need here is a modern take on a well know weakness of ours.

Closing to avoid confusion re prior OS base. But not discounting as we do need work in this area. But our resources have been focused on OS switch, and more recenly build system & dependency modernisation. So our options here re solutions should now be broader.
