### ISSUE TITLE
failure in share import prep re duplicate name and usage

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#1828]
Thanks to forum member @magicalyak for reporting and helping to diagnose this issue.  Under certain circumstances when a share on disk is not currently reflected in the db an attempt is made to import and mount each share.  This effort includes a check to establish if there are duplicate share names which is unfortunately circumvented due to a bug which causes this check to never be executed, along with various share calculations that would otherwise also be executed.

Please see the following forum thread for reference of this issues origin:
https://forum.rockstor.com/t/subvolumes-not-mounted-but-pools-mount/3797

**Comment by magicalyak** [comment]
Since there isn't a way to mount duplicates in /mnt2 due to naming, is there a way to mount the reported subvolid in rockstor or even just pick the first one and once a dupe is detected just not mount it (spit an error out in the logs and move on)?

**Comment by phillxnet** [comment]
I am currently working on this issue and have established it's root cause as related to incomplete changes relating to issue #930. I am currently in the process of refactoring the relevant code to help clarify further development and a pending fix re the side effects indicated.

**Comment by phillxnet** [comment]
@magicalyak Good point but can you please remove it from this issue and open a new feature request or better still a design discussion via a forum thread with the same as it is way over broad for this issue as defined and referenced. Thanks.

**Comment by phillxnet** [comment]
@magicalyak I have now corrected my omission re the indicated referenced forum thread.

**Comment by phillxnet** [comment]
The core cause of this issue is a legacy parameter type used when calling share_info but as this call is within a large try clause there are several potential effects that may result as the intended code has not been in effect for a couple of years. I am about to update the erroneous call and begin testing prior to submitting a pull request.

**Comment by phillxnet** [comment]
Correcting the legacy call to share_info() from within the try clause of import_shares() gives the following, intended, log entry to identify the issue found:
```
ERROR [storageadmin.util:44] exception: Another pool(pool-on-luks-dev) has a Share with this same name(luks-share) as this pool(luks-pool-on-bcache). This configuration is not supported. You can delete one of them manually with this command: btrfs subvol delete /mnt2/[pool name]/luks-share
Traceback (most recent call last):
  File "/opt/rockstor-dev/src/rockstor/storageadmin/views/share_helpers.py", line 111, in import_shares
    cshare = Share.objects.get(name=s_on_disk)
  File "/opt/rockstor-dev/eggs/Django-1.8.16-py2.7.egg/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/rockstor-dev/eggs/Django-1.8.16-py2.7.egg/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: Share matching query does not exist.
[22/Sep/2017 16:54:36] DEBUG [storageadmin.util:45] Current Rockstor version: unknown

```

**Comment by phillxnet** [comment]
Log error message updated to reflect the data loss component of the suggested command:

_"Another pool (pool-on-luks-dev) has a Share with this same name (luks-share) as this pool (luks-pool-on-bcache). This configuration is not supported. You can delete one of them manually with the following command: "btrfs subvol delete /mnt2/[pool name]/luks-share" WARNING this will remove the entire contents of that subvolume."_

**Comment by phillxnet** [comment]
I have a little more testing to do on the code / commits as associated and then I'll prepare the pull request.
