### ISSUE TITLE
nginx.conf empty - no "events" section in configuration

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#1833]
Thanks to forum members grizzly and petermc for highlighting this issue. On rare occasions the /opt/rockstor/etc/nginx/nginx.conf file is empty. This leads to a Web-UI failure and the following error messages in /var/log/nginx/errors.log:
```
2016/05/04 07:41:12 [emerg] 14606#0: no "events" section in configuration
2016/05/04 07:41:13 [emerg] 14636#0: no "events" section in configuration
2016/05/04 07:41:16 [emerg] 14794#0: no "events" section in configuration
2016/05/04 07:41:19 [emerg] 14861#0: no "events" section in configuration
```
The issue author has also seen this occurrence but it's cause has yet to be established:
```
ls -la /opt/rockstor/etc/nginx/nginx.conf 
-rw------- 1 root root 0 Nov  5 11:23 /opt/rockstor/etc/nginx/nginx.conf
```

Referenced forum threads (please update on this issues resolution):
grizzly: https://forum.rockstor.com/t/solved-rockstor-webui-no-longer-starts-3-8-13/1444
petermc: https://forum.rockstor.com/t/opt-rockstor-etc-nginx-nginx-conf-empty/3812

**Comment by phillxnet** [comment]
Thanks to petermc in the following forum thread for confirming the following 'work around' to re-assert / re-populate this file:
```
cat /opt/rockstor/conf/nginx.conf.in | sed -e 's/\${buildout:directory}/\/opt\/rockstor/g' -e 's/\${init-gunicorn:bind}/127.0.0.1/g' -e 's/\${init-gunicorn:port}/8000/g' > /opt/rockstor/etc/nginx/nginx.conf
chmod 600 /opt/rockstor/etc/nginx/nginx.conf
systemctl restart rockstor
```
from:
https://forum.rockstor.com/t/opt-rockstor-etc-nginx-nginx-conf-empty/3812/2

**Comment by skynett81** [comment]
i did have a problem that the web-gui dident start as normal , but after this it did work :) 
`cat /opt/rockstor/conf/nginx.conf.in | sed -e 's/\${buildout:directory}/\/opt\/rockstor/g' -e 's/\${init-gunicorn:bind}/127.0.0.1/g' -e 's/\${init-gunicorn:port}/8000/g' > /opt/rockstor/etc/nginx/nginx.conf
chmod 600 /opt/rockstor/etc/nginx/nginx.conf
systemctl restart rockstor`

**Comment by phillxnet** [comment]
@skynett81 Thanks for confirming the command. But note that the editor seems to have eaten some of your cut and paste (ie the back slashes) hence my quoting to preserve them in my last post.
Still not sure why this happens but good to know we have a workable command line work around available at least.

**Comment by wwwizzarrdry** [comment]
I has the same scenario happen last night. 
Just received a bunch of new cooling fans, dist covers and another 8gb of ram in the mail. I brought my server down normally, then went to work installing everything.

When I brought it back online, SSH worked but the rockstor ui was borked and only provided an error page with a link to a tarball of useful logs.

A few moments later, port 22 became unresponsive and I lost shell access.
A subsequent refresh of the webui was also met with a page not found error.

Rebooting was met with immediate kernel panic - not syncing errors.
The logs were full of memory segfaults.
For whatever reason, I finally rearranged my ram modules back to the original order (two original sticks in the first 2 slots, and the new sticks in the remaining two slots) and that magically fixed the kernel panic and rockstor booted fine again. Btrfs fi show had my pool online again.

All my shared were accessible via smb, and my Dockers were all working. Standalone Monitorix didn't work and neither did rockstor ui. (Obviously an nginx problem as the logs were full of "no events in config" warnings).

I switched monitorix to use it's own http server and that started working fine again, but I didn't know how to fix nginx. I'm only versed in Apache, but simple copying the nginx.conf.default to the now empty nginx.conf didn't work.

I finally found this thread and used the sed command, did a systemctl restart rockstor, and everything is groovy again.

Only thing I can think, is that perhaps the empty nginx conf is related somehow to the memory faults I experienced and the order in which services are loaded.

Either way, I think this post should be pinned for future reference. I also created a Cron job that checks the status of nginx every morning and runs the sed command  automatically if the nginx.conf file is empty.

I also made it a system command, so now I can just systemctl start repair_nginxconf and run it on demand.


Thanks for sharing this solution. Cheers.

**Comment by phillxnet** [comment]
@wwwizzarrdry Thanks for sharing your findings, quite a journey you had there and I'm glad my hack / work around helped get you up and running again.

This GitHub issue is really to observe the fix and collect what we can about the rare occasions that this has been seen. But you might well be interested in contributing to our forum https://forum.rockstor.com as it is a richer medium for discussion and I think your story would be of interest there. The forum thread links in this issue link back to others experiences that lead to it's opening. Plus any thread you add to goes to the top of the web view. Not sure it's common enough to make sticky / pin though.

I'm not convinced myself that this issue is down to memory faults, though of course, as you indicate, it could be. But I have seen it on an otherwise reliable machine (but it was old).

**Comment by smokku** [comment]
It happened to me when the server rebooted several times due to kernel panic wile startup (one of my CPU cores is unstable).
I have a feeling that some process editing this file on startup got interrupted and didn't flush modified file.

**Comment by phillxnet** [comment]
@smokku This is a good pointer, we do have the initrock.py script section here:

https://github.com/rockstor/rockstor-core/blob/master/src/rockstor/scripts/initrock.py#L154-L159

which in turn calls update_nginx(ip, port) here:

https://github.com/rockstor/rockstor-core/blob/686c5e88f1493428c42646607b72bc1f6073d2ab/src/rockstor/system/services.py#L221-L248

Popping these in as likely 'offenders'.

**Comment by Hooverdan96** [comment]
@phillxnet  with the implementation of #2420 (issue #2076) the offending code has substantially changed, and this issue can probably be closed.

**Comment by phillxnet** [comment]
@Hooverdan96 Thanks, closing as advised.
