### ISSUE TITLE
Lost internet connection

### ISSUE THREAD

**Issue by pariahsmile** [rockstor/rockstor-core#1840]
I have just run this program earlier and after the desk top reboot I could not connect to the internet. I have run a check on my computer found the the IP address show 0.0.0.0.0.

what has happened? I have called the service provider the technician claim that the cable from the modem to the computer need to be replaced. but I have used another cable, having done the IPCONFIG still finds the IP address not available. Currently am using the same modem connected to a wireless router, with my laptop the modem is working, but the desk top is not

**Comment by cron410** [comment]
Is this a Rockstor issue or a Windows computer issue?

**Comment by Hooverdan96** [comment]
Since there has not been any follow-up in the last 6 years, we can probably close this issue
