### ISSUE TITLE
Addon UNMS

### ISSUE THREAD

**Issue by skynett81** [rockstor/rockstor-core#1844]
can you make an addon for UNMS  its an addition to Unifi controller

Ubiquiti Network Management System (beta)
Manage all of your EdgeMAX®, EdgeSwitch®, airMAX® and UFiber devices.
          
	Centralized devices configuration, backups and mass FW upgrade
	Performance charts with real-time graphs
	Outage notifications and custom alerts
	Map of your network sites and endpoints

https://github.com/Ubiquiti-App/UNMS

**Comment by phillxnet** [comment]
@skynett81 Thanks for the suggestion / request but I think this feature / addon would best be addressed via our docker based Rock-on system and as such this belongs in our rockon-registry repository:
https://github.com/rockstor/rockon-registry

But given the vast majority of our Rock-on definitions are written by non core Rockstor contributors I would suggest that you also post on our forum with this idea / request as there you will reach more eyes of prospective authors.
https://forum.rockstor.com/

Hope that helps.

Should be OK to just cut and paste this issue's contents over to a new issue in rockon-registry repo and then link to the new one from your forum post. You could then close this issue.
