### ISSUE TITLE
Unable to update to 3.9.1-16 over 3.9.1-0

### ISSUE THREAD

**Issue by maclm** [rockstor/rockstor-core#1849]
I'm on Linux 4.10.6.
I've tried to update packages, via "Yum available updates" with no success.

**Comment by phillxnet** [comment]
@maclm Hello. Your issue may well be that you have yet to select an update channel. You did not specify if you had yet to do this, or any error messages you received after attempting your stated yum command. Initially, prior to fully defining a GitHub issue, it can be useful to first discuss the problem on our forum. Please consider joining our forum where there are more eyes to first establish the nature of what is holding up your update.

https://forum.rockstor.com/

You could link to this issue and copy and paste your text here; there.

Hope that helps.

**Comment by maclm** [comment]
Oh, I see.  Will try to do better next time.

Meanwhile, I've managed to resolve the issue following [this post](https://forum.rockstor.com/t/update-3-9-1-0-error/3904/5) and a bit of trial'n'error.

I suggest we close this one.

**Comment by phillxnet** [comment]
@maclm Glad you've got it sorted and have found the forum useful.

Please feel free to close the issue. Those opening issues have the right to close them. And make any additional notes you fancy on the resolution you found.

Thanks for the update.
