### ISSUE TITLE
suspected replication regression re share api change

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#1853]
Thanks to forum member clawes in the following thread for highlighting this issue. It would appear that we have a share api change related regression in the replication code as indicated by the submitted error message:
```
[08/Nov/2017 14:00:36] ERROR [smart_manager.replication.sender:73] Id: 423B4A9B-3B81-99CA-55E5-1A7620713001-2. Failed to create snapshot: aim_2_replication_1. Aborting… Exception: [u’Invalid api end point: http://127.0.0.1:8000/api/shares/aim/snapshots/aim_2_replication_1’]
```
Linking to the potentially related api change pr for context:
#1808 "change share and snapshot endpoints to by id and not by name."

Please update the following forum thread with this issues resolution:
https://forum.rockstor.com/t/replication-is-failing-on-v3-9-1-16/4005/1

**Comment by phillxnet** [comment]
@schakrava As this affects our latest stable I suggest that it be prioritised. I haven't looked at the replication code just yet but could do so, just not directly unfortunately. I'll note here if/when that changes.

**Comment by phillxnet** [comment]
Please also update the following forum thread with this issues resolution; forum member Prabu_Raj may well be affected similarly:
https://forum.rockstor.com/t/replication-on-a-remote-server/1176/3

**Comment by phillxnet** [comment]
Currently taking a quick look at this issue. I have reproduced and can confirmed that it is a share api change regression.

**Comment by phillxnet** [comment]
Should have an initial pr ready for this one soon as have narrowed down the issue to be a now non valid assumption of similarity re share url references between sender and receiver. Previous to our share api change from name based to db id based (pr #1808) a share could be successfully validated remotely via it's name within the relevant url. This is what the replication receiver did and so even after translating the required url's to shareId there was still a failure to validate the senders share from the receiver. My initial pr against this issue is expected to simply remove, or simply, this validation element and update the required urls until further discussion can be had on how best to proceed, ie if we need to send more info to allow for this function to be re-established for example.

![successful-rep-task](https://user-images.githubusercontent.com/2521585/34653536-fa0d1706-f3e4-11e7-84de-928d13a3be76.png)

**Comment by phillxnet** [comment]
Correct replication history table formatting to be in line with most other project table formats, ie with search and sort (data-table) and ensured history is most recent first via ID desc order sort.

Before:
![old-rep-send-history-table-format](https://user-images.githubusercontent.com/2521585/34736966-9bf4dd5a-f56c-11e7-819e-bdbc23eda006.png)

New:
![new-rep-send-history-table-format](https://user-images.githubusercontent.com/2521585/34736982-a52764ec-f56c-11e7-8395-410a22ff20e2.png)

**Comment by phillxnet** [comment]
Remaining issue to sort: replication now fails on the 6th incremental send with the following error:
"... Failed to promote the oldest Snapshot to Share. ..."
This will be my next focus within this issue and once a resolution is found I will submit a pr so we can at least take it from there. Broken UI elements (share / pool links) will probably be removed for now until further discussion / review of the resulting pr.

**Comment by phillxnet** [comment]
Debug info currently points to a parsing issue with:
fs.btrfs: **get_oldest_snap()**

ie with:

ls -la /mnt2/test-pool/.snapshots/C583C37F-08AE-478B-A726-E95235D1712B_plex-config
total 0
drwxr-xr-x. 1 root root 116 Jan 10 18:45 .
drwxr-xr-x. 1 root root 320 Jan 10 17:25 ..
drwxr-xr-x. 1 1011 1011  14 Jan 10 18:30 plex-config_5_replication_157
drwxr-xr-x. 1 1011 1011  14 Jan 10 18:30 plex-config_5_replication_158

Initial tests indicate we have a return to this question when asked by:

smart_manager/replication/receiver.py

as part of it's removing older snapshots (which is in prep for promoting oldest snap failure above)

[fs.btrfs:1324] get_oldest_snap called with subvol_path=/mnt2/test-pool/.snapshots/C583C37F-08AE-478B-A726-E95235D1712B_plex-config, num_retain=2 and regex=_replication_

(modified num_retain from 5 to 2 in order to speed up testing)

of:

DEBUG [smart_manager.replication.receiver:205] ## oldest_snap=**plex-config_5_replication_1** ##

**Comment by phillxnet** [comment]
Above concern re get_oldest_snap() is a red herring (from insufficient logging) as proved via testing, now debugging issue within replication receiver.py, which purposefully and successful deleted the correctly returned oldest snap, hence no longer in existence.

**Comment by phillxnet** [comment]
The issue of "... Failed to promote the oldest Snapshot to Share. ..." has now been resolved. We were moving the oldest received snapshot and then attempting to remove it. It is suspected that improvements in db update have exposed this issue where previously it did not cause a problem. Replication now working as before but because we remove a share only to have it's location re-populated by a fresh share (via shutils.move) we have shareId creep: creating UI issues when refreshing the receiver's share details or related pages. Previously (prior to share api url moving from name to db id) when we relied only on share name this was not an issue. Looking into a resolution / work around prior to pr submission.

**Comment by phillxnet** [comment]
The issue with shareId creep has now been resolved - by ensuring db was fully updated mid replication snap to share promotion procedure I had inadvertently caused the creation of a new share upon next db update: when the promoted snap-to-share existed again. This also covered up an existing and related issue where clones (snaps promoted to shares) are not auto mounted:
"shares via clone of writable snapshot not mounted on creation" #1836 
This issues pending pr is to be delayed whilst I now tend to #1836 as it's fix will have to sit well with the changes made against this issue.

**Comment by phillxnet** [comment]
As the indicated (and prerequisite) issue #1836 now has a pending pr this issue is again my main focus.
Pending remaining elements are the auto mount of the share that results from the oldest replication snapshot having been 'promoted' to share. There is also an intention to abstract the 'rep-clone' mechanism.

**Comment by phillxnet** [comment]
Auto mount issue of share from oldest replication snapshot now resolved. Final intended task in this issue is a short trial of an abstracted 'create_repclone' mechanism. May also tend to some broken UI links within the replication interface.

**Comment by enly1** [comment]
Would be good to get this fix out and create new tickets for optional
extras. This fault has left a key feature broken.

I'm watching this ticket closely as have no backup solution in place while
it's broken.

**Comment by phillxnet** [comment]
@enly1 I appreciate the frustration, however this is a fairly complex piece of code and is also a work in progress. Just trying to do what I can while I'm fresh on it as I may not be able to look again for a bit and if I rush to pr then that could in turn create further frustration. However you will be please, I hope, to know that the current code changes here have been successfully tested to over 100 cycles. So it's looking OK. But only yesterday I found and fixed a show stopper that was intermittent and would otherwise have broken a running replication. And it was the first instance I had ever seen of it.

I will continue to update this issue with my progress and hopefully it shouldn't be too much longer. Please be patient as I want to get this working as well as can be expected and there are a few more 'real life' tests to be performed now that I have most of the problems sorted. But given the scheduled nature of running real life tests they can in themselves take quite a while. In the mean time I was intending to look to the broken UI elements that are relatively trivial code wise in comparison.

Thanks for you input and do remember that we have the linked forum threads which may be a more appropriate medium for general communications. It also makes it easier for others following this thread for developer updates to not have to trawl through our chat.

**Comment by phillxnet** [comment]
The abstracted 'create_repclone' mechanism is now in play and tested satisfactorily between VMs.
Final testing on real hardware is currently underway.

**Comment by phillxnet** [comment]
About to remove GitHub branch to allow for squashing all associated commits locally. Will then re push as a single commit as per: http://rockstor.com/docs/contribute.html#commit-history-cleanup

Pull request to follow shortly there after.

**Comment by phillxnet** [comment]
Re-based on current master and squashed to  a single commit.
