### ISSUE TITLE
move to python 3

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#1877]
Because Rockstor makes extensive use of Django we are compelled to move to Python 3 as our current legacy python base prohibits us from adopting Django 2.x or later. As the first issue of 2018 it seems fitting to formally address this technical debt, an inevitability in any long running project.

It is suggested that we target Python 3.6, however our existing repositories already have 3.4 available (epel); as such 3.4 may serve as an initial first step and is supported by Django 2.0 but is not supported by Django 2.1 (see "What Python version can I use with Django?"):
https://docs.djangoproject.com/en/2.0/faq/install/#what-python-version-can-i-use-with-django

Relevant to this issue is the pending demise of Python 2.7:
https://pythonclock.org/

Potential resources:
http://python3porting.com/
http://python-future.org/compatible_idioms.html
https://docs.python.org/3.0/whatsnew/3.0.html
https://docs.python.org/3.6/howto/pyporting.html#learn-the-differences-between-python-2-3

Please feel free to comment / advise on this issue and provide any resources that might help with this transition.

**Comment by MFlyer** [comment]
Hi @phillxnet & @schakrava ,
my 2 cents on moving to Python 3 and Django 2 (just moved to Django 2 on my daily job before xmas :D ) : if we want to move to python 3 to have django 2, right now we can avoid it (main diffs: better url.py files with things like "/myurl/<slug:myslug>" instead of reg exps + every migration requiring on cascade!), if instead we want to move to python 3...to have python 3, well, I'm ok...although python 2 is still faster than python 3 eheh

Mirko

**Comment by phillxnet** [comment]
If we target at least Python 3.5 then we could move directly to Django Channels 2 (from gevent), as it has a reliance on the asyncio library and native Python async support:

https://channels.readthedocs.io/en/latest/one-to-two.html#requirements

Also Python 3.5 is the minimum for Django 2.1.

**Comment by bheiskell** [comment]
Hey folks,

I'm looking at rockstor for personal use, and I noticed that the version of django rockstor is using has [fallen out of support](https://docs.djangoproject.com/en/dev/faq/install/#what-python-version-can-i-use-with-django) for security fixes. There are a couple of [cves for django 1.8.16](https://www.cvedetails.com/vulnerability-list/vendor_id-10199/product_id-18211/version_id-211622/Djangoproject-Django-1.8.16.html). I thought about filing a separate ticket, but I figure it's not likely you'd go to 1.11 given that python 2 is falling out of support soon, so I'm tacking on here.

**Comment by phillxnet** [comment]
@bheiskell Thanks and Yes, we do have rather a technical debt situation going on. Slowly working through things but very much intend to get to this. Slightly lower priority as I at least consider Rockstor to be mostly deployed on private networks but yes we have some work to do but as always there is quite a lot of it. Please consider joining our forum over at:
https://forum.rockstor.com/
and thanks again for the addition here.

And given the Python move is 'non trivial' we may just move to at least 1.11.18 in the mean time. We have quite a few moving parts as it goes so all depends on syncing them up where and when we can.

**Comment by phillxnet** [comment]
Adding link to the python 2to3 library docs:
https://docs.python.org/2/library/2to3.html#to3-reference

**Comment by phillxnet** [comment]
```
pip install caniusepython3
python3 setup.py caniusepython3
running caniusepython3
Finding and checking dependencies ...

You need 2 projects to transition to Python 3.
Of those 2 projects, 2 have no direct dependencies blocking their transition:

  django-ztask
  gevent-websocket
```

Linking to the following closed issues for context:

https://github.com/rockstor/rockstor-core/pull/1220 (early pinning and suggested replacement)
https://github.com/rockstor/rockstor-core/pull/1312
https://github.com/rockstor/rockstor-core/pull/1996
https://github.com/rockstor/rockstor-core/pull/1510

And from 1 month ago we have unknown compatibility with Python > 3.5 in gevent-websocket:
https://gitlab.com/noppo/gevent-websocket/-/commit/9b87b850f50bdce99561a95c561c01395a87df7c

**Comment by phillxnet** [comment]
```
rleap15-3:/opt/rockstor-dev # python3 setup.py caniusepython3
running caniusepython3
Finding and checking dependencies ...

You need 1 project to transition to Python 3.
Of that 1 project, 1 has no direct dependencies blocking its transition:

  gevent-websocket
```

**Comment by phillxnet** [comment]
As of current testing channel for rockstor-core, rockstor-jslibs, & rockstor-rpmbuild, we have our first Py3.6 based Leap 15.4 & 15.5 build successes. A new testing channel development phase will be initiated by the resulting builds shortly.

Closing this issue as per all linked issues & pull requests. And the associated items in the same milestone as this issue.
