### ISSUE TITLE
Last two columns of Snapshot screen are not sortable

### ISSUE THREAD

**Issue by Hooverdan96** [rockstor/rockstor-core#1878]
When attempting to sort by either of the last two columns (Visibility, Writable), the column header symbols for sorting change, however, no sorting is performed. All other columns are sorted ascending/descending when respective sort icon in the column heading is selected.

![image](https://user-images.githubusercontent.com/35113775/34579698-fe9ceb28-f13e-11e7-805b-cf237a556bb1.png)

**Comment by phillxnet** [comment]
@Hooverdan96 Thanks for clear and concise bug report, much appreciated.
