### ISSUE TITLE
xenserver 6.2 Warning! Disk unusable as pool member

### ISSUE THREAD

**Issue by jacquesteh** [rockstor/rockstor-core#1901]
Hi,

Warning! Disk unusable as pool member - serial number is not legitimate or unique.
Disk names may change unfavourably upon reboot leading to inadvertent drive reallocation and potential data loss. This error is caused by the source of these disks such as your Hypervisor or SAN. Please ensure that disks are provided with unique serial numbers before proceeding further.

It used to work with older version and now all virtual drives are not working.

I saw there is a fix in vmware but not xenserver 6.2.

Can anyone help to fix this issues?

Thanks,
Jacques

**Comment by phillxnet** [comment]
@jacquesteh The unique serial for disks is part of the minimum system requirements and I don't know how to get xenserver to supply them, but I would suggest asking on the Rockstor forum as the question is likely to get more eyes there.
https://forum.rockstor.com/

But it's not, in my opinion, a bug on Rockstor's code side but a design decision. If xenserver can't provide these serials then it and Rockstor are not compatible. I'm not aware of any other VM host technology that is unable to provide these serials and real hw always has them. It might also be worth asking on a xenserver forum, it may just be a rather obscure setting.
