### ISSUE TITLE
Incorrect size calculation while removing disk from disk pool

### ISSUE THREAD

**Issue by niu-lin** [rockstor/rockstor-core#1918]
Use case is:
I have two disks, both are 2.7TB on a RAID1 setup, so actual space to store data is 2.7TB. Used space is 1.8T (on each disk), free space allowed for data is 0.9TB.
Now I add a 3rd disk of 2.7TB to the pool, effectively increases total usable disk space to 4.05TB, and free space allowed for data is 2.25TB.
The balance process started, and I canceled it at around 15% on the command line.
Then I use the "Resize pool" function to delete the newly added disk, but rockstor gives me the error like "the operation is not supported, because the pool size will shrink by 2.7TB, however, free size is only 2.25TB, there's no enough disk space to move data".
Actually though the pool is going to shrink by 2.7TB, the actual used space on the 3rd disk is only a few hundred GB, which is OK to spread to the other 2 disks, so btrfs should allow for that.
To confirm it, I started the device delete operation on the command line using `btrfs device delete xxx`, and btrfs accepted the operation and finished it without errors. The conclusion is the calculation and protection by rockstor is incorrect. To calculate whether there's enough free space to store the data from the deleted device, we need to base it on the used size of the device-to-be-deleted not the total size of it.

**Comment by phillxnet** [comment]
@niu-lin Thanks for the report. Yes the calculation is a little heavy handed and currently caters for a  worst case scenario from taking a quick look at it.

The calculation and it's consequent conditional exception is made in the following few lines:

https://github.com/rockstor/rockstor-core/blob/master/src/rockstor/storageadmin/views/pool.py#L525-L539

Take a look and see what you think, pull requests are welcome.

Could you also confirm your Rockstor version?

There was an improvement to that code made quite some time ago (bug fix):
"Issue: incorrect space calculation on disk removal" #1553
with it's consequent pull request:
"correct disk removal disqualification calculation. Fixes #1553" #1554 

Although the wording of the error message is different (but similar) to your report and hasn't change for quite a while either so I may have the wrong place. 

You can find your own installed instance of this code in the following file:

    /opt/rockstor/src/rockstor/storageadmin/views/pool.py

It may be what we need is an additional function to return the used space on an individual disk (ie parse btrfs fi usage for the disk in question and add it's data and metadata components) and then use that in this calculation: as your say.

Thanks for opening this issue and your details description and no worries if you don't fancy having a go as hopefully someone can step up and have a go themselves. I can't sort it myself for a bit as I've got a bit of a backlog but that bit of the code is pretty simple so have a look and see what you think. All pretty readable really. I'll have a go myself once I've sorted my backlog though if it hasn't already been picked up by anyone else.

Thanks again for highlighting this current calculation shortfall. Would be good to get it sorted.

**Comment by phillxnet** [comment]
Adding a recent report on a confusing space left report that also blocked a drive removal:
Thanks to forum member juchong for this additional and presumed related report:
https://forum.rockstor.com/t/cant-remove-disk-even-though-i-have-enough-space/5287

**Comment by phillxnet** [comment]
Code associated with a yet to be submitted pr for an otherwise unrelated issue has now added a per disk allocation property. This has been successfully used to resolve this 'over kill' bug and refine the calculation down to a far more sensible:
```
                for d in disks:
                    size_cut += d.allocated
                if size_cut >= (pool.size - usage):
                    e_msg = ('Removing disks ({}) may shrink the pool by '
                             '{} KB, which is greater than available free '
                             'space {} KB. This is '
                             'not supported.').format(dnames, size_cut, usage)
                    handle_exception(Exception(e_msg), request)
```
Where the relevant change is d.size to d.allocated (the new disk property).

As this is a simple single word change to resolve this issue along side the unrelated one I will include the fix in my current issue and reference this issue upon the pr being submitted, with it's associated adding of the 'allocated' disk property and related update mechanisms.
