### ISSUE TITLE
Rockon state cannot be determined

### ISSUE THREAD

**Issue by sgissi** [rockstor/rockstor-core#1933]
Hi team,

When running some rockons I get "unknown_error" as state. This is due to the docker inspect returning more than one line (e.g. if you have Health status) so the State fields are not parsed:
https://github.com/rockstor/rockstor-core/blob/907f5c2b28e8307c75154d56d0a10bec1ec98933/src/rockstor/storageadmin/views/rockon_utils.py#L30-L33

Can I open a PR to change the query to be "Error:{{.State.Error}},ExitCode:{{.State.ExitCode}}.Running:{{.State.Running}}"? These three fields are the only ones we care about in the code and changing the filter won't required more modifications, plus remains flexible if we want to add more fields in the future.

**Comment by phillxnet** [comment]
@sgissi You are more than welcome to open a pull request. As to your docker question that would be better handled by @MFlyer or @schakrava (project lead) as they are more up on the docker side of things than myself.

But please do open a pr, against this issue, and then any comments can be in the light of that code review. This looks like a nice find (at least to me) so should be most welcome.

Please see our:
http://rockstor.com/docs/contribute_section.html
and specifically the Developers section for our current submission guide:
http://rockstor.com/docs/contribute.html#developers

**Comment by sgissi** [comment]
Thanks Phil, I'm setting up a VM to test the fix and then push a PR.
