### ISSUE TITLE
Where can I found ISO for 3.9.2 version?

### ISSUE THREAD

**Issue by requtize** [rockstor/rockstor-core#1944]
Where can I found ISO for 3.9.2 version? On SourceForge is available only 3.9.1 ISO, and even in test channel updates, I can't update to 3.9.1-16 (this version is showing me in web-ui). In Github and mostly in SourceForge, there are available info about 3.9.2-28 version, but there is no any ISO of this version.

In my 3.9.0, I cannot update and cannot upload config backup, I don't know what can I do now. Any suggestions?

**Comment by phillxnet** [comment]
@requtize First off welcome, but this support request is more appropriate in our forum:

https://forum.rockstor.com/

Please ask your question there as then we can narrow down your particular issue. But as a quick part response there is no 3.9.2 iso version as 3.9.2 is from the stable channel subscription and has yet to reach the next iso release candidate. 3.9.1-16 is the most recent testing channel release and is only available once  the system has been configured for the testing channel updates.

Try first ensuring you have subscribed to testing and then you should be offered 3.9.1-16 or if you subscribe to stable channel updates then you should be offered 3.9.2-28 or whatever is the latest there. We no longer offer regular testing channel updates via rpm and testing channel 3.9.1-16 is essentially the same as 3.9.2-0.

There is however a bug when moving from latest testing channel to stable that requires a command line intervention.

Please present your remaining issues on the forum and we can take it from there.

Thanks.

**Comment by Hooverdan96** [comment]
@phillxnet another legacy question/issue that can be closed due to the move to OpenSUSE.
