### ISSUE TITLE
Attempting to restore from a non-GZip'ed Config Backup fails silently

### ISSUE THREAD

**Issue by doenietzomoeilijk** [rockstor/rockstor-core#1953]
As a user, I'd like some more feedback about a failed upload, so I can try again with a proper file.

Downloading the GZip'ed JSON data that a Config Backup spits out might result in a non-GZip'ed file if your OS decides to automagically uncompress things, or because you're curious. When restoring from such a file, you're allowed to upload it and attempt a restore from it, but this will silently fail. Checking the logs will tell you that the restore script expected a GZip'ed file.

Solutions:

* Add a bit of smarts to the restore script to let it handle non-GZip'ed backups. Frankly, this would be the best option IMO.
* Disallow uploading anything that is not a GZip archive - at least this prevents the issue.
* Complain loudly and visibly if things go wrong, so the user won't just there, waiting for things to happen in vain.

This issue was encountered in [this thread](https://forum.rockstor.com/t/solved-how-hosed-am-i-cleared-out-the-database-turns-out-not-that-hosed/5115/15?u=doenietzomoeilijk).

**Comment by FroggyFlox** [comment]
@doenietzomoeilijk , @phillxnet :

> * Add a bit of smarts to the restore script to let it handle non-GZip'ed backups. Frankly, this would be the best option IMO.

I'm currently looking into attacking this issue and I agree that this option above would be the best one.
I was thinking we can let the user select non-GZ files to upload (as currently), but then gzip the file automatically. This would save some disk space (even though it's still very small), and also allow to leave the restore script untouched and thus keep it as simple as possible.

Any thought(s)?

**Comment by FroggyFlox** [comment]
> I was thinking we can let the user select non-GZ files to upload (as currently), but then gzip the file automatically.

I now have a branch with a working fix: 
- branch: https://github.com/FroggyFlox/rockstor-core/tree/WIP_Upload_nonGZ  
- commit: https://github.com/FroggyFlox/rockstor-core/commit/c9abb15b3db11815229e8e5eac76b4f08a95551a  

In this branch, a check for gz format is added and the file is gzipped if not. If the file can be opened and read by the `gzip` module, it is considered already gzipped and the normal refresh procedure continues. If attempting to open and read the file throws an `IOError`, it is considered not gzipped and compressed using gzip. The corresponding `ConfigBackup` model is then updating accordingly.

@phillxnet , I'll of course see if I can improve upon this (and better organize everything), but let me know if you see a big problem with this approach.
