### ISSUE TITLE
Add support for mounting a particular device in Rockon

### ISSUE THREAD

**Issue by FroggyFlox** [rockstor/rockstor-core#1957]
I've been interested in trying to help improving the functionalities of the Rockon system following several obstacles I've encountered (multiple containers, custom `docker run` command argument, other `docker run` options) for a while now, but never dared digging through the code. 
Recently, however, I started looking into taking advantage of a new functionality of the EmbyServer container: hardware transcoding. Unfortunately, this would require the RockOn to support the `--device` option to `docker run`. 

As mentioned in the corresponding issue (https://github.com/rockstor/rockon-registry/issues/152), I was thus thinking to implement support for a new _**Devices**_ object in the JSON files. This object would follow the same structure as the _**Environment**_ object, with `"description"` and `"label"` fields in the JSON file triggering a new page in the Rockon install wizard for the user to input a custom device path (`/dev/dri/renderD128` for instance).
```
{
  "description": "path to hardware transcoding device (/dev/dri/renderD128)",
  "label": "VAAPI device"
}
```

I started working on it and modify the files I believe are involved in such a process (https://github.com/FroggyFlox/rockstor-core/tree/RockOn_device_option), but am hitting an obstacle in figuring out what's wrong. The problem I'm facing is that I do not get the Rockon install wizard to open a new page related to the _**Devices**_ object I'm trying to implement.

While I can read and understand more or less the intent behind the Python code, I am not familiar enough with Javascript to even understand whether my issue lies first in the frontend or backend. 

Would anyone be kind enough to offer some pointer(s)?
I've been testing the following changes:
https://github.com/FroggyFlox/rockstor-core/tree/RockOn_device_option

With the following JSON file:
https://github.com/FroggyFlox/rockon-registry/blob/emby_dotNET/embyserver.json

**Comment by phillxnet** [comment]
@FroggyFlox Hello again. This sounds like a great addition. I have some bits and bobs to tend to first but there after I'll try and take a look, unless of course someone beats me to it.

Chuffed this is under way as it's something I would like to have a play with myself. So time permitting I can have a look and see why that new option is not appearing. If you manage to fathom it in the mean time just update here.

Thanks for getting this one under way. It will be a nice addition and likely popular with the Emby, Plex, and possible the ZoneMinder rock-ons as in the last case it may facilitate access to a locally attached camera for example, ie a usb one.

**Comment by FroggyFlox** [comment]
Thanks a lot! Hope it'll help.

For debugging the backend, is there a way to run the code manually with a set file (JSON here for instance) and see directly in the python (or IDE) console how the different variables are populated? Because of the Django involvement I don't know how (or if) this is doable.

**Comment by phillxnet** [comment]
@FroggyFlox I have responded to your backend debugging / dev question, as best as I can currently, in a private message on our forum so as to keep this issue text as clean as possible. And as referenced in that message there are plans to enhance our existing dev docs re setting up such things.

Hopefully others can chip in here as all help is appreciated, assuming you haven't already sorted it by then of course.

**Comment by FroggyFlox** [comment]
As described in PR #1959, the Rock-on install Wizard now completes, passes the device info to the `docker run` command, installs the Rockon successfully. What remain is:

1.  Make newly-added device field in install wizard optional. For now the form validation has been commented but needs to be done correctly:
              - remove red asterisk denoting required field
              - Validate if field is empty, or if field value starts with `/dev`

2. Test passing several devices with multiple `devices` entries in JSON.

With regards to point 1 above, as I'm not familiar with JQuery validation I'll welcome any help/feedback.

**Comment by phillxnet** [comment]
@FroggyFlox Well done on getting all this sorted to date.

I can chip in with some example js validation code that has a few techniques in that my be of help:
https://github.com/rockstor/rockstor-core/blob/master/src/rockstor/storageadmin/static/storageadmin/js/views/smartcustom_disks.js#L74-L261
It does a free form text box validation intended to filter supported custom smart options and so has a few bits and bobs in.

**Comment by FroggyFlox** [comment]
Following the latest commit, points 1 and 2 above are working as expected (#1959).

**Comment by FroggyFlox** [comment]
A clean and functional PR has now been submitted. #1962
