### ISSUE TITLE
Recommended process for Subscribers to create a support ticket links to a dead site

### ISSUE THREAD

**Issue by cameron-doherty** [rockstor/rockstor-core#1961]
When receiving an error in the UI there is a recommended process for opening a support ticket if you are a subscriber.  Step 3 notes to open a ticket at a linked site support.rockstor.com/open.php but this URL is broken.  

Should be updated to either point subscribers to appropriate place or just removed altogether.

**Comment by phillxnet** [comment]
@t3kka Thanks for the report.
I think we need to call on @schakrava's for the direction / action to take on this one.

**Comment by FroggyFlox** [comment]
@phillxnet, I'm closing this as I believe this no longer applies. Please re-open if I'm wrong.
