### ISSUE TITLE
Enabling AFP prevents Samba shares from being discoverable

### ISSUE THREAD

**Issue by legbandj** [rockstor/rockstor-core#1970]
Rockstor 3.9.2-40
Running AFP and SAMBA

On my Windows 10 desktop, I was having trouble with my Rockstor Samba shares not showing up in the Network browser. On my Mac laptop, I was seeing the AFP share, but not the Samba share.

After a little research, it looks like running AFP (netatalk) creates a conflict with avahi broadcast of Samba. See detailed discussion here: https://unix.stackexchange.com/questions/93684/setting-up-samba-netatalk-and-avahi-bonjour-on-raspberry-pi

The solution is to add an smb.services file in /etc/avahi/services/ with the following:
```
<?xml version="1.0" standalone='no'?>
<!DOCTYPE service-group SYSTEM "avahi-service.dtd">
<service-group>
 <name replace-wildcards="yes">SMB on %h</name>
 <service>
   <type>_smb._tcp</type>
   <port>445</port>
 </service>
 <service>
   <type>_device-info._tcp</type>
   <port>0</port>
   <txt-record>model=RackMac</txt-record>
 </service>
</service-group>
```

After a restart of Samba, I am able to see the Samba share on both my Windows 10 desktop and my Mac laptop, and the AFP share on my Mac laptop.

**Comment by phillxnet** [comment]
@legbandj Thanks for the report and for sharing your findings / fix.

Nice find.  We could maybe add this to our list of system file edits during boot up.

Thanks again for the report. Please leave this issue open as a record. And do consider posting your findings on the forum, linking to this GitHub issue for context, as your findings are likely to be popular / appreciated prior to us automating accomplishing this by code. It might also attract further potential refinements / fixes in this area.

**Comment by FroggyFlox** [comment]
Following the deprecation of AFP by Apple, we are now using Samba as per upstream's recommendations. I'm thus closing this issue as legacy.
