### ISSUE TITLE
Upgrade to a more recent kernel + btrfs-progs version

### ISSUE THREAD

**Issue by wingrunr21** [rockstor/rockstor-core#1975]
Hey all,

Formally requesting a kernel upgrade. The last kernel upgrade was [in the beginning of August last year](https://github.com/rockstor/rockstor-core/commit/914ab0d52e3cacf40cdb6f0ec3de0dac823ef67c). There [are](https://forum.rockstor.com/t/when-can-we-get-kernel-4-12/3468) [a](https://forum.rockstor.com/t/upgrade-kernel-to-4-16/4749/2) [few](https://forum.rockstor.com/t/upgrading-to-latest-elrepo-kernel-kernel-ml-4-15-0-1-el7-elrepo-x86-64-rpm/4410/6) forum threads on the issue + a few issues here on GitHub (like rockstor/rockstor-core#1886) where a newer kernel is being asked for and/or someone from Rockstor has acknowledged a newer kernel is probably needed.

A newer kernel will also allow a newer version of btrfs-progs to be pulled in. Given the number of btrfs fixes that have gone into both the kernel and btrfs-progs over the past year, it'd be nice to get an upgraded version.

If you are unable to do a kernel upgrade in the mainline repo, it'd be nice if you'd at least write up a "blessed" way of doing the upgrade yourself.

**Comment by phillxnet** [comment]
@wingrunr21 Thanks for the input and agreed.

I like the write up idea, and it has occurred to me, and given we essentially use regular unmodified elrepo kernel-ml's (at least on our current CentOS linux base):

https://elrepo.org/tiki/kernel-ml

that bit is fairly straight forward.

I may have a go at the write up myself when I get time, unless someone beats me to it of course.

We are in the slow and steady process of re-basing on openSUSE but this is going to take a while longer. But once completed that will leave us with less 'maintenance' / weak areas so there is hope going forward on this one: especially given openSUSE / SUSE have a lot of btrfs expertise 'in house' and do their own back ports to accommodate their default btrfs root. But as stated, this is more a medium term plan as there are a few show stoppers in our current code yet to be address that must take priority (to serve our existing users installs, ie issue #1722: recently referenced in pr #1971), apart from changing our entire roll out mechanism of course.

Please be patient on this front and I'll try and get around to that write up as a stop gap for the time being.

**Comment by Luke-Nukem** [comment]
@phillxnet anywhere I can help with the openSUSE re-base? I've got a fair amount of experience with them.

**Comment by phillxnet** [comment]
Closing issue as we no longer release for CentOS, and our newer 'Built on openSUSE' endeavour no longer requires us to supply kernel/btrfs rpm updates as we can now rely on upstream for these.
