### ISSUE TITLE
Installer does support wifi, while Rockstor on boot does not...

### ISSUE THREAD

**Issue by jbrepogmailcom** [rockstor/rockstor-core#2011]
During installation it is possible to enter wifi credentials. But after installation, wifi is not enabled after boot and nmcli shows "missing plugin" error message.

Expected behaviour is that if WiFi is configured during installation, it will be used after boot.

**Comment by FroggyFlox** [comment]
We have now moved to a new OS base and are using a new installer. I'm thus closing this now as a legacy issue.
