### ISSUE TITLE
[Rock-ons] Unpublish ports and join network

### ISSUE THREAD

**Issue by FroggyFlox** [rockstor/rockstor-core#2013]
This issue relates to step 3 of Rock-ons networking work described in #1982, and follows steps 1 (#2003) and 2 (#2009). It is meant as tracking and discussion material for a work currently **in progress**.

In order to make custom docker networks (described in #2009) useful, we need to create an interface to edit the ports described in a Rock-on JSON file. Indeed, as described by @Luke-Nukem in the issue referenced above (https://github.com/rockstor/rockstor-core/issues/1982#issuecomment-434972256), joining a docker network would be useful/required only if predefined ports are not published:

> I would actually like to see an option to export or not the ports in the GUI, _then_ we would have a use for network creation and joining.

As a result, we can offer an advanced post-install customization option to advanced users to un-publish predefined ports and then join docker networks of interest.
This could be implemented on the Rock-on customization dialog next to the other customization options currently existing (see below).

![image](https://user-images.githubusercontent.com/30297881/52304407-ac8c8400-2960-11e9-8dbd-0cd327661f2f.png)

Clicking on the "Ports" button would lead to a dialog to edit all ports:
![image](https://user-images.githubusercontent.com/30297881/52304489-dd6cb900-2960-11e9-8a27-9bd370d5db5e.png)

On the next step (or below this one), one may attach the Rock-on's container(s) to one or more pre-existing docker networks. In the future, we may work on adding the possibility to create the network from here, as an enhancement.

A few points to consider: 

1. If one chooses to unpublish a port, I can see three possibilities:

- expose automatically the port
- let user choose to not expose the port (if desired) via checkbox (such checkbox would be checked by default)
- leave the port unexposed

2. Should we offer the possibility to edit the container port as well (or leave this for a future and separate issue/PR)?

3. If the webUI port (if applicable) is unpublished, the webUI button displayed in the Rock-ons summary page would not work anymore. Should we thus leave it in a _disabled_ state (greyed out) or simply hide it? I would tend to lean on the former, as it would provide further indication to the user that the Rock-on does have a webUI and that changes to the ports were made.

**Comment by phillxnet** [comment]
@FroggyFlox I can chip in here on point 3.
Definitely agree with your preferences to leave UI button 'greyed out' in this scenario. Otherwise we loose information: as you say if we remove the button entirely there is no indication that a Web-UI even exists for that Rock-on (loss of info), where as if it's greyed out then we at least know it's due to some configuration. Tooltip to give reason for disabled state maybe: i.e. "Web-UI disabled due to current Rock-on/docker port/network settings. See: spanner icon." type thing.

**Comment by FroggyFlox** [comment]
Thanks @phillxnet for your suggestion. I have now included your suggestion regarding point 3 (see screenshot below).
![image](https://user-images.githubusercontent.com/30297881/52969780-9b3f7080-337f-11e9-868b-3868e6cc7af0.png)

Regarding point 2, I'm currently leaning towards leaving it for an eventual future and dedicated issue as I'm still unsure of (i) its use and (ii) its compatibility with all containers (which is a crucial point).

Still thinking about point 1 for now, and would need further tests of container connectivity to decide which route is the best.

**Comment by FroggyFlox** [comment]
Linking here to issue #2009 as it now includes an update and description of the proposed UI to join a network: https://github.com/rockstor/rockstor-core/issues/2009#issuecomment-493048687.
