### ISSUE TITLE
Installation fails on HPE DL20 Gen9

### ISSUE THREAD

**Issue by nerdalertdk** [rockstor/rockstor-core#2021]
Hi

I'm getting this error when trying to install Rockstor 3.9.1
https://gyazo.com/684a0886677133cddf59e68bb4cdfe56

But 3.8.16 works though

Hardware:
HPE DL20 Gen9
CPU: Intel G4400 
Ram 16gb
onboard sata controller
Nic; HPE 1Gb 2-port 332i Adapter, 10Gb 2-port 530SFP+ Adapter

tried normal bios settings and below.
Bios, sr-ivo is disable on the nc530, all virtualization is disablede

**Comment by phillxnet** [comment]
@nerdalertdk Thanks for the report but a better place for this would be on our forum where we can hopefully first resolve the nature of this and then if it's down to our code we can bring it back to a focused issue here on GitHub. I.e. best to start on the forum:

https://forum.rockstor.com/

Hope that helps.
