### ISSUE TITLE
Add HD with data securely and share

### ISSUE THREAD

**Issue by marcelloinfoweb** [rockstor/rockstor-core#2025]
In the company where I work, I am mounting a server with Rockstor3 to replace another with Debian and samba, in this we have a 2TB HD only with company data (the systems are in another HD).

**1)** How do I add this HD without losing the data, and use Rockstor to share the data that is in that HD?

**2)** Is it possible to do RAID 1 with the 2TB HD with the data adding another 2TB HD clean? As?

**Comment by phillxnet** [comment]
@marcelloinfoweb Linking to you forum thread for context and closing this issue as GitHub issues is not the location for support requests.
https://forum.rockstor.com/t/add-hd-with-data-securely-and-share/5857

**Comment by phillxnet** [comment]
@marcelloinfoweb Thanks for the enquiry by the way. There are more eyes on the forum as GitHub is really for development only. You should receive a response shortly hopefully. Essentially Rockstor's Web-UI deals only in btrfs so will not help you with any other filesystem. But using instructions for CentOS (our current linux distro base) should help you temporarily mount and copy your data via cli to a Rockstor created and managed pool / subvol on another drive / or pool of drives which can use btrfs's built in software raid capability.

As the linked issue on the forum was your first post there it was flagged for some reason but I have now accepted it and so it should now be published there.

Hope that helps.
