### ISSUE TITLE
cannot install plex and or emby in rockstor

### ISSUE THREAD

**Issue by martinwlee** [rockstor/rockstor-core#2029]
I have tried to install plex or emby on rockstor 3.9.2-47
![tried to install plex or emby on rockstor 3 9 2-47](https://user-images.githubusercontent.com/48964809/55290266-1fe2cd00-53c9-11e9-81ec-936cc9ac22a0.jpg)
I have tried to install plex or emby on rockstor 3.9.2-47

Having followed the rockstor documentation to install plex rock-on or emby rock-on in rockstor.

I have notice the plex install wizard is not showing the resource type e.g Env 1001 PUID, Env 1001 GUID, Env latest VERSION

This is before the install of the rock-on has started.

Is there a way I can get the plex or emby rock-on installed on the rockstor server?

Enclosed is a gui screen shot of the plex install wizard before I submit it for installation.

**Comment by FroggyFlox** [comment]
Thanks for creating this issue @martinwlee !

As I mentioned in your forum post, this should only be a display bug and I believe to have found the source. I'll submit a pull request with a fix shortly.

Here's a link to the forum post as reference:
https://forum.rockstor.com/t/cannot-install-plex-or-emby/5936/2
