### ISSUE TITLE
failure to establish Rockstor-Stable repo

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#2031]
Thanks to forum member notrin for highlighting this issue. By way of an as yet undetermined sequence of events the stable channel repo can fail to become established after having been selected. Notrin reported a work around via enabling auto updates.

This issue need a reproducer to effectively diagnose the cause. Creating issue to document the observed failure and the reported the work around.

Please update the following forum thread with this issues resolution:
https://forum.rockstor.com/t/fresh-install-upgrade-breaks/5930/9

**Comment by Hooverdan96** [comment]
@phillxnet since this was reported on 3.9.x this can probably be closed.

**Comment by phillxnet** [comment]
> This issue need a reproducer to effectively diagnose the cause.
