### ISSUE TITLE
Restoring 6 or more samba exports using config restore fails

### ISSUE THREAD

**Issue by FroggyFlox** [rockstor/rockstor-core#2053]
This issue has been observed in CentOS and Leap 15.1 variants.

### Brief description  
When restoring a config backup that contains more than 5 samba exports, the restore of the 6th export (and possibly every 6th export) will fail. The logs show the following errors for the `smb.service`:

```
Jun 12 11:28:37 rockdev systemd[1]: start request repeated too quickly for smb.service
Jun 12 11:28:37 rockdev systemd[1]: Failed to start Samba SMB Daemon.
Jun 12 11:28:37 rockdev systemd[1]: smb.service failed.
```

### Mechanisms  
We currently restart the samba service at the end of the restore process **for each export**. This means that for _n_ exports, the samba service is restarted _n_ times in a very short period. Unfortunately, this errors out as by default, systemd will block services that attempt to restart more than 5 times in a 10 sec interval (from what I could gather). 

### Reproducers  
1. Create 10+ shares and create a samba export for all of them.
2. Backup current Rockstor config.
3. Delete all samba exports from the webUI.
4. Restore the config backup created in step 2 above: the error above will appear and all exports except the 6th one will fail to be restored.

### Resolution strategies  
I currently see different ways to address this:
1. From systemd manual, we can disable such automatic blocking by setting `StartLimitBurst=0` or increasing `StartLimitInterval` in `smb.service`. This may not be the best way to approach that, however, as it will disable what I believe to be a default fail-safe implemented for good reason(s).
2. It appears that using `systemctl reload` (instead of `restart`) is not subject to this limitation and will thus not trigger this fail-safe.
3. Grouping all samba exports to restore into a single call would only trigger a single smb.service restart. This may be the best option.

### Miscellaneous 
Although I haven't tested it yet, I would think this issue will occur during the restore of any export that triggers a service restart (NFS?).

**Comment by phillxnet** [comment]
@FroggyFlox Yet another nice find.
I agree with your tentative options 3 from Resolution strategies myself as long as it doesn't mangle our restore code. Reload seems like a nice simply work around but is less robust: we mostly likely use restart for good reason hence option 3.
Thanks for an excellent report/exposition, and additional Leap 15.1 testing much appreciated.

**Comment by FroggyFlox** [comment]
Thanks for the rapid feedback @phillxnet! 



> I agree with your tentative options 3 from Resolution strategies myself as long as it doesn't mangle our restore code.

I'll try to approach it that way, then. It seems like I may have to change the samba export creation code itself (`post()` in `views/samba.py`) to better deal with several exports at once, but am not sure how much change would be needed. It can already export several shares with the same samba options without problem, but it may need to be adapted to be able exports several shares with each their own options.

I'll have a better look at it and update this.
