### ISSUE TITLE
[Rock-ons] Share mapping is ignored if the same share is chosen

### ISSUE THREAD

**Issue by FroggyFlox** [rockstor/rockstor-core#2064]
At rock-on install wizard, if the same share is selected for two or more volumes, only the first one is saved and sent to the rock-on API for the rock-on install.

### Illustration
For instance, if the share `emby-conf` is selected for both volume mappings of the _Emby server_ rock-on (see Picture 1 below), only the mapping for _Media Storage_ is saved (see Picture 2 below).

_**Picture 1**_
![image](https://user-images.githubusercontent.com/30297881/63448028-1525e480-c40b-11e9-82d1-3020e6bd38d8.png)

_**Picture 2**_
![image](https://user-images.githubusercontent.com/30297881/63448064-2c64d200-c40b-11e9-909a-404cafb3926c.png)

### Consequence
Although docker still runs the container, Rockstor detects the install as _failed_, but no error is thrown to the user.

### Cause
I suspect this is simply due to the fact that the `share:volume` mapping is stored as a dict, with the share as key. As keys must be unique, the each new mapping value overwrites the previous one. The related code is: 
https://github.com/rockstor/rockstor-core/blob/3ad7eee27a40badab7edeea6dc198e800f6b121e/src/rockstor/storageadmin/static/storageadmin/js/views/rockons.js#L603-L607

### Resolution options
Although it may be recommended to choose a dedicated share for each mapping, this is not explicitly mentioned during the install wizard, but we may choose to enforce the choice of different shares for each volume mapping. This could be done with any combination of:
1. use form validation to check for duplicate share selected
2. remove the share from the list of possible choices if selected in another drop-down select field.

Some users may still prefer to use the same share for multiple mappings, however, so we might rewrite how this form information is parsed. This would require a substantial rewrite of both the front- and back-end of things, however.

**Comment by FroggyFlox** [comment]
I'm currently working on this.
I personally favor option 1 above:

> use form validation to check for duplicate share selected

Indeed, although it would seem elegant to simply remove the share from the list of selectable shares, it actually seems detrimental:
- the user may wonder why the share they're looking for is not displayed
- if the user actually wants to select share B for volume B while it was erroneously selected for volume A, they would need to first select another share for volume A first before being able to select share B for volume B

I think a good form validation letting the user know that the current form is invalid **because one share was selected multiple** would be clearer and more intuitive to the user.

@phillxnet , as always, let me know if I'm missing a glaring problem with that. :smiley:

**Comment by FroggyFlox** [comment]
Following [ba87d74](https://github.com/FroggyFlox/rockstor-core/commit/ba87d74266a4770ef5318b9617bd14abe934a50c), we now have validation for shares selected multiple times, in addition to the currently existing "Required" rule.

The examples below are using the ecoDMS 18.09 Rock-On to illustrate various validations outputs; it has 4 volumes defined. Note that all validations occur upon clicking the "Next" button.

- 4 empty
![image](https://user-images.githubusercontent.com/30297881/213571891-48f3f810-9de3-460c-b66b-dde1c17df49e.png)

- 1 share used 3 times + 1 empty
![image](https://user-images.githubusercontent.com/30297881/213571975-cc681fc2-b6ec-44d6-885b-68345ecfa2a2.png)

- 1 share used 3 times + 0 empty
![image](https://user-images.githubusercontent.com/30297881/213572053-fc90ae69-a12c-4eea-8140-ba58e1e28250.png)

- 2 shares used 2 times each
![image](https://user-images.githubusercontent.com/30297881/213572119-a3bdd012-4d7f-486d-8c48-b6d4a39cc657.png)

- 1 share used 2 times + 0 empty
![image](https://user-images.githubusercontent.com/30297881/213572197-6ced163d-9bf9-4b49-8376-d4fecd0de0a4.png)

- 0 duplicates, 0 empty: clicking "Next" goes to the Ports selection step.

**Comment by phillxnet** [comment]
Closing as:
Fixed by #2481
