### ISSUE TITLE
activation code retrieval

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#2067]
It is proposed that to ease system migrations we provide a Web-UI mechanism by which a particular installs activation code can be retrieved.

Please see the following forum thread for context:
https://forum.rockstor.com/t/how-do-i-recover-the-activation-license-to-the-1-year-subscription/5878

**Comment by Hooverdan96** [comment]
@phillxnet, now with the new OpenCollective and appman management options for subscription transfers, does this issue need to remain open?

**Comment by phillxnet** [comment]
@Hooverdan96 It has received no actual interest and we do now, as you say, have improvements in this area re Appman etc.

Closing a lack-of-interest.
