### ISSUE TITLE
nginx outdated

### ISSUE THREAD

**Issue by magicalyak** [rockstor/rockstor-core#2073]
Can we modify the RPM dependency on nginx to be at or later rather than equals to?  THis shouldn't affect current users, but would allow advanced ones to update past dependencies for security purposes.  There are a lot of vulnerabilities exposed with v12 and we should be able to use the latest v19
rockstor                                                                                                                               | 2.9 kB  00:00:00     
Resolving Dependencies
--> Running transaction check
---> Package rockstor.x86_64 0:3.9.2-48 will be updated
---> Package rockstor.x86_64 0:3.9.2-49 will be an update
--> Processing Dependency: nginx for package: rockstor-3.9.2-49.x86_64
Package 1:nginx-1.12.2-3.el7.x86_64 is obsoleted by nginx-plus-19-1.el7.ngx.x86_64 which is already installed
--> Finished Dependency Resolution
Error: Package: rockstor-3.9.2-49.x86_64 (Rockstor-Stable)
           Requires: nginx
           Available: 1:nginx-1.12.2-3.el7.x86_64 (epel)
               nginx = 1:1.12.2-3.el7

**Comment by magicalyak** [comment]
Just realized mine is using plus, I can modify the spec with a oneoff using rpmrebuild.
This would fix it in the spec though

Requires: (nginx or nginx-plus)

**Comment by phillxnet** [comment]
@magicalyak Hello again.

From a quick look at the rpm dependency for 3.9.2-49 we simply have:
```
Requires: nginx
```
which is born out via:
```
rpm -qpR rockstor-3.9.2-49.x86_64.rpm | grep nginx
nginx
```

so don't think this is a direct rockstor packge / nginx dependency.

You dependency issue message mentions nginx-plus however. So on a quick read your repos don't contain a newer version of nginx.

Apologies if I have the wrong end of the stick here, but a little distracted with todays 3.9.2-49 release.

OK, looks like we have cross posted, posting anyway for info purposes.

**Comment by magicalyak** [comment]
I'm trying some modifications to the specfile, I'll post if I get one workings.  Hopefully an OR is acceptable as a PR here
Requires: nginx or nginx-plus
the () seemed to conflict with the rpmbuild version at the moment..

**Comment by magicalyak** [comment]
This can be ignored, I rebuilt the rpm for nginx-plus to provide nginx so I'm good :)
