### ISSUE TITLE
'Remore', 'Aplliance' and Access Key consistency

### ISSUE THREAD

**Issue by jonpwilson** [rockstor/rockstor-core#2116]
I've spotted a couple of spelling errors:

- 'Remore' on the Add Replication Task page
- 'Aplliance' on the tooltip for 'Access key ID' on the Add Appliance page

Additionally, there's some inconsistency with how 'Access key' is referenced, switching between 'Access key' and 'Access Key' across the page. I believe it should be 'Access Key' given the current 'Access Key' menu item and casing on that page.

**Comment by phillxnet** [comment]
@jonpwilson Thanks for creating this issue to go with your existing pull request. It really helps with keeping our Web-UI attribution system working as intended.
