### ISSUE TITLE
'Email' or 'E-mail' wording

### ISSUE THREAD

**Issue by jonpwilson** [rockstor/rockstor-core#2122]
Hello,

I'm happy to make the changes to this, just wanted to check which one should be the consistent spelling of e(-)mail.

The menu item is 'Email':
![image](https://user-images.githubusercontent.com/6515084/73752540-0d5bc180-4759-11ea-947c-d54ccaf6d434.png)

The page that opens is 'E-mail':
![image](https://user-images.githubusercontent.com/6515084/73752571-1c427400-4759-11ea-810b-7991898c4383.png)

The form for setting it up reverts back to 'Email':
![image](https://user-images.githubusercontent.com/6515084/73752608-2a909000-4759-11ea-98f5-73602f6ea1a9.png)

I'm happy to change them either way, it should just be the same spelling each time.

Thanks

**Comment by FroggyFlox** [comment]
Another nice spotting, @jonpwilson !

I agree with you that we need consistency there. The question is then: which one?
I quickly looked it up and it seems that no consensus has been reached on either form of the word. The hyphenated "e-mail" seems to progressively fade away in favor or the non-hypenated form "email", so I would lean towards the latter ("email"). 

I also personally prefer "email" over "e-mail", to be honest.

**Comment by jonpwilson** [comment]
I'm glad I wasn't the only one who couldn't find a consensus. The closest I've found is that Merriam-Webster appears to redirect 'email' to 'e-mail': https://www.merriam-webster.com/dictionary/email

I don't have access to the main dictionary itself, but the OED uses 'e-mail' on its own site: 
![image](https://user-images.githubusercontent.com/6515084/73754276-113d1300-475c-11ea-9f86-9d64d29049ec.png)

Like you, I prefer 'email' but I think that's just years of (ab)use...

**Comment by FroggyFlox** [comment]
That begins to be a fun little conversation :) .

I noticed the same about Merriam-Webster, but also noticed it seems to be among the last few institutions to retain recommendation of "e-mail". Others who used to be in the same group now favor "email" apparently, that's why I was thinking it's "only" a matter of time before Merriam-Webster too adapt.

The more I think about it, the more it looks like I'm trying to convince myself that my preference for "email" is entirely justified ;) .

**Comment by jonpwilson** [comment]
> The more I think about it, the more it looks like I'm trying to convince myself that my preference for "email" is entirely justified ;) .
Ha! That's entirely the reason I created this rather than just making the changes, I wanted someone else to justify it for me :)

I'll make the change to a 'email' then, the consistency is more important to me than a hyphen!

**Comment by FroggyFlox** [comment]
> I'll make the change to a 'email' then, the consistency is more important to me than a hyphen!

I couldn't agree more; thanks a lot for taking care of this!

**Comment by jonpwilson** [comment]
Apologies for the double PR - I had an issue with Sublime deleting most of the JSON in the fixtures which I'd only spotted after I created it. Reverting the changes didn't reflect in the created one so I had to create a second.

Sorry!

**Comment by phillxnet** [comment]
> Apologies for the double PR - I had an issue with Sublime deleting most of the JSON

No worries at all. I've left a note on your pr re the fixtures stuff that should help here.
