### ISSUE TITLE
[openSUSE] fix cert file path in alert mail config

### ISSUE THREAD

**Issue by tyukh** [rockstor/rockstor-core#2133]
Need change **/etc/postfix/main.cf** value form `smtp_tls_CAfile = /etc/ssl/certs/ca-bundle.crt` to `smtp_tls_CAfile = /etc/ssl/ca-bundle.pem` as OpenSUSE uses different cert type and path.

**Comment by phillxnet** [comment]
@tyukh Thanks for creating this issue, with fix included: nice. Much appreciated.

**Comment by phillxnet** [comment]
@tyukh I am currently working on this issue, let me know here if I'm stepping on your toes.

**Comment by tyukh** [comment]
> @tyukh I am currently working on this issue, let me know here if I'm stepping on your toes.
Nope. I'm not familiar enough with the code base and design rules of the project as a whole, so my best leave that to a more competent person.
