### ISSUE TITLE
ALL mount points lost after reboot (version 3.9.1)

### ISSUE THREAD

**Issue by jediator** [rockstor/rockstor-core#2154]
I am running the latest stable rockstor (3.9.1) and after system reboot, all mount points (including to hard drives, pools and share drives) were lost.  The /etc/fstab doesn't show any persistent mounts other than for the OS.  Any suggestions how to resolve this?

**Comment by phillxnet** [comment]
@jediator Thanks for the report, however with no updates our 3.9.1 ISO is now over 2.5 years old. Our latest code, on the CentOS side is currently only in the Stable Channel but we do have an early adopters/developers only Testing channel in preparation for our re-launch as part of our 'Built on openSUSE' effrot:

## Relevant links
Update Channels: http://rockstor.com/docs/update-channels/update_channels.html
and:
Built on openSUSE testing channel live (early-adopters/developers only):
https://forum.rockstor.com/t/built-on-opensuse-testing-channel-live-early-adopters-developers-only/6592
And the following indicates our Stable Channel progress to date:
https://forum.rockstor.com/t/3-9-2-stable-channel-changelog/5741/23

I would like to invite you to our community forum where this kind of question / support request is best dealt with. In shot though if there is a pool problem then the pool will not load and you will have no mount point. Investigating that further is best done on the forum where all our currently active developers are members. But that far back Rockstor had fewer capabilities to assist with with letting you know what might have gone wrong. So I suggest you join the forum and start a new thread with your specific problem. But if the pool is poorly, and a simple reboot does not return your mount points, then you can be advised further on the forum where there are many folks with experience in how rockstor behaves in various versions and who you might best be returned to function as it were.

Closing this issue as more appropriate for forum given it's support request nature.

And do please consider posting on the forum where hopefully other members can help to work out what is wrong with our pool (the likely issue here). And remember to put in details like the raid level used rockstor version, and what lead to your current situation.

Hope that helps.

**Comment by jediator** [comment]
Thanks Pill for your response.  I am an end user not a developer and expect a "stable" version to work reasonably well.  It seems that Rockstor is just a geek's toy instead of a true enterprise product.  If Rockstor just keeps chasing the latest technologies instead of ensuring product quality, you will loose a lot of end users like me to your competitors (e.g. FreeNAS etc..).  Sorry for complaints...
