### ISSUE TITLE
libpopt0 not in /lib64 on openSUSE

### ISSUE THREAD

**Issue by freaktechnik** [rockstor/rockstor-core#2155]
As reported in https://forum.rockstor.com/t/can-not-create-an-sftp-share-on-opensuse/7026

It appears libpopt0 is not in /lib64 and instead in /usr/lib64 on openSUSE. This leads to a failure when creating SFTP shares.

The offending code is at https://github.com/rockstor/rockstor-core/blob/dc98a1cc59587cd9b5225da7cad0556cb84781e1/src/rockstor/system/ssh.py#L123-L127

When I checked on my system _only_ libpopt0 is in /usr/lib64, all the other libs are still in /lib64, as such a special case for libpopt should likely be introduced.

**Comment by FroggyFlox** [comment]
Hi @freaktechnik ,

I was thinking about looking into this one but wanted to check with you first to avoid duplication of effort: have you already started something on it?

Thanks again for reporting that, by the way!

**Comment by freaktechnik** [comment]
I have not done any code changes or similar - not familiar enough with python nor the actual process that is going on for this specific case. Se please, feel free to take a look @FroggyFlox.

**Comment by FroggyFlox** [comment]
> 
> 
> I have not done any code changes or similar - not familiar enough with python nor the actual process that is going on for this specific case. So please, feel free to take a look @FroggyFlox.

Thanks a lot for your prompt reply! I'll see if I can fix that, then.

Cheers,

**Comment by FroggyFlox** [comment]
After a quick investigation, there seems to be differences in the shared libraries dependency needed. If I'm correct, the following should give us what's needed:
```
ldd /usr/bin/rsync
ldd /bin/bash
```

Filtering out the redundancies between the two, we have the following: 

| Current                 | Leap 15.2               | Tumbleweed (20200501) |
|-------------------------|-------------------------|-----------------------|
| ld-linux-x86-64.so.2 | ld-linux-x86-64.so.2 | ld-linux-x86-64.so.2  |
| libacl.so.1          | libacl.so.1          | libacl.so.1           |
| libattr.so.1         | libattr.so.1         | libattr.so.1          |
| libc.so.6            | libc.so.6            | libc.so.6             |
| libdl.so.2           | libdl.so.2           | libdl.so.2            |
| libpopt.so.0         | libpopt.so.0         | libpopt.so.0          |
| libtinfo.so.5        | libtinfo.so.6        | libtinfo.so.6         |
|                         | libz.so.1              | libz.so.1             |
|                         | libslp.so.1            | libslp.so.1           |
|                         | libcrypto.so.1.1       | libcrypto.so.1.1      |
|                         | libpthread.so.0        | libpthread.so.0       |
|                         | libreadline.so.7        | libreadline.so.8      |

As we can see, even within the openSUSE bases we have some differences in version. This is expected in Tumbleweed after all, and does suggest we may need to find a way to check for needed libraries automatically--especially true for Tumbleweed as I would expect it to change more often there than in Leap, which I would expect to be more stable in this regard.
