### ISSUE TITLE
BTRFS Scrub status shows Unknown with newer kernel

### ISSUE THREAD

**Issue by ubenmackin** [rockstor/rockstor-core#2162]
Starting with btrfs-progs v5.2.1, the status output was changed which breaks some of the parsing Rockstor uses to get the scrub status and other information.

**Comment by ubenmackin** [comment]
I first noticed this on the CentOS build, when I was using a newer kernel back in September and posted on the forums:

https://forum.rockstor.com/t/trouble-using-newer-kernel-btrfs-progs/6342

I proposed an update and change here:

https://forum.rockstor.com/t/built-on-opensuse-testing-channel-live-early-adopters-developers-only/6592/22?u=kupan787

**Comment by phillxnet** [comment]
@ubenmackin Thanks for getting this issue sorted.
Linking for context to an issue that proposed a subset of your what you ended up addressing in your linked pull request for this issue:

"add ongoing scrub end time estimate" #1922
