### ISSUE TITLE
SFTP server runs unconfigured by default

### ISSUE THREAD

**Issue by FroggyFlox** [rockstor/rockstor-core#2168]
On a new Rockstor install, the SFTP server is running by default. While this isn't a problem in itself, it unfortunately means it's running with the default openSSH subsystem rather than the `internal-sftp` subsystem that we need. 

As a result, users can export a share via SFTP without a problem, but access to it won't work. Although a current workaround is to simply turn the service OFF and then back ON again, we should make sure the service is running always as we intend.

The reason we are detecting the SFTP server as running by default is because we check for the presence of the sftp subsystem definition regardless of what the definition is:
https://github.com/rockstor/rockstor-core/blob/ce8f4e788f831866ed19cfedcadaa2266133ea44/src/rockstor/system/services.py#L150-L153

One option to resolve this issue would thus be to make sure we detect the service as ON only if we have the correct sftp subsystem configured (`sftp-internal`).

**Comment by FroggyFlox** [comment]
I am currently working on this issue and have a working fix.

**Comment by FroggyFlox** [comment]
@phillxnet ,

I believe I now have a working fix.

There are a few options on which I'm hesitating:
1. Turn the service ON or OFF by default. The default `sshd_config` has the openssh server running by default, so for now I made the `internal-sftp` server defined in the config during `initrock,py` and thus ON by default. We could easily turn it OFF by default, however, as it might be better from a security perspective to leave the service OFF for users who don't need it. I personally don't have expertise on the mater so I'd rather have your feedback on that first.

2. The openSUSE wiki does mention an additional option for SFTP:
> Match group sftponly
>     ForceCommand internal-sftp
>     ChrootDirectory /home/%u 
>     X11Forwarding no
>     AllowTcpForwarding no

https://en.opensuse.org/SDB:SFTP_server_with_Chroot#Configure_SSHD

While the last two are more a preference than anything else, the first one `ForceCommand internal-sftp` seems to be more important. The wiki reads:

> The ForceCommand option makes sure that the restricted users can only use the SSHD for SFTP, so they don't have the possibility of opening a regular SSH session. The ForceCommand option must always be the first one! Don't let other examples on the internet misguide you. If the "internal-sftp" is not running before the call to chroot() then the chroot() will fail, since the "internal-sftp" is doing all the dirty jobs to make this possible. If the chroot() fails, the user will be kicked off.

Do you think we should keep the same options as currently, or try to follow these recommendations and include (at least) the `ForceCommand` setting?

**Comment by phillxnet** [comment]
@FroggyFlox Thanks for the nice run-down here.

> Do you think we should keep the same options as currently, or try to follow these recommendations and include (at least) the `ForceCommand` setting?

I think the latter, if it doesn't interfere with our root users ability to login, which I'm assuming is ensured via the:
```
PermitRootLogin yes
```
referenced in #2005, then I think it's a good way to go. But we must leave full ssh access for the root user fully functional if at all possible.

Re:
> 1. Turn the service ON or OFF by default.

I think we should have ssh on by default, as per the default server profile install in Leap15.* on which we are modelling progressively more of our defaults; where our stuff is modern enough anyway. This does seem like a good time to alight out ssh config as closely as possible to that of the default openSUSE Leap config actually, with your observed recommendations, and playing on the safe side. But we still need facility, hence the on by default also, given our mostly headless deployment. As that way if there is Web-UI failure (many moving parts) access can still be had via the root user.

Hope that helps, at least with my 'vote'.

If you are close to a pull request on this one we may well be able to get this in pretty quickly ready for the next testing rpm release. As long as we have a clear way to test the changes we should be OK to pop them in. Would also be nice to preserve the recent sftp fix of your of course i.e.:

https://github.com/rockstor/rockstor-core/pull/2167

Although I suspect the rsync over ssh functionality will be hit by this additional "ForceCommand" restriction so we can weigh that up also. Main functionality is the sftp to share anyway, as a documented Rockstor service:
http://rockstor.com/docs/sftp/sftp.html
and the rsync over ssh capability can always be 'uncovered' by an additional Web-UI spanner against the ssh later down the road, now that we know it can work, post #2167.

Thanks again for seeing to this stuff and for heeding the security side. We need more of this as we go on, but our general update across the board via the Python 3 move should help there at least.

**Comment by FroggyFlox** [comment]
Thanks a lot for your feedback, @phillxnet !

I'll try to set the service ON by default, then.

> I suspect the rsync over ssh functionality will be hit by this additional "ForceCommand" restriction so we can weigh that up also. Main functionality is the sftp to share anyway, (...)

You are correct: including `ForceCommand internal-sftp` breaks the rsync over ssh functionality. With or without it, the sftp connection and file transfer work, though.

> the rsync over ssh capability can always be 'uncovered' by an additional Web-UI spanner against the ssh later down the road,

OK. If I understand correctly, we can thus enforce the `ForceCommand internal-sftp` by default, and we can later work a webUI option to disable that and restore the rsync over ssh functionality.

I'll follow these goals and should be able to pop a PR relatively soon.

> If you are close to a pull request on this one we may well be able to get this in pretty quickly ready for the next testing rpm release. As long as we have a clear way to test the changes we should be OK to pop them in. 

It seems to work in my brief tests so far so it may ready for the next release. It isn't a very critical fix, though, so it can wait for the following one. There are a few details I'd like to verify with my current way of reading/writing the config file and how these would behave in real scenarios (especially during initrock.py). Bottom line, I believe it may not be needed to delay the next testing release for that. ;)
