### ISSUE TITLE
Vagrant/Ansible Development/Test environment.

### ISSUE THREAD

**Issue by mikemonkers** [rockstor/rockstor-core#2206]
As a new member of the community I need a development environment.

Creating this using Vagrant/Ansible will provide a reproducible environment to a consistent template. It will also help ease on-boarding of new Devs in future.

The environment should be able to either:
- Deploy from RPMs from the testing channel.
- Build and deploy from the source in this repo.
- Make the build/test cycle simple/repeatable.

**Comment by FroggyFlox** [comment]
>  @FroggyFlox we could probably start doing this whenever folks declare that they are working on an issue or as @mikemonkers has done here, when they request the issues assignment?

Yes, I completely agree... it can only help so I don't see why we shouldn't do it ;-) 

I'll try to keep in mind next time somebody mentions (s)he's working on an issue.

Cheers,

**Comment by mikemonkers** [comment]
@phillxnet, Deploying from RPMs as an alternative helps speed up our ability to construct a test VM based on RPMs for comparison against code changes and or reproducing reported issues. 

Installing from ISO which is:
- quite mandraulic and therefore slow
- has potential for human error

For these reasons would result in a tendency to keep 'test' VMs around and live. Where as with Vagrant they can be more ephemeral, but more consistent. The vagrant and ansible also forms the 'recipe' documentation to a degree.

More, importantly I'd already got that working before raising the ticket so it was no trouble! ;-)

I'm about to submit the PR for review. A couple of things to point out:

1. The user vagrant need to maintain ssh access. You'll see this added in the core code - open for discussion?
2. In the ansible I've install the python2 packages from Python PIP instead or from the OSS repo RPMs. This is allows you to have both pip2 and pip3 in parallel and therefore python2 and python3 variants of the packages. It also gives you more up to date versions of these packages. It is possible to pin package versions with PIP if you prefer - which I imagine you might in a release.
3. Number 2 also fixes the Tumbleweed build dependencies - I think? Well it seem to compile but fails in Rockstor-pre due to the DM migration (shock news!)

Otherwise it defaults to building from source since that seems to be your preference and the most useful.

**Comment by mikemonkers** [comment]
This issue can be closed as it is now covered in the new repo at: rockstor/rockstor-dev-env#1
