### ISSUE TITLE
[NG] - Authorized_keys doesn't allow public key ssh login

### ISSUE THREAD

**Issue by rssfed23** [rockstor/rockstor-core#2212]
Hope this is the right place to report this (let me know if not :) ).

Fresh install of 4.0.1 on Leap 15.2 using the testing packages method.

**Problem:** 
Pasting an authorised key into a user profile saves the key to /home/$user/.ssh/authorized_keys, but I believe due to the file permissions of the .ssh directory and file created it doesn't actually allow the user to log in via SSH.

**Steps to reproduce:**
Create a user and paste a public key in the profile. Try to login via SSH with that key, and you're asked for a password.

**Suspected cause:**
The key/.ssh directory is created with the following permissions:
`nas:/home/rob # ll /home/rob/ | grep .ssh
d-w-rwxr-T 1 rob users   30 Sep 13 20:53 .ssh`

And the key:
`nas:/home/rob # ll /home/rob/.ssh/
total 4
---x-wx--T 1 rob users 394 Sep 13 20:53 authorized_keys`

However, if I remove the .ssh directory and run the usual ssh-copy-id command from a client, the permissions are as follows (and public key login works):
`nas:/home/rob # ll /home/rob/ | grep .ssh
drwx------ 1 rob users   30 Sep 13 20:55 .ssh`

And the key:
`nas:/home/rob # ll /home/rob/.ssh/
total 4
-rw------- 1 rob users 394 Sep 13 20:55 authorized_keys`

https://en.opensuse.org/SDB:OpenSSH_public_key_authentication#Security explains the permissions I believe in a bit more detail, but I believe it must be at most 700 and preferably 600.

**Comment by phillxnet** [comment]
@rssfed23 Thanks for the excellent report.

I think I know what's happened here. We've had a similar issue previously in other areas where a Python wrapper to set permissions was miss-used resulting in some wacky file permissions and I thought I'd got them all sorted on the last pass. I should be able to look at this fairly soon and we can hopefully get the fix out in 4.0.2-0 which is due out shortly.

Nice find by the way and thanks for the authoritative reference re the permissions and working through diagnosing the issue. It would seem this is a seldom used feature. But would be great to get this sorted. I'll use this issue to report my progress, unless @FroggyFlox, or someone else beats me to it of course.

**Comment by phillxnet** [comment]
Noting suspected relevant code:
https://github.com/rockstor/rockstor-core/blob/master/src/rockstor/system/users.py#L226-L252
and as suspected os.chmod just doesn't work like that!

Linking to better example (with comments), from some far more recent code here:
https://github.com/rockstor/rockstor-core/blob/master/src/rockstor/system/pkg_mgmt.py#L223-L224

We should ensure we always use the tool for the job here, i.e. the stat import and it's associated values.

**Comment by phillxnet** [comment]
I am currently working on this issue.
