### ISSUE TITLE
slow admin user filter on Samba export when using Chrome

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#2220]
While working on an NIS config regression issue where the test case is 30,000 users, it was found that in Firefox each character entered into the Add Samba Export "Admin User" form field took approximately 1 second to resolve (show matching users in drop down). Where as the same function within Chrome resulted in a 20 second per character delay, which given the length of this delay could easily lead to a time out on a typical user name entry give the delay is accumulative; and a decidedly unpleasant/miss-leading user experience re unresponsive UI.

These measurements were observed on a 2013 Haswell desktop class machine running openSUSE Leap 15.2 Linux with relatively recent versions of both browsers. At this point the majority of Web-UI code is running browser side so the Rockstor server speed is far less relevant.

It is suspected that a difference in JS optimisation is causing this issue and the suspected JS code segment is within the "display_adminUser_options" HandlebarHelper:

https://github.com/rockstor/rockstor-core/blob/master/src/rockstor/storageadmin/static/storageadmin/js/views/add_samba_export.js#L245-L264

And initial suspicion is the lack of loop length caching within the inner for command used to match input to each in turn of all known users, resulting in repeated redundant calls to the non trivial (at scale) _this.smbShare.get('admin_users').length

```
                    for(i=0; i< _this.smbShare.get('admin_users').length; i++){
                        if(_this.smbShare.get('admin_users')[i].username == userName){
                            html += 'selected= "selected"';
                        }
```
In order to provide the html highlight of a matching user within the options drop down.

**Comment by phillxnet** [comment]
Linking for context to my current issue where this browser contextual slow down was observed:

"NIS regression re Rockstor 4 release candidates" #2216

I am, as a result, also now working on this issue in parallel given the test scenarios overlap.

**Comment by phillxnet** [comment]
Having experimented a little this looks to be something a little deeper than our implementation of creating a highlighted list option depending on already selected admin users as once a single user is selected Chrome behaves, performance wise, similar to Firefox when no user has been selected, i.e. considerably faster. This may well be down to the implementation of the multi selection box primitive and how it's implemented by each browser.

**Comment by FroggyFlox** [comment]
> This may well be down to the implementation of the multi selection box primitive and how it's implemented by each browser.

A quick thought about it as I had to deal a little with .select2() recently: could this be something improved by using the `minimumInputLength` parameter? Their documentation reads:

> Select2 will issue a request to the specified URL when the user opens the control (unless there is a minimumInputLength set as a Select2 option), and again every time the user types in the search box. 

https://select2.org/data-sources/ajax

**Comment by phillxnet** [comment]
@FroggyFlox Thanks, that's a nice pointer. I'll try and given that a go soon. Definitely worth a try and may at least avoid the initial key press delays hopefully. And it's funny how once the first admin user is selected it all calms down to be just like within Firefox. Pretty sure it's out code now but we do need a solution to this.

**Comment by phillxnet** [comment]
@FroggyFlox I've just tried your suggested potential work around (minimumInputLength: 3) and in Chrome there is still a significant wait of around 20 seconds even after just clicking in the "Admin users" window. But the subsequent 2 key presses (if set to 3 min) at least appears directly there after. I'm leaning towards adding this as it at least alleviates some, if not most of the problem. And may help lower power machines cope with something more common place than my current 30,000 user test case anyway. Still investigating user number effects on speed within Chrome thought. Firefox still just fine with around 1 second delay once a search is required and no delay with new minimumInputLength settings at least initially.

**Comment by phillxnet** [comment]
Reducing the NIS user count to 15,000 from 30,000 (and slightly improving NIS server speed) roughly halfs the time for the initial Add Samba Export page to appear, but moves each filtered key response time, i.e. 3rd char with mininput filter, in Chrome from around 20 seconds to around 3 so significantly more than the proportional (half) reduction in users to filter.

**Comment by FroggyFlox** [comment]
That's odd, indeed... I'm glad you were able to improve the performance, though. I'm starting to wonder if there's anything we can do to improve that further, though.

**Comment by phillxnet** [comment]
I've been looking into a custom match so it only matches from the beginning of the user, rather than the default substring, as I  thought that might help speed things up on the search front which now looks to be the hold up, but alas my JS is slow going and sparse. But if this helps speed up the chrome it may be worth it given chromes popularity. And loosing substring search on usernames is probably not a big loss. Have also considered pagination but that looks to be for remote source only. Where as matcher is for local sets which we have. Got no custom matcher working as of yet though as only just got onto this angle.

**Comment by phillxnet** [comment]
Canonical reference, to date, on custom matcher:
https://select2.org/searching#customizing-how-results-are-matched

**Comment by phillxnet** [comment]
I've now got a working custom matcher so will, when next available, see if this can be used as a work around for the Chrome speed issue.

**Comment by phillxnet** [comment]
Very little progress on this to date but have implemented @FroggyFlox minimumInputLength to improved usability and have also got working, simplified custom search to try and reduce client CPU load on larger user sets, 15-30K in the reported tests.

I'll submit a pr with what I have to date as it's a start and we can re-visit later once these initial minor improvements are out.
