### ISSUE TITLE
Stuck on 3.9.2 Release: 57

### ISSUE THREAD

**Issue by MBadberg** [rockstor/rockstor-core#2230]
Hi,
i wondered today, if there a no updates anymore and then i looked a bit deeper.
I have 3.9.2 Release:57 but there is Release 60 outside, but no update available for me. Why?

Can i easily update to 4? I have to do a fresh install on version 4, right? Because of mayor version change?
Is my update subscription still active for 4 or only for 3.9.x?

Greetings
Markus

**Comment by FroggyFlox** [comment]
Hi @MBadberg,
I'll try to answer as best as I can below.



>  I have 3.9.2 Release:57 but there is Release 60 outside, but no update available for me. Why?

This is normal. 3.9.2-57 was the last Stable update to be released on the legacy CentOS base, and all further releases on the CentOS base to 3.9.2-60 were in the Testing channel. This was for a variety of reasons, including technical ones, and you will find more information in the related announcements made on the forum by @phillxnet:
https://forum.rockstor.com/t/3-9-2-stable-channel-changelog/5741/25
https://forum.rockstor.com/t/beta-built-on-opensuse-testing-channel-changelog/7097/6


> Can i easily update to 4? I have to do a fresh install on version 4, right? Because of mayor version change?

Yes, you will indeed need to make a fresh install for Rockstor 4 as we moved to a different base OS (built on openSUSE Leap 15.2).  We have now published instructions on how to build your own installer (a pre-built installer will be made available as soon as possible) and everything is explained at the link below:
https://forum.rockstor.com/t/rockstor-4-installer-recipe-call-for-beta-testers/7237

The process is very easy so I encourage you to give it a try, with different options available on how to build it depending on your preference. 



>  Is my update subscription still active for 4 or only for 3.9.x?

Your subscription will still be active on Rockstor 4. Each subscription is tied to an appliance ID (that Rockstor tries to get from your motherboard), so all you need to is to re-activate your Stable channel once you have Rockstor 4 the same as you did on Rockstor 3.9.2-57: enter the activation code you received and it should work. Note, however, that you may need to verify that your appliance ID is the same as before. @phillxnet created a user-friendly application called AppMan that allows you to verify the status of your subscription, the appliance ID, as update any of this as/if needed: https://appman.rockstor.com I highly encourage you to sign-up for AppMan (using the same email you used when purchasing your Stable subscription) and AppMan should pickup all your previous order(s) and subscription status. Feel free to email support@rockstor.com if you encounter any problem using it.
On a related note, the Stable channel is currently empty on the current "Built on openSUSE", but the first Stable release there should happen relatively soon, hopefully, as we are now at Release Candidate 5:
https://forum.rockstor.com/t/beta-built-on-opensuse-testing-channel-changelog/7097/11

Hopefully all this helps, 
If you have any more question, feel free to open a new thread on the forum (https://forum.rockstor.com) as that is the preferred medium for this sort of inquiry.

**Comment by Hooverdan96** [comment]
@phillxnet, @FroggyFlox since we are now on 4.x and moving to 5.x on OpenSUSE soon, this can probably closed as a legacy issue.
