### ISSUE TITLE
Active Directory is broken in our "built on openSUSE" offering

### ISSUE THREAD

**Issue by FroggyFlox** [rockstor/rockstor-core#2232]
Thanks to forum user _HB7_ for bringing this to our attention: in our "Built on openSUSE" offering, the Active Directory (AD) implementation is currently broken as it currently relies on CentOS-specific tools such as `authconfig`. See forum post below for details:
https://forum.rockstor.com/t/failed-to-join-ad-domain/7394

As recommended by @phillxnet in [an earlier forum thread](https://forum.rockstor.com/t/active-directory-integration-failure/6681/3?u=flox), we should revert back to using SSSD rather than winbind (currently used), which provides a much simpler way to join/leave an AD. In addition, it is important to note that we can re-use most of our past attempt at using SSSD that was reverted back: #1174.
Indeed, @schakrava kept most of the SSSD implementation while reverting it, which means we should be able to switch back to using SSSD as the default method to join an AD domain.

We should also pay particular attention as testing authentication of Samba shares using AD users as this has been reported in the same forum thread as requiring additional configuration, thanks to our forum user _Lorez85_:
https://forum.rockstor.com/t/failed-to-join-ad-domain/7394/9

**Comment by FroggyFlox** [comment]
I started looking into this and could set a test AD server using Samba as an Active Directory Domain Controller, following Samba Wiki's instructions:
https://wiki.samba.org/index.php/Setting_up_Samba_as_an_Active_Directory_Domain_Controller

...combined with a third-party blog, as I was encountering some name resolution/DNS issues (due to my own setup):
https://blog.ricosharp.com/posts/2019/Samba-4-Active-Directory-Domain-Controller-on-Ubuntu-18-04-Server

**Comment by FroggyFlox** [comment]
Of note, the following **new packages** would be needed for SSSD:
- sssd
- sssd-ad
- sssd-tools

**Comment by FroggyFlox** [comment]
I somehow cannot seem to have `realm` edit `/etc/nsswitch.conf` automatically to add the `nss` service, despite its documentation stating it does:

> The join operation does the following:
> 
>     Discovers information about the domain.
> 
>     Installs the necessary software to join the domain, such as SSSD or Winbind.
> 
>     If administrative credentials are required, a password will be prompted for.
> 
>     A computer account in the domain will be created, and or updated.
> 
>     A host keytab file at /etc/krb5.keytab is created.
> 
>     Configures the SSSD or Winbind services, and restarts and enables them as appropriate.
> 
>     Enables domain users in /etc/nsswitch.conf
 

Joining a domain in a Leap 15.2 desktop VM using the Yast config tool, does create the following settings in `/etc/nsswitch.conf`, however, so it seems we may need to add the `nss` setting there manually:
```
testdesktop:~ # cat /etc/nsswitch.conf
(...)
passwd: compat sss
group:  compat sss
shadow: compat
(...)
```

Of note, the same Yast configuration also overwrites the existing `/etc/samba.smb.conf` appropriately:
```
[global]
    security = ads
    realm = samdom.example.com
    workgroup = SAMDOM
    log file = /var/log/samba/%m.log
    kerberos method = secrets and keytab
    client signing = yes
    client use spnego = yes
```
We should thus try to also emulate that, I believe.

Thanks to any expert on the matter for the feedback you may have on such settings.

**Comment by FroggyFlox** [comment]
I now have a first working implementation using SSSD to join an Active Directory domain controller. See the following commit:
https://github.com/FroggyFlox/rockstor-core/commit/a9ea3be8135f5b616cfad89680e9d82ae9f070a0

Although using the `adcli` tools to join the AD (default in `realmd`) worked very well, it does not work very well when the client is also using a samba server to serve files/directory shares. Indeed, it would require manually creating some Samba databases if those do not already exist (see this [bug report](https://bugzilla.redhat.com/show_bug.cgi?id=1665794#c6) for some illustration). Although there are some workaround that would require to manually set the domain SID (we can automate that), it appears more robust to use the Samba-provided `net` tool to join the domain, still using realmd and sssd, though:
```shell script
realm join --membership-software=samba -U Administrator
```

Using this, we can successfully start Samba using the "barebone" config described above:
```
[global]
    security = ads
    realm = samdom.example.com
    workgroup = SAMDOM
    log file = /var/log/samba/%m.log
    kerberos method = secrets and keytab
    client signing = yes
    client use spnego = yes
```

**Comment by FroggyFlox** [comment]
By default, `realmd` sets the following SSSD domain settings:
```
[domain/samdom.example.com]
default_shell = /bin/bash
krb5_store_password_if_offline = True
cache_credentials = True
krb5_realm = SAMDOM.EXAMPLE.COM
realmd_tags = manages-system joined-with-samba 
id_provider = ad
fallback_homedir = /home/%u@%d
ad_domain = samdom.example.com
use_fully_qualified_names = True
ldap_id_mapping = True
access_provider = ad
```

Based on user feedback in the forum, as well as exploration of `sssd` man pages, it seems we could offer customization of the following settings as these seem to be the most important ones:
- **ldap_id_mapping** (configurable within the `realm join` command itself)
- **enumerate**
- **case_sensitive**

These should be quick and easy implementations, thereby representing good candidates for a first offer at customizing the Active Directory service. While we could offer a blank slate like we do for the Samba service, it implies more refactoring, and introduces more opportunities for failures; we could thus think of implementing something like that in the future when the core Active Directory functioning is established.

As usual, thanks for any feedback on these settings!

**Comment by FroggyFlox** [comment]
After testing sharing of a share (hosted by Rockstor) via Samba using a domain user (`administrator@samdom.example.com) as admin user, and then accessing it from a separate Leap 15.2 client joined to the same AD (`samdom.example.com`), it appears we need to have the `samba-winbind` installed so that winbind can take care of the id mapping. This is consistent with instructions and recommendations by Red Hat on their documentation:

> **Important**
> Using SSSD as a client in IdM or Active Directory domains has certain limitations, and Red Hat does not recommend using SSSD as ID mapping plug-in for Winbind. For further details, see the “What is the support status for Samba file server running on IdM clients or directly enrolled AD clients where SSSD is used as the client daemon” article.
> SSSD does not support all the services that Winbind provides. For example, SSSD does not support authentication using the NT LAN Manager (NTLM) or NetBIOS name lookup. If you need these services, use Winbind. Note that in Identity Management domains, Kerberos authentication and DNS name lookup are available for the same purposes. 

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/windows_integration_guide/smb-sssd

It is also consistent with other reports from users online joining an AD via SSSD, but needing to have the Winbind service running in order to access their samba shares, as well as the report of our own users in the forum (user Lorez85):
> I want to add that during my tests the mere SSSD isn’t enough to consistently authenticate AD users to Samba shares, i’ve also had to configure Windows Domain Membership over Yast.

https://forum.rockstor.com/t/failed-to-join-ad-domain/7394/9


We thus need to have the corresponding package installed on the Rockstor machine as well: `samba-winbind`

**Comment by phillxnet** [comment]
> We thus need to have the corresponding package installed on the Rockstor machine as well: `samba-winbind`

This is all good stuff @FroggyFlox. Well done on getting this all sorted so far.
In your (pending) pr make a note of all the additional packages we will now need and I'll add them as dependencies so we can test the final rpm before release as an upgrade to an existing system.

Thanks again for picking this one up. Bit of a show stopper for our other wise planned Stable release. Oh well. Under way now by the look of it. Nice.

**Comment by FroggyFlox** [comment]
> Well done on getting this all sorted so far.

Thanks for the kind words, @phillxnet , but I'm not sure I've sorted everything as there are still a few obscure corners for me. The ID mapping, for instance, and the exact interaction between SSSD id-mapping plugin and winbind's id-mapping module is still unclear. As a result, it's unclear to me whether we still need all the winbind specific settings in our samba config. It seems to work without all of it in my tests, so I commented that out, but maybe it'll be necessary for some users. Let me know if you know that this is the wrong approach (we'll see in the PR, anyway).

This is the reason why I kept the forum post linked above up-to-date with my progress so that anybody can chip in if they notice something wrong in the approach. Let me know if you think I should detail a bit more this aspect on the forum post.

Thanks!

**Comment by FroggyFlox** [comment]
On a related note, our LDAP implementation is also broken for the same reason as our AD one: reliance on `authconfig`
https://github.com/rockstor/rockstor-core/blob/897587beccb662838bb61be35568fd0728e03047/src/rockstor/smart_manager/views/ldap_service.py#L50-L52

As this is very similar to the AD fix, we can address the LDAP fix in the same PR as the AD fix; these will likely require configuration in the `sssd.conf` and `nsswitch.conf` files. @phillxnet, let me know if that's OK with you or if you'd prefer two separate PR for that. As I've already included some logic to customize `sssd.conf` in the AD fix, the LDAP fix will depend on the AD fix to be implemented so we might as well include them in the same PR.

**Comment by phillxnet** [comment]
@FroggyFlox Re:
> so we might as well include them in the same PR.

Totally agree. Best we get this all sorted in one go I think. Especially give your findings re the interplay.

All looking rather promising.Thanks again for all your sterling efforts on this issue.

**Comment by FroggyFlox** [comment]
I believe to finally have a working openLDAP server setup, that led me to the following minimal working `sssd.conf` settings:
```
[domain/default]
ldap_id_use_start_tls = True
cache_credentials = True
ldap_search_base = dc=example,dc=com
id_provider = ldap
auth_provider = ldap
chpass_provider = ldap
ldap_uri = ldap://rockldapserver.example.com
ldap_tls_reqcert = demand
ldap_tls_cacert = /etc/ssl/certs/ldapcacert.crt
ldap_tls_cacertdir = /etc/ssl/ssl/certs
enumerate = True
```

This leads to the following users being fetched by `getent passwd` (used by Rockstor to list users):
```
rockdev:~ # getent passwd
(...)
janedoe:*:2001:2000:janedoe:/home/janedoe:/bin/bash
johndoe:*:2003:2000:johndoe:/home/johndoe:/bin/bash
```

Now, we "simply" need to implement this into Rockstor.

**Comment by FroggyFlox** [comment]
Linking to #564 as the reference issue to fix with the upcoming PR (in addition to this issue).

**Comment by FroggyFlox** [comment]
As of the latest commit (https://github.com/FroggyFlox/rockstor-core/commit/7ef9426325c7102ad75bbc43d1e8ae5b5b7a6392), we now have a seemingly working LDAP implementation, as measured by the presence of LDAP users on `getent passwd`.
