### ISSUE TITLE
Inaccurate field label for Certificate path in LDAP service configuration form

### ISSUE THREAD

**Issue by FroggyFlox** [rockstor/rockstor-core#2244]
Following our rework of LDAP implementation (#2235), we now require the user to provide a **path** to TLS certificate rather than a **URL** to the certificate. Unfortunately, the corresponding form label was not updated accordingly in #2235 (my fault). See example below:
![image](https://user-images.githubusercontent.com/30297881/101959374-3481eb80-3bd3-11eb-90f7-b6ebbd966535.png)

This can be rather misleading to the user and should thus be changed to **Certificate path** rather than "Certificate URL".

**Comment by FroggyFlox** [comment]
@phillxnet, my apologies for missing something so obvious in my related PR. I'll submit another PR to fix this inaccuracy soon.

**Comment by phillxnet** [comment]
@FroggyFlox Nice find and apologies from me also for not catching this in the review. Oh well, at least we have it now and it should be a nice little fix to pop in ready for the next Stable channel release.
