### ISSUE TITLE
update embedded Web-UI rocknet doc link

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#2263]
Now that we have a specific rocknet doc entry, thanks to @FroggyFlox; post "Document rocknets creation and use."  (https://github.com/rockstor/rockstor-doc/pull/257), we can update the Web-UI embedded link to point to this new doc entry.

E.g.: http://rockstor.com/docs/docker-based-rock-ons/overview.html#networking

Currently the existing link (image below):
![rocknet-web-ui-doc-link](https://user-images.githubusercontent.com/2521585/105737127-7a013a80-5f2d-11eb-9f8f-b4bf7e10c3d0.png)
points, provisionally, to the docs in general: http://rockstor.com/docs/

**Comment by FroggyFlox** [comment]
Thanks for creating this issue, @phillxnet! I meant to but kept forgetting about it...

I actually was also thinking of putting the same "?" icon in our AD and LDAP services configuration windows pointing to their respective new doc sections. Do you think it would be a good approach as well?

**Comment by phillxnet** [comment]
@FroggyFlox Re:
> Do you think it would be a good approach as well?

I do, I really like the contextual doc links and they are super helpful especially for those less familiar with our somewhat esoteric jargon, i.e. Rock-ons/rockons rocknets etc. And that's on top of the usual dockier/plugin service type stuff that it's easy for folks who are more familiar with it to forget just what a jungle it can all be. So contextual links are king/queen in my book. We have been meaning to add them for a long time now and it looks like you've go that underway. I'd actually missed the link on my first review of that code. And I remember you mentioning it also. Oh well: bit by bit.

**Comment by phillxnet** [comment]
Also I added this to our ongoing milestone given it's a relatively valuable bug simple fix. We don't need for it to mission creep to any other links however, not unless it takes the 'doers' fancy of course.

**Comment by FroggyFlox** [comment]
Sounds good! I'll keep including such links in future work, then.
