### ISSUE TITLE
update specified psutil version

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#2272]
We currently pin psutil to version 3.3.0. This is now very old and it is proposed that we update to the latest 5.6.6. However it is pinned in a couple of places:

Version stipulations for psutil are in:
setup.py
& a peculiar hard wiring in:
conf/django-hack

>     join(base, 'eggs/psutil-3.3.0-py2.7-linux-x86_64.egg'),

Uses are in:
A defunct Rock-on 'special' handler:

> src/rockstor/storageadmin/views/rockon_discourse.py # currently outdated rock-on https://github.com/rockstor/rockon-registry/issues/185

and on the dashboard via data_collector.py:

> src/rockstor/smart_manager/data_collector.py:import psutil  # noqa E402
> src/rockstor/smart_manager/data_collector.py:            vals = psutil.cpu_times_percent(percpu=True)

**Comment by phillxnet** [comment]
The upstream changelog:
https://github.com/giampaolo/psutil/blob/master/HISTORY.rst

**Comment by phillxnet** [comment]
Given psutil on PyPi is at 5.8.0 and the above changelog doesn't mention any Python 3 only versions we may consider specifying 5.8.0. More research and testing required to finalise the version we end up pinning here.

**Comment by FroggyFlox** [comment]
We now pin 5.9.4 after #2432. 
https://github.com/rockstor/rockstor-core/blob/ac664dca1f097796c4272a702062f6bb04f9b47f/pyproject.toml#L89
