### ISSUE TITLE
Dmesg (Kernel) log option dis-functional in v4 release candidates

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#2281]
In our 'Built on openSUSE' variant the Dmesg (Kernel) log option misleadingly reports "Selected log file is empty or doesn't exist". This is thought to be attributable to underlying OS changes since our transition from CentOS to openSUSE as our base OS.

![empty-dmesg-Web-UI](https://user-images.githubusercontent.com/2521585/109296973-21250a80-7829-11eb-99f8-5678c46498de.png)

Where as the inferred dmesg / kernel logging on the host OS is as expected:

```
rleap15-2:~ # dmesg 
[    0.000000] Linux version 5.3.18-lp152.63-default (geeko@buildhost) (gcc version 7.5.0 (SUSE Linux)) #1 SMP Mon Feb 1 17:31:55 UTC 2021 (98caa86)
[    0.000000] Command line: BOOT_IMAGE=/boot/vmlinuz-5.3.18-lp152.63-default root=UUID=6703ad52-1045-4ed5-b598-a2442279547c ipv6.disable=1 plymouth.enable=0 rd.kiwi.oem.maxdisk=5000G
...
[ 4033.203013] BTRFS info (device sda): relocating block group 21303918592 flags data|raid1
[ 4040.856969] BTRFS info (device sda): found 13458 extents
[ 4041.839313] BTRFS info (device sda): found 13458 extents
[ 4042.113920] BTRFS info (device sda): balance: ended with status: 0
[ 4869.440990] BTRFS info (device sda): relocating block group 42238738432 flags data|raid1
[ 4876.545526] BTRFS info (device sda): found 18003 extents
[ 4878.202176] BTRFS info (device sda): found 18003 extents
```
And given the relevance here to btrfs related output for things like failed balances this issue is deemed to be a priority.

**Comment by phillxnet** [comment]
Linking for context to when this Web-UI log view element was added:
"Issue#762 logs on demand" #1312

**Comment by FroggyFlox** [comment]
@phillxnet, thinking it might be a matter of file path, I was curious about that one but it turns out it actually is the result of different logging systems as openSUSE Leap 15.2 uses `journald`.
While we currently try to read the dmesg log from `/var/log/dmesg`, there is no such file in Leap 15.2 as we're based on `journald`. It thus seems we need to adapt to our current mechanisms accordingly.

In this context, we might need to create new _readers_ for dmesg logs:
- `journalctl -k` for "static" reader
- `journactl -kf` for the "live" reader (equivalent to `tail -f`)

Of note, there are officials python bindings for `journald`, but that would be for another day: https://www.freedesktop.org/software/systemd/python-systemd/journal.html#systemd.journal.Reader

**Comment by phillxnet** [comment]
@FroggyFlox Thanks for taking an initial look at this.
Re:

> Of note, there are officials python bindings for `journald`, but that would be for another day: https://www.freedesktop.org/software/systemd/python-systemd/journal.html#systemd.journal.Reader

Agreed.




> When dmesg logs need to be downloaded, one simple yet rudimentary option is to simply export the output to `/var/log/dmesg` as we currently expect it: `journalctl -k > /var/log/dmesg`.

Nice.

**Comment by FroggyFlox** [comment]
As of 581edfb, I now have a simple but working fix to write the dmesg log to file; the following now works from the webUI:
- download the dmesg log
- read the log file

I still need to implement `journalctl -kf` in the live log reader, though.

**Comment by phillxnet** [comment]
@FroggyFlox Excellent. Thanks for stepping up to this one. Much appreciated. I've initially assigned to you given your progress to date to help avoid duplication of effort.

Thanks again for tending to this 4 Stabel release milestone issue.
Bit by bit.

**Comment by FroggyFlox** [comment]
As of 02137e7, we now have `journalctl -kf` implemented as a live reader so we can watch the dmesg logs from the webUI.

I'll go ahead and proceed with a final look on this and verify all tests (if any) still pass.

**Comment by phillxnet** [comment]
Nice. Well done.
