### ISSUE TITLE
Not putting a group under rockstor management is not respected

### ISSUE THREAD

**Issue by FroggyFlox** [rockstor/rockstor-core#2294]
Following [a report](https://forum.rockstor.com/t/deleting-a-user-newbie-question/7756?u=flox) by forum user *wdc* and subsequent attempts at reproducing the issue described therein, I noticed a quirk in the creation of a new group:

<img src="https://user-images.githubusercontent.com/30297881/114020172-4c921080-983d-11eb-889a-4953affb3309.png" width="500">

Indeed, the setting of the checkbox *Put this group under Rockstor management?* is **not** respected and the new group created ends up being managed by Rockstor regardless of the selected status of this checkbox.

After a brief investigation, it seems we simply fail to pull the value of this checkbox and include it in the payload; combined to the fact that we default this value to `True` in our `Group` model, we end up with all groups created from the webUI as being placed under Rockstor management. It seems we lost this setting somewhere in #530, fixing #401.

**Comment by FroggyFlox** [comment]
@phillxnet, this seems to be a problem on the javascript side of things and a quick javascript attempt on my end seemed to resolve the issue. Feel free to assign this me if you'd like.

**Comment by phillxnet** [comment]
@FroggyFlox Sorted (after a little mouse fumbling).

Thanks and nice find.
