### ISSUE TITLE
Move Rock-on url default definitions from built time to runtime

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#2305]
It is proposed that we move to declaring our Rock-on related 'repo' variables at run-time to more easily facilitate future enhancement re custom Rock-on repositories and enable easier manual adjustment in the mean time for this potential future configuration element without having to rebuild from source.

Please resource the later discussion in @korg's recent related pull request: specifically @FroggyFlox 's comment onward:
https://github.com/rockstor/rockstor-core/pull/2303#issuecomment-882971576

We currently define the canonical rock-on repositories (remove and local) as Django setting variables. This is now considered to be overkill (given the re-build requirement to effect a change). We could simplify this process and reduce our currently extensive reliance on the Django settings for such elements and keep things simple by just establishing constants (or as near as we can with Python) for these. It is further proposed that this move add an easily accessible edit to allow users to define their own rock-on repos to address such things as crippling internet latencies, or to avoid potentially unwanted out-of-lan calls by using a local lan mirror for example.

**Comment by FroggyFlox** [comment]
Thanks for taking care of writing this up!



> It is further proposed that this move add an easily accessible edit to allow users to define their own rock-on repos to address such things as crippling internet latencies, or to avoid potentially unwanted out-of-lan calls by using a local lan mirror for example.

I completely agree. We could propose this as a further customization of the *Rock-ons* service, for instance, and let users specify the path to the directory containing the `root.json` and the individual rock-ons json definitions. We could even think of implementing a button (somewhere) to sync this "local repo" with the rockon-registry; the current `rockons-metastore` folder/method could still be used as it is used now. 

I haven't properly thought of all that yet, but I wanted to note this down in case it gets interest from users.

**Comment by phillxnet** [comment]
The following text is copied form a Duplicate (now closed) issue #2358

> Thanks to @FroggyFlox for highlighting this issue. We currently define the Rock-ons default url at build-time. This does not favour those users where accessing the official Rock-ons repo is inappropriate, or maybe too slow. Nor does it easily allow the relocation, say to a local server, for those that may need to keep such definitions under their own control, or simply to modify the url to play nicely with a proxy server setup.
> 
> During the discussion in the following pull request:
> "change rockons default url to https #2304" #2303
> @FroggyFlox raised the prospect of moving this build-time definition to be run-time, and in the process we edge further along our path of simplifying our existing build system to in-turn replace it with a more modern alternative.

**Comment by phillxnet** [comment]
I think the core concept in this issue should be the move to run-time definition of Rock-on url default. We can then use this more flexible setup in future Rock-on enhancements which can similarly be defined in their own focused issues.

**Comment by FroggyFlox** [comment]
@phillxnet,
I started taking care of this one, following a simple relocation similar to what was done for MIN_DISK_SIZE, for instance, in https://github.com/rockstor/rockstor-core/pull/2360. I just realized one limitation of that approach, however:

The new ROCKONS constant would be located in `src/rocsktor/storageadmin/views/rockon.py`. For those needing/wanting to change the value of this constant, they can simply change it in that file and then restart the rockstor.service to see their changes applied.

Now, these user changes would be overwritten by the next rpm update, isn't it?

I still think this move is the right thing to do and a first step in allowing user-customization of the locations of the rock-ons repositories, but I wanted to confirm that with you; I'll need to put some warning/instructions before that constant definition accordingly.

**Comment by phillxnet** [comment]
@FroggyFlox Thanks for stepping up to this one.

> I still think this move is the right thing to do and a first step in allowing user-customization of the locations of the rock-ons repositories, but I wanted to confirm that with you; I'll need to put some warning/instructions before that constant definition accordingly.

Agreed. Re the rpm update (unistall/install) I think we can maintain settings/file by attributing them as config files. We just don't have this yet, but we could move in that direction. So yes, initially lets just break stuff out to build-time as per the referenced #2360 and we can then later maybe collect in an overall config file that we designate as such in our packaging and then have this survive updates. Or we extend the db to have such over-all configs of course. That may be more in keeping with our existing user settings approach.

However this initial step lets more advanced folks do their own thing re hosting and they can then be, as you say, informed of the drawbacks via a comment. I just don't like user settings in the Django settings, hence the move to make them run-time. Far easier for folks to do a trivial file tweak and reboot than do re-builds. So step-by-step.

**Comment by FroggyFlox** [comment]
Thanks for the feedback, I'll just go ahead and do just that.

> Or we extend the db to have such over-all configs of course. That may be more in keeping with our existing user settings approach.

I had a look yesterday and it seems we may "just" be able to use the current service Model without needing to alter it as we should be able to add the remote and local metastore definitions as part of the `config` element. That's a discussion of its own dedicated issue but I do think we can do without the need for a specific conf file in this case.

**Comment by FroggyFlox** [comment]
Closing as fixed by #2490
