### ISSUE TITLE
rpm_build_info: 'rockstor' hardcoded in error

### ISSUE THREAD

**Issue by chrstphrchvz** [rockstor/rockstor-core#2306]
In the `rpm_build_info` function, the `rockstor` package hardcoded in one of the possible errors:

https://github.com/rockstor/rockstor-core/blob/f170ee56ce129d12e3b4c81534a39f72a767e4f0/src/rockstor/system/pkg_mgmt.py#L118

Since the function is getting the package name from the `pkg` argument, `pkg` should be used in the error instead, even though the function is currently only used to check for the rockstor package.

**Comment by phillxnet** [comment]
@chrstphrchvz Agreed. Nice.
Thanks for your continued efforts in this part of the code. Much appreciated. Hopefully I can take a closer look  at this soon. Unless @FroggyFlox beats me to it of course.
