### ISSUE TITLE
Rockstor on OpenSUSE - System Update Logs pointing to Yum Logs

### ISSUE THREAD

**Issue by Hooverdan96** [rockstor/rockstor-core#2314]
In the Logs section, the system update logs are pointing to the original Centos-based Yum logs. 

![image](https://user-images.githubusercontent.com/35113775/134381414-93d7d4a8-ccbd-4057-ae46-a6e14d910c21.png)

It would be good to see the zypper related logs in this space.

Curated comments from @FroggyFlox:
Note that we still use yum to fetch changelogs for updates but yes, we do use zypper for updates so we should indeed reflect that in that dialog window and fetch the zypper logs.
/var/log/zypper.log might be too detailed for what we might want here. I feel we would prefer to have /var/log/zypp/history instead. Note that we also have /var/log/dnf.log that would be the equivalent to the yum logs that were targeted by the webUI logs manager, but these only include the yum changelog <package> and yum info rockstor as these are the current uses for yum. @phillxnet it might “just” require pointing to /var/log/zypp/history instead of /var/log/yum.log.

**Comment by FroggyFlox** [comment]
I'm working on the issue.
