### ISSUE TITLE
Logs Archive 'Click to download' link broken

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#2317]
Thanks to clink & HarryHUK (@harryhuk) in the linked forum thread for highlighting this issue. When selecting one or more logs in the "Logs Downloader" section of System - Log Manager, the expected requested_logs.tgz file is non-existent, resulting in a silent fail in Firefox or a "Failed - Network error" in chrome when clicking on the link. A related log entry, upon clicking the provided link generated by the "Download Logs Archive" button, reads as follows:

/opt/rockstor/var/log/supervisord_data-collector_stderr.log
```
/usr/bin/tar: Removing leading `/' from member names
tar (child): /opt/rockstor/src/rockstor/logs/requested_logs.tgz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
/usr/bin/tar: Child returned status 2
/usr/bin/tar: Error is not recoverable: exiting now
```

Encountered by issue author while reviewing pr:
"Replace Yum logs with Zypper history in Logs Manager (#2314)" #2315

Thanks to the indicated forum report:
https://forum.rockstor.com/t/selecting-logs-to-download-and-trying-to-download-them-fails/7679

We can be assured that this issue is not related to the indicated pull request review.

**Comment by phillxnet** [comment]
I am currently looking further into this issue.

**Comment by phillxnet** [comment]
The log manager feature was added in the following pr:
https://github.com/rockstor/rockstor-core/pull/1312

**Comment by FroggyFlox** [comment]
Thanks, @phillxnet ... I thought I tried that one and it worked. I must be confusing with the download link from the Logs Reader. I do remember mention(s) of this in our forum or in a past issue in this repo; I can't remember for sure or check for the moment, unfortunately.

**Comment by phillxnet** [comment]
@FroggyFlox Re:
> ... do remember mention(s) of this in our forum or in a past issue in this repo;
Yes, me too. I've looked in issue for a bit but have yet to look in forum. Would be good to have attribution on this one if it was raised and we missed it. I'll stagger on for a bit as it might be something simple I can quickly fix for the next release, which in turn will avoid inadvertent association with you pr which I'm pretty certain is just find. I just wanted a full complement of testing around it and the only thing I can't 'prove' is this download after one or more log selections bit.

**Comment by phillxnet** [comment]
@FroggyFlox I think this is the one we are both remembering:

https://forum.rockstor.com/t/selecting-logs-to-download-and-trying-to-download-them-fails/7679

I'll add attribution and a forum link to this issue directly.

**Comment by phillxnet** [comment]
OK so I've managed to track this down to a change made in our build system. Our rpm's used to have the following directory:
/opt/rockstor/src/rockstor/logs/
If this is created via:
```
mkdir -p /opt/rockstor/src/rockstor/logs/
```
The the log download functions as expected and we get the far less concerning:
/opt/rockstor/var/log/supervisord_data-collector_stderr.log
```
/usr/bin/tar: Removing leading `/' from member names
/usr/bin/tar: Removing leading `/' from hard link targets
```
I propose that we no longer use this now non existent directory and instead use our existing log directory of:
```
/opt/rockstor/var/log/
```
i.e settings.ROOT_DIR/var/log/

This directory appears at first glance to be declared in logs_downloader()
https://github.com/rockstor/rockstor-core/blob/master/src/rockstor/smart_manager/data_collector.py#L416

I will confirm these findings further and prepare a pull request shortly, ready for the pending 4.0.9-0 rpm release.

**Comment by phillxnet** [comment]
I'll probably have to re-think the "/opt/rockstor/var/log/" idea as that introduces more complexity regarding webserver write access:
```

```

**Comment by phillxnet** [comment]
We also have the associated Web-UI js code:
https://github.com/rockstor/rockstor-core/blob/master/src/rockstor/storageadmin/static/storageadmin/js/views/logs.js

After a little experimentation my prior preference for using our existing log directory may over complicate things regarding webserver access.
