### ISSUE TITLE
Postfix hash format is deprecated in Leap 15.3

### ISSUE THREAD

**Issue by FroggyFlox** [rockstor/rockstor-core#2324]
Thanks to forum user **njmike73** for reporting an issue related to our expectations in the postfix configuration. See forum thread below for reference:
https://forum.rockstor.com/t/errno-2-no-such-file-or-directory-etc-postfix-sasl-passwd-db/8083

As detailed in that forum thread, this is related to an updated version of the `postfix` package in Leap 15.3 where the `hash/db` file type is no longer supported. As we currently expect and use the `hash/db` file type in a few places, this causes our email setup configuration to fail.

According to its documentation, the default file type used in postfix can be retrieved by `postconf -d` (http://www.postfix.org/postconf.5.html#default_database_type).

**Comment by phillxnet** [comment]
## Leap 15.2 (hash type = *.db)
```
rleap15-2:~ # postconf -d | grep default_database_type
default_database_type = hash

ls -la /etc/postfix/ | grep "hash\|db"
-rw-r--r-- 1 root root 12288 Aug  6 15:51 access.db
-rw-r--r-- 1 root root 12288 Aug  6 15:51 canonical.db
-rw-r--r-- 1 root root 12288 Aug  6 15:51 helo_access.db
-rw-r--r-- 1 root root 12288 Aug  6 15:51 relay_ccerts.db
-rw-r--r-- 1 root root 12288 Aug  6 15:51 relay.db
-rw-r--r-- 1 root root 12288 Aug  6 15:51 relocated.db
-rw------- 1 root root 12288 Aug  6 15:51 sasl_passwd.db
-rw-r--r-- 1 root root 12288 Aug  6 15:51 sender_canonical.db
-rw-r--r-- 1 root root 12288 Aug  6 15:51 transport.db
-rw-r--r-- 1 root root 12288 Aug  6 15:51 virtual.db
```

## Leap 15.3 (lmdb type = *.lmdb)
```
rleap15-3:~ # postconf -d | grep default_database_type
default_database_type = lmdb

ls -la /etc/postfix/ | grep "hash\|db"
-rw-r--r-- 1 root root  8192 Nov 18 17:45 access.lmdb
-rw-r--r-- 1 root root  8192 Nov 18 17:45 canonical.lmdb
-rw-r--r-- 1 root root  8192 Nov 18 17:45 helo_access.lmdb
-rw-r--r-- 1 root root  8192 Nov 18 17:45 relay_ccerts.lmdb
-rw-r--r-- 1 root root  8192 Nov 18 17:45 relay.lmdb
-rw-r--r-- 1 root root  8192 Nov 18 17:45 relocated.lmdb
-rw------- 1 root root  8192 Nov 18 17:45 sasl_passwd.lmdb
-rw-r--r-- 1 root root  8192 Nov 18 17:45 sender_canonical.lmdb
-rw-r--r-- 1 root root  8192 Nov 18 17:45 transport.lmdb
-rw-r--r-- 1 root root  8192 Nov 18 17:45 virtual.lmdb
```

**Comment by phillxnet** [comment]
The core issue here is that we are micro managing what is now managed successfully by our upstream package.
I.e. we are attempting to enforcing the access writes on the files:
```
/etc/postfix/generic.*
/etc/postfix/sasl_passwd.*
```
But this is clearly the domain of the postfix installation: not ours.

In tests using a Leap 15.3 base (with our micro-management removed) we see that the execution of the relevant pre-process to create the final .db/.lmdb database files; and in fact our own python framed execution of the same:
```
    run_command([POSTMAP, GENERIC])
    run_command([POSTMAP, sasl_file])
```
Which corresponds to:
```
/usr/sbin/postmap /etc/postfix/generic
/usr/sbin/postmap /etc/postfix/sasl_passwd
```
results in the sane:
```
ls -la | grep "generic\|sasl_passwd"
-r-------- 1 root root    82 Jan  3 13:22 generic
-rw-r--r-- 1 root root 12288 Jan  3 13:22 generic.lmdb
-r-------- 1 root root    65 Jan  3 13:22 sasl_passwd
-rw------- 1 root root 20480 Jan  3 13:22 sasl_passwd.lmdb
```
Where our generated source file of sasl_passwd is read-only by root alone (as intended and unaltered from prior behaviour).
But the resulting (non micromanaged) target file is sanely set to rw root only.

Our 'part' of the generic.lmdb file generation is also similarly secure and we trust in the managing package of postfix that it's generated file permissions are appropriate. This file after all does not contain the secrets of sasl_passwd.lmdb/db. As evident from it's treatment once out-of-our-hands.

Typically /etc/postfix/generic contains only email mappings:
http://www.postfix.org/generic.5.html
for example:
```
@rleap15-3 user@email.domain.com
@rleap15-3.localdomain user@email.domain.com
```
from the above postfix email manual entry:

>        The optional generic(5) table specifies an address mapping that applies
>        when mail is delivered. This is the opposite of  canonical(5)  mapping,
>        which applies when mail is received.
> 
>        Typically, one would use the generic(5) table on a system that does not
>        have a valid Internet domain name and that uses something like localdo-
>        main.local  instead.   The generic(5) table is then used by the smtp(8)
>        client to transform local  mail  addresses  into  valid  Internet  mail
>        addresses  when mail has to be sent across the Internet.  See the EXAM-
>        PLE section at the end of this document.
> 
>        The generic(5) mapping affects  both  message  header  addresses  (i.e.
>        addresses  that  appear inside messages) and message envelope addresses
>        (for example, the addresses that are used in SMTP protocol commands).
> 
>        Normally, the generic(5) table is specified as a text file that  serves
>        as input to the postmap(1) command.  The result, an indexed file in dbm
>        or db format, is used for fast searching by the  mail  system.  Execute
>        the  command  "postmap /etc/postfix/generic" to rebuild an indexed file
>        after changing the corresponding text file.

It is there-fore proposed that we simply drop our inappropriate micro-management of the postfix generated files. And in turn avoid our current failure to address the correct file ending.

**Comment by phillxnet** [comment]
Post the proposal we drop our micro-management of the postfix generated files we are left with our own enforced use of the now deprecated hash database type:
```
    fo.write("smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd\n")
    ....
    fo.write("smtp_generic_maps = hash:/etc/postfix/generic\n")
```

**Comment by phillxnet** [comment]
N.B. the disparity between our enforced /etc/generic file permissions and those found in a default openSUSE was also reported by forum member kri164
See:
https://forum.rockstor.com/t/postfix-problem/7460/3
for context.
