### ISSUE TITLE
Unable to configure email alerts if the local network domain is localdomain

### ISSUE THREAD

**Issue by parthjoshi-pc** [rockstor/rockstor-core#2373]
Because of a quirk of the rockstor Django application, if your local network has its default domain configured as `localdomain`, then it is not possible to configure email alerts. This is because Rockstor automatically adds an entry to the `/etc/default/generic` postfix lookup table with the domain name `localdomain` and then tries to add another entry for the default domain of the host. This leads to a duplicate entry being added in the lookup table with the `postmap` command failing with the following error:

```
CommandException: Error running a command. cmd = /usr/sbin/postmap /etc/postfix/generic. rc = 1. stdout = ['']. stderr = ['postmap: warning: lmdb:/etc/postfix/generic: duplicate entry: "@hostxxxx.localdomain"', 'postmap: fatal: error updating lmdb:/etc/postfix/generic: Invalid argument', '']
```

This can be fixed trivially by not adding the extra entry in this case.

**Comment by phillxnet** [comment]
Closing as:
Fixed by #2374 
Thanks again to @parthjoshi-pc for also providing the fix. Much appreciated.
