### ISSUE TITLE
(t) avoid recalculating pool free

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#2386]
(t) = testing branch. While working on #2384 and revising mocking of such things as pool free space, we see a redundant re-calculation of the same in our PUT (remove) pool command when the exact same calculation has already been made via an earlier Pool object @property instantiation still held.

Pool "free" property definition:
https://github.com/rockstor/rockstor-core/blob/afa3e413a0202042fcabdc7c7e69b42d9042fe4f/src/rockstor/storageadmin/models/pool.py#L97-L104

storageadmin.views.pool.PoolDetailView -put()
https://github.com/rockstor/rockstor-core/blob/afa3e413a0202042fcabdc7c7e69b42d9042fe4f/src/rockstor/storageadmin/views/pool.py#L700-L705

This is obviously redundant. And given the second in-transaction re-use/repeat-call is the only other user of fs.btrfs.pool_usage() we can improve/ease our traceability and mocking by centralising this methods use.

**Comment by FroggyFlox** [comment]
Closing as fixed by #2387 .
