### ISSUE TITLE
Don't load non-json rockon config files?

### ISSUE THREAD

**Issue by kanecko** [rockstor/rockstor-core#2473]
This happened on 4.5.4-0.

I have added `omada-controller.json` to the usual place in order to install it as a rockon via WebUI. Because I make a lot of amendments during testing, my text editor creates a backup file to the same dir but appends a tilde: `omada-controller.json~`

I have found that when clicking the Update button in WebUI, an arbitrary file is chosen from that dir. Sometimes with the tilde, sometimes without.

I suggest that you search for more specific rockon config files. E.g. that they end with, and only with ".json".
Of course, it is my duty to make sure only one, valid JSON rockon config file is in that dir, but I thought I put up the issue up for discussion anyway.

I'm confident that this can be repro'd by placing any two .json and json~ files in the dir.

![1674120763716 - Copy](https://user-images.githubusercontent.com/5829467/213411079-c8098862-3494-423c-850a-fc314fdf5ad8.jpg)

**Comment by phillxnet** [comment]
@kanecko Thanks for creating this issue, much appreciated. And I totally agree.
Do you fancy preparing a pull request against this issue?
We have the following extensive wiki guide on the forum written by @FroggyFlox on how our Rock-on subsystem works:
https://forum.rockstor.com/t/rock-on-framework-implementation/6288

**Comment by kanecko** [comment]
Maybe. My first priority is setting up my home network before my vacation time runs out :)

**Comment by phillxnet** [comment]
Closing as:
Fixed by #2482
