### ISSUE TITLE
HDD to SSD pool migration?

### ISSUE THREAD

**Issue by Mercbot7** [rockstor/rockstor-core#2521]
I would like to migrate my existing HDD pool to an SSD Pool. Mostly for noise and energy. I currently have 4 1TB HDD in a RAID 10. I have one SATA port open on the Mobo. I would like to migrate to 4 1TB SSD. Is it possible to simply replace disks in the pool, one by one, with the SSDs? Giving them time to replicate and the pool to be stable each time before proceeding? Is it as simple as that or is there an issue or problem with a pool of disks of mixed type?

**Comment by phillxnet** [comment]
@Mercbot7 Hello there. In brief, yes.

But I would advise that you open a new forum thread on this question as the GitHub issues is not the place for advice/support. Just open a new forum post here: https://forum.rockstor.com/ with your setup etc.

But yes, although we don't yet support btrfs replace via the Web-UI, but you can add (an ssd), wait for balance to finish, then remove (an hdd). You can also do this with several drives at a time. Again ask on the forum as your raid level is currently at minimum so it would be good to keep that above during the majority of the procedure.

There is no issue with mixing hdd, ssd, they are all seen as block devices. You can also mix sizes incidentally.

Closing issue as
- moved to forum (support).

**Comment by Mercbot7** [comment]
@phillxnet sorry about that. I was on the blog link form the website and it would not let me start a new topic and did not think to try the `Wiki` link on the website as the forums. Perhaps consider changing the name of `Wiki` title to `Forums`?

**Comment by phillxnet** [comment]
@Mercbot7 Hello there. We do have a forum link form the main website:
https://rockstor.com/
and it, in turn, has a top level menu item of: Community which in turn has a Forum sub-item.

Which Wiki entry are you referencing here?

**Comment by phillxnet** [comment]
@Mercbot7 Our forum "Wiki" subsection is for developer notes only, maybe that is why it didn't let you create a new issue.
The main forum should be just find however, as long as you login that is. Let us know how you get on. Thanks for the suggestion thought, but I think this is a miss-understanding as to our wiki subsection and the form as a whole.
