### ISSUE TITLE
RockOn Installation: the environment form has no scrollbar when there are many vars defined

### ISSUE THREAD

**Issue by kanecko** [rockstor/rockstor-core#2533]
If a RockOn has a lot of environment variables defined, they will be added to the form, but the form itself will be simply cut off, when there is no more height available on the browser.
This means height becomes a rare commodity on smaller devices, and even on desktop monitors it becomes an issue after 10-14 variables.

**Comment by Hooverdan96** [comment]
could this be possibly remedied by adding `overflow:auto;` or the combo of 
```
overflow-y:auto;
overflow-x:hidden;
```
to this section in the css file?

https://github.com/rockstor/rockstor-core/blob/3ad7eee27a40badab7edeea6dc198e800f6b121e/src/rockstor/storageadmin/static/storageadmin/css/style.css#L521-L523

Or would it need to be in the overall overlay piece?
https://github.com/rockstor/rockstor-core/blob/3ad7eee27a40badab7edeea6dc198e800f6b121e/src/rockstor/storageadmin/static/storageadmin/css/style.css#L510-L519

**Comment by kanecko** [comment]
I am not familiar with the whole system so I tried to limit the scope of my change to only the installation form. See pr

**Comment by phillxnet** [comment]
@Hooverdan96 Thanks for chipping in on this issue. I'm a little nervous at making larger scope changes at this late RC stage but we can try a broader approach down the line once we are clearly into the next testing channel.

@kanecko's change in the linked pr looks to be pretty narrow, and tested OK. So I'll pop that in as-is for now shortly. But we can always do with attention in these areas so we can keep the broader approach in mind once we are in the clear of the next testing channel run where we can be more far reaching with our changes.

**Comment by kanecko** [comment]
Closed due to PR check-in
