### ISSUE TITLE
(t) Suboptimal permissions on crontabs created by Rockstor

### ISSUE THREAD

**Issue by FroggyFlox** [rockstor/rockstor-core#2556]
This issue results from a discussion with @phillxnet related to #2540: https://github.com/FroggyFlox/rockstor-core/commit/5fb66a66e1e0d0a0baf68c13c556a70d7181c04a#r114644668

As detailed and demonstrated by @phillxnet in that conversation thread, our current creation of crontabs keeps the default mode of 644 whereas security hardening would recommend keeping these files accessible by `root` only.

It is thus proposed that we ensure a mode of 600 for the creation of our crontabs:
- scheduled tasks: https://github.com/rockstor/rockstor-core/blob/8e65ada122112ac45cebd1dd5dd03c0ce6796069/src/rockstor/smart_manager/views/task_scheduler.py#L88
- replication service: https://github.com/rockstor/rockstor-core/blob/8e65ada122112ac45cebd1dd5dd03c0ce6796069/src/rockstor/smart_manager/views/replication.py#L40

**Comment by phillxnet** [comment]
Closing as:
Fixed by #2559
