### ISSUE TITLE
Py3.6 System - Logs manager - Logs Reader fails

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#2568]
Post #2567 in testing branch we have a failure in our" Logs Reader" - "Logs Downloader" however works as intended.

**Comment by FroggyFlox** [comment]
The issue was related to 2 problems:
- `subprocess.Popen()` returning a bytes sequence rather than str
- use of the `xrange()` function that no-longer exists in Python3 (Python3's `range()` behaves the same).

Fixes have been identified.

**Comment by phillxnet** [comment]
To be closed as:
Fixed by #2586 

Thanks to @FroggyFlox for resolving this issue.
