### ISSUE TITLE
Py3.6 Dashboard Network widget not functional

### ISSUE THREAD

**Issue by FroggyFlox** [rockstor/rockstor-core#2577]
This problem was first reported in: https://github.com/rockstor/rockstor-core/pull/2565#issuecomment-1576937019

Post #2567, we have an empty Network widget:
![image](https://github.com/rockstor/rockstor-core/assets/30297881/20def811-22c9-4ff5-93ff-519671c7116f)

In the browser's developer console, we see the following message when resizing the Network widget.
```
Uncaught TypeError: this.NetworkChart is null
    resize https://buildvm/static/storageadmin/js/storageadmin.js:22189
    jQuery 2
        dispatch
        handle
```

It does seem that the data for the network widget do not come through.

**Comment by FroggyFlox** [comment]
As previously mentioned, a fix has been identified; I just need to find some time to submit the corresponding PR.

**Comment by phillxnet** [comment]
Closing as:
Fixed by #2583 

Thanks to @FroggyFlox for researching and providing the fix.

**Comment by Hooverdan96** [comment]
@FroggyFlox, again does not necessarily belong here, and I can delete this comment later .. I did a search on other uses of map(), and was wondering whether change will be required for those usages as well, or whether the return in 3.6 will be in the right format. I tend to think those instances are ok, but might be worthwhile to quickly peek at them:

https://github.com/rockstor/rockstor-core/blob/716aa4fe7a22ef76d06c204d86e7303a8c0f3262/src/rockstor/storageadmin/views/rockon.py#L249-L259

https://github.com/rockstor/rockstor-core/blob/716aa4fe7a22ef76d06c204d86e7303a8c0f3262/src/rockstor/smart_manager/replication/listener_broker.py#L350-L355

https://github.com/rockstor/rockstor-core/blob/716aa4fe7a22ef76d06c204d86e7303a8c0f3262/src/rockstor/storageadmin/static/storageadmin/js/views/dashboard/top_shares.js#L61-L77

**Comment by phillxnet** [comment]
@Hooverdan96 Thanks for this, definitely worth having these notes - and as you say they can always be transferred to a dedicated issue. I've not tried the replication yet and fully expect some issues there.
N.B. your last entry is however in JS not Python so likely unaffected.

**Comment by Hooverdan96** [comment]
oh, shoot, right I didn't pay attention on the last one. I was filtering out all js ones ...
