### ISSUE TITLE
Release process  changes in accompanying repositories

### ISSUE THREAD

**Issue by FroggyFlox** [rockstor/rockstor-core#2596]
Once a release in rockstor-core is created, we currently need to also proceed with a few modifications in two of our accompanying repositories.:
- rockstor/rockstor-jslibs
- rockstor/rockstor-rpmbuild

This process is rather simple but requires quite a bit of manual work that is very time-consuming. We should instead strive to automate the process.

**Comment by Hooverdan96** [comment]
Is this something that would need to eventually apply somehow to the documentation repo (not sure how many references we have in there to a release version)?

**Comment by FroggyFlox** [comment]
Oh that's an excellent point... That would be a good opportunity to expand our use of substitutions there (https://github.com/rockstor/rockstor-doc/issues/422) so that we can easily update any mention of latest release-version throughout.
