### ISSUE TITLE
Revise Stable Updates activation instructions re legacy shop removal

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#2599]
We have now dropped our legacy 'shop' that was maintain (at 100% discount) solely due to it's involvement in activation code issuance: see: https://forum.rockstor.com/t/appman-rockstor-com-maintenance-open-collective-integration/8867

It is proposed that we now update our Web-UI embedded instructions, as a follow-up to the prior transition changes introduced in the following pull request:
https://github.com/rockstor/rockstor-core/pull/2539
That accommodated our initial Open Collective arrangements.

We no longer require any reference to our now legacy/defunct 'shop', give we now have preliminary Appman  to Open Collective integration: serving the vast majority of our prior use cases.

The pull request associated with this issue should remain as small/focused as possible give it's relevance to not only our Release Candidate/Stable master branch, but also our pending release new testing branch/updates. It should also be squashed to a single commit to assist with the cherry picking process.

**Comment by phillxnet** [comment]
@FroggyFlox & @Hooverdan96 given we have our initial Open Collective integration at Appman I'd like to get this proposed change into both master and testing before our 4.6.1-0 Stable and 5.0.0-0 testing releases.

**Comment by FroggyFlox** [comment]
@phillxnet, looks good to me!
Thanks for taking care of updating that.
