### ISSUE TITLE
Compression cosmetics

### ISSUE THREAD

**Issue by StephenBrown2** [rockstor/rockstor-core#2640]
<blockquote cite="https://github.com/rockstor/rockstor-core/pull/2619#pullrequestreview-1558934778_">
@StephenBrown2 Hello again.
Functional/cosmetic review only here as we can re-visit in follow-up issue-pr sets as and when.

## Cosmetics 
It would be nice to normalise our ordering across and within tooltips/selectors.

### Share compression options
Take a look at for example our share detail where the tooltip order is not that of the selector. Not a show-stopper but a nice to have in some usability follow-up as I'm keen to get this functional extension of a PR in as-is given your work to date to get it working and roughly in shape.

- tooltip and selector
![share-detail-compression-tooltip_and_selector](https://github.com/rockstor/rockstor-core/assets/2521585/734b38ed-0ca6-4b98-b664-f5b6a64367d1)

Tooltip ordering is consistent and I agree with putting the new zstd option at the end: sort of chronological ordering, at least for us. So we likely just need to re-order our share selector. But in another pr I think as only a cosmetic. On the same note we have existing issues re formatting etc. Note our missing space after "lzo:" in share and pool tooltips. Oh and thanks for throwing in some other little fixes re "it's" correction, that one was probably my mistake actually.

### Pool compression options
**Overview**
- tooltip
![pool-overview-compression-tooltip](https://github.com/rockstor/rockstor-core/assets/2521585/dbb2e8c1-9ab4-4d83-b927-7b7086f5e252)
- selector
![pool-overview-compression-selector](https://github.com/rockstor/rockstor-core/assets/2521585/edba3b45-a3ea-493c-96e6-f1b31e58e588)

**Detail**
- tooltip
![pool-detail-compression-tooltip](https://github.com/rockstor/rockstor-core/assets/2521585/0b9c75d0-3d38-42d7-835f-2ad53ccdce29)
- selector
![pool-overview-compression-selector](https://github.com/rockstor/rockstor-core/assets/2521585/2a12dfa1-107e-4328-bd08-29d78f7d0fd1)

As you noted in your PR we really need to abstract these out to a single source of truth, easier said than done but it would be another great addition - especially as this is not going to be our last addition here. That way future changes / corrections would be far more trivial and have consistency by design. But bit by bit and all good.

As you also noted, we have a reflection of the setting at the pool level in our active mount options:
![zstd-pool-active-mount-options](https://github.com/rockstor/rockstor-core/assets/2521585/1b8e58c5-1501-4630-9d47-19c6ed0d2db4)
Nice.

Thanks again for your effort here: much appreciated. Likely we need some infrastructure improvements in this area to support further enhancements but again: bit by bit.
</blockquote>

_Originally posted by @phillxnet in https://github.com/rockstor/rockstor-core/pull/2619#pullrequestreview-1558934778_

I've done some work to pretty up the tooltip text, and re-ordered to be consistent, PR coming shortly. Wanted to reference this in a new issue for tracking.

**Comment by phillxnet** [comment]
Closing as:
Fixed by #2641
