### ISSUE TITLE
Rockstor build changes to .gitignore

### ISSUE THREAD

**Issue by StephenBrown2** [rockstor/rockstor-core#2644]
> @StephenBrown2 These changes to .gitignore are a nice addition actually - and yes I think it would be good to have them split out into their own issue/pull request set. We will then have them to point to for folks that want to add similar dev environment additions/enhancements such as these. It will also help with cherry picking these changes, in isolation, if they end up being required in another branch.
> 
> Thanks for thinking of this and highlighting it. Plus it will help to split out 'things' from one another. Always nice.
> It can also help with reviewing to have stuff split down into more manageable chunks.

_Originally posted by @phillxnet in https://github.com/rockstor/rockstor-core/pull/2641#discussion_r1285107554_

**Comment by phillxnet** [comment]
Closing as:
Fixed by #2643
