### ISSUE TITLE
(t) Outdated version for django-pipeline

### ISSUE THREAD

**Issue by FroggyFlox** [rockstor/rockstor-core#2646]
We currently use `django-pipeline` version 1.6.9:
https://github.com/rockstor/rockstor-core/blob/387667dfd393d5c424fd1fa4892e61518cc3b75e/pyproject.toml#L66C10-L66C10
```toml
django-pipeline = "==1.6.9"
```
Interestingly, we can see from their release notes that support for Django 1.11 (our current version) was added in django-pipeline 1.6.12, and then "verified" in 1.6.13. From PyPI's tags, the last version to list Django 1.11 and Python 3.6 is **django-pipeline** 1.7.

It is thus proposed that we temporarily upgrade to django-pipeline 1.7 now, before further upgrading during our move to Django 2.2 LTS, for which support was added in https://github.com/jazzband/django-pipeline/pull/693 (thanks to @phillxnet for finding that last one).

**Comment by phillxnet** [comment]
Note that we also have a configuration short-fall which is to be addressed in the following issue as it does not relate to the version update targeted in this issue:
https://github.com/rockstor/rockstor-core/issues/2653
and pertains only to easing development re static files serving of our pipelined storageadmin.js composition.

**Comment by phillxnet** [comment]
> Note that we also have a configuration short-fall which is to be addressed in the following issue ...

This 'config shortfall' has now been resolved in testing branch as part of: "Enhance development ease #2653" #2655

**Comment by phillxnet** [comment]
Closing as:
Fixed by #2659
