### ISSUE TITLE
(t) `use_for_related_fields` is deprecated in Django 2.0

### ISSUE THREAD

**Issue by FroggyFlox** [rockstor/rockstor-core#2666]
Using Python's warning, we can see the following warning:
```
/opt/rockstor/.venv/lib/python3.6/site-packages/django/utils/functional.py:35: RemovedInDjango20Warning: use_for_related_fields is deprecated, instead set Meta.base_manager_name on 'storageadmin.Disk'.
  res = instance.__dict__[self.name] = self.func(instance)
```

# Steps to reproduce
Under a `runserver` configuration:
1. go to the disks page
2. Click the "rescan" button.
3. The warning message appears.

# Information
We can see the following in Django 2.0 feature removal:
https://docs.djangoproject.com/en/4.2/releases/2.0/#features-removed-in-2-0
> Manager.use_for_related_fields is removed.

This was part of the deprecations started in Django 1.10:
https://docs.djangoproject.com/en/4.2/releases/1.10/#manager-use-for-related-fields-and-inheritance-changes
> Manager.use_for_related_fields is deprecated in favor of setting [Meta.base_manager_name](https://docs.djangoproject.com/en/4.2/ref/models/options/#django.db.models.Options.base_manager_name) on the model.
>
> Model Manager inheritance will follow MRO inheritance rules in Django 2.0, changing the current behavior where managers defined on non-abstract base classes aren’t inherited by child classes. A deprecating warning with instructions on how to adapt your code is raised if you have any affected managers. You’ll either redeclare a manager from an abstract model on the child class to override the manager from the concrete model, or you’ll set the model’s Meta.manager_inheritance_from_future=True option to opt-in to the new inheritance behavior.

# In our code
The only instance of `use_for_related_fields` I can find is in `storageadmin.models.disks.py`:
```
buildvm155:/opt/rockstor # grep -r --include "*.py" "use_for_related_fields" src/rockstor/
src/rockstor/storageadmin/models/disk.py:    use_for_related_fields = True
```

**Comment by phillxnet** [comment]
Closing as:
Fixed by #2667
