### ISSUE TITLE
[Tailscale]: consider regex filtering for hostname validation/adjustments

### ISSUE THREAD

**Issue by Hooverdan96** [rockstor/rockstor-core#2714]
Follow up to the excellent initial pull request, regarding how hostnames are evaluated and adjusted in the corresponding python code.

              quick question, can a hostname not have unicode characters in it?  If that's the case, wouldn't some "inclusive" regex be better than excluding what we currently know as "special" characters"?

_Originally posted by @Hooverdan96 in https://github.com/rockstor/rockstor-core/pull/2712#discussion_r1364553929_

**Comment by FroggyFlox** [comment]
Closing as fixed by #2719.
