### ISSUE TITLE
[t] OpenVPN scripts for key generation and client enumeration don't work anymore with python3.11+

### ISSUE THREAD

**Issue by Hooverdan96** [rockstor/rockstor-core#2803]
Thanks to user [ZeusMR](https://forum.rockstor.com/u/zeusmr) who uncovered a renamed python 2.x function. The `raw_input`  function was used in one of the specialized scripts connected to the OpenVPN Rockon to generate keys, etc.

Unfortunately, this function has been renamed to `input()` so the interpreted won't recognize the `raw_input` function name anymore.

https://peps.python.org/pep-3111/

This affect these two script functions that were created for the OpenVPN Rockon:

https://github.com/rockstor/rockstor-core/blob/6c86e3858079ce8edc62c62684a7f2cf50fb6d79/src/rockstor/scripts/ovpn_util.py#L33-L50

It will hopefully be as easy as replacing the renamed function name with the new one to get it to work again.

**Comment by Hooverdan96** [comment]
Also, these seem to be the only 2 instances (at least the Github search didn't surface any others) where `raw_input` was used.

**Comment by phillxnet** [comment]
Closing as:
Fixed by #2804
