### ISSUE TITLE
Outdated zypper repo's (Docker)

### ISSUE THREAD

**Issue by DoganM95** [rockstor/rockstor-core#2840]
Just tried updating my docker using 
```shell
zypper update docker
```  
  
The response the following, indicating an old version is the newest , that zypper is aware of:
```
No update candidate for 'docker-24.0.7_ce-150000.190.4.x86_64'. The highest available version is already installed.
```

However, according to [https://docs.docker.com/engine/release-notes/26.1/#2613](https://docs.docker.com/engine/release-notes/26.1/#2613), the most recent version is 26.1.3  

Could you please update the sources, so that the latest docker version is always used? Having always the latest version bring some obvious advantages and may be applicable to other old zypper packages also:

- Security Enhancements
- Performance Improvements
- New Features
- Bug Fixes
- etc.

### Manual installation attempt

I have meanwhile tried installing docker 26.1 manually, by forcefully overwriting the binaries using
```shell
wget https://download.docker.com/linux/static/stable/x86_64/docker-26.1.3.tgz
tar xzvf docker-26.1.3.tgz
sudo systemctl stop docker
sudo cp docker/* /usr/bin/
sudo systemctl start docker
```
which reported version 26.1 on `docker --version`, but containers could not be started:
```
DEVICE:~ # docker start 7270eeee159a
Error response from daemon: secret store is not initialized
```
so i had to revert to the old binaries to fix it.

**Comment by phillxnet** [comment]
@DoganM95 Thanks for the report, however this is not in our domain. We are a "Built on openSUSE" specialised distro and basically leave almost all the upstream repos in-place. So the docker version available is dictated by the openSUSE variant your install is based on.

A caveat here is that our installers are currently in the throws of being re-build using Leap 15.6 & 15.6 (RC): which is another way of saying they are currently outdated. But you can update an existing install by following our following docs; depending on the current base you are running (top-right of Web-UI should indicate this - with older installs requiring a mouse-over):

- https://rockstor.com/docs/howtos/15-2_to_15-3.html
- https://rockstor.com/docs/howtos/15-3_to_15-4.html
and we have yet to publish a 14.5 to 15.5 (but the last above should be close with some by-hand edits).

Hope that helps. And note that distros such as openSUSE will often be behind themselves from their own upstreams. Tumbleweed less so - but it then entails additional risk as a result of so many shifting sands.

> I have meanwhile tried installing docker 26.1 manually, by forcefully overwriting the binaries using

That is almost always a bad idea: we leave the foundational stuff to our upstream here, as they have the expertise available to create the distro where most stuff works out-of-the-box. We simply build on their expertise: and add our own customisation which involves almost no changes to the foundational services.

Keep an eye out for our new installers, or take a look at the above how-tos re our requirements for zypper dup prep. We already have 15.5 and 15.6 testing rpm, but are currently busy prepping and testing new installers.

---

Related issues/PRs:
- https://github.com/rockstor/rockstor-installer/pull/168
- https://github.com/rockstor/rockstor-website/pull/95

**Comment by phillxnet** [comment]
Pending closure as per last comment: as we do not control the docker version pre-installed as it is sourced from default upstream (openSUSE) repos. And upstream tends to such things as security back-ports to their chosen major package versions.

**Comment by DoganM95** [comment]
Thanks for the detailed response! I understood, that the zypper packages available are managed by openSUSE and not rockstor, thus i will close this non-rockstor issue.
