### ISSUE TITLE
Sporadic system service connection issues

### ISSUE THREAD

**Issue by DoganM95** [rockstor/rockstor-core#2899]
Sometimes the services of rockstor stop responding to any connection request. 

This issue contains but is not limited to `http UI`, `FTP`, `SMD`, `SSH`,  so that when trying to access 
- the web-ui, "This site can’t be reached"
- SMB, "network timeout"
- SSH, "Connection timed out"
- etc.

Overall something seems to break every once in a while, so the services become unreachable, reuquiring a restart of the system.
I observed this a couple times when i closed the lid of my laptop that was still connected via ssh, maybe causing an exception in the system by not doing a graceful conenction shutdown.
However, docker containers are still perfectly reachable during that time, meaning its not a network interface issue.

**Comment by phillxnet** [comment]
@DoganM95 Could you narrow this down via a form post to discuss further what exactly is failing here. On first read this looks like a caching issue with the indicated services. All will time-out under certain circumstances. I.e. Web-UI may need browser refresh, ssh/smb will timeout etc. Our SMB, ssh etc are all managed by our host OS: openSUSE Leap, so are near generic bar some minor tweaks. Curious though!

Open a new forum thread to help narrow down what you are seeing. And indicate the nature of your install, i.e. base OS, how it was installed, what Rockstor version you are experiencing this with: this is indicated in top-right of the Web-UI etc.

https://forum.rockstor.com/

That way we can hopefully narrow this down to an appropriate focus for a GitHub issue.
