### ISSUE TITLE
Rockon pre & post-install summaries are inconsistent

### ISSUE THREAD

**Issue by Hooverdan96** [rockstor/rockstor-core#2904]
As a continuation of the original issue #1588 (and associated PR #2887) there is possibly another instance where the shares are swapped Name of share within the docker container vs. the Rockstor share mapped to it. For example, when installing the WGEasy Rockon (also see recent PR [#389](https://github.com/rockstor/rockon-registry/pull/389)) the share is swapped in the summary screen before the installation is triggered:

![image](https://github.com/user-attachments/assets/d37459eb-358a-40a5-8589-1aa09db6144f)

`/etc/wireguard` should be the name, and the blurred out Rockstor share would be the `Mapped Representation`

**Comment by phillxnet** [comment]
# From the current mouse-over/tooltips

- src/rockstor/storageadmin/static/storageadmin/js/templates/rockons/settings_summary_table.jst

## Name:

> "Name of the resource according to Rockstor. Eg: Share names, port numbers etc.."

## Mapped representation:

> "Name/representation of the resource inside the Rock-on. Eg: Shares map to directories, ports map to (possibly different)ports to send traffic to the Rock-on, etc.."

@Hooverdan96 in the given example: this is counter to:

> `/etc/wireguard` should be the name, and the blurred out Rockstor share would be the `Mapped Representation`

Room for improvement for sure on these wordings however: in both tooltip and header text. Still investigating there as I know we have other anomalies. I'll likely just change this issues title once I'm clear on what is mostly wrong here :) . And the previously discussed (in your referenced issues) our self-inconsistency re this summary table and the post install info table.

**Comment by phillxnet** [comment]
# Settings summary:

https://github.com/rockstor/rockstor-core/blob/bbb47209097031ba7fd5c38edda5a2709274fd72/src/rockstor/storageadmin/static/storageadmin/js/views/rockons.js#L1576-L1583

Referenced template:

Rock-ons settings summary table:
https://github.com/rockstor/rockstor-core/blob/testing/src/rockstor/storageadmin/static/storageadmin/js/templates/rockons/settings_summary_table.jst

**Comment by phillxnet** [comment]
I'm moving in the direction of normalising on the order we see in the pre-install summary: but with major table header changes:

I.e. our pre and post install table ordering was inconsistent: moving towards pre-install column ordering but with improved headers:

Proposed post install thus:
![2FA-Post-install-summary](https://github.com/user-attachments/assets/fb5e3a40-8920-4390-83bf-57936565b4eb)


Pre-install / confirmation table changes to follow:

**Comment by phillxnet** [comment]
@Hooverdan96 Mid development I now see more your examples exact reference. E.g. I just go the following in the pre-install summary screen:


Resource type | Internal Reference | External Reference / Configured value
-- | -- | --
Share | 2FAuth-config:container-id:1 | /2fauth

The new headings make it clearer I think. But yes the /2fauth should be in the Internal column. Working on this now to update/complete the last comment with examples.
