### ISSUE TITLE
Remove obsolete browser compatibility - html5shim

### ISSUE THREAD

**Issue by Hooverdan96** [rockstor/rockstor-core#2920]
As the usage of IE9 and other, older, browser flavors has faded, backwards compatibility is not as necessary anymore. Furthermore, the referenced `html5shim` link does not exist anymore (http://html5shim.googlecode.com/svn/trunk/html5.js) and probably hasn't for some time.

The suggestion is to remove this part from the affected webpages:

https://github.com/rockstor/rockstor-core/blob/4d60a2c683140aaa10a8e5b201157163cc9a898b/src/rockstor/storageadmin/templates/storageadmin/user_create.html#L29-L32

https://github.com/rockstor/rockstor-core/blob/4d60a2c683140aaa10a8e5b201157163cc9a898b/src/rockstor/storageadmin/templates/storageadmin/setup.html#L32-L35

https://github.com/rockstor/rockstor-core/blob/4d60a2c683140aaa10a8e5b201157163cc9a898b/src/rockstor/storageadmin/templates/storageadmin/login.html#L35-L38

https://github.com/rockstor/rockstor-core/blob/4d60a2c683140aaa10a8e5b201157163cc9a898b/src/rockstor/storageadmin/templates/storageadmin/base.html#L41-L44

**Comment by Hooverdan96** [comment]
@phillxnet would it make sense to establish a label that can be assigned for UI renovation topics, so that these types of things can be grouped together later (especially, if the there are more fundamental changes planned?

**Comment by phillxnet** [comment]
@Hooverdan96 Re:

> @phillxnet would it make sense to establish a label that can be assigned for UI renovation topics

Absolutely. Label created, and issue so labelled. Thanks.

**Comment by phillxnet** [comment]
Closing as:
Fixed by #2928
