### ISSUE TITLE
Use django pipleine variables while including static assets

### ISSUE THREAD

**Issue by sujeetsr** [rockstor/rockstor-core#340]
Instead of hardcoded paths for js and css in base.html, use compressed_js and compressed_css variables so that paths are expanded appropriately in development and production

This will also allow for faster development without the need to run buildout.

**Comment by Hooverdan96** [comment]
@phillxnet, @FroggyFlox I think, since we switched to poetry and all that, is this still a good-to-have, it's obsolete, or you don't want to pursue it? Real question I am asking, of course, should this be closed?
