### ISSUE TITLE
NFS mount doesn't reflect the correct share size

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-core#375]

**Comment by Hooverdan96** [comment]
@phillxnet, @FroggyFlox, can this one be closed? this was reported over 10 years ago, and is probably not relevant at this time.

**Comment by FroggyFlox** [comment]
@Hooverdan96 
Agreed... I don't recall another report of that either so I'm closing now. We can always create a new one with details and reproducers if we receive this kind of report.

Thanks a lot for the pointer!
