### ISSUE TITLE
rockstor config data/dbs should be reconstructible

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-core#392]
In cases of OS reinstall or db corruption.

**Comment by phillxnet** [comment]
I suggest this issue can be closed as a duplicate of issue #663, I know the other way round might make sense but issue #663 has current activity and greater involvement / info; ie we can put a use case note on #663 of "In cases of OS reinstall or db corruption" which is nice and concise.  There is a set milestone inconsistency but this issue has older information in.
