### ISSUE TITLE
disks enhancements

### ISSUE THREAD

**Issue by sujeetsr** [rockstor/rockstor-core#441]
The backend should return disk errors if any.
The disks table should display disk status
Users should be able to filter and sort.
Use backgrid.js (http://backgridjs.com/) for filtering, sorting the disks table.

**Comment by Hooverdan96** [comment]
I think we've made some progress on this front (like surfacing some device errors), some of the filtering/sorting exists now as well. Should we keep this open, or revisit once the UI discussion and reduction of reliance on js libraries picks up steam?
