### ISSUE TITLE
manual snapshot cannot be deleted through web ui

### ISSUE THREAD

**Issue by debejerry** [rockstor/rockstor-core#478]
If trying to delete a manual triggered snapshot the deletion attempt gets aborted with the error:
Error!
A low level error occured while deleting snapshot(test). Try again later.

I then tried to delete the snapshot with console commands which worked, the snapshot got deleted on the filesystem, but this seems to confuse the web UI / database, as the now deleted snapshot is still shown in the web ui and in consequence i'm unable to delete the share were the snapshot was taken.

**Comment by schakrava** [comment]
I am closing this issue, feel free to comment if the issue appears for you again.
