### ISSUE TITLE
Feature - Filesystem indexing/search (e.g. Recoll, Tracker)

### ISSUE THREAD

**Issue by victorhooi** [rockstor/rockstor-core#484]
It would be awesome if there was some kind of filesystem indexing/search feature available.

(I.e. not just `locate`, which only checks filenames).

E.g. something like Tracker (https://wiki.ubuntu.com/Tracker) or Recoll (http://www.lesbonscomptes.com/recoll/)

**Comment by Hooverdan96** [comment]
@phillxnet, @FroggyFlox wondering whether this should be rather a Rockon offering (or eventually multiple ones so users can pick between different ones)?

**Comment by phillxnet** [comment]
@Hooverdan96 Agreed. There has been no further developer interest or user pick-up here so closing.
