### ISSUE TITLE
Add S.M.A.R.T support

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-core#498]

**Comment by iFloris** [comment]
Yes, this would be very good to have. Even more so if we can see errors on a time scale, such as how many errors did we get this month? And last? But to start with, just having access to smart from the web-ui would be a great addition.

**Comment by freeurmind** [comment]
For now I just did "yum install smartmontools". Web-ui can come later but please consider wrap smartmontools package into next update.
