### ISSUE TITLE
revisit django-pipeline

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-core#527]
we are currently using django-pipeline 1.2.3 which is pretty old. Either we should update and make sure it doesn't break asset packaging or explore if this is even needed in the current version of django that we use or may be there is a simpler way to package assets.

**Comment by MFlyer** [comment]
@schakrava can we close this considering your Django updates? :)

**Comment by MFlyer** [comment]
Up to @schakrava , our current pipeline is 1.6.9 (upstream is 1.6.11, so we are quite good)

Mirko
