### ISSUE TITLE
empty disk serial number

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-core#545]
Looks like disks coming from a SAN or a hypervisor like VMWare may not have unique serial number if at all. User submitted feedback below from (http://rockstor.com/forums/index.php?p=/discussion/15/only-detecting-one-disk#latest)

Hey, 

Sorry for my lack of information. to clarify fdisk -l is showing the following: 

```
Disk /dev/sda: 10.7 GB, 10737418240 bytes, 20971520 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk label type: dos
Disk identifier: 0x000b9b40

Device Boot Start End Blocks Id System
/dev/sda1 * 2048 1026047 512000 83 Linux
/dev/sda2 1026048 3123199 1048576 82 Linux swap / Solaris
/dev/sda3 3123200 20971519 8924160 83 Linux

Disk /dev/sdb: 1099.5 GB, 1099511627776 bytes, 2147483648 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/sdc: 1099.5 GB, 1099511627776 bytes, 2147483648 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
```

The command you asked me to run shows: 

```
NAME="sda" MODEL="Virtual disk " SERIAL="" SIZE="10G" TRAN="spi" VENDOR="VMware " HCTL="2:0:0:0" TYPE="disk" FSTYPE="" LABEL="" UUID=""
NAME="sda1" MODEL="" SERIAL="" SIZE="500M" TRAN="" VENDOR="" HCTL="" TYPE="part" FSTYPE="ext4" LABEL="" UUID="086d6a03-8b54-4ceb-b5dc-e9569063bd83"
NAME="sda2" MODEL="" SERIAL="" SIZE="1G" TRAN="" VENDOR="" HCTL="" TYPE="part" FSTYPE="swap" LABEL="" UUID="1a0957a1-e122-40a8-a851-32382b0e0d26"
NAME="sda3" MODEL="" SERIAL="" SIZE="8.5G" TRAN="" VENDOR="" HCTL="" TYPE="part" FSTYPE="btrfs" LABEL="rockstor_rockstor" UUID="ece5ed17-0da7-44b9-a8ca-1666da5b4555"
NAME="sdb" MODEL="Virtual disk " SERIAL="" SIZE="1T" TRAN="spi" VENDOR="VMware " HCTL="2:0:1:0" TYPE="disk" FSTYPE="" LABEL="" UUID=""
NAME="sdc" MODEL="Virtual disk " SERIAL="" SIZE="1T" TRAN="spi" VENDOR="VMware " HCTL="2:0:2:0" TYPE="disk" FSTYPE="" LABEL="" UUID=""
NAME="sr0" MODEL="VMware IDE CDR10" SERIAL="10000000000000000001" SIZE="1024M" TRAN="ata" VENDOR="NECVMWar" HCTL="1:0:0:0" TYPE="rom" FSTYPE="" LABEL="" UUID=""
```

The only disk that is showing up on the web console for RockStor is sdc..

**Comment by perezil** [comment]
I believe this may be occurring because VMware Tools is not included with Rockstor. Has anyone installed VMware tools, and if so does this error go away?

**Comment by Frogger666** [comment]
Yes, doesn't go away with only vmtools installed. Tested on vmware player 6.0 & Rockstor 3.6-4.
disk.EnableUUID="true" helped though...

**Comment by cron410** [comment]
The installation documentation should have users run a VMware command to generate a UUID on each VMDK (VHD).
    #vmkfstools -J setuuid /vmfs/volumes/datastore/VM/vm.vmdk

I got it from this Vmware article:
http://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=1021189

**Comment by cron410** [comment]
Nevermind, it appears ESXi automatically generates UUID for each VMDK. Adding the disk.EnableUUID="true" to the .VMX file solved this.

**Comment by agaver** [comment]
Having this issue when installing on a XenServer.
Any ideas?
Thx.

**Comment by nooneusethisname** [comment]
hi how do i add disk.EnableUUID="true" to hyper-v's VM? thanks!

**Comment by phillxnet** [comment]
@nooneusethisname See our following doc entry:

[Quick Start](https://rockstor.com/docs/installation/quickstart.html) - subsection [VMware advisory](https://rockstor.com/docs/installation/quickstart.html#vmware-advisory)

Beyond that pointer ask on our forum here: https://forum.rockstor.com/

Hope that helps.
