### ISSUE TITLE
Wrong kernel loaded after upgrade

### ISSUE THREAD

**Issue by jjlauer** [rockstor/rockstor-core#557]
I recently upgraded from 3.5.0 to 3.5.1 (but failed to edit the upstream CentOS repo beforehand).  Looks like my old kernel 3.10.0-123.13.2.el7.x86_64 continues to be loaded first (its the first menu item for some reason).  I've manually done a "grub2-set-default 1" to get the newer kernel, but after a single reboot, it defaults back to the 3.10 kernel.

Not sure exactly what the right fix is.

**Comment by schakrava** [comment]
I debugged this issue a little today and thanks @imryno! you are spot on.

I'm thinking about using grubby to set the default kernel which lets us deal with kernel paths and hence is consistent.

I've committed the main change, but will probably make more changes before merging the fix. Also, the default kernel will most likely change to 3.18.1 with the next update.

Thanks for helping me fix this issue faster with your contributions @jjlauer @imryno
