### ISSUE TITLE
Support bonded networking

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-core#560]
I tried to set up bonded networking. There were several issues I ran into.

    NetworkManager conflicts with Rockstor and they both try to use different interface names and overwrite each others setting. I just uninstalled NetworkManager with yum.
    Bonded networking adds a file /sys/class/net/bonding_masters which Rockstor tries to enumurate as a network interface and errors out. In system/osi.py network_devices I changed
        devices = os.listdir('/sys/class/net')
    to
        ifpath = '/sys/class/net'
        devices = [name for name in os.listdir(ifpath) if os.path.isdir(os.path.join(ifpath, name))]
    so it only enumerates directories.
    If viewing the interface properties in Rockstor, even if no changes are made and cancel is clicked, Rockstor rewrites the ifcfg file and clobbers the bonding settings

It would be great if Rockstor could fully support bonded networking for either failover or aggregation, but at minimum it should play nicely with a manual setup.

**Comment by schakrava** [comment]
More user feedback to consider

I noticed that the default for the network interfaces is DHCP. I have 2 interfaces on the system, one for internal network testing (no DHCP) and one external with DHCP. I noticed that the Network Manager spams the logs trying to configure this second interface. 
Include an option to manually disable network interfaces, if it is the only active interface have a warning before proceeding.
If the interface cannot be configured after 10 attempts, automatically disable it. This can always be reconfigured later.

**Comment by roweryan** [comment]
If you can't support bonded networking yet, could you give us a way to configure the networking ourselves, so that rockstor doesn't overwrite it?

**Comment by schakrava** [comment]
@roweryan You might want to look at this wiki post on the forum: http://forum.rockstor.com/t/network-management-implementation-details/441

In summary, Rockstor doesn't (and shouldn't) override your custom configuration. It would be great if you get bonding working and share the steps by way of replying to that wiki post on the forum.

**Comment by schakrava** [comment]
Fixed by #1253
