### ISSUE TITLE
ldap service is broken

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-core#564]
code must be iterated over to be more robust. there may be a few different issues.

service toggle doesn't work when there's no config
when there is config, errors, if any are not communicated to the user properly.

**Comment by chrisbrookes** [comment]
+1, I'd like to use Rockstor instead of FreeNAS/other alternatives, but LDAP auth is a high priority.

**Comment by cropse** [comment]
Hi, is that fixed?
I try the LDAP at version 3.9.1 not work, but Introduction is show product-ready.

**Comment by FroggyFlox** [comment]
Closing as fixed by #2235
