### ISSUE TITLE
Redesign snapshot UI for better UX

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-core#573]
There's some offline discussion about this and @sujeetsr will probably layout specific implementation details. But the goal is to provide the ability to manage all snapshots of the system together instead of doing so in each Share's context. This has the benefit of looking at the usage model of the system from a snapshot point of view which can be insightful.

**Comment by cron410** [comment]
My vote is to place the global Snapshot UI in the Storage tab for easy access.
