### ISSUE TITLE
Pool Migration Issue

### ISSUE THREAD

**Issue by baggar11** [rockstor/rockstor-core#577]
I am coming across some errors when trying to use the recently added migration.

Example: Adding 2 disks to a raid1 pool and then trying to move the pool to single or raid0 volume fails.

**Comment by schakrava** [comment]
What is the error message you get?

We don't actually support pool migration from raid1 -> raid0/single. Ideally, the error message should convey that.

**Comment by baggar11** [comment]
The message says "Please select atleast one disk"

I added a 3rd drive to my test. Trying to move from raid1 to Single/Raid0/Raid5 all fail. Will raid1 to raid5/5/10 ever be supported?

**Comment by baggar11** [comment]
After adding another hd to my test rig, I was able to migrate from raid1 to raid10. Will migration to and from raid5/6 be supported in the future?

**Comment by schakrava** [comment]
I think the UI can be improved. It's not clear to the user that 

(1)raid level can only transition from a certain set to the other. These are the supported transitions:
single -> raid0, raid1 and raid10
raid0 -> raid1 and raid10
raid1 -> raid10

(2)raid level can be migrated only when adding disks. Without adding new disks, you cannot proceed. But the error message and UI is confusing.

We'll improve the UI as part of this issue.

Regarding raid5/6, We are continuing to test raid5/6 and hope to include that support soon once things are stable.

**Comment by baggar11** [comment]
Maybe narrow down the choices to user based on starting raid level.

I was under the impression that btrfs itself could do raid5 --> raid1 --> raid6 if need be. Is that something that RockStor will not be supporting or does btrfs itself not support it?

**Comment by schakrava** [comment]
btrfs and hence Rockstor can do that, but right now btrfs behavior is pretty flaky especially with migrations involving raid5/6. That's why the current support for pool migration is pretty conservative.

**Comment by baggar11** [comment]
Understandable. Well here's hoping for more btrfs stability with raid5/6.

**Comment by schakrava** [comment]
Fixed by #596
