### ISSUE TITLE
optimize disk write of service-monitor

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-core#585]
Thanks for becoming a user and welcome to the Rockstor community! There's a service called data collector that collects various metrics like share/pool/cpu/mem usage etc.. and writes to it's database which is on the root disk. For your usecase, you may not want that information being collected all the time. On my home NAS, I always keep it on mostly because I try to stress test every feature.

You can turn off the metric collection as follows

1. On the dashboard, there's a on/off switch under "Metric Collection". It's on the left in the side navbar. You can turn it off there.

2. You can also turn it off from the System -> Services screen. The service name is "Data Collector".

This should help. Let me know how it goes.

**Comment by schakrava** [comment]
Thanks for the answer. The metric collection is turned off ( off as Data collector too) however there is still constant disk access. The disk activity light on the drive blink in a repeated pattern every 3 seconds or so.

**Comment by schakrava** [comment]
Was there a noticeable difference between with/without data collector?

There are other db reads and writes going on, but not that much. You can turn off replication and task scheduler if you are not using them. You could also turn off the service monitor entirely with the command /opt/rockstor/bin/supervisorctl stop service-monitor (turning it off is not supported from the web-ui, but you can turn it back on from the web-ui)

I am curious to find out how much you save, if any with various things turned off. Please share your observations if you can.

Thanks!

**Comment by schakrava** [comment]
No, not a massive difference with the data collector off. 

I have installed iotop to monitor the disk io using flags -ao for cumulative collection of active processes. 

I have turned off all of the services in the services page as well as the data collector. Service monitor is still enabled. Over a 10 minute period, iotop gives:-

Total DISK READ :       0.00 B/s | Total DISK WRITE :     361.13 K/s
Actual DISK READ:       0.00 B/s | Actual DISK WRITE:     683.00 K/s
  TID  PRIO  USER     DISK READ  DISK WRITE  SWAPIN     IO>    COMMAND
 2125 be/4 postgres      0.00 B    149.34 M  0.00 %  7.88 % postgres: rocky smartdb [local] COMMIT
  844 be/4 root          0.00 B     16.14 M  0.00 %  0.13 % [btrfs-transacti]
 2112 be/4 postgres      0.00 B   1276.00 K  0.00 %  0.09 % postgres: checkpointer process
 2116 be/4 postgres      0.00 B      9.47 M  0.00 %  0.00 % postgres: stats collector process
 7820 be/4 root          0.00 B    144.00 K  0.00 %  0.00 % [kworker/u4:0]
 5390 be/4 root          0.00 B   1008.00 K  0.00 %  0.00 % [kworker/u4:1]
29479 be/4 root          0.00 B      2.19 M  0.00 %  0.00 % [kworker/u4:3]
  843 be/4 root          0.00 B    112.00 K  0.00 %  0.00 % [btrfs-cleaner]

Essentially over 10 minutes: 140M of information is being written to the postgres smartdb! That's a lot for a machine doing nothing:)

if I disable the service monitor using - '/opt/rockstor/bin/supervisorctl stop service-monitor' as you suggest and then run iotop for a further 10 minutes I get:-

Total DISK READ :       0.00 B/s | Total DISK WRITE :       0.00 B/s
Actual DISK READ:       0.00 B/s | Actual DISK WRITE:       0.00 B/s
  TID  PRIO  USER     DISK READ  DISK WRITE  SWAPIN     IO>    COMMAND
  844 be/4 root          0.00 B      9.23 M  0.00 %  0.11 % [btrfs-transacti]
 2112 be/4 postgres      0.00 B    540.00 K  0.00 %  0.04 % postgres: checkpointer process
 2116 be/4 postgres      0.00 B      6.72 M  0.00 %  0.00 % postgres: stats collector process
 7820 be/4 root          0.00 B    448.00 K  0.00 %  0.00 % [kworker/u4:0]
29479 be/4 root          0.00 B    384.00 K  0.00 %  0.00 % [kworker/u4:3]

So, the main culprit has disappeared! Much more reasonable. 

I'm curious though as to why there should be 9M of btrfs transactions for an idle machine. That might still stop the drive going into suspend mode.

**Comment by javahaxxor** [comment]
I'm also experiencing the high I/O on the system disk, postgres writing around 300kb/s .. Service monitor could not be stopped from the web ui, had to kill it from the console, now I/O is adequate

**Comment by schakrava** [comment]
Thanks @javahaxxor . service monitor needs improvement. We hope to get to it sooner than later.

**Comment by Lennie** [comment]
To get that last bit of PostgreSQL to write less I have a suggestion:

PostgreSQL writes a stats file for the auto I believe: pgstat.stat
http://www.postgresql.org/docs/9.3/static/monitoring-stats.html

Maybe you can increase the time between writes by increasing autovacuum_naptime
http://www.postgresql.org/docs/9.3/static/runtime-config-autovacuum.html

**Comment by therealprof** [comment]
I do see the exact same behaviour and disabling the service monitor sufficiently addresses that. For me this is a huge problem since I'm booting and running the system from SD card which is going to break very swiftly with a constant writing of a few hundred kB/s.

**Comment by schakrava** [comment]
Thanks for the comment @therealprof . I've made this issue high priority and would like to fix it no later than the next couple of releases.
