### ISSUE TITLE
network widget scale seems wrong

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-core#589]
The network widget seems to show wrong numbers.
Here is a screenshot of the network widget while performing a backup from two machines to rockstor:
https://www.dropbox.com/s/v67ijuqtg7hs9hf/Schermafdruk%202015-02-07%2016.09.03.jpg?dl=0

Perhaps I am looking at this graph wrong, but I am fairly certain my network does not support 67gigabyte/second transfers!

**Comment by iFloris** [comment]
Thanks for opening an issue.
My machine is an intel SSR212MC2, with a S5000PSL server board using two Intel 82563EB onboard NICs.

**Comment by MFlyer** [comment]
Hi @schakrava , can we close this?? Actually on my env charts seem ok

M.

**Comment by MFlyer** [comment]
Already fixed over #1457 @schakrava , we can close it

Mirko

**Comment by MFlyer** [comment]
@schakrava this can be closed
M.

**Comment by FroggyFlox** [comment]
Closing this as seems to be confirmed fixed above.
