### ISSUE TITLE
Feature: Linux 3.19 Release Support for Fast Replacement

### ISSUE THREAD

**Issue by baggar11** [rockstor/rockstor-core#593]
When available in CentOS, add GUI support for fast replacement.

---

Btrfs has added a explicit device replacement operation which is much faster:

**Comment by phillxnet** [comment]
@schakrava I propose we close this issue as a duplicate of #1611 as it has more current info and is linked to from the forum. Also we have a rogue commit linking to this issue.
@baggar11 I hope you are OK with this suggestion. My fault as I hadn't previously noticed this issue.

**Comment by baggar11** [comment]
Yeah, no problem.
