### ISSUE TITLE
more than two drives for RAID1

### ISSUE THREAD

**Issue by erazortt** [rockstor/rockstor-core#594]
It is sometimes usefully for data security reasons to be able to have more then two drives in a mirror setup. btrfs is able to do this, I assume it is just the webfrontend which does not permit one to do so.

**Comment by schakrava** [comment]
@erazortt Having more than 2 drives in a raid1 pool is indeed supported. Is your Rockstor updated? The latest version is 3.6-4. If you are running the latest and get an error while creating raid1 pool, let us know.

**Comment by iFloris** [comment]
This works fine, I have 6 drives in raid 1 now for testing.

**Comment by erazortt** [comment]
Oh sorry, my fault. I had checked this a time ago but havn't tried it again. You guys seem to working a quite some pace. :)
