### ISSUE TITLE
add support for UPS 

### ISSUE THREAD

**Issue by erazortt** [rockstor/rockstor-core#595]
This is quite an important topic for serious NAS. I do not know much about it, but other projects use the Network UPS Tools, which should very easily be integrable.

**Comment by schakrava** [comment]
Thanks for filing the issue. If you can experiment with Network UPS Tools and provide some insight, it could speed up development. Thanks!

**Comment by erazortt** [comment]
Ok I will try to install it on some linux setup during the weekend and see how it works.

**Comment by erazortt** [comment]
Ok so things are really easy. I just followd this guide:
http://luzem.dyndns.org/2015/01/25/install-ups-in-centos-7/comment-page-1/

**Comment by erazortt** [comment]
There is also the EPEL package nut-cgi, which adds some GSI scripts for monitoring. I would guess these are not the top priority though.

**Comment by phillxnet** [comment]
I have set myself the task of integrating/adding nut into Rockstor as a getting started exercise, but I struggle for time.  I am quite familiar with NUT and linux though.  I am however unfamiliar with many of Rockstor's technologies / languages.  So fingers crossed.  I hope not to duplicating anyone's efforts but I have only just found this issue and just now getting setup / started.  Please comment with any pointers.

@erazortt  yes usbhid-ups is a good first bet and I intended to offer it as a first suggestion but the nut package comes with them all anyway and they are each only tiny.

For my own itch / requirement I first have to implement netclient mode to a nut server (even easier to setup) so hoping that should help ease me in.

**Comment by phillxnet** [comment]
I am currently working on this issue and have the following proposal:-
Start out with an entry form akin to what we currently have in snmp only larger, this is not particularly friendly but will serve as a starting point to get the other mechanisms in place. Nut in is't various capacities involves tying 5 to 6 config files together and can work in 4 different modes so it would be nice to have a reactive input form such as we see now in tasks where only appropriate info is presented to the user upon an overarching selection (the mode). But I think it's worth doing a basic (dumb) interface to start with and build that up in co-operation with community requests / suggestions. I hope to extend the config form to have a scan button (using nut-scanner) to enable auto fill of what info we can get from that method. This will simplify the form entry yet still allow for customization and cancel of auto details that may have overwritten previous form contents.
I think at a later date the addition of a nut ups info section akin to what we have re s.m.a.r.t data would be nice however a simply python binding retrieval of model / load will suffice initially. This could also be used to add an additional fancy widget to the dashboard on pus load / battery charge. Global exceptions should be raised to alert users of OB (On Battery) status, these could be displayed as warnings above all pages using the existing warning system. Also email notifications on the same and on the return of Line Power if this is before shutdown occurs.

**Comment by phillxnet** [comment]
@erazortt Thanks for opening this issue, as of release 3.8-8 we now have at least a beta implementation of a nut configuration component in place. In time it is planned to improve on this feature and improve especially on the ups status info but going forward I think it's best that individual issues for nut be raised for problems as they are defined. I you are not comfortable with closing this issue or finding it closed then please comment and or reopen.
@schakrava I think we can close this now as fixed by pull request #892 .

**Comment by schakrava** [comment]
Very happy to close this issue! There will be improvements no doubt, but thanks for contributing this feature @phillxnet
