### ISSUE TITLE
RockStor ISO Torrent Download Option

### ISSUE THREAD

**Issue by baggar11** [rockstor/rockstor-core#597]
Can we get a torrent option for download? The Sourceforge downloads have been hit and miss for a couple months now. I've been trying to grab the latest ISO without issue. All mirrors stop downloading at 312MB for some reason.

**Comment by schakrava** [comment]
torrent option sounds like a great idea. I'll look into it. It's surprising that sourceforge has been unreliable. Thanks for bringing it to our attention.

**Comment by baggar11** [comment]
Lots of "We are back at full capacity" messages for a while.

https://twitter.com/sfnet_ops

**Comment by schakrava** [comment]
@baggar11 Try downloading from this torrent. I just started seeding it.

http://rockstor.com/Rockstor-3.5-5.iso.torrent

**Comment by baggar11** [comment]
Thanks, I'll seed for a while.

**Comment by baggar11** [comment]
Will this be added as a download option on the website?

**Comment by schakrava** [comment]
Yes and hopefully soon.

**Comment by freeurmind** [comment]
Also consider add zsync file distribution at server side : -)

**Comment by schakrava** [comment]
Ok, so The latest iso (3.8-0) is available for last week or so as a torrent file. I've been seeding it with the Transmission Rock-on from one of my Rockstor boxes. I'd appreciate more seeders, especially if you can do it with the Transmission Rock-on :)

Website's been updated.

**Comment by baggar11** [comment]
Thanks, I just grabbed the ISO and will be seeding it.
