### ISSUE TITLE
discover root disk label dynamically

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-core#603]
Right now, it's hard coded to rockstor_rockstor and it's effecting users that install rockstor on centos.

**Comment by Hooverdan96** [comment]
@phillxnet I think this not a problem anymore? At least I have not seen any issues for users that have installed Rockstor on top of Vanilla OpenSUSE so far. If that's correct, this can probably be closed?

**Comment by bigfoot90** [comment]
People didn't install it because of complicated and problematic procedure installation like this. 
They have found another solution.
