### ISSUE TITLE
Feature request: Auto update for Rockstor

### ISSUE THREAD

**Issue by iFloris** [rockstor/rockstor-core#605]
Request for consideration: 
The option to set an auto update schedule for Rockstor, so that users may always use the latest and greatest version.
This is similar to what Synology is doing in their DSM 5.1.x software.

Is this something that seems suitable to Rockstor?

**Comment by schakrava** [comment]
Thanks for creating this issue. We have similar plans and this came at a good time.

**Comment by schakrava** [comment]
Can't seem to find the pull request for this one, I think it got done as part of another issue a few months ago. Users can auto update their Rockstor systems via the Web-UI.
