### ISSUE TITLE
Feature : webUI - allows user to setup SSH public key

### ISSUE THREAD

**Issue by freeurmind** [rockstor/rockstor-core#608]
It would be nice to have webUI allowing user to upload or copy/paste their SSH public key, once ~/.ssh/authorized_keys in position, it would be easier to login Rockstor via terminal.

**Comment by schakrava** [comment]
This is already supported. You can supply the public key when you create a user or as part of edit. The field is called "Public Key" as you can see in the attached picture

![user_add](https://cloud.githubusercontent.com/assets/1123552/7243524/ff2be5a8-e782-11e4-870e-1eca57b2c07b.png)

**Comment by freeurmind** [comment]
@schakrava Bravo, your work is appreciated!

**Comment by schakrava** [comment]
Cool. @freeurmind Are you on our forums(http://rockstor.com/forums)? I encourage you to participate. Also, feel free to email me(suman@rockstor.com) with your ideas and feedback.
