### ISSUE TITLE
AFP export doesn't expand when underneath share (subvolume in btrfs) expands

### ISSUE THREAD

**Issue by freeurmind** [rockstor/rockstor-core#614]
Reproduce steps:
1. Create a 10GB share (subvolume) in btrfs
2. Export this 10GB share (subvolume) thru AFP
3. Mount 10GB share, df -h shows 10GB free space
1. Expand above share (subvolume) to 20GB in btrfs
2. Mount share, df -h still shows 10GB
3. You will have to delete/ re-create the AFP share to get the Mac see 20GB free space

**Comment by schakrava** [comment]
Thanks for opening this issue

**Comment by freeurmind** [comment]
Did a quick "dd" test on 1GB subvolume/share, expanded to 2GB, able to write 1.5GB file via AFP, which shows you are correct, it should merely be an issue of wrong reporting.

The reason I noticed this is because my Time Machine backup constantly fails complaining not enough free space, caught the wrong reporting during regular check. The problem is gone after I expanded subvolume and re-created AFP share.

**Comment by freeurmind** [comment]
Turns out "df -h" gives whatever it is in "vol size limit = xxx" on each share in /etc/afp.conf

So the issue is, "vol size limit = xxx" in /etc/afp.conf doesn't get updated after btrfs subvolume expands. I did try to remove this line on specific subvolume, "df -h" instead gives free space on /, which is not what we want either.

**Comment by schakrava** [comment]
Cool. You practically solved this for us. It's just a matter of coding it up. Thanks!

**Comment by sambucka** [comment]
I had a similar issue. Created pool, created share (it defaulted to 1GB soft limit). Created AFP share. Mounted AFP and it showed 1TB volume, also it showed 1TB after opening TimeMachine, but once backup was started it errored out that there is not enough space (1GB available only). I have deleted the share and recreated with soft limit of 1TB and was able to backup with TimeMachine.

**Comment by phillxnet** [comment]
@sambucka Thanks for the confirmation on this one.
