### ISSUE TITLE
Change how to enter the "Task Frequency" on the "Add a new schedule task" page

### ISSUE THREAD

**Issue by Zoltrex** [rockstor/rockstor-core#619]
Is it possible to either have a check box and you pick what you would want like:
Dynamic choices:
_seconds
_days
_weeks
_month
Static choices:
_bi-annual
_year

**Comment by cron410** [comment]
Seconded. Bigtime!

**Comment by schakrava** [comment]
@Zoltrex @cron410 Thanks for providing your input on this issue. We made scheduling tasks much better in the latest 3.8-4 update. You can select minutes, hours, by week, by month and more with the new simple interface. Let us know if you have any more feedback.

Fixed by #728
