### ISSUE TITLE
rockstor.service dies

### ISSUE THREAD

**Issue by javahaxxor** [rockstor/rockstor-core#620]
Rockstor service dies. Luckily AFP and NFS services are still up. How does one trace what happens ?

[root@NAS ~]# systemctl status rockstor
rockstor.service - RockStor startup script
   Loaded: loaded (/etc/systemd/system/rockstor.service; enabled)
   Active: inactive (dead) since Sun 2015-03-08 20:32:31 CET; 3 days ago
 Main PID: 1745 (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/rockstor.service

Mar 01 00:08:17 NAS supervisord[1745]: 2015-03-01 00:08:17,102 INFO success: nginx entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
Mar 01 00:08:17 NAS supervisord[1745]: 2015-03-01 00:08:17,102 INFO success: gunicorn entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
Mar 08 20:32:31 NAS systemd[1]: Stopping RockStor startup script...
Mar 08 20:32:31 NAS supervisord[1745]: 2015-03-08 20:32:31,403 WARN received SIGTERM indicating exit request
Mar 08 20:32:31 NAS supervisord[1745]: 2015-03-08 20:32:31,416 INFO waiting for gunicorn, nginx, smart_manager, service-monitor to die
Mar 08 20:32:31 NAS supervisord[1745]: 2015-03-08 20:32:31,417 INFO exited: smart_manager (terminated by SIGTERM; not expected)
Mar 08 20:32:31 NAS supervisord[1745]: 2015-03-08 20:32:31,417 INFO stopped: service-monitor (terminated by SIGTERM)
Mar 08 20:32:31 NAS supervisord[1745]: 2015-03-08 20:32:31,726 INFO exited: gunicorn (exit status 0; expected)
Mar 08 20:32:31 NAS supervisord[1745]: 2015-03-08 20:32:31,753 INFO exited: nginx (exit status 0; expected)
Mar 08 20:32:31 NAS systemd[1]: Stopped RockStor startup script.

**Comment by schakrava** [comment]
Is it reproducible? If so, let us know the steps.

Also, please tar and email /opt/rockstor/var/log directory or paste relevant lines in the logs here.

**Comment by javahaxxor** [comment]
It hasn't happened in the last 56 days , but if it does, I'll paste the logs

**Comment by schakrava** [comment]
OK, closing for now.
