### ISSUE TITLE
Ajax-Loader.gif does not dissappear

### ISSUE THREAD

**Issue by cron410** [rockstor/rockstor-core#623]
I have not figured out what is causing this loading icon to persist on top of every page. It seems to be completely random. I am using Chrome in Incognito mode if that helps.
![image](https://cloud.githubusercontent.com/assets/3082899/6680035/242bdfdc-cc28-11e4-9501-bc592f5fc310.png)

**Comment by Mchakravartula** [comment]
I have tested couple of times to reproduce the issue mentioned above but the loading icon disappears as expected. Could you please include the steps to reproduce the issue you are experiencing?

**Comment by cron410** [comment]
I cannot. It appears on some of my computers running Windows 8.1 using the latest Chrome. It does not appear on any Windows 7 machines.

**Comment by phillxnet** [comment]
@cron410 Do you still have this problem as I think @gkadillak has done a bunch of changes since March but I'm not sure it they would affect this behaviour? Ie does it still happen for you in the latest testing release and if so how to reproduce, otherwise it's tricky to approach / confirm a fix. Thanks.

I know a way back when I would see this often myself a browser refresh would sort it so not sure if that helps anyone. It is a great deal less common for me now but I am only on linux with chrome and firefox.

**Comment by neoeny152** [comment]
I'm having this problem myself. I'd be glad to help by giving someone access to my box and showing how I reproduce it. My Rockstor box is just a test box so I don't mind giving full access to it for someone that is trying to help resolve issues. 

I'm running 3.8-9.03 and I access the GUI via Chrome within Windows 10. It happens fairly often, but not all the time. Let me know if someone would like to access my machine to work on this. - FYI I'm brand new to Rockstor and Github.

**Comment by schakrava** [comment]
Thanks for the offer @neoeny152 . I now have a decent idea why it's happening. I may take up on your offer. Are you able to reproduce the behavior consistently? If so, could you list the steps to reproduce?

**Comment by neoeny152** [comment]
Yes I'm able to reproduce it pretty consistently, pretty much every time I tinker around with the box. What I've noticed that causes it the most is if I go to another tab for a while and come back to rockstor, then the loader gif is there and I can't get it to go away unless I do a full refresh.

**Comment by schakrava** [comment]
@priyaganti  -- I am 90% sure the problem is triggered when we have the gif displayed in a view pending an ajax/api call, and the user switches to another view. In such a scenario, we need to ensure the gif is removed in the view's cleanup call.
