### ISSUE TITLE
WebUI needs to wait for background services to start

### ISSUE THREAD

**Issue by cron410** [rockstor/rockstor-core#624]
Directly after a reboot, it appears at least one service that runs the authentication for the WebUI seems to be starting slowly, or late. The login screen loads, but I cannot log in for at least 30 seconds. During which time I am wondering if I am typing the correct password. The WebUI should probably give some kind of informational warning that it is waiting for certain background services to start.

**Comment by phillxnet** [comment]
@cron410 I haven't seen this myself but I know there have been a number of  changes quite recently on how rockstor starts up, ie leaveraging systemd more. Hopefully this has improved things for you in this regard. Could you let us know if you are still affected by this issue. Thanks.

Good call though as it's the kind of off putting thing that's nice to avoid.

**Comment by schakrava** [comment]
This behavior has been updated by serializing services with systemd in 3.8-9. Once the rockstor.service is up, it can handle Web-UI authentiation. So even while rockstor-bootstrap is still activating, it doesn't slow down or prevent Web-UI logins.

Thanks for reporting this issue, and feel free to re-open if the issue still exists.
