### ISSUE TITLE
Installation as Xen guest fail

### ISSUE THREAD

**Issue by HTPC-Schrauber** [rockstor/rockstor-core#628]
I tried to install Rockstor as a Xen guest. This fails while installing. The message was, that package lvm2 is missing.

Here is the bug report created by rockstor:
https://owncloud.galantgdi.de/index.php/s/69njhUhcRzlpZq9

**Comment by schakrava** [comment]
@HTPC-Schrauber Thanks for sending the bug report. When we burn the next iso, we can include the lvm2 package with it.

I haven't played with Xen in a while. Can you point me to instructions on how your setup is? I'd like to reproduce the problem and go from there. Thanks!

**Comment by HTPC-Schrauber** [comment]
My host runs on Ubuntu Server 15.04 with Xen 4.5. You can simply install Ubuntu Server. Then add the package xen-hypervisor and your Xen host is up and running.

For easier management I have installed libvirt and Archipel as WebGUI.

I can give you a simple step by step guide how to set this up. But this is a draft at this time.

**Comment by schakrava** [comment]
Thank you. I'll give these steps a try. But yeah, more information you provide, the faster it would be for us to get going on this. I suspect there may be issues beyond just including lvm2 package in the iso, so it would be good to validate it all the way through.

**Comment by HTPC-Schrauber** [comment]
OK here you go. How I said this guide is a draft. So maybe some steps are missing.

- Ubuntu Server 15.04 + OpenSSH (hostname in this guide is xenhost)
- sudo apt-get install bridge-utils
- sudo apt-get update
- sudo apt-get dist-upgrade
- extend /etc/network/interfaces with bridge xenbr0 
- sudo apt-get install xen-hypervisor
- configure /etc/default/grub.d/xen.cfg:
#XEN_OVERRIDE_GRUB_DEFAULT=0
XEN_OVERRIDE_GRUB_DEFAULT=1

- sudo update-grub
- reboot
- sudo xl info (should show infos about Xen)
- sudo xl list (should show Domain-0)
- sudo apt-get install build-essential
- sudo apt-get install libvirt-bin
- sudo nano /etc/libvirt/libvirt.conf
#uri_default = "qemu:///system"
uri_default = "xen:///"

- sudo virsh version
Kompiliert gegen die Bibliothek: libvirt 1.2.2
Verwende Bibliothek: libvirt 1.2.2
Verwende API: Xen 1.2.2
Laufender Hypervisor: Xen 4.4.0

- sudo apt-get install python-libvirt
- sudo apt-get install python-imaging
- sudo apt-get install python-numpy
- sudo apt-get install python-sqlalchemy
- sudo apt-get install python-apscheduler
- sudo apt-get install python-setuptools
- sudo apt-get install ejabberd
- sudo apt-get install python-dev
- sudo apt-get install apache2
- sudo su
- replace ejabberd.yml with the one found in the Archipel wiki
- replace FQDN in ejabberd.yml with hostname

- openssl req -new -x509 -newkey rsa:1024 -days 3650 -keyout /etc/ejabberd/privkey.pem -out /etc/ejabberd/ejabberd.pem
- openssl rsa -in /etc/ejabberd/privkey.pem -out /etc/ejabberd/privkey.pem
- cat /etc/ejabberd/privkey.pem >> /etc/ejabberd/ejabberd.pem
- rm /etc/ejabberd/privkey.pem
- service ejabberd stop
- service ejabberd start
- ejabberdctl status
- ejabberdctl register admin xenhost PASSWORD
- exit
- cd ~
- wget http://nightlies.archipelproject.org/latest-archipel-agent.tar.gz
- tar xvzf ../latest-archipel-agent.tar.gz
- sudo cp -r ./ArchipelAgent /opt/
- cd /opt/ArchipelAgent/
- sudo ./buildAgent -d
- sudo easy_install PIL
- sudo archipel-initinstall
- edit /etc/archipel/archipel.conf
machine_ip                  = xenhost
libvirt_uri                 = xen:///

- sudo archipel-tagnode --jid=admin@xenhost --password=YOURPASSWORD --create
- sudo archipel-rolesnode --jid=admin@xenhost --password=YOURPASSWORD --create
- sudo archipel-adminaccounts --jid=admin@xenhost --password=YOURPASSWORD --create
- sudo service archipel start
- sudo update-rc.d archipel defaults 25

- cd ~
- wget http://nightlies.archipelproject.org/latest-archipel-client.tar.gz
- mkdir ArchipelClient
- cd ArchipelClient
- tar xvzf ../latest-archipel-client.tar.gz
- sudo cp -r ./Archipel /var/www/html/

- http://xenhost/Archipel

- click on + in the lower left and add contact "xenhost@xenhost"
- create some VMs


And here is the ejabberd.yml:
`###
###             ejabberd configuration file
###         Archipel Sample default condiguration

###     =========
###     DEBUGGING

loglevel: 3

###     ================
###     SERVED HOSTNAMES

# Change it for you FQDN
hosts:
    - "xenhost"

###     ===============
###     LISTENING PORTS

listen:

## If you have compiled the ejabberd-xmlrpc, uncomment the following line

    #-
    #   #ip : 127.0.0.1
    #   port: 4560
    #   module: ejabberd_xmlrpc
    #   #timeout: 30000
    #   #maxsessions: 20
    #   access_commands:
    #         xmlrpcaccess:
    #             all : []

## ejabberd c2s
    -
        port: 5222
        module: ejabberd_c2s
        ##
        ## If TLS is compiled in and you installed a SSL
        ## certificate, specify the full path to the
        ## file and uncomment this line:
        ##
        ## certfile: "/etc/ejabberd/ejabberd.pem"
        ## starttls: true
        max_stanza_size: 65536000
        shaper: c2s_shaper
        access: c2s

## ejabbed s2s
    -
        port: 5269
        module: ejabberd_s2s_in
        max_stanza_size: 65536000

## ejabberd http/s (BOSH)
    -
        port: 5280
        module: ejabberd_http
        ##
        ## If TLS is compiled in and you installed a SSL
        ## certificate, specify the full path to the
        ## file and uncomment this line:
        ##
        ## certfile: "/etc/ejabberd/ejabberd.pem"
        ## tls: true
        web_admin: true
        http_poll: true
        http_bind: true



###     ===
###     S2S

s2s_use_starttls: optional

s2s_certifile: "/etc/ejabberd/ejabberd.pem"

## domain_certfile: Specify a different certificate for each served hostname.
##
## host_config:
##   "example.org":
##     domain_certfile: "/path/to/example_org.pem"
##   "example.com":
##     domain_certfile: "/path/to/example_com.pem"

s2s_policy: s2s_access

###     ==============
###     AUTHENTICATION

auth_method: internal

###     ===============
###     TRAFFIC SHAPERS

shaper:
  ##
  ## The "normal" shaper limits traffic speed to 1000 B/s
  ##
  normal: 1000

  ##
  ## The "fast" shaper limits traffic speed to 50000 B/s
  ##
  fast: 50000

###     ====================
###     ACCESS CONTROL LISTS

acl:

    admin:
        user:
            - "admin": "xenhost"

    local:
        user_regexp:
            - []


###     ============
###     ACCESS RULES

access:

    max_user_sessions:
        all: 10

    local:
        local: allow

    c2s:
        blocked: deny
        all: allow

    c2s_shaper:
        admin: none
        all: fast

    s2s_shaper:
        all: fast

    announce:
        admin: allow

    configure:
        admin: allow

    muc_admin:
        admin: allow

    muc_create:
        local: allow

    muc:
        all: allow

    pubsub_createnode:
        all: allow

    register:
        all: allow

    xmlrpcaccess:
        admin : allow

### Frequency of account registration
registration_timeout: infinity

###     ================
###     DEFAULT LANGUAGE

language: "en"

###     =======
###     MODULES

modules:

    mod_adhoc: []

    mod_announce:
        access: announce

    mod_caps: []

    mod_configure: []

    mod_disco: []

    mod_http_bind:
        max_inactivity: 400 # timeout valie for BOSH usefull for a large number of VM

    mod_irc: []

    mod_last: []

    mod_muc:
        access: muc
        access_create: muc_create
        access_persistent: muc_create
        access_admin: muc_admin

    mod_offline: []

    mod_privacy: []

    mod_private: []

    mod_pubsub:
        access_createnode: pubsub_createnode
        ignore_pep_from_offline: true
        last_item_cache: false
        max_items_node: 1000
        plugins:
            - "flat"
            - "hometree"
            - "pep"

    mod_register:
        access: register

    mod_roster: []

    mod_shared_roster: []

    mod_time: []

    mod_vcard: []

    mod_version: []

    mod_admin_extra: []
`

**Comment by HTPC-Schrauber** [comment]
Here an additional info in configuring Archipel:
In newer versions of Archipel the client tries to connect to the XMPP server through websocket. This failes when configured with the upper steps.
One must change the XMPP URL from ws:/HOSTNAME:5280/xmpp to http://HOSTNAME:5280/http-bind by hand.

**Comment by schakrava** [comment]
@HTPC-Schrauber really appreciate all the additional info.

**Comment by schakrava** [comment]
@HTPC-Schrauber It took me a while to work on this, but finally I have some good news to share. First off, thanks a lot for detailed instructions. It was very helpful. However, I ran into problems with Archipel. I couldn't get the hypervisor online. Then I tried virt-manager and saw the lvm dependency problem. The good news is that in new iso, these dependencies are fixed and I was able to install and test it a bit on Xen with virt-manager.

The new iso(3.7-9 or later) should be out shortly and I'll add a comment when it is ready for you to download and confirm.

**Comment by phillxnet** [comment]
@schakrava So are we awaiting @HTPC-Schrauber  confirmation / satisfaction there?

**Comment by schakrava** [comment]
@phillxnet yes. or if anyone else can confirm, that would be great as well.

**Comment by schakrava** [comment]
Closing the issue. Feel free to add a comment and we'll reopen if needed.

**Comment by HTPC-Schrauber** [comment]
Sorry for the late answer. I got twins in may. Therefor I was somewhat bussy last time ;)

I tried the 3.8 ISO. Installation now works fine under xen. Many thanks.

**Comment by schakrava** [comment]
Congrats! Thanks for confirming. Also, please join our forum: http://forum.rockstor.com
