### ISSUE TITLE
Certain RAID levels prevent adding/removing disks in odd ways

### ISSUE THREAD

**Issue by Hell-Fire** [rockstor/rockstor-core#629]
Was playing around a little in a testing setup, and came across adding and removing drives in a raid10 config needing to be done in even ways.  BTRFS has no requirement for drives to need to be added in pairs, as the RAID is applied to chunks, not to disks.  Seems completely arbitrary to require even numbers of disks, or add/remove things in pairs, when a rebalance on a single disk added or removed will redistribute the data to best use it.

**Comment by freeurmind** [comment]
Agree, BTRFS RAID works on chunk level not disk level. My comment in issue 621 vaguely mentioned this, there are also arbitrary requirement in web-ui regarding free space when attempting to remove a disk or convert RAID level. For now to get the most of BTRFS RAID, I would suggest user to get hands dirty & play with CLI.

**Comment by schakrava** [comment]
Here's a well defined issue that will address concerns from this issue: #747
