### ISSUE TITLE
Update not working on slow media

### ISSUE THREAD

**Issue by therealprof** [rockstor/rockstor-core#641]
I tried to use the update feature in the UI to go from 3.6-7 to 3.7-5 but it didn't work. I tried to watch the process on the CLI but it seems that the synch call to yum simply couldn't finish in the anticipated time due to a slow download process (I blame the SD card but could also be the server, definitely not the connection). Manually updating via yum worked albeit also very slowly.

**Comment by therealprof** [comment]
I found out that the reason for the abort is something entirely differently:

```
Loaded plugins: changelog, fastestmirror
Loading mirror speeds from cached hostfile
 * base: ftp.plusline.de
 * extras: ftp.plusline.de
 * updates: ftp.plusline.de
Resolving Dependencies
--> Running transaction check
---> Package perl.x86_64 4:5.16.3-283.el7 will be updated
---> Package perl.x86_64 4:5.16.3-285.el7 will be an update
--> Processing Dependency: perl(Time::HiRes) for package: 4:perl-5.16.3-285.el7.x86_64
---> Package perl-libs.x86_64 4:5.16.3-283.el7 will be updated
---> Package perl-libs.x86_64 4:5.16.3-285.el7 will be an update
---> Package perl-macros.x86_64 4:5.16.3-283.el7 will be updated
---> Package perl-macros.x86_64 4:5.16.3-285.el7 will be an update
--> Running transaction check
---> Package perl-Time-HiRes.x86_64 4:1.9725-3.el7 will be installed
--> Processing Dependency: /bin/perl for package: 4:netatalk-3.1.6-0.0.1.el2.x86_64
--> Finished Dependency Resolution
Error: Package: 4:netatalk-3.1.6-0.0.1.el2.x86_64 (@rockstor)
           Requires: /bin/perl
           Removing: 4:perl-5.16.3-283.el7.x86_64 (@anaconda/3)
               Not found
           Updated By: 4:perl-5.16.3-285.el7.x86_64 (base)
               Not found
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

**Comment by iFloris** [comment]
My system was having the same problem.
AFP would not start at all.
Doing 'yum update rockstor’ to get to 3.7-9 seems to have fixed the problem for me.

Kind regards,

Floris van Lint

Op 22 mei 2015 bij 10:06:48, therealprof (notifications@github.com) schreef:

I found out that the reason for the abort is something entirely differently:

Loaded plugins: changelog, fastestmirror
Loading mirror speeds from cached hostfile
 * base: ftp.plusline.de
 * extras: ftp.plusline.de
 * updates: ftp.plusline.de
Resolving Dependencies
--> Running transaction check
---> Package perl.x86_64 4:5.16.3-283.el7 will be updated
---> Package perl.x86_64 4:5.16.3-285.el7 will be an update
--> Processing Dependency: perl(Time::HiRes) for package: 4:perl-5.16.3-285.el7.x86_64
---> Package perl-libs.x86_64 4:5.16.3-283.el7 will be updated
---> Package perl-libs.x86_64 4:5.16.3-285.el7 will be an update
---> Package perl-macros.x86_64 4:5.16.3-283.el7 will be updated
---> Package perl-macros.x86_64 4:5.16.3-285.el7 will be an update
--> Running transaction check
---> Package perl-Time-HiRes.x86_64 4:1.9725-3.el7 will be installed
--> Processing Dependency: /bin/perl for package: 4:netatalk-3.1.6-0.0.1.el2.x86_64
--> Finished Dependency Resolution
Error: Package: 4:netatalk-3.1.6-0.0.1.el2.x86_64 (@rockstor)
           Requires: /bin/perl
           Removing: 4:perl-5.16.3-283.el7.x86_64 (@anaconda/3)
               Not found
           Updated By: 4:perl-5.16.3-285.el7.x86_64 (base)
               Not found
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**Comment by therealprof** [comment]
That's only a workaround because it will only update that single package but not the rest of the system including the rest of the rockstor owned/modified packages; also future updates from the GUI will not be possible.

**Comment by iFloris** [comment]
Well, goes to show what I know.
Now I think I have to reinstall and update from gui.
Thanks for the heads up :+1:

**Comment by freeurmind** [comment]
Since I added more other repos to Rockstor in order to get some utilities I want, seeing similar package dependency issue doesn't prove a bug in Rockstor, as here more other users reported this issue, I'd like to report mine.

```
~  ᐅ yum update
Loaded plugins: changelog, fastestmirror
base                                                                                                                                        | 3.6 kB  00:00:00
epel/x86_64/metalink                                                                                                                        | 4.6 kB  00:00:00
extras                                                                                                                                      | 3.4 kB  00:00:00
nux-dextop                                                                                                                                  | 2.9 kB  00:00:00
rockstor                                                                                                                                    | 2.9 kB  00:00:00
updates                                                                                                                                     | 3.4 kB  00:00:00
Loading mirror speeds from cached hostfile
 * base: mirrors.163.com
 * epel: mirror01.idc.hinet.net
 * extras: mirrors.pubyun.com
 * nux-dextop: li.nux.ro
 * updates: mirrors.pubyun.com
Resolving Dependencies
--> Running transaction check
---> Package btrfs-progs.x86_64 0:3.18-1.el2 will be updated
---> Package btrfs-progs.x86_64 0:4.0-1.el2 will be an update
---> Package kernel-ml.x86_64 0:4.0.2-1.el7.elrepo will be installed
---> Package perl.x86_64 4:5.16.3-283.el7 will be updated
---> Package perl.x86_64 4:5.16.3-285.el7 will be an update
--> Processing Dependency: perl(Time::HiRes) for package: 4:perl-5.16.3-285.el7.x86_64
---> Package perl-libs.x86_64 4:5.16.3-283.el7 will be updated
---> Package perl-libs.x86_64 4:5.16.3-285.el7 will be an update
---> Package perl-macros.x86_64 4:5.16.3-283.el7 will be updated
---> Package perl-macros.x86_64 4:5.16.3-285.el7 will be an update
---> Package rockstor.x86_64 0:3.7-8 will be updated
---> Package rockstor.x86_64 0:3.7-9 will be an update
--> Running transaction check
---> Package perl-Time-HiRes.x86_64 4:1.9725-3.el7 will be installed
--> Processing Dependency: /bin/perl for package: 4:netatalk-3.1.6-0.0.1.el2.x86_64
--> Finished Dependency Resolution
Error: Package: 4:netatalk-3.1.6-0.0.1.el2.x86_64 (@rockstor)
           Requires: /bin/perl
           Removing: 4:perl-5.16.3-283.el7.x86_64 (@anaconda/3)
               Not found
           Updated By: 4:perl-5.16.3-285.el7.x86_64 (base)
               Not found
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

~  ᐅ yum upgrade --skip-broken
Loaded plugins: changelog, fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrors.163.com
 * epel: mirror01.idc.hinet.net
 * extras: mirrors.pubyun.com
 * nux-dextop: li.nux.ro
 * updates: mirrors.pubyun.com
Resolving Dependencies
--> Running transaction check
---> Package btrfs-progs.x86_64 0:3.18-1.el2 will be updated
---> Package btrfs-progs.x86_64 0:4.0-1.el2 will be an update
---> Package kernel-ml.x86_64 0:4.0.2-1.el7.elrepo will be installed
---> Package perl.x86_64 4:5.16.3-283.el7 will be updated
---> Package perl.x86_64 4:5.16.3-285.el7 will be an update
--> Processing Dependency: perl(Time::HiRes) for package: 4:perl-5.16.3-285.el7.x86_64
---> Package perl-libs.x86_64 4:5.16.3-283.el7 will be updated
---> Package perl-libs.x86_64 4:5.16.3-285.el7 will be an update
---> Package perl-macros.x86_64 4:5.16.3-283.el7 will be updated
---> Package perl-macros.x86_64 4:5.16.3-285.el7 will be an update
---> Package rockstor.x86_64 0:3.7-8 will be updated
---> Package rockstor.x86_64 0:3.7-9 will be an update
--> Running transaction check
---> Package perl-Time-HiRes.x86_64 4:1.9725-3.el7 will be installed
--> Processing Dependency: /bin/perl for package: 4:netatalk-3.1.6-0.0.1.el2.x86_64
--> Running transaction check
---> Package btrfs-progs.x86_64 0:3.18-1.el2 will be updated
---> Package btrfs-progs.x86_64 0:4.0-1.el2 will be an update
---> Package kernel-ml.x86_64 0:4.0.2-1.el7.elrepo will be installed
---> Package rockstor.x86_64 0:3.7-8 will be updated
---> Package rockstor.x86_64 0:3.7-9 will be an update
--> Running transaction check
---> Package btrfs-progs.x86_64 0:3.18-1.el2 will be updated
---> Package btrfs-progs.x86_64 0:4.0-1.el2 will be an update
---> Package kernel-ml.x86_64 0:4.0.2-1.el7.elrepo will be installed
---> Package rockstor.x86_64 0:3.7-8 will be updated
---> Package rockstor.x86_64 0:3.7-9 will be an update
--> Finished Dependency Resolution

Packages skipped because of dependency problems:
    4:perl-5.16.3-285.el7.x86_64 from base
    4:perl-Time-HiRes-1.9725-3.el7.x86_64 from base
    4:perl-libs-5.16.3-285.el7.x86_64 from base
    4:perl-macros-5.16.3-285.el7.x86_64 from base

Dependencies Resolved

===================================================================================================================================================================
 Package                                   Arch                             Version                                       Repository                          Size
===================================================================================================================================================================
Installing:
 kernel-ml                                 x86_64                           4.0.2-1.el7.elrepo                            rockstor                            36 M
Updating:
 btrfs-progs                               x86_64                           4.0-1.el2                                     rockstor                           553 k
 rockstor                                  x86_64                           3.7-9                                         rockstor                            12 M
Skipped (dependency problems):
 perl                                      x86_64                           4:5.16.3-285.el7                              base                               8.0 M
 perl-Time-HiRes                           x86_64                           4:1.9725-3.el7                                base                                45 k
 perl-libs                                 x86_64                           4:5.16.3-285.el7                              base                               687 k
 perl-macros                               x86_64                           4:5.16.3-285.el7                              base                                42 k

Transaction Summary
===================================================================================================================================================================
Install                        1 Package
Upgrade                        2 Packages
Skipped (dependency problems)  4 Packages

Total download size: 48 M
Is this ok [y/d/N]: y
Downloading packages:
Delta RPMs disabled because /usr/bin/applydeltarpm not installed.
(1/3): btrfs-progs-4.0-1.el2.x86_64.rpm                                                                                                     | 553 kB  00:00:20
(2/3): rockstor-3.7-9.x86_64.rpm                                                                                                            |  12 MB  00:06:46
(3/3): kernel-ml-4.0.2-1.el7.elrepo.x86_64.rpm                                                                                              |  36 MB  00:17:00
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                               48 kB/s |  48 MB  00:17:00
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : kernel-ml-4.0.2-1.el7.elrepo.x86_64                                                                                                             1/5
  Updating   : btrfs-progs-4.0-1.el2.x86_64                                                                                                                    2/5
  Updating   : rockstor-3.7-9.x86_64                                                                                                                           3/5
Running migrations for storageadmin:
- Nothing to migrate.
 - Loading initial data for storageadmin.
Installed 0 object(s) from 0 fixture(s)
Running migrations for oauth2_provider:
- Nothing to migrate.
 - Loading initial data for oauth2_provider.
Installed 0 object(s) from 0 fixture(s)
Running migrations for django_ztask:
- Nothing to migrate.
 - Loading initial data for django_ztask.
Installed 0 object(s) from 0 fixture(s)
Running migrations for smart_manager:
- Nothing to migrate.
 - Loading initial data for smart_manager.
Installed 0 object(s) from 0 fixture(s)
Running migrations for backup:
- Nothing to migrate.
 - Loading initial data for backup.
Installed 0 object(s) from 0 fixture(s)
2015-05-22 06:52:15,704: Default kernel set to /boot/vmlinuz-4.0.2-1.el7.elrepo.x86_64
2015-05-22 06:52:15,713: initrock ran successfully before, so not running it again. Running it again can destroy your Rockstor state. If you know what you are doing, remove /opt/rockstor/.initrock and run again.
  Cleanup    : rockstor-3.7-8.x86_64                                                                                                                           4/5
  Cleanup    : btrfs-progs-3.18-1.el2.x86_64                                                                                                                   5/5
  Verifying  : btrfs-progs-4.0-1.el2.x86_64                                                                                                                    1/5
  Verifying  : kernel-ml-4.0.2-1.el7.elrepo.x86_64                                                                                                             2/5
  Verifying  : rockstor-3.7-9.x86_64                                                                                                                           3/5
  Verifying  : btrfs-progs-3.18-1.el2.x86_64                                                                                                                   4/5
  Verifying  : rockstor-3.7-8.x86_64                                                                                                                           5/5

Installed:
  kernel-ml.x86_64 0:4.0.2-1.el7.elrepo

Updated:
  btrfs-progs.x86_64 0:4.0-1.el2                                                      rockstor.x86_64 0:3.7-9

Skipped (dependency problems):
  perl.x86_64 4:5.16.3-285.el7       perl-Time-HiRes.x86_64 4:1.9725-3.el7       perl-libs.x86_64 4:5.16.3-285.el7       perl-macros.x86_64 4:5.16.3-285.el7

Complete!
```
I have to run "yum upgrade --skip-broken" to keep Rockstor updated ever since I have this issue.

**Comment by iFloris** [comment]
My install is running from internal usb stick (16gb)
@therealprof is using SD, @freeurmind are you also using a similar type of media?
Perhaps this problem appears when not using a sata/sas type interface.

**Comment by freeurmind** [comment]
@iFloris nah im using a 250gb sata disk for rockstor

**Comment by schakrava** [comment]
@iFloris we are are releasing an updated iso soon, you might want to wait.

**Comment by iFloris** [comment]
Thanks Suman, I will wait.

**Comment by iFloris** [comment]
@schakrava thanks for releasing the new iso! I reinstalled and made a bunch of shares.
Then I tried to share these via AFP. Something is still wrong, or maybe it is just me:

[28/May/2015 04:00:59] ERROR [smart_manager.data_collector:328] Unable to get latest pool usage object for pool(rockstor_rockstor). A new one will be created.
[28/May/2015 04:05:57] DEBUG [smart_manager.scheduler.task_dispatcher:186] Started Task Scheduler
[28/May/2015 04:07:59] ERROR [smart_manager.data_collector:301] Unable to get latest share usage object for share(etime). A new one will be created.
[28/May/2015 04:07:59] ERROR [smart_manager.data_collector:328] Unable to get latest pool usage object for pool(everyraid). A new one will be created.
[28/May/2015 04:08:30] ERROR [smart_manager.data_collector:301] Unable to get latest share usage object for share(jtime). A new one will be created.
[28/May/2015 04:08:30] ERROR [smart_manager.data_collector:301] Unable to get latest share usage object for share(mediastor). A new one will be created.
[28/May/2015 04:08:59] ERROR [smart_manager.data_collector:301] Unable to get latest share usage object for share(stock). A new one will be created.
[28/May/2015 04:09:02] ERROR [storageadmin.util:38] request path: /api/netatalk method: POST data: {u'time_machine': u'yes', u'shares': [u'etime', u'jtime']}
[28/May/2015 04:09:02] ERROR [storageadmin.util:39] exception: [Errno 2] No such file or directory: '/etc/afp.conf'
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/storageadmin/views/netatalk.py", line 135, in post
    refresh_afp_config(list(NetatalkShare.objects.all()))
  File "/opt/rockstor/src/rockstor/system/services.py", line 184, in refresh_afp_config
    with open(AFP_CONFIG) as afo, open(npath, 'w') as tfo:
IOError: [Errno 2] No such file or directory: '/etc/afp.conf'
[28/May/2015 04:09:25] ERROR [storageadmin.util:38] request path: /api/netatalk method: POST data: {u'time_machine': u'yes', u'shares': [u'etime', u'jtime']}
[28/May/2015 04:09:25] ERROR [storageadmin.util:39] exception: [Errno 2] No such file or directory: '/etc/afp.conf'
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/storageadmin/views/netatalk.py", line 135, in post
    refresh_afp_config(list(NetatalkShare.objects.all()))
  File "/opt/rockstor/src/rockstor/system/services.py", line 184, in refresh_afp_config
    with open(AFP_CONFIG) as afo, open(npath, 'w') as tfo:
IOError: [Errno 2] No such file or directory: '/etc/afp.conf'
[28/May/2015 04:09:28] ERROR [storageadmin.util:38] request path: /api/netatalk method: POST data: {u'time_machine': u'yes', u'shares': [u'etime', u'jtime']}
[28/May/2015 04:09:28] ERROR [storageadmin.util:39] exception: [Errno 2] No such file or directory: '/etc/afp.conf'
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/storageadmin/views/netatalk.py", line 135, in post
    refresh_afp_config(list(NetatalkShare.objects.all()))
  File "/opt/rockstor/src/rockstor/system/services.py", line 184, in refresh_afp_config
    with open(AFP_CONFIG) as afo, open(npath, 'w') as tfo:
IOError: [Errno 2] No such file or directory: '/etc/afp.conf'

Seems as though the afp conf was not created while enabling the AFP service. I tried disabling and reenabling it in both services and on the afp share page. No luck.
@therealprof is AFP working for you in the new iso?

**Comment by therealprof** [comment]
I haven't tried. Updating using an ISO is not really a straight forward approach for me...

**Comment by schakrava** [comment]
@iFloris I put the latest(3.1.7) netatalk rpm in the new iso and it looks like they have moved the config file from /etc/afp.conf to /etc/netatalk/afp.conf which is causing this problem. As far as I can tell, there are no other backwards compatibility issues. Can you edit /opt/rockstor/src/rockstor/system/services.py file and edit this line(# 35):
AFP_CONFIG = '/etc/afp.conf'
to this:
AFP_CONFIG = '/etc/netatalk/afp.conf'

After that, restart rockstor (systemctl restart rockstor) and try again.

Please do test that everything is working as I don't have a mac to test this feature myself.

**Comment by iFloris** [comment]
@schakrava thanks, I followed your instructions and AFP is working again

**Comment by therealprof** [comment]
Automatic updates seem to work again. Please feel free to close if you feel that is appropriate now.

**Comment by schakrava** [comment]
Thanks everyone. Things do look better now.
