### ISSUE TITLE
Django migrations not run while updating

### ISSUE THREAD

**Issue by therealprof** [rockstor/rockstor-core#642]
I had a couple of interesting problems in the web UI after an upgrade including a complaint that the service-manager was neither running nor could be started. So I tried to reinstall using yum and found this message:
"initrock ran successfully before, so not running it again. Running it again can destroy your Rockstor state. If you know what you are doing, remove /opt/rockstor/.initrock and run again."

Digging a bit deeper I saw that after that shortcircuit there're plenty a few commands which I think should also be ran after an update, like the django migrations.

Curiously enough running:

```
# sudo /opt/rockstor/bin/django migrate smart_manager --database=default
Running migrations for smart_manager:
 - Migrating forwards to 0004_auto__del_field_poolusage_usage__add_field_poolusage_free__add_field_p.
 > smart_manager:0001_initial
 > smart_manager:0002_auto__chg_field_task_state
 > smart_manager:0003_auto__chg_field_nfsdsharedistribution_num_write__chg_field_nfsdsharedi
 > smart_manager:0004_auto__del_field_poolusage_usage__add_field_poolusage_free__add_field_p
 - Loading initial data for smart_manager.
Installed 0 object(s) from 0 fixture(s)
```

fixed all of my problems.

**Comment by schakrava** [comment]
This may have been a one off issue. I was never able to reproduce it.

Please reopen this issue if you see this problem again.
