### ISSUE TITLE
Rockstor partitions should be mounted "noatime"

### ISSUE THREAD

**Issue by therealprof** [rockstor/rockstor-core#643]
Rockstor should not really have any data which requires the access time to be recorded in the FS so updating the access time will cause lots of unnecessary writes which is especially bad if the system is run from flash. This can be easily addressed by adding the noatime mount option.

**Comment by phillxnet** [comment]
This is a good point; however the kernel default is now to use relatime which updates access time less often.  But relatime does still cause an update at least once a day.
But from the following reference "... that's too much still."

From the time mark of 24:00:-
YouTube Linux.conf.au 2015 Marc MERLIN Google employee
https://youtu.be/6DplcPrQjvA?t=1440
from the slide:-
"... if you use snapshots, noatime is strongly recommended."
and from the audio:-
"... unless you really really really need access time which most people really don't now a days just turn it off ..."
"... the single fact of reading data will actually use up disk space"
which is definitely as the speaker says non-intuitive, at least to me.

So I would have to concur.  Although the above reference is in the context of snapshots there is still the "... most people really don't ..." bit.

So I too vote for noatime on all btrfs mounts unless specifically requested.

**Comment by schakrava** [comment]
This sounds good, but I wonder if it's a good idea to add noatime to /, which is also a btrfs mount. relatime may be good enough default that doesn't trip up any application relying on atime. 

How about we make all mounts except for / with noatime? For users that run rootfs on flash and want to turn off atime, it can be done manually by editing /etc/fstab.

**Comment by therealprof** [comment]
Not sure why we need atime (I think the only sane use of that is for the read status on mail server) on a storage system but relatime works for me as well as long as we can get rid of those pesky writes.

**Comment by phillxnet** [comment]
Sounds like a good start.
But as far as I can find out the only programs these days that rely on atime are the likes of mutt, pine, sendmail, debians popcon, and tmpwatch which is no longer installed by default and has been replaced by systemd-tmpfiles apparently.
Also some backup programs can use atime.

Given that Rockstor is appliance in nature I think we are best off trying to push in as much modern practice as we can.  Also running from usb keys really should be an aim in my opinion.  Our competition can already do this and we are far from it.  I'm thinking of FreeNAS here with their nano-bsd.  I suppose we have the possibility of Snappy / Ubuntu Core around the corner (transactional updates and support for docker containers). Or even RedHats Project Atomic.

Anyway getting a bit ahead of myself here.

atime reference from 2007 where they began trying to phase it out:-
https://lkml.org/lkml/2007/8/10/200
And we are currently at the semi smart relatime as default for general purpose linux distos to cater even to the really old / odd  programs.
And another from about the same time:-
https://lwn.net/Articles/244829/

tmpwatch reference:-
http://lists.centos.org/pipermail/centos/2014-October/147155.html

Snappy / Ubuntu core references:-
https://developer.ubuntu.com/en/snappy/
http://www.ubuntu.com/things

Project Atomic:-
http://www.projectatomic.io/
http://www.projectatomic.io/docs/introduction/

Any other ideas on the issue of noatime anyone?

**Comment by phillxnet** [comment]
@schakrava Maybe this is due for review / closure as I believe with non spinning install targets a recent commit of yours alters mount options to include noatime.
https://github.com/schakrava/rockstor-core/commit/ff908930179be7f501d440fce38e9fb36c83b108

I see in for example the following that rockstor_rockstor (the filesystem) has relatime.
```
mount | grep sdb
/dev/sdb3 on / type btrfs (rw,noatime,ssd,space_cache)
/dev/sdb3 on /home type btrfs (rw,noatime,ssd,space_cache)
/dev/sdb1 on /boot type ext4 (rw,noatime,data=ordered)
/dev/sdb3 on /mnt2/rockstor_rockstor type btrfs (rw,relatime,ssd,space_cache)
```
The above is from a 3.8-6 install using one of those pcie-msata adapters in the shop as install target.

But my understanding of noatime mount option precedence is that these noatime options on the sub-volumes (home and /) should supersede the file-system option. Does this mean we are "job done" at least on non rotational install media re this issue.

Reference on precedence:-
Duncan on linux-btrfs "IIRC/AFAIK, the btrfs-specific mount options should be per filesystem, 
while stuff like relatime vs noatime is VFS level and should work per 
subvolume."
http://permalink.gmane.org/gmane.comp.file-systems.btrfs/36914

**Comment by phillxnet** [comment]
@schakrava Another old issue due for closure I suspect, see my last comment in this issue.

**Comment by Hooverdan96** [comment]
Looks like we have implemented `relatime` and 'noatime' in the pools sections. @phillxnet so seems this could be closed?
