### ISSUE TITLE
Still lots of unnecessary disk writes coming from postgresql

### ISSUE THREAD

**Issue by therealprof** [rockstor/rockstor-core#644]
While the change to the service-manager removed many of the writes from pgsql there's still lots of IO coming from postgresql causing harm if the system is run from flash. One of the main offenders seem to be the postgresql statistics for which the guys themselves recommend putting the temporary storage in RAM:

```
stats_temp_directory (string)

Sets the directory to store temporary statistics data in. This can be a path relative to the data directory or an absolute path. The default is pg_stat_tmp. Pointing this at a RAM-based file system will decrease physical I/O requirements and can lead to improved performance. This parameter can only be set in the postgresql.conf file or on the server command line.
```

Setting 
**stats_temp_directory = '/tmp/'**
in /var/lib/pgsql/data/postgresql.conf

seems to be a decent improvement.

**Comment by therealprof** [comment]
Actually I retract my statement, /tmp/ is not on a tmpfs but ends up on flash; I thus changed the directory to /run/postgresql.

This is the diff for my configuration:

```
diff -ur ./opt/rockstor/conf/postgresql.conf ./var/lib/pgsql/data/postgresql.conf
--- ./opt/rockstor/conf/postgresql.conf	2015-05-21 07:18:54.000000000 +0200
+++ ./var/lib/pgsql/data/postgresql.conf	2015-05-22 09:07:13.271119907 +0200
@@ -147,8 +147,8 @@
 
 # - Background Writer -
 
-#bgwriter_delay = 200ms			# 10-10000ms between rounds
-#bgwriter_lru_maxpages = 100		# 0-1000 max buffers written/round
+bgwriter_delay = 1000ms			# 10-10000ms between rounds
+bgwriter_lru_maxpages = 1000		# 0-1000 max buffers written/round
 #bgwriter_lru_multiplier = 2.0		# 0-10.0 multipler on buffers scanned/round
 
 # - Asynchronous Behavior -
@@ -162,10 +162,10 @@
 
 # - Settings -
 
-#wal_level = minimal			# minimal, archive, or hot_standby
+wal_level = minimal			# minimal, archive, or hot_standby
 					# (change requires restart)
-#fsync = on				# turns forced synchronization on or off
-#synchronous_commit = on		# synchronization level;
+fsync = off				# turns forced synchronization on or off
+synchronous_commit = off		# synchronization level;
 					# off, local, remote_write, or on
 #wal_sync_method = fsync		# the default is the first option
 					# supported by the operating system:
@@ -177,15 +177,15 @@
 #full_page_writes = on			# recover from partial page writes
 #wal_buffers = -1			# min 32kB, -1 sets based on shared_buffers
 					# (change requires restart)
-#wal_writer_delay = 200ms		# 1-10000 milliseconds
+wal_writer_delay = 10000ms		# 1-10000 milliseconds
 
-#commit_delay = 0			# range 0-100000, in microseconds
+commit_delay = 100000			# range 0-100000, in microseconds
 #commit_siblings = 5			# range 1-1000
 
 # - Checkpoints -
 
-#checkpoint_segments = 3		# in logfile segments, min 1, 16MB each
-#checkpoint_timeout = 5min		# range 30s-1h
+checkpoint_segments = 1		# in logfile segments, min 1, 16MB each
+checkpoint_timeout = 1h		# range 30s-1h
 #checkpoint_completion_target = 0.5	# checkpoint target duration, 0.0 - 1.0
 #checkpoint_warning = 30s		# 0 disables
 
@@ -432,7 +432,7 @@
 #track_functions = none			# none, pl, all
 #track_activity_query_size = 1024 	# (change requires restart)
 #update_process_title = on
-#stats_temp_directory = 'pg_stat_tmp'
+stats_temp_directory = '/run/postgresql/'
 
 
 # - Statistics Monitoring -
```

**Comment by schakrava** [comment]
How about we mount /tmp as tmpfs if the root disk is on flash?

/sys/block/<BLOCK_DEVICE>/queue/rotational tells us if the drive is rotational media or not. Then if it's flash, we can enable tmp as tmpfs by "systemctl enable tmp.mount; systemctl start tmp.mount"

**Comment by therealprof** [comment]
That's actually a nice idea. However this seems to fail for sdcards as in my case:
# cat /sys/block/sdc/queue/rotational 
1
# cat /sys/block/sdc/device/vendor 
HP iLO  
# cat /sys/block/sdc/device/model 
Internal SD-CARD

**Comment by therealprof** [comment]
But thanks for letting me know how to enable /tmp mount anyway. ;)

**Comment by schakrava** [comment]
Ok, this issue is pretty much fixed after #725

**Comment by therealprof** [comment]
We'll see about that. ;)

**Comment by therealprof** [comment]
Actually it's not but thanks anyway for playing. Would it be a possibility to put the data on a separate partition e.g. by using a special system share somewhere on the storage?

**Comment by schakrava** [comment]
I've replied to you on #725 . We are open to making any more possible optimizations. Also, we are slowly improving the application behavior to write less and less data to the root drive, especially if it's on non-rotational media. These are incremental changes, however.

I'll think about your suggestion about system share. May I suggest you start a topic on the forum(http://forum.rockstor.com) to get other user feedback?
