### ISSUE TITLE
Add new Rock-ons

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-core#645]
Add the following rockons and improve the overall stability of the feature.

1. transmission
2. btsync

**Comment by silopolis** [comment]
May I suggest https://syncthing.net/ before btsync ?!

**Comment by schakrava** [comment]
@silopolis . syncthing is indeed awesome. I am just getting started with it where as pretty familiar with btsync. But we'll try our best to add syncthing soon.

**Comment by silopolis** [comment]
Great, keep it on !

**Comment by schakrava** [comment]
@silopolis We've added Syncthing as well. Thanks for asking, It's a neat app!

**Comment by schakrava** [comment]
fixed by #665

**Comment by silopolis** [comment]
Great !



2015-06-05 20:09 GMT+02:00 Suman Chakravartula <notifications@github.com>:

> Closed #645 <https://github.com/rockstor/rockstor-core/issues/645>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rockstor/rockstor-core/issues/645#event-323830838>.
>



-- 
--
Jérémie Tarot
http://about.me/silopolis
