### ISSUE TITLE
Samba guest access problem

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-core#656]
User comments:

System doesn't seem to allow guest access. I followed these instructions: http://rockstor.com/docs/samba_ops.html and managed to create a CIFS share which works in windows, but requires a username and password even though I selected guest access. It should be able to login without a username or password prompt once guest access is enabled.

**Comment by schakrava** [comment]
I verified that guest access works. First I added a samba export from the Storage -> Samba screen. I chose yes for browsable, guest ok and no for read only. Then from a ubuntu client, I was able to mount the share without authentication.

**Comment by schakrava** [comment]
Can anyone else reproduce this problem? I am closing the issue for now since I can't reproduce (version 3.8-1)

**Comment by baggar11** [comment]
I can't seem to get guest access working. Currently on 3.8-7. I've tried editing existing shares to allow guest access, no go. I've tried creating a new share and then creating a new samba export for it with guest access, still no go.

I found this closed ticket and thought I'd respond. If you like, I can create a new ticket.

**Comment by schakrava** [comment]
@baggar11 Are you trying this from a windows client or linux? What do the samba export options(browsable, guest ok etc..) look like?

**Comment by baggar11** [comment]
Ubuntu 14.04 system:

baggar11@madsonic:~$ sudo mount -t cifs //192.168.10.89/mp3 /var/music
Password for root@//192.168.10.89/mp3: 
mount error(13): Permission denied
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)

smb.conf from RockStor:

[mp3]
    comment = Samba-Export
    path = /mnt2/mp3
    browseable = yes
    read only = no
    guest ok = yes
    admin users = baggar11

**Comment by baggar11** [comment]
I just tested the same share on a Windows 7 machine, seems to work fine.

**Comment by baggar11** [comment]
Alright, just did another round of testing. Something odd is afloat. smbclient seems to work connecting as guest. But I can't for the life of me get mount.cifs or mount -t cifs to work as guest. I always get a permission denied error.

So I started poking around and grabbed my complete working smb.conf from my OpenMediaVault box, rebooted, and still no go. Then I noticed the management IP on the dashboard was wrong. And the appliance ID IP was also wrong as well. I had previously installed RockStor using DHCP, then set a dhcp reservation. For some reason, those IPs are not rectifying themselves after the fact.

So then I built up another RockStor instance, kept the dhcp installation IP, created a new pool, created a new share, then setup a samba export with guest access. Low and behold, it works.

So this is probably more of an issue with my RockStor instance. But I believe something got tweaked after the IP change. RockStor and/or Samba are holding onto old IP infor possibly? Is that ringing any bells?

**Comment by schakrava** [comment]
Add a -o guest to your mount command, that should bypass authentication.

**Comment by baggar11** [comment]
Well, I ended up rebuilding my main rockstor installation and that seemed to fix it. Believe me, I tried all sorts of options like -o guest and -o guest,sec=[none/ntlmv2/lanman] and user=guest,pass=. Nothing was working. I got it resolved after the re-installation. Thanks.

**Comment by MFlyer** [comment]
Actually this can be closed @schakrava
