### ISSUE TITLE
Feature request: Configuration backup

### ISSUE THREAD

**Issue by iFloris** [rockstor/rockstor-core#663]
For various reasons, I have reinstalled my rockstor server a couple of times now.
Every time, I get around to configuring and customizing more and more settings in the web-ui.
It would be very useful if it was possible to make a backup of the configuration settings, in order to be able to restore them later.
Restoring could be a manual replace file through ftp type of affair, or it could be an option on the web ui.
For me, being able to backup settings at all would be nice to have (but not essential in any way).

**Comment by schakrava** [comment]
Thanks for opening this issue. By settings/configuration, do you mean the state before reinstall? eg: pools, shares, users etc..? To be able to import in some way and have the state restored from previous install?

**Comment by iFloris** [comment]
@schakrava thanks for your reply.
Yes, I mean the state before reinstall. 
As you wrote, I would think of settings such as users, configurations in snmp/smart, scheduled tasks and pools, shares, but also smaller things such as current view on the dashboard (especially if more data goes on the dashboard at some point).
The configuration backup would ideally restore all settings, users and pools/shares to the point that reinstalling or reverting to a backup would be practically painless.

**Comment by phillxnet** [comment]
This would be a great feature; and given it's global effect I think stopping all affected service and applying the configuration and then requiring (or automating) a reboot might not be too much of an inconvenience / imposition.  This way we might minimize the complexity of such a potentially large re-configuration. Assuming the configuration is sane of course.  Might be nice if the config backup held some kind of self checksum also.  That way it could at least be checked for corruption prior to being applied.  Could also embed the Rockstor version that made the backup.  This way boundaries could be established as it may not be reasonable to expect a really old config to apply.  Could then warn users in this case, or even provide a fail over extraction mechanism to inform the use of what could be applied and what can't.  That way they can make their choices.

**Comment by phillxnet** [comment]
Quoting GIDDION from the forum http://forum.rockstor.com/t/appliance-management/155/2

"I'd like a config inport/export feature to enable easy configuration cloning of systems, which is especially useful for DR implementations that need to be the same. With this in mind, a push config changes to remote Appliance would also be usefukl as it would mean easy centralised (common) configuration."

Note that in this context we would have to deal with the hostname issue, ie preserve original found or add a number or something, maybe a popup to query the admin on this.

This suggestion also relates to another multi host suggestion made by GIDDION in the forums that I have referenced in #702 .

**Comment by schakrava** [comment]
@phillxnet I think your last comment deserves an issue of it's own. The primary request behind this issue is resolved. Please feel free to open new issues for specific enhancements.
