### ISSUE TITLE
no anaconda-ks.cfg file in repo and no iso build instructions

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#684]
I think it would be useful to have this file in the git repository as then we can track changes and do pull requests involving it, ie such as one to resolve #602 so that we might have full VirtIO capability, ie we could then install on either sda or vda, rather than just sda.

It would also be great to have the procedure used to create the distributed iso as then one could trial changes to installation files such as anaconda-ks.cfg or whatever, create the resulting iso (as per the official method) and test the resulting install behaviour prior to submitting patches.

Any thoughts on this?

I could have a stab at documenting the procedure if it was of interest; given the raw material / official method that is.

Apologies if I've missed something obvious here.

**Comment by schakrava** [comment]
I've created a new repo(rockstor-iso) where we could put iso related scripts and resources. Hope to get to it soon.

**Comment by phillxnet** [comment]
@schakrava That's great, thanks.  I look forward to having a dabble.  When we have enough info in there I could do a quick howto that could be added to the docs. Good idea to put in a separate repo, didn't think of that.  Might save some time / effort in the future to have this out and hopefully fully scripted / automated.

**Comment by phillxnet** [comment]
@schakrava Appologies but I've left this one open for ages after it's resolution in:
https://github.com/rockstor/rockstor-iso/commit/82d8ac8cc1618509acca6e490c5a1c104eb66307
Closing as fixed by the above commit.
