### ISSUE TITLE
Samba spotlight support

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-core#690]
Something mac users would find useful.

https://wiki.samba.org/index.php/Spotlight

**Comment by iFloris** [comment]
Sounds good! Will this also work on AFP? Or am I being ignorant and is this already supposed to work? If so, it does not seem to work for me :)

**Comment by gkadillak** [comment]
Don't believe that's implemented yet. @schakrava would be the person to ask.

**Comment by schakrava** [comment]
@iFloris not sure. But @gkadillak is a mac user, so we'll test with a mac client when we do implement this feature. There's a forum thread from a user who got this working on Rockstor using AFP, but let's not hijack this issue from samba to afp. Perhaps you can start a discussion on the forum about afp v samba for spotlight? It would be nice if there is no need for afp.

**Comment by elmcrest** [comment]
Any Updates on this? Would be really convenient to have. Maybe it's motivating that Synology will support this with it's DSM 6 Release ;)

**Comment by ScarabMonkey** [comment]
This would be rather useful...

**Comment by Hooverdan96** [comment]
considering that there was never a search "pickup" in this issue #484 and samba/spotlight recommends something like ElasticSearch, we should close this for now as well, until renewed interest is raised?
