### ISSUE TITLE
reload samba config after export changes

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#699]
Reported by seijirou on forum:- "Currently I either have to manually stop and start the samba service, or reload the config at the command line when I make a samba export change (systemctl reload smb).

Please consider having this reload run automatically when a change is made to samba exports."

Please update the forum threat at:- 
http://forum.rockstor.com/t/reload-samba-config-when-samba-exports-are-modified/140/1
when appropriate.

**Comment by phillxnet** [comment]
From the forum discussion seijirou was in favour of an "Apply Changes Now" button.  Less hairy than a whole sale auto affair.

**Comment by schakrava** [comment]
This is already the case -- smb gets reloaded whenever an exports are changed. 

I've verified it. Not sure if I am missing anything. Can someone provide reproducible steps?

**Comment by phillxnet** [comment]
@schakrava Have I left this dangling? There have been commits of yours that relate to samba restart changes being applied since this issue was opened
ie:-
https://github.com/schakrava/rockstor-core/commit/948258bc5a730082516ee4e6b5bf4376d0e067f1
where nmb is routinely restarted also.
This should have made things more robust already.

**Comment by schakrava** [comment]
@phillxnet I don't think I was able to reproduce this problem even before those changes. Are you able to  now? If not, safe to close the issue, IMO.

**Comment by phillxnet** [comment]
Closing as we have no steps to reproduce; please feel free to comment if anyone can provide steps to reproduce, that way we can re-open and have something to action on. Thanks.
