### ISSUE TITLE
Improve navigation between screens

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-core#702]
Navigating between say pool screen to services screen is a bit cumbersome with few hops too many. It will be nice to make transitions a lot better.

Input from a user
Perhaps this might be best implemented as optional, but I would love to see drop-down subitems for the top menus.

For example, I know I want to go to 'Shares'. Ideally I'd like to point my mouse at Storage, get a drop down list of the subpages under Storage so I can slick Shares from there. I very rarely actually want the first page I'm taken when I click on any of menus so being able to directly go where I want is just nice.

If you're familiar with the menus in napp-it, that's exactly what I'm talking about.

Another alternative implementation that I like is an expansion of the left pane to be more like a site-map with all the main and subpages listed on the left regardless of what you're looking at in the right pane. An example of this would be in pfSense, changing the theme from pfsense-ng to just 'pfsense' (done under System -> General Setup -> Theme).

With either of these, whatever you want is just a point->click or scroll->click away. While 2 clicks isn't the end of the world, sometimes you wonder what main section that subsection is under and you'd know it if you see it, but you have to click through main sections to hunt for it before you can see it.

http://forum.rockstor.com/t/drop-downs-for-top-menus/141

**Comment by phillxnet** [comment]
Adding to the above input from forum member seijirou I am including here another related suggestion:-
This time from forum member GIDDION relating to navigation between hosts with multi-host dashboard arrangements.

"After adding more rockstor appliances to the management, on both system's UI.
You should be able to pull down the "hostname management" in the top left to select each system.

The screen should be refreshed within the same TAB, not spawn a new TAB.

If the configuration is done on each system, you will be able to easily select a system from the top left "hostname management" pull down, giving the look and feel of a single unified UI."

**Comment by phillxnet** [comment]
GIDDION has further suggested the idea of pre-set split screen formats available on certain views ie pools, shares, disks etc as in a twin view or 2 x 2 views such that each cell displays that screen (ie disks) for a Rockstor appliance.  I think the idea is to cater for simultaneous and syncronized (rather than multiple web windows) views of multiple Rockstor appliances.
Summarizing (a bit) for inclusion in this issue.
This sounds like a nice idea, maybe each view could be more summarized in these necessarily smaller views.

**Comment by schakrava** [comment]
@phillxnet Thanks for consolidating similar feedback, but your previous two comments demand issues of their own so we don't scope creep this original issue, which IMO is resolved by more than a few improvements we made in 3.8-6 and 3.8-7 updates. For things that are not accomplished but desired, please file new issues.
