### ISSUE TITLE
user created on initial setup can't set as Admin users of smb share

### ISSUE THREAD

**Issue by xudaiqing** [rockstor/rockstor-core#703]
it's simply isn't in the list

**Comment by xudaiqing** [comment]
Very strange. i now in a state where i have Rockstor managed users splite in three page.
Users in the first page works normally, users in other pages not displayed as avaliable user in the Admin users list of smb share.
if i create user when i at first or second page, it will go to first page and work normally.
if i create user when i at third page, it will go random page and if it go to first page seems another user once in the first page go to second or third page.

![p1](https://cloud.githubusercontent.com/assets/3690727/8409699/366b3bd0-1eac-11e5-9569-ecd5d719f015.PNG)
![p2](https://cloud.githubusercontent.com/assets/3690727/8409703/398a2f6a-1eac-11e5-8d01-daa8ef160144.PNG)
![p3](https://cloud.githubusercontent.com/assets/3690727/8409709/3bffb922-1eac-11e5-8d66-213655a074d0.PNG)
![l1](https://cloud.githubusercontent.com/assets/3690727/8409718/484fd702-1eac-11e5-9e8c-97b5ca1ae497.png)
![l2](https://cloud.githubusercontent.com/assets/3690727/8409723/4c71fa5e-1eac-11e5-91fb-edd6ada34267.png)

**Comment by schakrava** [comment]
@xudaiqing Thanks for opening this issue and sorry for a delayed response. The user management has been revised in 3.8-3 and the users/groups screen is better now. I've verified that the behavior you reported doesn't exist in the latest(3.8-4) as well.

I'll close the issue for now, but if you still see the same please add your comment and I'll reopen it.
