### ISSUE TITLE
can't get sftp work

### ISSUE THREAD

**Issue by xudaiqing** [rockstor/rockstor-core#705]
install rockstor, update to 3.8-1, create a new share then get following error when try to create sftp share.

    Share(s2) is owned by root. It cannot be exported via SFTP with root ownership

**Comment by schakrava** [comment]
We'll improve the error message, but you need to go to the Share page and change the ownership of it to a different user and then try sftp.

**Comment by xudaiqing** [comment]
it solved the problem.
actually, i have look at the share before the first post. but because the owner information didn't display in the list view, i just think it isn't handle there. 
and the fact samba's ownership is handled when create smb share also contrubute to the misunderstand
