### ISSUE TITLE
replace Gb with GB

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#709]
From GIDDION in forum "Throughout the UI there is confusion about Gb (Gigabit) and GB (GigaByte). Please do a search and replace to fix this."

This is a very good point, we deal almost exclusively in B (Bytes) not b (bits); only really the network readout might use Gb (Giga bit), Mb (Mega bit).
Just had a look over and the following are at question:

Items to change:-
Dashboard:-
- "Top Shares  by Usage"
- "Total Capacity, Allocation and Usage"
Storage:-
- Disks - Capacity column
- Pools - Size column
- Pools - Create Pool - Capacity column
- Pools - Usage column (N.B. we have a Mb that should be MB here as well)
- Shares - Size column
- Shares - Usage column (N.B. we also have Kb instead of KB here)
- Snapshots - Total size (I have a bunch of 0.00 Pb which if anything should also be PB)
- Snapshots - Exclusive Size (again with the 0.00 Pb)

This last Snapshot measurement is also a little strange with it defaulting to the high end ie PB not MB

But we do seem to be adhering to SI guidelines re a space between the numeric and the Unit.

**Comment by phillxnet** [comment]
Please update the forum on resolution of this issue:- http://forum.rockstor.com/t/gb-confused-with-gb/156

**Comment by schakrava** [comment]
major props to @phillxnet for very helpful input!

**Comment by Mchakravartula** [comment]
One line of code need to be changed in humanize.js located in rockstor downloads. Currently units are assigned as " var units = ['bytes', 'Kb', 'Mb', 'Gb', 'Tb', 'Pb'];  " . Replace with 'B' rather than 'b' for byte abbreviations.

**Comment by Mchakravartula** [comment]
Please ignore my previous comment. I would like to rephrase what I mentioned above. We need to get the new updated humanize library, which has fixed this byte abbreviation issue.

**Comment by Mchakravartula** [comment]
I have tested with the updated library and its working as expected. All we need to do is to update the library. https://github.com/taijinlee/humanize

**Comment by schakrava** [comment]
Thanks @Mchakravartula I probably can't squeeze it in this release(there are too many changes already), but sure to include in the next one!

**Comment by schakrava** [comment]
This is fixed in 3.8-3 release. No code change, just updated the library.
