### ISSUE TITLE
syncthing and transmission rock-ons ipv6 only

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#710]
Rockstor 3.8-1
I need this confirmed but installs in KVM and real hardware of Syncthing plugin:-

```
netstat -plunt | grep '8080\|22000\|21025'
tcp6       0      0 :::21025                :::*                    LISTEN      6167/docker-proxy   
tcp6       0      0 :::8080                 :::*                    LISTEN      6183/docker-proxy   
tcp6       0      0 :::22000                :::*                    LISTEN      6175/docker-proxy
```
ie no 0.0.0.0

By way of comparison the Plex web UI on 32400 shows as:-
```
netstat -plunt | grep 32400
tcp        0      0 0.0.0.0:32400           0.0.0.0:*               LISTEN      5434/./Plex Media S
```
As my ipv6 is broken here this prevents my access to the syncthing WebUI, I am assuming we can reconfigure syncthing to listen on both ipv4 & ipv6 rather than ipv6 only.

Apologies if I have misunderstood this.

**Comment by phillxnet** [comment]
Similarly transmission seems to share this ipv6 only trait:-
KVM and real hardware:-
```
netstat -plunt | grep '9091\|51413'
tcp6       0      0 :::9091                 :::*                    LISTEN      7390/docker-proxy   
tcp6       0      0 :::51413                :::*                    LISTEN      7382/docker-proxy  
```
Could this be related to forum post:-
http://forum.rockstor.com/t/syncthing-or-transmission-not-access-to-web-interface/152

**Comment by phillxnet** [comment]
Note that I can get to rockstor.lan:9091 transmission WebUI
and I can also get to rockstor.lan:8888 btsync WebUI
```
 netstat -plunt | grep 8888
tcp6       0      0 :::8888                 :::*                    LISTEN      8059/docker-proxy
```
but not the rockstor.lan:8080 syncthing WebUI

Where in the code can we find out which upstream docker container each rock-on is using?

**Comment by schakrava** [comment]
@phillxnet timing is great on this, thanks! I'll test it out as part of #711. But I have no access issue with Syncthing Rock-on so far. It's doesn't matter as things are getting much better in that pull request.

regarding where the code is, let me comment on that after I merge #711

**Comment by schakrava** [comment]
@phillxnet I am wondering if there is anything actionable from this issue. Kindly provide your thoughts.

**Comment by phillxnet** [comment]
@schakrava Yes sorry left this one dangling, closing as all rock-on webui access now working for me.
