### ISSUE TITLE
Task issues with dev 3.8-1.6

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#716]
Please note this is the development / unstable 3.8-1.6 release of Rockstor

The Task Scheduler reverts to OFF after reboot when it was previously ON.

Also unable to edit or disable individual tasks, no entry on tick mouse over and "edit" results in:-
"Unknown internal error doing a GET to /api/sm/tasks/7" or whatever number the task is.

N.B. It may be relevant that these tasks have yet to run a single time.

**Comment by schakrava** [comment]
Thanks @phillxnet for creating this issue. This is also due to not making the change persistent in supervisor configuration similar to #660 

The edit problem looks like a different issue, however. I'll test it.

**Comment by phillxnet** [comment]
@schakrava We now have #728 open on "Can't Edit Scheduled Tasks" so just linking here for convenience.

**Comment by phillxnet** [comment]
Closing as the scheduler reverting to OFF is fixed in 3.8-3 and we have existing referenced issues open for the side line mentioned here of editing tasks failing.
