### ISSUE TITLE
Display tool tips & error messages consistently throughout the web UI

### ISSUE THREAD

**Issue by Mchakravartula** [rockstor/rockstor-core#722]

**Comment by MFlyer** [comment]
@schakrava can you explain this??
Every error/tooltip usually is related to current view, so I don't understand that 

> consistently throughout the web UI

M.

**Comment by FroggyFlox** [comment]
Closing this as it relates to a now very-old state of Rocsktor's webUI. A lot of progress has indeed been made since. We would now prefer more focused issue(s) targeting a specific shortcoming (if any) in tooltip/error feedback to the user.
