### ISSUE TITLE
buggy behavior with clone display and delete

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-core#727]
Here's the report from a user

Hello,

Just instaled rockstor on a custom 12 disk machine.
updated to latest version via webui
created a raid6 pool with 6 disks
created a share
exported the share via samba and nfs
created a snapshot
cloned the share
tried to delete the clone. gives me the error
tried to delete the snapshot gives me the error
the clone is not available on the share para to create another share based on the clone.

The issue is clearly reproducible even without samba and nfs steps. This is definitely a regression introduced with the auto pool import changes. Let's not close this issue without proper test coverage.

**Comment by finasfinas** [comment]
thanks for taking care of this bug! 
Was my first test of rockstor and well.. didn't work, but I still was impressed with what I saw.

**Comment by schakrava** [comment]
forum thread to follow up: http://forum.rockstor.com/t/this-snapshot-was-created-outside-rockstor-error/190/3
