### ISSUE TITLE
Can't remove disk from Rockstor UI pool

### ISSUE THREAD

**Issue by modelrockettier** [rockstor/rockstor-core#729]
I accidentally added my spare SSD to my main btrfs pool (RAID5, 4 3TB+ drives).  The web UI does not allow me to remove the SSD, so I had to remove it manually.

Now the Rockstor web UI is still saying that the SSD is still part of the pool ("btrfs fi sh" does NOT show it as part of the pool).

So please add a way to either remove the disk from the pool via the web UI, or add a way to refresh the Rockstor pool information after making manual changes to the filesystem (or both).

**Comment by therealprof** [comment]
I second that. I've had a similar problem: I added a few test devices and was not able to get them out of the system again other than through manual database rummaging.

**Comment by modelrockettier** [comment]
Today I updated my rockstor via yum, and just noticed that my SSD is no longer showing up as part of my pool.  Someone from Rockstor can confirm, but it looks like this may be fixed.

**Comment by schakrava** [comment]
Thanks for your comments @modelrockettier and @therealprof . I indeed fixed this in https://github.com/rockstor/rockstor-core/commit/68f6e1df2b7ee99ea6546a726977999422644068 but forgot to refer to this issue.
