### ISSUE TITLE
Schedule power down/up of the system

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-core#735]
feature request from the forum thread: http://forum.rockstor.com/t/features-i-would-like-in-rockstor/210

relevant section:
You can also power the NAS down and up again on a schedule, but I'm not sure this could be implemented on RockStor, due to lack of control over how to power the sytem up again.

**Comment by phillxnet** [comment]
@schakrava A "Task type" profile to go along with the existing scrub and snapshot profiles could do a poweroff command at a configurable time. Users can always configure their BIOS to do timed power on with many systems these days until we get a proper UEFI interface option to do timed power-ups.

**Comment by phillxnet** [comment]
Noting @MFlyer supplied link to acpi / RTC info for scheduled wake-up from the following forum thread:
https://www.mythtv.org/wiki/ACPI_Wakeup
please update the following forum thread with the resolution of this issue:
https://forum.rockstor.com/t/power-management-auto-power-off-and-on/2815/4

Linking back to related issue #1036 which also has some info on ACPI / RTC  wake up programming.

**Comment by MFlyer** [comment]
Some good reference too:

https://www.linux.com/learn/wake-linux-rtc-alarm-clock

**Comment by MFlyer** [comment]
Having code on this like a separate/test/base PR for #1036

**Comment by MFlyer** [comment]
Cross ref to #1306

**Comment by MFlyer** [comment]
@schakrava @phillxnet 
Updates:
successfully scheduled a reboot or shutdown task, currently missing:
- task editing funcs
- custom shutdown options to allow wake on rtc
- live wake rtc tester (inform user about rtc avail or not and suggest a test to try shutdown + wake on rtc)
- WebUI helpers to alert connected users on incoming shutdown/reboot

Mirko

**Comment by MFlyer** [comment]
Asking @rockstor/developers and users feedbacks:

Can you shell check this?
`journalctl | grep rtc`

On my dev env got an S4 support, so no available rtc wake up after system shutdown, but wake up from suspend wyth `systemctl suspend`([ACPI reference](https://en.wikipedia.org/wiki/Advanced_Configuration_and_Power_Interface))
Probably 99% env support S4 only, so we can grant a suspend+wake up and not shutdown + wake up

**Comment by phillxnet** [comment]
@MFlyer OK, on my ASUS N3700-ITX board I get:
```
journalctl | grep rtc
Feb 19 18:50:39 cube kernel: rtc_cmos 00:00: RTC can wake from S4
Feb 19 18:50:39 cube kernel: rtc_cmos 00:00: rtc core: registered rtc_cmos as rtc0
Feb 19 18:50:39 cube kernel: rtc_cmos 00:00: alarms up to one month, y3k, 242 bytes nvram
Feb 19 18:50:39 cube kernel: rtc_cmos 00:00: setting system clock to 2017-02-19 18:50:39 UTC (1487530239)
```

From memory isn't S4 essentially off anyway,  S3 is regular suspend. I.e when bios set to have WOL doesn't that mean that off is S4 level and no deeper.
This motherboard is very likely to have wake on RTC, even from off, ie power down not just suspend.

Also from a NUC I have I get the following:
```
Feb 19 08:46:40 ytagit kernel: [    1.693588] rtc_cmos 00:05: RTC can wake from S4
Feb 19 08:46:40 ytagit kernel: [    1.693705] rtc_cmos 00:05: rtc core: registered rtc_cmos as rtc0
Feb 19 08:46:40 ytagit kernel: [    1.693734] rtc_cmos 00:05: alarms up to one month, y3k, 242 bytes nvram, hpet irqs
Feb 19 08:46:40 ytagit kernel: [    1.708649] rtc_cmos 00:05: setting system clock to 2017-02-19 08:46:36 UTC (1487493996)
```
And this device wakes itself every morning via bios settings after shutting itself down via the following cron job every night:
```
# power off at 30 mins past midnight every day
30 0 * * * /sbin/poweroff
```

Does that help?

**Comment by MFlyer** [comment]
Thanks for your feedback @phillxnet ,
got same output on my Rockstor dev env, but no wake up from power off, trying to understand if guest over Proxmox related or not (quite sure about virtualization issue / missing params)

Can you test system wake up on that ASUS with:
```
echo 0 > /sys/class/rtc/rtc0/wakealarm
echo `date '+%s' -d '+ 5 minutes'` > /sys/class/rtc/rtc0/wakealarm
shutdown -h now
```
On a working motherboard this will provide system wake up from power off after 5 mins

**Comment by MFlyer** [comment]
Having some tests with built-in rtcwake tool (shutdown/suspend + wake after 120 sec):

`rtcwake -m disk -s 120` -> fails, mode disk is S4
`rtcwake -m mem -s 120` -> ok, mode mem is S3
`rtcwake -m off -s 120` -> fails, mod off is system poweroff S5
`rtcwake -m freeze -s 120` -> VM seems running, but no response

**Comment by maxhq** [comment]
Hi @MFlyer, on my HP ProLiant MicroServer Gen8 I get:
```
Jan 11 15:19:17 Sigurd kernel: rtc_cmos 00:01: RTC can wake from S4
Jan 11 15:19:17 Sigurd kernel: rtc_cmos 00:01: rtc core: registered rtc_cmos as rtc0
Jan 11 15:19:17 Sigurd kernel: rtc_cmos 00:01: alarms up to one day, 114 bytes nvram, hpet irqs
Jan 11 15:19:17 Sigurd kernel: rtc_cmos 00:01: setting system clock to 2017-01-11 14:19:17 UTC (1484144357)
```

**Comment by MFlyer** [comment]
Hi @maxhq ,
thanks for your feedback :+1: 
Can you try `rtcwake -m mem -s 120` (suspend + wakeup) and `rtcwake -m off -s 120` (poweroff + wakeup) ? Note: probably suspend + wakeup will work fine, not sure about poweroff + wakeup <- you' ll need to manually poweron your machine

Mirko

**Comment by magicalyak** [comment]
Nothing on journalctl (it's pretty busy) but dmesg | grep rtc
[root@rocky ~]# dmesg | grep rtc
[    7.694698] rtc_cmos 00:01: RTC can wake from S4
[    7.695045] rtc_cmos 00:01: rtc core: registered rtc_cmos as rtc0
[    7.695076] rtc_cmos 00:01: alarms up to one month, y3k, 114 bytes nvram, hpet irqs
[    7.733611] rtc_cmos 00:01: setting system clock to 2016-12-24 18:47:12 UTC (1482605232)

I'm not in a position shutdown/suspend and restart at the moment. My server is up 24/7 (it also runs DNS for me)

**Comment by maxhq** [comment]
@MFlyer Sorry for the late feedback, but here are the results:
```
[root@Sigurd ~]# rtcwake -m mem -s 120
rtcwake: suspend to "mem" unavailable
```
... so it failed, but:

```
[root@Sigurd ~]# rtcwake -m off -s 120
rtcwake: wakeup from "off" using /dev/rtc0 at Fri Feb 24 01:01:59 2017
```
... and it automatically powered on again!

**Comment by MFlyer** [comment]
Thanks @maxhq !
So on my side fails over poweroff and works on mem, on your side works on poweroff and fails over mem eheh

Conclusion: will go on with current coding - having both shutdown and suspend option, telling users to test and choose :wink:

**Comment by MFlyer** [comment]
Hi @schakrava , like on #1306 i missed Fixes statement on commits.
Can be closed
M.

**Comment by MFlyer** [comment]
After Yum updates back on this: new job 🎉 , new nephew (welcome Zeno!!!), new cool issue 😃

Mirko

**Comment by MFlyer** [comment]
Starting up again with a [fresh new branch](https://github.com/MFlyer/rockstor-core/tree/issue%23735_issue%231036_Custom_Scheduled_tasks) from last rockstor core updates

**Comment by phillxnet** [comment]
@MFlyer Am I right that this can be closed as Fixed by pr #1659
Your linked other issue #1306 has now been closed.
Bit confusing as further comment there after!

**Comment by MFlyer** [comment]
You're right @phillxnet , already told it to @schakrava on previous message :)
Mirko

**Comment by schakrava** [comment]
Thank you @MFlyer ! Sorry this got missed.
