### ISSUE TITLE
As a user I'd like to replace failed drives in a RAID with new ones

### ISSUE THREAD

**Issue by therealprof** [rockstor/rockstor-core#737]
For some reason unknown to me there does not seem to be an obvious way to replace a failed drive which is part of a RAID pool by a new one and resync the pool. 

Steps to reproduce: 

1) Set up a RAID-1 pool
2) Shut down the system
3) Pull a drive
4) Reboot the system
5) Have a look around and discover that there's no evidence of a degraded RAID or any possibility to remove the failed drive or add a new one in its place

**Comment by iFloris** [comment]
Ran into a situation comparable to what @therealprof describes here just now. 
My steps are the following:

- Raid 6 pool, running for a few weeks. 
- 1 drive failed. 
- Shares no longer mountable.
- Bunch of errors in the web-ui such as: Unknown internal error doing a GET to /api/pools?page=1&format=json&page_size=15&count= and Another pool(rockstor_rockstor) has a Share with this same name(home) as this pool(everyraid). This configuration is not supported. You can delete one of them manually with this command: btrfs subvol delete /mnt2/[pool name]/home 
- Delete dropped drive from disk view.
- Searched for but did not find: a way to repair or resize raid pool.
- Try to delete pool and start from scratch :(
- Systems complains I need to delete shares first
- Try to delete shares - system complains it is in read only mode
- Try suggested terminal commands to remove shares - errors

End result as in step 5 as described by @therealprof : File system gets stuck in read only mode with no (visible?) way to repair

Next step: Reinstall Rockstor from usb and start over.

**Comment by schakrava** [comment]
Thanks @iFloris and @therealprof for your detailed comments. I am holding off until 4.2 kernel to test DR scenarios including this one. The prediction is sometime mid august. Once the behavior is consistent with the kernel, we can add support in Rockstor. @gkadillak is working on a useful alert framework, so it's all coming together. Thanks for your patience.

**Comment by iFloris** [comment]
@schakrava Thanks, sounds great! Other than a slight inconvenience, it is not a problem for me as I currently only use Rockstor to store backups from other machines on and do some testing. (Off topic: Your last two sentences sounded like 80's A-Team Hannibal's voice in my head)

**Comment by therealprof** [comment]
@iFloris For me rockstor still feels quite a immature for production use so similarly to you I'm making sure that I do have plenty of fresh backups around (remote and local on external drives) so I can fully restore any valuable data quickly. This also helped me to work around the broken RAID issue by simply manually  removing everything from the database and starting fresh from a backup.
