### ISSUE TITLE
Cannot edit existing scheduled task

### ISSUE THREAD

**Issue by therealprof** [rockstor/rockstor-core#738]
I created a scheduled backup task but for whatever reason I'm unable to change it after the fact and instead I get the following error:

> Error! 
> Unknown internal error doing a GET to /api/sm/tasks/1 
> If you need more help on this issue, email us at support@rockstor.com with the following information:
> The error message: "Unknown internal error doing a GET to /api/sm/tasks/1"
> A step by step description of the actions leading up to the error.
> Download the tarred and zipped server logs by clicking here, and attach it to the email.

I have checked the logs but there's no evidence whatsoever actually pointing to this particular problem.

**Comment by modelrockettier** [comment]
Is this a duplicate of #728?

**Comment by therealprof** [comment]
Oh sorry, I checked the existing ones but missed that one.
