### ISSUE TITLE
"Created on" column in snapshot list will always be the one of the latest snapshot

### ISSUE THREAD

**Issue by therealprof** [rockstor/rockstor-core#739]
I have a task scheduled to create a snapshot of my photos and in addition I manually created a read-only snapshot (thanks to not being able to edit my scheduled tasks #738 which is read-write and my desire to have a local backup to another share #736 which requires a read-only snapshot) and discovered that the snapshot list will always display the timestamp of the latest snapshot for all of them (regardless whether they've been done by the scheduler or manually):

> 	 Photos-snapshot	July 15th 2015, 12:04:45 am	Photos	Hidden	No	293.46 Gb	293.46 Gb
>	 Photos_snapshot_20150714182114	July 15th 2015, 12:04:45 am	Photos	Visible	Yes	293.46 Gb	293.46 Gb
>	 Photos_snapshot_20150712121120	July 15th 2015, 12:04:45 am	Photos	Visible	Yes	1.07 Gb	1.07 Gb

**Comment by schakrava** [comment]
Thanks for this report @therealprof . I have fixed it in https://github.com/gkadillak/rockstor-core/commit/285dae43d6dc675a85457481caa7f6b918d6a74d

It's pending testing and merge. FYI.

**Comment by schakrava** [comment]
Ok, the fix is rolled out with 3.8-4. Please update and let me know if you have any questions.
