### ISSUE TITLE
creating a raid1pool makes a single pool

### ISSUE THREAD

**Issue by xavierle** [rockstor/rockstor-core#742]
i am creating a pool with 2 similar drives

i am choosing raid1 
and as a result i always get always single configuration

**Comment by schakrava** [comment]
I've noticed that too. Can you run a balance and refresh the page. Seems to be something funky with the new btrfs changes.

I've noticed that if I run balance and it correctly removes the single metadata.

**Comment by xavierle** [comment]
when i try to click on the pool name to access the page when the balance is usually i have this message : 

Error!
invalid literal for int() with base 10: 'after'

**Comment by schakrava** [comment]
What's your rockstor version?

**Comment by xavierle** [comment]
balance have solved the issue once but most of the time i have the error : 

Error!
invalid literal for int() with base 10: 'after'

**Comment by phillxnet** [comment]
Seems this is affecting asapkota on the forum when trying to create a RAID10 pool also.
http://forum.rockstor.com/t/raid-10-question/241

**Comment by phillxnet** [comment]
I have opened an issue #752 recently, prompted by a forum member's findings, that may relate to the:-
Error!
invalid literal for int() with base 10: 'after'
When trying to view pool scrub status.

**Comment by schakrava** [comment]
I've added the critical label to this issue. I looked at this briefly several days ago when I added the previous comment. I am not convinced to put any workaround, perhaps this will be a non-issue with the next kernel and btrfs-progs update.

**Comment by schakrava** [comment]
Glad to inform that this is not an issue on 4.2.2 kernel + btrfs-progs 4.2.1. I tried a few times with all raid levels and was not able to reproduce the issue. Fair to say this issue doesn't occur after the 3.8-8 update.

I'll close the case, but please reopen if it happens again.
