### ISSUE TITLE
rock-ons not installing on Firefox

### ISSUE THREAD

**Issue by xavierle** [rockstor/rockstor-core#744]
for every rock on

when i try to submit the configuration on the last configuration screen

then nothing is happening

**Comment by schakrava** [comment]
Which browser are you using?

**Comment by priyaganti** [comment]
I just tested it out on Firefox. It doesn't work. It does work with Chrome.

**Comment by phillxnet** [comment]
@xavierle @schakrava @priyaganti I can confirm this on (default) Firefox 39.0 in Ubuntu Gnome 15.04. Last Submit button flashes but doesn't register. Same system with Chrome 43.0.2357.134 (64-bit) all dandy.  Both Rockstor 3.8-2 and upgrade to 3.8-3 show this behaviour for me.

**Comment by xavierle** [comment]
it seems it works better with  chrome.

i was able to launch some rocks on install.
by the way most of the install fails

**Comment by pecigonzalo** [comment]
Most of the UI does not work on Firefox. (EG: The graphs ont he main page)

**Comment by phillxnet** [comment]
@pecigonzalo Thanks for reporting you findings.  What version of Rockstor are you testing with?

**Comment by pecigonzalo** [comment]
@phillxnet Sorry for the late reply, but i was not able to check. The version was the latest one at the time of the comment. I think it was version 3.8.2 or similar, ill confirm once back at my place. 
Firefox version was 40.0.2
I was just adding it as a comment here because maybe it was related.
