### ISSUE TITLE
Share resize units dropdown shows KB by default 

### ISSUE THREAD

**Issue by priyaganti** [rockstor/rockstor-core#745]
Shares -> click on share  -> click on resize button -> two fields one with size and other with units.
Size field displays correct values but Units dropdown is set to KB by default. 
Even if we choose 26 GB, in resize it shows 26.00 KB.

**Comment by modelrockettier** [comment]
I've also encountered this issue on 3.8-3

**Comment by phillxnet** [comment]
A recently merged pull request #748 by @Mchakravartula has addressed this issue so it should be sorted in the next release.

**Comment by schakrava** [comment]
Fixed by #748
