### ISSUE TITLE
Kernel error not showing up

### ISSUE THREAD

**Issue by gkadillak** [rockstor/rockstor-core#746]
An global alert should be shown telling the user to reboot in order to run the correct kernel.

**Comment by phillxnet** [comment]
Confirming and just adding that this kernel version warning stopped appearing in the 3.8-3 update from a fresh 3.8-0 iso install. Pretty sure I saw it in 3.8-2 update from 3.8-0 install.

This commit looks like the culprit but haven't looked into it, just saw it go by.
https://github.com/rockstor/rockstor-core/commit/2e7fb835549f0f3babac680df75ffa24d2b9685c

**Comment by gkadillak** [comment]
This is my fault actually, @phillxnet. I'll patch that up today. Thanks for bringing it to my attention :)

**Comment by schakrava** [comment]
@gkadillak Just a reminder to refer to this issue from the commit messages. Makes it easier for me to merge :)
