### ISSUE TITLE
Pool resize v2

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-core#747]
pool resize needs another iteration to incorporate the following.
1. Remove/readjust constraints based on current btrfs support(>4.1 kernel)
2. Make resize asynchronous
3. Improve UI design (alerts via websockets)

**Comment by Hooverdan96** [comment]
@phillxnet, is this still considered an open design item, or has this been addressed over the last 8 years with more convenient RAID resizing/disk operations?

**Comment by phillxnet** [comment]
@Hooverdan96 Lets close it, much has changed and this was very early in the project as an umbrella 'note' issue I think. Plus we do now Re-Raid via Huey (for some time now) so 2. is now sorted. And we have some UI feedback improvements re drive table etc.
