### ISSUE TITLE
cannot acces pool information

### ISSUE THREAD

**Issue by xavierle** [rockstor/rockstor-core#749]
following issue #742 for which the advices worked

now i cannot access any of my pools

it always shows this error : 

Error!
invalid literal for int() with base 10: 'after'

i cannot go to the page from balance and scrub

**Comment by gkadillak** [comment]
Can you post what the logs display. Just run <code>tail /opt/rockstor/var/logs/rockstor.log</code>

**Comment by phillxnet** [comment]
This could be a duplicate of #752 which has more information; including log snippets. #752 is derived from a forum post Entitled "Error when clicking on pool" see http://forum.rockstor.com/t/error-when-clicking-on-pool/225

**Comment by phillxnet** [comment]
linking to #720 as same error.

**Comment by schakrava** [comment]
Thanks @phillxnet closing as it is indeed a duplicate. #720 has the critical label, so it's high priority. Thanks for your patience.
