### ISSUE TITLE
Typos in network mouse over hints

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#753]
We have an "ENter" in IP Address field and spelling in Netmask.
Trivial but noting here so it isn't missed

**Comment by gkadillak** [comment]
I actually noticed this, @phillxnet, and it will be fixed in the the patch for #728

**Comment by phillxnet** [comment]
@gkadillak should I now close this then or leave it open to remind us until the patch / pull request is merged?

**Comment by gkadillak** [comment]
If you can confirm that the issue is fixed by pulling down [this branch](https://github.com/rockstor/rockstor-core/pull/751), I don't see the issue in closing it.

**Comment by phillxnet** [comment]
Closing as @gkadillak referenced fix now merged.
