### ISSUE TITLE
Share resize passing in the wrong qgroup id

### ISSUE THREAD

**Issue by modelrockettier** [rockstor/rockstor-core#756]
I'm trying to resize a share from 1GiB to 10GiB, and it's failing with the following error:
btrfs qgroup limit: invalid option -- '1'

I was able to extract the rockstor command and the issue was readily apparent, for some reason rockstor is passing an invalid qgroup id of -1/-1.
The command:
btrfs qgroup limit 10737418240 -1/-1 /mnt2/pool1

**Comment by schakrava** [comment]
Thanks for filing the issue @modelrockettier . We should've caught this before releasing 3.8-3. For what it's worth(given fast sprints), we are extending rc testing period going forward to help with bugs like these.

Back to the issue, this happens on Shares created before 3.8-3 where qgroup assignment was different. The new qgroup organization is better but old shares need to be ported. I've just made a commit to do that during the bootstrap process.
