### ISSUE TITLE
Time Machine backups not working OS X mavericks 10.9.5

### ISSUE THREAD

**Issue by AshAmAshi** [rockstor/rockstor-core#758]
I have exactly followed the steps listed here http://goo.gl/MmVyF0 from the RockStor blog.
* Created share with 1TB size.
* Exported using AFP and specified time machine option
* Issue the required command on terminal for allowing network based backups.
* Created specific user
+ Successfully found the backup disk via Time Machine tool settings on mac.
- All the above done using WIFI option, Time machine fails to find the backup disc...after spinning for couple minutes.

Using RockStor 3.8-2

![image](https://cloud.githubusercontent.com/assets/589813/8891114/3beaa63a-32d0-11e5-98d3-944e998a8653.png)

**Comment by AshAmAshi** [comment]
Using RockStor 3.8-2

**Comment by AshAmAshi** [comment]
x

**Comment by AshAmAshi** [comment]
Updated to RockStor 3.8-3 but the issue persists.

**Comment by AshAmAshi** [comment]
I was able to resolve the issue following the steps from the this article (http://goo.gl/calo4G)
* Follow the steps for creating a share in RockStor and export as AFP share.
* Then create the sparse image either by command line or disk utility as suggested in the article above and copy it to your RockStor share and mount it.
* Initiate backup using Time Machine.

**Comment by schakrava** [comment]
Thanks @AshAmAshi. Do you recommend we update the blog post with the sparse image steps?
