### ISSUE TITLE
documentation on website

### ISSUE THREAD

**Issue by Maskedman** [rockstor/rockstor-core#765]
for networks that don't have DHCP. need to do the following:

set static IP in **/etc/sysconfig/network-scripts/ifconfig-enp3s0** (or other interface name)

then reboot server for rockstor webui to be active.

trying to restart specific services does not work such as entering command:

**systemctl restart rockstor** <or any other service> results in error from systemctl.

**Comment by schakrava** [comment]
@Maskedman I've updated the documentation. Manual(static IP) and Auto(dhcp) configurations are now fully supported from the web-ui and documentation is current. Thanks for reporting this issue!
