### ISSUE TITLE
Editing Share Access Control, random user/group selected as default

### ISSUE THREAD

**Issue by modelrockettier** [rockstor/rockstor-core#775]
When I view a share's access control, everything is correct (user:root, group:root, perm:755), but when I hit edit, the perms stay correct, but the selected user becomes sync and the selected group becomes wheel.

It would be nice if these reflected the actual user and group.  This would be especially nice when you only want to change the user or group, but not both because right now you have to re-select the proper user AND group.

Also, the user and group lists are currently listed in a random order (not sorted and the order is different from what appears in /etc/passwd and /etc/group), which takes longer to select the item I'm looking for (though browser tricks like typing the first couple letters sometimes help get around this).

Rockstor 3.8-3.

**Comment by schakrava** [comment]
Thanks for providing the right amount of detail @modelrockettier

**Comment by modelrockettier** [comment]
I just updated to 3.8-4 and this is still present.

**Comment by schakrava** [comment]
Fixed by #778
