### ISSUE TITLE
Webpages no longer load correcty after installing update 3.6.4

### ISSUE THREAD

**Issue by Zoltrex** [rockstor/rockstor-core#785]
The Admin webpages have trouble loading after installing 3.6.4 update and all I see is the blue swirl, swirling.

**Comment by schakrava** [comment]
@Zoltrex Do you mean 3.8-4? Please provide more details, it works fine for me. You could refresh your browser and see if that fixes it, if you haven't already.

**Comment by Zoltrex** [comment]
I am sorry for the late reply the login page does not come up anymore and I cannot log into the GUI interface..

**Comment by schakrava** [comment]
@Zoltrex if the login page is not loading then (1) it could be a network issue where your laptop/browser is unable to reach Rockstor box or (2) Rockstor service may have gone down. You can restart rockstor with `systemctl restart rockstor` command.

Try using Chrome browser if you can. There are some lingering issues with firefox we need to address.

**Comment by Zoltrex** [comment]
Ok thanks I figured it out by going to the console and looking at the screen there. The IP addressed changed when I visited the Interfaces page. I am sure I hit the cancel button on that page but the default is DHCP. I will do more testing on that page and see what happens when I hit the cancel button. Thanks for your input with this issue.

**Comment by schakrava** [comment]
@Zoltrex glad you are able to figure it out. I am glad to help, but for problems like these that don't have clear reproducible steps, a github issue won't get as much attention as a forum topic where there are more eyes and more help as a result.

Please join our forum: http://forum.rockstor.com
