### ISSUE TITLE
eula.html missing?

### ISSUE THREAD

**Issue by arneko** [rockstor/rockstor-core#791]
Hi,
I am new to rockstor, but wanted to give it a try for a NAS I am about to setup. When, at first login, I wanted to read through the EULA, however, it send me to http://rockstor.com/eula.html - which gave me a 404 Error, indicating that the file is simply not there.

**Comment by schakrava** [comment]
Thanks for alerting us @arneko. I've just fixed it. Thanks for trying out Rockstor and welcome to our community!

**Comment by phillxnet** [comment]
@schakrava as you have now resolved this issue should it now be closed? @arneko I am assuming you would be OK with that.
