### ISSUE TITLE
Improve the design of services page

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-core#796]
This has been overdue for a while anyway, and here's a relevant user comment:

The "on/off" switch graphic is hard to spot check when there's a bunch of them, like on the services page.

**Comment by phillxnet** [comment]
Not sure if this fits under the design banner but I think it would be nice to have the entries always display in the same order; easier to find each time then.

**Comment by phillxnet** [comment]
@schakrava I think this has now been addressed by @priyaganti in the massive handlebars pr:-
https://github.com/rockstor/rockstor-core/pull/1020
Plus the services are also now displayed in Alphabetical order.
Could this one now be closed then?

**Comment by schakrava** [comment]
Fixed by #1171
