### ISSUE TITLE
Add a "send test email" button in the email alerts page

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-core#798]

**Comment by phillxnet** [comment]
Works for me in 3.8-8. Thanks. Will try and update docs as per https://github.com/rockstor/rockstor-doc/pull/71

**Comment by phillxnet** [comment]
Pull request https://github.com/rockstor/rockstor-doc/pull/94 addresses adding additional docs for email test feature.

**Comment by schakrava** [comment]
Fixed as part of #906
