### ISSUE TITLE
Rock-ons use a different timezone

### ISSUE THREAD

**Issue by modelrockettier** [rockstor/rockstor-core#809]
Right now, the BTSync, Plex, and Transmission Rock-Ons (and probably others) use UTC for the timezone, which can cause some unexpected behavior.

Two effects of this that I've noticed are Transmission turning on and off its alternate speed limits at times other than what was intended and Plex choosing to generate thumbnails at unexpected times.

This can be fixed by passing docker the additional arguments "-v /etc/localtime:/etc/localtime:ro" during the run call.

Rockstor 3.8-5

**Comment by phillxnet** [comment]
Just linking here to a possibly related recent merge #843

**Comment by schakrava** [comment]
@modelrockettier Thanks for opening this issue and I apologize for taking a long time for what is a simple change. Anyway, it's done and will be shipped with next update.
