### ISSUE TITLE
Add AFP export throws error when the service is turned off 

### ISSUE THREAD

**Issue by priyaganti** [rockstor/rockstor-core#813]
1. Rockstor version: 3.8-5.11

When the service is turned ON, I am able to add the afp export without any issues.
![afpexport](https://cloud.githubusercontent.com/assets/1999710/9426384/22d2c6d6-48f2-11e5-9975-8dec3665dfb2.png)

**Comment by sfranzen** [comment]
@schakrava This one can be closed as well now.
