### ISSUE TITLE
etc/rc.d/rc.local duplicate entries

### ISSUE THREAD

**Issue by paul-aviles** [rockstor/rockstor-core#818]
On a new fresh installation the rc.local file has duplicated entries.

#rockstor script. dont remove
/opt/rockstor/bin/initrock -x
#rockstor script. dont remove
/opt/rockstor//bin/initrock -x

Probably the last one should be removed and a proper systemctl service should be created instead of leveraging rc.local.

**Comment by phillxnet** [comment]
@paul-aviles Thank you for your report and I believe this is a know issue (the double entry). Rockstor does also install and use a rockstor.service (/etc/systemd/system/rockstor.service) which is used to serialize it's start along with postgresql and link itself to multi-user.target but I'm afraid I will have to leave the initrock -x rc.local explanation to @schakrava . Thanks for opening this issue as it would be nice to clean this up, although I don't think that it currently has any consequences.
However it is certainly questionable.

**Comment by schakrava** [comment]
Fixed as part of #931 

I've refactored the startup sequence so rc.local is not longer necessary. We are leveraging systemd instead and things are looking much better.

Thanks @paul-aviles
