### ISSUE TITLE
openvpn rocks on not starting

### ISSUE THREAD

**Issue by xavierle** [rockstor/rockstor-core#827]
install was successful but now openvpn rock on does not want to start

**Comment by schakrava** [comment]
If you click the information icon in the Openvpn Rock-on pane, you'll notice that there are some commands you need to execute before the Rock-on could start. This cannot be automated for security reasons. See the below image for more info.
![openvpn_info](https://cloud.githubusercontent.com/assets/1123552/12029617/28285e68-ada4-11e5-903a-ff88be1e92c1.png)
