### ISSUE TITLE
Improve OwnCloud Rock-on Messaging

### ISSUE THREAD

**Issue by vinima** [rockstor/rockstor-core#829]
1.  During the OwnCloud installation process, it is recommended that shares such as owncloud-db, owncloud-config etc, be created.  However, the size is not recommended.  It is assumed that the size will be default to the size of the pool.  It will be useful to have size recommendations on the tool-tip.
2.  I ran across strange behavior while installing OwnCloud.  Later I noticed that I was warned about this.  So, can you please put this line in BOLD RED to draw attention :  "We strongly recommend creating dedicated Share assignments. If a Config or Data Share is assigned to more than one Rock-on, it could cause strange behavior".
3.  It is recommended that three folders be created for OwnCloud installation - DB Storage, Data Storage, Config Storage, but the message "To create needed Storage(Shares) and come back, click here." takes you back just once, forcing you to remember the folder names.  If you don't remember, it causes lot of back and forth.

**Comment by vinima** [comment]
The above improvements apply to Syncthing Rock-on too.

**Comment by vinima** [comment]
These apply to Transmission Rock-on too.

**Comment by Hooverdan96** [comment]
@FroggyFlox if we still need this "information" we should probably move this to the Rockon section ... or, if the Rockon framework requests for being able to use multiple shares, defining folders (e.g. #2258) will be taken up, this might become obsolete, too --> so could roll this issue into the folder enhancement request?

**Comment by FroggyFlox** [comment]
@Hooverdan96, thanks for flagging this!

I actually believe this is now addressed by #2481 (see #2064 for an expanded rationale). As you do mention, though, this would be further improved by #2258.
I'm thus closing this as fixed by #2481.
