### ISSUE TITLE
Blank Tasks page TypeError toUpperCase in js

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#833]
3.8-5 to 3.8-6
Earlier today @xavierle reported (in a closed thread) receiving a blank Tasks page.
See chat from 25 - 26 Aug @xavierle and me.
I was unable to reproduce this but he was across multiple browsers. Finally a re-install sorted the problem for @xavierle but I have just reproduced what I think is the same problem here after a 3.8-5-3.8-6 upgrade:-

![3 8-5_to_3 8-6_taks_issue](https://cloud.githubusercontent.com/assets/2521585/9493027/922a11d8-4bf4-11e5-8745-7d4c8cd0bb62.png)

Nothing shows in rockstor.log during this page access.
However other upgrades from testing to 3.8-6 on other systems work fine on this page.

**Comment by phillxnet** [comment]
I have also just reproduced this in 3.8-3 to 3.8-6 upgrade.

**Comment by phillxnet** [comment]
An upgrade that went from 3.8-4 (with no tasks set) to 3.8-6 went fine however, a little while ago.

**Comment by phillxnet** [comment]
Fresh installs of 3.8-6 (using experimental iso) don't seem to be affect by this issue.

**Comment by xavierle** [comment]
@phillxnet so there was a real problem during my previous  upgrade that corrupted the file.
i did not pay attention from which version it was


for my new install i started from the sourceforge file and updated to the last version
it seems ok.

**Comment by phillxnet** [comment]
@xavierle Thanks for this info. I now don't think it was a corrupt file, just don't know yet. But once we build up enough context in this bug report someone might be able to pin it down. In both working and non working instances the indicated file version was the same for me but I don't think that file is the issue anyway, just where the fault shows up. I'm quite pleased to have been able to reproduce it as it goes but wont be able to look into it any further myself for a bit. For the record I'm assuming your install was 3.8.0 iso install and then upgraded to 3.8-6. Thanks for chipping in again.

**Comment by phillxnet** [comment]
@xavierle @schakrava I do have a vm machine with this issue, even after upgrade to 3.8-8 however it is of no consequence as the machine is kept just as an example of this issue.
My understanding is that @xavierle you are no longer affected after sorting via re-install and my vm is of no consequence and I haven't seen this elsewhere and nobody has added to this bug report I'm closing as an unimportant mystery. Would have been nice to work out what it was but may have been a corner case dating back to 3.8-3 or 3.8-5 so not largely relevant going forward. Please re-open if you are affected or have found a solution to this.
