### ISSUE TITLE
Alert e-mails require port 587

### ISSUE THREAD

**Issue by nikarul** [rockstor/rockstor-core#837]
I just set up alert e-mails through the RockStor web interface (running version 3.8-6), and it let me specify the mail server address but wouldn't let me specify a port, it is apparently hard coded to 587.  My mail server only runs on port 25 internally (I forward 587 to it on the firewall), so I had to hand edit the Postfix configuration to get it to work.  Now I certainly could also change my mail server config, but it would be nice if the web interface simply had an option to specify a custom port.

**Comment by schakrava** [comment]
http://forum.rockstor.com/t/smtp-port-on-email-notification-setup/568

**Comment by baggar11** [comment]
I actually think the Email section could be cleaned up a bit too. To give you an idea of how OMV does their notifications with Postfix.

Options:
Enable (toggle on/off)
SMTP Server
SMTP port
SSL/TLS (toggle on/off) (dictated by port used)
Authentication(toggle on/off)
username
password
primary email(recipient)
secondary email(recipient)

**Comment by phillxnet** [comment]
Just linking to a related forum post where SSL was requested.
http://forum.rockstor.com/t/add-ssl-for-e-mail-alerts-or-create-a-list-of-compatible-providers/737
Please note the informative article at 
https://www.fastmail.com/help/technical/ssltlsstarttls.html
that covers nicely some conundrums of Port / SSL / TLS / STARTTLS options.

**Comment by schakrava** [comment]
@baggar11 and @phillxnet , even though I closed this issue, I am with you on proposed enhancements. The issue is closed because the original request(port customization) is now implemented. Other proposed enhancements will be done in #1184. FYI.
