### ISSUE TITLE
User's .ssh directory owned by root

### ISSUE THREAD

**Issue by nikarul** [rockstor/rockstor-core#838]
I was having some trouble creating a user account in RockStor (3.8-6) through the web interface when I tried to specify an SSH key.  I was able to create the account without the key, but then got the same error when I tried to edit the account and add the key.  I went to the user's home via the shell and it shows that .ssh is owned by root:root.  I manually changed the ownership and tried the web interface again, and it gave the same error but actually set the key.  ~/.ssh/authorized_users seems to have the correct permissions as well.  The web error is:

Error running a command. cmd = ['/usr/bin/chown', u'link:link', u'/home/link/.ssh/authorized_keys']. rc = 1. stdout = ['']. stderr = ['/usr/bin/chown: invalid group: \xe2\x80\x98link:link\xe2\x80\x99', ''] 

Note that the user had previously existed with the group 'link', but I deleted and remade it with the group 'users' instead.  May be related.

**Comment by schakrava** [comment]
Thanks @nikarul for filing this issue. I've labeled it critical, so will get to this asap.
