### ISSUE TITLE
flash in websockets

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-core#848]
do we really need

src/rockstor/storageadmin/static/storageadmin/js/WebSocketMain.swf
src/rockstor/storageadmin/static/storageadmin/js/WebSocketMainInsecure.swf

?

**Comment by MFlyer** [comment]
Hi @schakrava , while digging around Rockstor issues I found this too.

Actually, considering every current browser, i think we don't need it anymore (maybe just for IE...):
this is current websockets support -> http://caniuse.com/#search=websocket so we should be ok without .swf, but we can leave it there for backward compatibility

**Comment by MFlyer** [comment]
to be closed (IMO) by @schakrava

**Comment by MFlyer** [comment]
Reminder to @schakrava - issue can be closed

**Comment by phillxnet** [comment]
@MFlyer As per your previous comment 21/6 , are you still proposing that we leave these files in place?
If they represent an arcane access method I would have thought a better / safer approach would be to remove them. That was my original thought anyway.

**Comment by MFlyer** [comment]
Hi @phillxnet ,
 we're in 2016 and every user should have a websockets enabled browser, but if all fail those two files grant websockets. I'm :+1:  to remove them, but leaving them there grant websockets working over worst case too ( 99.999999999999999% those two will never be used )

**Comment by phillxnet** [comment]
@MFlyer It just concerns me to leave such things lying around, in the vein of sorting / cleaning as we go. Think we are in agreement on their lack of utility so probably shouldn't be there.

I vote for removal so they don't bit us back. The less old technology hanging around the better.

**Comment by MFlyer** [comment]
My unique concern with tout court deleting:
our socket.io is 0.9.6 (04/2012 - because of gevent-socketio fixed to that) and reading current minified library code there's a reference to swf files

Best solution: upgrade genvet-socketio having new socket.io lib without flash websockets (latest releases don't have it :) )

**Comment by phillxnet** [comment]
Agreed, better to upgrade gevent-socket.io and then remove these files, just in case. Good thinking.

And something that may be related:
The following has been niggling at me:
https://github.com/rockstor/rockstor-core/commit/97a9b377c7b8f145897ae41c1d7ff24e4c439393
Note the comments in this commit. As can be seen we had an issue previously with a specific python version and it's compatibility re gevent which appears to have now passed as 2.7.5.39.el7_2 seems to be OK again.

Also note the following comment in this commit by @schakrava re move to tornado:
https://github.com/rockstor/rockstor-core/commit/410ead25498ee8cbbade0d0db81859d2f70b6b71
When gevent and friends were locked down to the indicated versions.
ie gevent-socketio 0.3.6

Not my best area I'm afraid but given your knowledge on this one thought I'd bring it up for your perusal. Especially given the talk of upgrading these libraries. Looks like we need to spin out some additional issues here.

**Comment by MFlyer** [comment]
Hi @phillxnet ,
i remember about gevent forced downgrade, those where my first days in Rockstor :)
We can nicely move socket.io js to latest - will test and PR asap - while updating to tornado or update gevent socletio imo is a 3.8-16 roadmap update to have more testing.

**Comment by phillxnet** [comment]
@MFlyer Oops getting my socket.io libs and langs all mixed up by the looks of it. Oh well. Will have to put more time (when available) into this side of things.

**Comment by MFlyer** [comment]
Hi @phillxnet & @schakrava , here some updates:
Removed swf files and it seems ok with chrome/chromium & firefox, Safari supports websockets to and same should do IE by version 11

Moving socket.io from our 0.9.6 to latest 1.5.1 : 
WOW, it's a mess. Code had major changes so had to check it and test it (new way to connect, etc etc etc) and except for that, with my first test I'm not sure our gevent-socketio is compatible :/

**Comment by MFlyer** [comment]
gevent-socketio seems "dead", mantainer no more coding on it / taking care of PR.
Alternative found today : http://python-socketio.readthedocs.io/en/latest/

Compatible with socket.io 1.3.5+ - will checking on next Rockstor cycle
