### ISSUE TITLE
Next phase Rock-on improvements

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-core#858]

**Comment by adrienbrault** [comment]
Will this include a way for users to create their own ? :smiley:

**Comment by schakrava** [comment]
@adrienbrault yes. Here's the wiki post that details the high level plan: http://forum.rockstor.com/t/next-phase-of-rock-on-framework-improvements/417 . I should have posted this link earlier, so thanks for your question. And, join our forum if you haven't already.

**Comment by schakrava** [comment]
@adrienbrault Checkout this readme on how to add your own Rock-Ons pretty easily: https://github.com/rockstor/rockon-registry/blob/master/README.md

**Comment by schakrava** [comment]
Fixed by #1077 #1082 #1092 #1114
