### ISSUE TITLE
USB Devices dont auto mount

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-core#880]
More details here: http://forum.rockstor.com/t/usb-devices-dont-auto-mount/435

**Comment by schakrava** [comment]
I am unable to reproduce this issue. Feel free to reopen with clear reproducible steps.

**Comment by MFlyer** [comment]
Hi @schakrava , so Kilauea Iki ended? good :smile: 

Flyer

**Comment by schakrava** [comment]
Yup. Thanks for your contributions @MFlyer!
