### ISSUE TITLE
drive power down interface

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#885]
Currently it seems the only way to set / enable drive powerdown is via cli hdparm commands.

Now that Rockstor has hdparm by default we can add a facility to set this figure on each device.
Issues:-
Drive names change but that is dealt with at some level elsewhere I am just not sure how we translate that to the device parameter that hdparm takes, presumably via the same function that shows the drive name in Disks table.
Reasons:-
Power / noise save.
Avoid users having to enter eg /sbin/hdparm -S120 /dev/sdb above initrock -x entries in /etc/rc.local to enable 10 min power down. (a value of 239 sets a 20 mins power down)

Obvious place to add this interface might be an additional column or icon in Disks. This might then also equate to the current power state. I believe smart can relay the drives current power state so we could poll from that database but I think it better to have a dedicated entry / mechanism for power setting / state read as then lighter and can be polled without drawing in all of the smart data.

Options in this drive setting - set how long before drive enters sleep (no disk motor activity) state and an instant sleep mode option on each / all drives.

**Comment by maxhq** [comment]
Two thoughts about that:

**1. Per-pool timeout instead of per-disk**

I wonder if setting this for each drive might lead to confusion, as the user has to check which drives belong to the same pool. Maybe it should be better set per pool (BTRFS filesystem)?
Then the corresponding drives could be fetched via `btrfs fi show -d` and timeout can be set.

**2. Non-rotational devices**
There might be problems when spindown is configured on non-rotational devices (USD stick, SD card, SSD). So that might have to be checked first.
I tried it on a USB stick and it became completely unaccessible (very old Linux though).

Currently I do the following in a systemd startup script:

```Shell
#!/bin/sh
# list all disks
lsblk -p -i -o KNAME,TYPE,SIZE,MODEL | while read dev type size model; do
	# only process disks (skip partitions etc.)
	test $type != "disk" && continue
	
	# skip non-rotational disks (indicators: rotation rate or acoustic management)
	spin_rate=`udevadm info --query=all --name=$dev | grep 'ID_ATA_ROTATION_RATE_RPM=' | cut -d= -f2`
	test -z $spin_rate && spin_rate=0
	aam=`udevadm info --query=all --name=$dev | grep 'ID_ATA_FEATURE_SET_AAM=' | cut -d= -f2`
	test "$spin_rate" == "0" -a "x$aam" != "x1" && continue

	logger -t diskspindown "Setting spindown time to 60min for $dev ($model, $size)"
	# set APM to allow spin down (ignore failures - drive might not support it)
	hdparm -B127 $dev >/dev/null 2>&1
	# set timeout to 60min
	hdparm -S242 $dev >/dev/null
done
```

**Comment by jakieu** [comment]
This is something that would make me buy a 5 year subscription instantly :+1:

**Comment by phillxnet** [comment]
@maxhq Thanks for all this excellent info, I particularly like the per pool power down idea.
The drive power down issue has come up again on the forum so linking here so that it might get updated in the case of development in this area. Thanks for the script by the way, nice.

Please update the following forum thread with development on this issue: http://forum.rockstor.com/t/smart-status-and-disk-spin-down/793/7

**Comment by phillxnet** [comment]
Taking a quick look at this again now.

**Comment by phillxnet** [comment]
Disk Power Status is on the way:
![disks-power-status-column](https://cloud.githubusercontent.com/assets/2521585/14331913/21354690-fc3f-11e5-9f2f-724debd0652a.png)
The edit icon leads to configuring the spid down time.

**Comment by phillxnet** [comment]
- [ ] add dev name to by-id wrapper for use in hdparm systemd script.
- [ ] add persistence over reboot via systemd as hdparm -S doesn't survive reboots.

**Comment by phillxnet** [comment]
Current spindown settings now displayed (to be made more friendly) and we have an instant spindown / pause button which doubles as a graphical indicator of power state by only being enabled (orange) when the associated drive is in active/idle mode (spinning). Screenshot:
![drive-pause-and-config-settings](https://cloud.githubusercontent.com/assets/2521585/14438411/f44d9cf8-001d-11e6-903f-27efbf5fe043.png)

**Comment by phillxnet** [comment]
Linking to recently closed pr for collaboration purposes (closed due to deleting and recreating the github branch):
#1260 
I will shortly open a fresh pr using the now re-created and rebased (on 3.8-13) branch by the same name.

**Comment by phillxnet** [comment]
remaining issues:-
- input validation bug caused by contention between the text box updating the slider first rather than triggering the validation routine. Will have another look shortly.
- dealing with completely removing a drives custom config for spin-down, and the associated systemd service config when the last drive entry is removed.

**Comment by phillxnet** [comment]
Linking to disk table helper changes in #1275 as I've added a couple of columns to the disk table in this issue.

**Comment by phillxnet** [comment]
Currently doing final testing prior to submitting pull request for review.

**Comment by maxhq** [comment]
The power down feature works great but I get the following warning from systemd when the service unit is updated:
`May  2 13:08:24 Sigurd systemd[1]: Configuration file /etc/systemd/system/rockstor-hdparm.service is marked world-inaccessible. This has no effect as configuration data is accessible via APIs without restrictions. Proceeding anyway.`

**Comment by phillxnet** [comment]
@maxhq Thanks for the report and I'm chuffed it's working for you. We have a few similar systemd file rights warning on some other services as well. Doesn't look like it's a problem but yes this is definitely something that needs to be sorted at some point. Started happening a few releases ago and I suspect it's down to some upstream policy changes on such things.

Would you mind stating what drive models you have had success with and if they needed any non default apm settings; especially useful if the drives are a popular model. Though this discussion may well be better located on the forum in a thread of it's own, but anywhere is good really.

Thanks again for you input.

**Comment by maxhq** [comment]
@phillxnet Sorry: bad news. Powering down only seems to work for my Seagate Barracuda ST1000DM003-1ER162 disks. I set APM to 127 (default: 128).
It does not work for Western Digital WDC WD10EARS-00Y5B1, which has no APM feature.

**Comment by phillxnet** [comment]
@maxhq Well I'd rather see this as good news actually, at least it works on some drives.:) .
I have tested here on some pretty old drives (eg 80 - 360 GB examples) with some working and other not so it's a bit hit and miss. Is you experience that the setting doesn't take, ie doesn't show up in the disks table, or that it shows up but doesn't then enter standby when left idle?

There may also be some upper limits imposed by as yet undetermined factors ie a couple of 
ST3000VN000-1HJ1 3TB Seagate NAS drives I have here only work on values up to 20 minutes so that another thing to try.

(Leaving a browser open on some pages of Rockstor's WebUI can inhibit spin down, this has been noticed most on the disks page so far)

Given that this issue is now closed we are likely to get more eyes on this if we continue in the forum thread that is now open to work out what might be done to improve things.
"[Disk spin down does not work on some of my disks](https://forum.rockstor.com/t/disk-spin-down-does-not-work-on-some-of-my-disks/1442)"
which in turn grew from this post: https://forum.rockstor.com/t/dev-log-for-3-8-14/1412/11?u=phillxnet
in the generic dev log thread.
There is already some diagnostic questions I've posted there that may help narrow down what's not working as well as it could.
The first thread currently addresses the first arrangement (config not showing up), as far as I'm currently aware, and I'm awaiting feedback on the referenced problem there. Please do chip in there if you think it's relevant or open another thread if that one doesn't seem to be appropriate. We can then open fresh issues here that are focused on particular findings or feature requests, ie an override to auto is_rotational but I'm not sure such things are a good idea really, hence a discussion first on the forum.

As you indicate we are not likely to safely achieve a 100% success on this but there is definitely room for improvement, especially given the length of time it's been available / in development. Also the big hw players in this field also struggle with this one. Seems many drives just don't always behave as expected.

Thanks @maxhq I think with a little more forum chat we can get more success on this one going forward and work out what needs to be issued on GitHub in manageable chunks. Please do open a forum post with specific finding on particular models as this is bound to help. I am definitely interested in refining this a little more at least, in fact that referenced thread may have already brought up an easy improvement that may be worth testing. Cheers.
