### ISSUE TITLE
Async replication improvements

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-core#886]
Appliance to Appliance asynchronous replication of Shares stopped working after 4.x kernel updates. 

My personal replication setup is also in a broken state. :(

**Comment by iFloris** [comment]
Bummer, but that is the real dogfooding :) So kudos for that.

**Comment by schakrava** [comment]
http://forum.rockstor.com/t/rockstor-3-8-8-on-vsphere-6-0-u1-storage-issue/547

**Comment by schakrava** [comment]
Closed by #994 #1002 #1010 #1016 #1047
