### ISSUE TITLE
Test mount behavior with renamed drives

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-core#897]
There may be a bug because of leaving renamed/deleted drives in the db until the user deletes. This may be interfering with mounting. Reproduce and find the root cause.

**Comment by phillxnet** [comment]
@schakrava I was wondering if this issue could be related to the removed drives being miss-identified as existing drives ie #937 Linking here in the hope it might help. Haven't looked code wise yet though.

**Comment by schakrava** [comment]
@phillxnet You are right. Your earlier pr #1045 fixed this issue by design. Nicely done. I do have one request. We should perhaps make the fake-serial more meaningful. How about something like "offline-disk-<serial_num>-<previously_known_disk_name>"?

I've tightened up the the code around importing, bootstrap etc.. referencing this issue. My changes are only somewhat related to the main issue here, however.

**Comment by schakrava** [comment]
Fixed by #1045 and #1074
