### ISSUE TITLE
Clarify up-to-date message

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#903]
This message as I understand it is a reflection of the sate of the Rockstor package version not the system package version. Hence we have the situation of displaying "System is up-to-date" then in fact it's only the Rockstor package that is up to date and there may very well be additional package updates available from base and updates repos pending.
I suggest we change this message to indicate "Rockstor is up-to-date" but add an additional notifier that indicates if there are any pending non Rockstor systems updates pending. This mainly serves those who choose not to enable auto updates which is not the recommended setting but I am guessing is a common configuration never the less.
Maybe:-

Rockstor (current) - System (current)
and
Rockstor (current) - System (**updates available**)
and
Rockstor (**update available**) - System (current)
and
Rockstor (**update available**) - System (**updates available**)

Since, as I see it, we are aiming at appliance this does complicate things; the splitting of Rockstor and system updates when this is a "Rockstor System".

The alternative is to not consider the system up-to-date when there are non Rockstor updates available but the Rockstor package is not entirely separate from these. Hence my suggestion re- messaging.

**Comment by phillxnet** [comment]
Please update the following forum thread on progress with this issue:- http://forum.rockstor.com/t/unable-to-update-rockstor-read-this/44

An element that I may not have transferred from the forum thread is that with the current arrangement I think the system updates are not WebUI installable until a Rockstor update is available; this is obviously a short coming. Thanks to @herbert from the forum for clarifying this.

**Comment by phillxnet** [comment]
@schakrava I'm not really sure how to deal with this one as all updates thrown together and we still have the issue of having system updates but no rockstor updates, in that situation how are updates applied via GUI, and how is the user informed of them.

**Comment by gotchi** [comment]
Wouldn't it be nice to have 2 sections.
Rockstor Updates and System Updates

both with an update button for the user, this would also allow users to activate the stable or testing release. On the system update site I would say, the packages to be updated should be listed in a box. For Rockstor it is fine to link to the release notes.

Everything on one page and I wouldn't change the notification as it is now, because otherwise people tend to forget the system updates which are as important as the rockstor ones.

**Comment by phillxnet** [comment]
@schakrava I think @MFlyer 's recent addition of being able to update all but the Rockstor package addresses the essence of this issue. Linking as a relevant reference/development:

#1690 "Adding Yum updates capabilities to Rockstor WebUI"

It may be that we simply need a little more text on the Rockstor update page pointing out the alternative "all but Rockstor package" option added in the referenced pr.

**Comment by Hooverdan96** [comment]
@phillxnet, with all the changes on the stable/testing channel screen and the Open Collective work, is this still relevant

**Comment by FroggyFlox** [comment]
Agreed... This has been improved a lot since that issue was created so I think it should be closed as fixed. If we do have some minor shortcomings on that part reported by users, we can create dedicated and focused issues as needed.

Thanks a lot!
