### ISSUE TITLE
Missing warning message for no running NFS service

### ISSUE THREAD

**Issue by roweryan** [rockstor/rockstor-core#911]
There is no warning message when you try and configure an NFS share and NFS is not running.

i.e. we need this message:

    Warning! NFS Service is not running. Clients won't be able to mount unless NFS is running.

**Comment by schakrava** [comment]
@roweryan That warning does exist as you can see in this screenshot. Are you talking about something different? If so, please explain in more detail.
![nfs_service_warning](https://cloud.githubusercontent.com/assets/1123552/11049651/bcf587a4-86f4-11e5-9a18-7468f2ee6b8c.png)

**Comment by roweryan** [comment]
I never saw that message, was on a fresh install. I guess it can be closed then :)
