### ISSUE TITLE
The rock-on "installing" overlay is at a higher level than the drop-down menu

### ISSUE THREAD

**Issue by roweryan** [rockstor/rockstor-core#920]
Means some items on the menu cannot be used while on that page.

**Comment by MFlyer** [comment]
Currently not able to check this over last Rockstor 3.8-14, all seem fine so on my side this can be closed

@schakrava @priyaganti

**Comment by schakrava** [comment]
@roweryan feel free to re-open this issue, but please provide as many details and steps as possible so we can all equally and fully understand the problem
