### ISSUE TITLE
systemd shows network.service as failed

### ISSUE THREAD

**Issue by roweryan** [rockstor/rockstor-core#922]
but it should be disabled/inactive instead - NeworkManager is used.

**Comment by phillxnet** [comment]
@roweryan @schakrava As of checking 3.8-10.17 I don't see this message. Presumably the recent upstream updates (CentOS) now deal more elegantly with how we do things.
I propose this issue can now be closed.

**Comment by roweryan** [comment]
I don't see it either

**Comment by phillxnet** [comment]
@schakrava Looks like this is sorted now.
