### ISSUE TITLE
nfs service check does not monitor sub-components

### ISSUE THREAD

**Issue by roweryan** [rockstor/rockstor-core#923]
e.g. rpc-statd

**Comment by schakrava** [comment]
What are all the sub-components? Is there a authoritative RHEL/CentOS document you recommend?

**Comment by roweryan** [comment]
/usr/lib/systemd/system/nfs-server.service

is a good start. Maybe I can get the info out of systemd directly, I will check.

**Comment by schakrava** [comment]
Correct me if I am wrong, but nfs-server.service systemd unit is properly setup with dependencies by default. Unless I am missing something here, we don't need to go around default systemd behavior to ensure proper nfs-server functionality. Please confirm and provide appropriate information if we do need to improve any thing...
