### ISSUE TITLE
rc.local looks wrong

### ISSUE THREAD

**Issue by roweryan** [rockstor/rockstor-core#925]
#rockstor script. dont remove
    /opt/rockstor/bin/initrock -x
    #rockstor script. dont remove
    /opt/rockstor//bin/initrock -x

**Comment by phillxnet** [comment]
@roweryan I suggesting that this is a duplicate of #818 I hope you agree that this is the case.

**Comment by roweryan** [comment]
oops yep! sorry!

**Comment by phillxnet** [comment]
@roweryan no worries there are so many, I was just trying to keep them as tied together as possible. Thanks for contributing.

**Comment by roweryan** [comment]
:+1:
