### ISSUE TITLE
[security] rockstor rpm packages do not have their gpg signatures checked

### ISSUE THREAD

**Issue by roweryan** [rockstor/rockstor-core#927]
$ grep gpgcheck= /etc/yum.repos.d/RockStor-Base.repo
    gpgcheck=0

**Comment by roweryan** [comment]
Same for /etc/yum.repos.d/Rockstor-Testing.repo

**Comment by roweryan** [comment]
I still see:

    /etc/yum.repos.d/Rockstor-Testing.repo:gpgcheck=0

**Comment by schakrava** [comment]
@roweryan you may have seen it before the update that fixed it was downloaded. All packages are signed now.
