### ISSUE TITLE
RockStor-Base.repo is misnamed

### ISSUE THREAD

**Issue by roweryan** [rockstor/rockstor-core#928]
Should be Rockstor-Base.repo

**Comment by phillxnet** [comment]
@roweryan I think this is for historical reasons; ie early on Rockstor was branded as RockStor so don't think this is anything to worry about, ie not a fault but a feature. :)

**Comment by phillxnet** [comment]
@roweryan I think there is nothing to action here, so I propose that this issue be closed.

**Comment by roweryan** [comment]
Okay, your call!
