### ISSUE TITLE
Failed to delete the Share(Images). Error from the OS: 'NoneType' object has no attribute 'name'

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-core#930]
In my installation I had a single harddrive with a pool on it an a share over the whole drive.
I removed this drive because of failed sectors and did not replace it by another. Now I am not able to remove the share or the pool in the UI.
If I go to delete the share, I get the following:
Failed to delete the Share(Images). Error from the OS: 'NoneType' object has no attribute 'name'

If I go to delete the pool, I get this:
Pool(pool1) is not empty. Delete is not allowed until all shares in the pool are deleted

**Comment by iFloris** [comment]
This sounds like it could be related to #737. Is that correct?

**Comment by HTPC-Schrauber** [comment]
It is not exactly the same. In this case it was a single Drive, that was removed. After drive removal the share from this drive is still in the UI. I wanted to delete the share, because the drive should not be replaced. But the share can not be deleted.

**Comment by schakrava** [comment]
http://forum.rockstor.com/t/internal-implementation-of-pools-shares-snapshots-and-clones/453/2

**Comment by arneko** [comment]
Yup, that sounds exactly like my problem. You did not have any kernel panics coming along with this, did you? I seem to get these a lot too, not sure if it is related. Will post a picture next time I get a chance.

**Comment by arneko** [comment]
As I mentioned in the <a href=http://forum.rockstor.com/t/one-disk-failed-rockstor-messed-up/701>forum</a>, this problem also occurs if that share contained snapshots. So while you're at it, please look into that as well.

**Comment by schakrava** [comment]
Thanks @arneko . I want to get to this issue very soon. Really appreciate your input!
