### ISSUE TITLE
"Update certificate" is a confusing menu item

### ISSUE THREAD

**Issue by roweryan** [rockstor/rockstor-core#938]
Does it mean "update the certificate", or "something to do with an update certificate, is my stable key a certificate for an update, is it for an ssl certificate?...

**Comment by phillxnet** [comment]
@roweryan You got it with SSL certificate I believe. Nothing to do with update channels anyway. @schakrava can you confirm this?

**Comment by roweryan** [comment]
@phillxnet It is SSL Certificate, I was just trying to show how it could be read :)

**Comment by phillxnet** [comment]
@roweryan OK, so what if it was changed to read "Update SSL Cert"? "Certificate" might be a bit long in the menu entry with the additional SSL.
Or maybe since it leads to an area that explains itself then maybe just "SSL Certificate" in the menu. I prefer this latter suggestion. And you?

**Comment by phillxnet** [comment]
I am now working on a pull request for this issue.

**Comment by roweryan** [comment]
Just saw your comments, looks good!
