### ISSUE TITLE
Cannot edit weekly scheduled task (scrub)

### ISSUE THREAD

**Issue by roweryan** [rockstor/rockstor-core#942]
Firefox.

If I click the edit button next to my weekly scheduled task, I can't edit any of the fields in the job.

**Comment by Mchakravartula** [comment]
I tried testing on both Chrome and Firefox and its working as expected. 
Some of the fields are supposed to be non editable. Can you please let us know which fields you are trying to edit.

**Comment by schakrava** [comment]
Thanks @Mchakravartula. You are right, certain uneditable fields are grayed out. I am closing this issue. Please provide more info and reproducible steps if re-opening.
