### ISSUE TITLE
Added a new disk, all data gone 8-|

### ISSUE THREAD

**Issue by frederick-lemasson** [rockstor/rockstor-core#951]
Hi

So after I removed a failing disk wish produced some interface related inconsistencies : https://github.com/rockstor/rockstor-core/issues/937  I still had my data (Raid1, 3 disks originally and one removed)

I replaced the broken disk with a brand new one, Rockstor sees it, but i see inconsistencies in data usage report :

![capture du 2015-10-13 18 50 43](https://cloud.githubusercontent.com/assets/7714032/10462017/8a5a504a-71dc-11e5-9ac0-22ca7cd5652d.png)
![capture du 2015-10-13 18 51 10](https://cloud.githubusercontent.com/assets/7714032/10462040/acc71708-71dc-11e5-9989-125d0ac052c9.png)

So on the pools page I get 0% usage, and on the dashboard I see my last correct usage (1.56 TB/3.00 TB)

My data share mounts, but is empty :/
Then I remove the newly added disk hopping I will get back to normal, nothing ... all data gone ... or at least it seems it is ... I dono how to check, repair or debug this ...

To be honest I find this a bit disappointing, I though that I could count on solid btrfs Raid, I never imagined getting so much trouble with failing/adding disks which is the main rock solid feature a nas should have.

May be I didn't do what I was supposed to though .. but I felt like I didn't do dangerous things ...

Could someone give me some hints on how to check whether I indeed lost all data ?

Best regards.

**Comment by frederick-lemasson** [comment]
so apparently my data is still here, after mounting one of the raid1 drive : 
[root@rockstor ~]# mount -o degraded /dev/sdd /mnt2/data/

[root@rockstor ~]# btrfs device delete missing /mnt2/data
executes forever, no reply
[root@rockstor ~]# btrfs device add /dev/sda /mnt2/data
[root@rockstor ~]# echo $?
0
no error
but no sign of the new disk : 
[root@rockstor ~]# btrfs filesystem show
Label: 'rockstor_rockstor'  uuid: f9674e49-fcb2-480f-a012-490cea875e6a
	Total devices 1 FS bytes used 3.46GiB
	devid    1 size 26.35GiB used 5.52GiB path /dev/sdc3

Label: 'raid1'  uuid: b7ed32b3-43a3-423e-82e7-a9bc60676e2f
	Total devices 3 FS bytes used 1.57TiB
	devid    2 size 3.64TiB used 1.57TiB path /dev/sdb
	devid    3 size 931.51GiB used 38.01GiB path /dev/sdd
	*** Some devices missing


I feel so alone ;)

**Comment by schakrava** [comment]
Hey @frederick-lemasson. You are not alone :)

Please join our community forum: forum.rockstor.com. Forum is a better place than github to discuss a troubleshooting matter like this.

**Comment by phillxnet** [comment]
@frederick-lemasson I see from your forum post http://forum.rockstor.com/t/trouble-replacing-a-broken-drive/559/5 , where this issue was discussed further, that @schakrava managed to talk you through this. Now that we have a link to that discussion are you happy with this issue being closed?

**Comment by frederick-lemasson** [comment]
Yes Philip, lets make it a happy ending.

2015-10-18 18:37 GMT+02:00 Philip Guyton <notifications@github.com>:

**Comment by phillxnet** [comment]
@schakrava So looks like we can close this now then.

**Comment by phillxnet** [comment]
@schakrava I think given the above we can close this now.

**Comment by phillxnet** [comment]
@schakrava I think we have a 'for closure' candidate here still.

**Comment by FroggyFlox** [comment]
Closing as it has been resolved as per discussion above.
