### ISSUE TITLE
rpmlint for rpm files?

### ISSUE THREAD

**Issue by roweryan** [rockstor/rockstor-core#955]
The rpm scripts for rockstor look a bit unconventional to my eye...

```
rpm -q --scripts rockstor
```

There are manual directory creations, copies of files, and the docker comparison doesn't use cmp but a system of md5sums and chmod. Also the changelog format doesn't contain version numbers.

Maybe we could use the same system as fedora system for checking rpm spec files, including rpmlint.

Not important for now, just opened an issue because I thought of it.

**Comment by schakrava** [comment]
Thanks for opening this issue! Definitely would like to improve it sooner than later.
