### ISSUE TITLE
Users and groups not showing up

### ISSUE THREAD

**Issue by roweryan** [rockstor/rockstor-core#958]
When I got to the users or to the groups page, I do not see any Rockstor Admin Users. If I go to page 2, I do.

If on page 2 I try to edit the admin user, it shows me that their username is admin1000 (the username and uid are combined).

**Comment by roweryan** [comment]
Rockstor 3.8-8.06

**Comment by roweryan** [comment]
Same on Rockstor 3.8-8.07

**Comment by TheFluffyOne** [comment]
The UI behaviour around groups is definitely a bit strange. It looks like you're parsing the group list into chunks of 15 entries, and then choosing whether to display them in the "Rockstor managed" or "Other system" sections of the screen. Would make more sense to manage the two sections separately.

**Comment by schakrava** [comment]
Thanks guys. We are going to redesign the user/group UI. I'll keep this issue open until then

**Comment by fkurth** [comment]
This seems to be a bug, related to datatables paging. It pages the upper and the lower list of groups simultaneously, leading to a strange behavior, finding the first non-system group on page 2 and so on.

**Comment by MFlyer** [comment]
To @schakrava - This Looney Bean issue has already been resolved by recent @priyaganti PRs

**Comment by MFlyer** [comment]
To be closed @schakrava (see previous message)

**Comment by MFlyer** [comment]
Once again to @schakrava , this is an old one to be closed :)

**Comment by schakrava** [comment]
Thank you @MFlyer, shame on me for not noticing your earlier comment.
