### ISSUE TITLE
Duration in Task history for scheduled scrub makes no sense. - 3.8-8.07

### ISSUE THREAD

**Issue by dragon2611** [rockstor/rockstor-core#968]
Noticed the duration for the task I created for scrubbing the root pool under the duration column shows "3 Minutes ago"

This doesn't make sense give the columns heading, I suspect it means the duration was 3 minutes, which would make sense given the pool is pretty much empty (I don't store data on the root pool so it's just the OS/Rockstor itself)

![screenshot from 2015-10-19 15 51 26](https://cloud.githubusercontent.com/assets/6185399/10581222/79df585e-7679-11e5-8c6c-66821a07c3dd.png)

**Comment by dragon2611** [comment]
Ah What I had failed to spot at the time is the End time is 3 minutes before the Start Time, which probably explains the strange value for duration, are start time/end time the right way round or is there some other process that also happens at 3am (e.g ntp sync)

**Comment by priyaganti** [comment]
Duration column from the Task History table has been removed in on of the previous releases. So, the problem doesn't exist anymore.
