### ISSUE TITLE
Kelnel panic during Owncloud installation

### ISSUE THREAD

**Issue by romanshein** [rockstor/rockstor-core#969]
I've tried to install Owncloud. I set an existing share as a destination for Owncloud & Rockon files. The pool & share was created with Rockstore. It looks like during installation process the installer tries to chown the files, which causes the panic.
I believe the panic is due to btrfs itself, not Rockstor, but I leave it here for your consideration:

[1674.219316] general protection fault: 0000 [#1] SMP
[ 1674.220013] Modules linked in: veth xt_conntrack ipt.MASQUERADE nf_nat_masquerade_ipv4 iptable_nat nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ v4 xt.addrtype iptable_filter ip_tables nf_nat nf_conntrack ext4 mbcache jbd2 input.leds serio.rau pcspkr hyperv_keyboard 8250_fintek hv.utilï v_balloon joydev i2c_piix4 acpi_cpufreq hyperv.fb dm_mirror dm_region_hash dm_log dm.mod uinput btrfs xor raid6_pq sd_mod sr_mod cdrom hv.net' hid.hyperv hv.storvsc ata_generic pata_acpi floppy atajpiix hv.vmbus libata [ 1674.220013] CPU: 0 PID: 447 Comm: kworker/ul28:2 Not tainted 4.2.2-1.el?.elrepo.x86_64 #1 [ 1674.220013] Hardware name: Microsoft Corporation Uirtual Machine/Uirtual Machine, BI0S 090006	05/23/2012
[ 1674.220013] Workqueue: btrfs-qgroup-rescan btrfs_qgroup_rescan_helper [btrfs]
[ 1674.220013] task: ffff880036c9dl40 ti: ffff88003732c000 task.ti: ffff88003732c000 [ 1674.220013] RIP: 0010:Uffffffff81323bc2>]	[<ffffffff81323bc2>] _memcpy+0x12/0x20
[ 1674.220013] RSP: 0018:ffff88003732fc90 EFLAGS: 00010202
[	1674.220013]	RAX:	ffff88003732fd3f	RBX:	0000000000000009	RCX:	0000000000000001
[	1674.220013]	RDX:	0000000000000001	RSI:	0005080000000000	RDI:	ffff88003732fd3f
[	1674.220013]	RBP:	ffff88003732fcd8	R08:	0000000000019ba0	R09:	ffff88003d619ba0
[	1674.220013]	R10:	ffffea0000ade2c0	Rll:	0200000000000008	R12:	ffff880016dc7ac0
[	1674.220013]	R13:	0000160000000000	R14:	ffff88003732fd48	R15:	0000000000000009
[ 1674.220013] FS:	00007fa288206840(0000) GS:ffff88003d600000(0000) knlGS:0000000000000000
[ 1674.220013] CS:	0010 DS: 0000 ES: 0000 CR0: 000000008005003b
[ 1674.220013] CR2: 00007fa28821e000 CR3: 0000000039d65000 CR4: 00000000000006f0 [ 1674.220013] Stack:
[ 1674.220013] ffffffffa01cab48 ffff88003732fcd8 00000000d64e4el4 ffff88003732fd28 [ 1674.220013]	000000000000028b 0000000000000000 0000000000000001 ffff880016dc7a00
[ 1674.220013]	0000160000000000 ffff88003732fd98 ffffffffa020f808 ffff88003baa8df0
[ 1674.220013] Call Trace:
[ 1674.220013] [<ffffffffa01cab48>] ? read_extent_buffer+0xb8/0xll0 [btrfs]
[ 1674.220013] [<ffffffffa020f808>] btrfs_qgroup_rescan_worker+0x2a8/0x5f0 [btrfs]
[ 1674.220013] [<ffffffffa01d8290>] normal.work.helper+0xc0/0x250 [btrfs]
[ 1674.220013] [<ffffffffa01d8632>] btrfs_qgroup_rescan_he1per+0x12/0x20 [btrfs]
[ 1674.220013] [<ffffffff81091d2c>] process_one_work+0xl4c/0x3c0 [ 1674.220013] [<ffffffff810923d4>] worker_thread+0x114/0x470 [ 1674.220013] [<ffffffff810922c0>] ? rescuer.thread+0x320/0x320 [ 1674.220013] [<ffffffff81097d08>] kthread+0xd8/0xf0
[ 1674.220013] [<ffffffff81097c30>] ? kthread_create_on_node+0xlb0/0xlb0 [ 1674.220013] [<ffffffff816ce05f>] ret_from_fork+0x3f/0x?0 [ 1674.220013] [<ffffffff81097c30>] ? kthread_create_on_node+0xlb0/0xlb0
[ 1674.220013] Code: 4e 48 83 c4 08 5b 5d c3 e8 9c fc ff ff eb e? 90 90 90 90 90 90 90 90 90 90 0f lf 44 00 00 48 89 f8 48 89 dl 48 cl e9 03 { e2 07 <f3> 48 a5 89 dl f3 a4 c3 66 0f lf 44 00 00 48 89 f8 48 89 dl f3 [ 1674.220013] RIP [<ffffffff81323bc2>] _memcpy+0x12/0x20 [ 1674.220013] RSP <ffff88003732fc90>
[ 1674.291955] ---[ end trace 75673fd5a0bc8532 ]---
[ 1674.293518] Kernel panic - not syncing: Fatal exception [ 1674.2948221 Kernel Offset: disabled
[ 1674.2948221 ---[ end Kernel panic - not syncing: Fatal exception
[ 1760.1665541 hrtimer: interrupt took 4629795 ns

**Comment by schakrava** [comment]
Could you please try on the latest release(3.8-11) and reopen this issue if you are able to reproduce the issue? I've installed owncloud Rock-on on a few Rockstor instances here and haven't been able to reproduce it.
