### ISSUE TITLE
Postfix SMTP sender address

### ISSUE THREAD

**Issue by maxhq** [rockstor/rockstor-core#970]
**Problem**
When mail is sent by Rockstor (or manually using `echo "test" | mail root`), my ISP complains:

> invalid DNS MX or A/AAAA resource record (in reply to MAIL FROM command)

...because Rockstor's Postfix sends the following header with a local domain:

> MAIL FROM:<root@Rockstor.localdomain>

**Solution**
This can be prevented by (see http://www.postfix.org/ADDRESS_REWRITING_README.html#generic):

1. adding this to /etc/postfix/generic:
> root mysender@myisp.com

2. running `postmap generic`
3. adding this to /etc/postfix/main.cf:
> smtp_generic_maps = hash:/etc/postfix/generic

4. running `postfix reload`

I guess it's not too hard to include these steps in the mail configuration script.

**Comment by phillxnet** [comment]
@maxhq Thanks for this excellent advise. The email feature is a recent one and I also think it would definitely benefit from this.
In a configuration of my own https://github.com/phillxnet/ubuntu-home-server-postfix-installer-with-ssl-relayhost/blob/master/ubuntu-home-server-postfix-installer-with-ssl-relayhost I have the following in /etc/postfix/generic:-
where the rockstor system is named "rockstor.lan"
and the address of the dedicated sending account is rockstor@fastmail.co.uk
(as in the rockstor online docs)

@rockstor rockstor@fastmail.co.uk
@rockstor.lan rockstor@fastmail.co.uk

That way not only roots emails will be re mapped.

Does that look like a reasonable idea to you? In which case I'd be happy to have a crack at it as the email notification feature is quite important for notifications and failure alerts and the like so we don't want it rejected for having an invalid domain name.

**Comment by maxhq** [comment]
@phillxnet Your version is even better - thank you!

**Comment by phillxnet** [comment]
@maxhq Thanks, hopefully I can make it work. I am currently working on a pull request for this issue.
