### ISSUE TITLE
Kernel freeze/hangup with kernel => 3.3

### ISSUE THREAD

**Issue by Termitebug** [rockstor/rockstor-core#977]
Hi, I have Acer M3201 running Rockstor. Usually I can't start my system automaticly as it will hang or freeze to kernel initialization. By so far get black screen and this followup:
<code>ata3: softreset failed (device not ready) k10temp: 0000:00:18.3: unreliable CPU thermal sensor; monitoring disabled.</code>
Then nothing happens.
However, I can get my system up by choosing very old kernel vesion with debugging enabled.
What should I do?

**Comment by schakrava** [comment]
@Termitebug I am afraid this is outside the scope of Rockstor code. If you are still having the problem, I suggest you head over to our forum(http://forum.rockstor.com) and create a post. Other community members with same hardware may be able to help you.
