### ISSUE TITLE
Send test email reports success even if failed.

### ISSUE THREAD

**Issue by dragon2611** [rockstor/rockstor-core#978]
It seems you will get the "Test e-mail sent successfully" dialogue in the web interface even if actually authentication to the SMTP relay failed completely.

The send test email function actually needs to validate the email was infact delivered successfully rather than just handing off to postfix and reporting success.

**Comment by schakrava** [comment]
Thanks for reporting this @dragon2611. Do you know how to validate if the email was actually delivered?

**Comment by dragon2611** [comment]
Possibly parse the logs to confirm it was accepted by the remote server?

Sent from Outlook Mobile<https://aka.ms/blhgte>



On Fri, Dec 11, 2015 at 7:14 PM -0800, "Suman Chakravartula" <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for reporting this @dragon2611<https://github.com/dragon2611>. Do you know how to validate if the email was actually delivered?

-

**Comment by victoriasavi** [comment]
I had the same issue. I suggest looking into the log to find out what went wrong.

` tail -f /var/log/maillog `

For my case I made a new issue: #1083
