### ISSUE TITLE
Suggetion: Warning when deleting Shares (subvoulmes)

### ISSUE THREAD

**Issue by pecigonzalo** [rockstor/rockstor-core#979]
I would like to suggest adding a warning similar to the one GitHub does when deleting subvolumes.
A prompt explaining whats going to happen and a confirmation that you had read ( put the share name here or something)
This operation can lead to losing a lot of data and i dont think its shown enough.
Same concept could be applied to pools.

Cheers

**Comment by schakrava** [comment]
Fixed by #1149
