### ISSUE TITLE
Improve UX for 'Delete all' feature of snapshots

### ISSUE THREAD

**Issue by vinima** [rockstor/rockstor-core#988]
There are some inconsistencies with the 'delete all' feature for snapshots.

1.  The button needs to be called 'Delete all Snapshots' or something similar instead of 'Delete'
2.  If snapshots are accessed from the "Share" screen, the 'Delete' (or rather delete all) button is on top right (along with Rollback and Clone buttons) and bottom right. However, the bottom right is not visible unless the screen is scrolled.  

![image](https://cloud.githubusercontent.com/assets/13106797/10806541/6fba8134-7d93-11e5-8f84-586a7d3b7bd6.png)

![image](https://cloud.githubusercontent.com/assets/13106797/10806663/81cd3730-7d94-11e5-903d-0b4cca24a919.png)

3.  If snapshots are accessed from 'Snapshot' screen, the 'Delete' (or rather delete all) button does not appear on top right of the screen with 'Create' and 'Schedule' buttons, but rather appears on the bottom left of the screen that is not visible until the screen is horizontally scrolled.  The buttons should be consistent, whether snapshots are accessed from Shares or Snapshots screen.  To add to it, 'Clone' and 'Rollback' buttons should also be part of Snapshot screen.

![image](https://cloud.githubusercontent.com/assets/13106797/10806633/36d45524-7d94-11e5-91f2-001f94c624df.png)

![image](https://cloud.githubusercontent.com/assets/13106797/10806671/982b1808-7d94-11e5-8943-e170901d36cb.png)

**Comment by schakrava** [comment]
Fixed by #1154
