### ISSUE TITLE
RFE: Use PatternFly for WebUI 

### ISSUE THREAD

**Issue by duncaninnes** [rockstor/rockstor-core#990]
From the Forums: http://forum.rockstor.com/t/consider-patternfly-interface/183

Several Open Source projects now adopting the PatternFly interface to one extent or another:

Cockpit: http://cockpit-project.org/
Spacewalk: https://fedorahosted.org/spacewalk/
FreeIPA: http://www.freeipa.org
oVirt: http://www.ovirt.org

The end result is a polished UI which uses a unified approach across the board.

**Comment by Hooverdan96** [comment]
Considering that we had discussions around whether the UI needs to be completely changed vs. renovated (reduce reliance on JS libraries, htmx, etcpp.) I propose that we close this, as I don't at this time a complete framework change is not considered.
