### ISSUE TITLE
Uptime on the web UI seems to be glitched in 3.8-9

### ISSUE THREAD

**Issue by haoto** [rockstor/rockstor-core#995]
I've just installed Rockstor 3.8-9 less than 24 hours ago, and the uptime is already 1 day, 21:36 on the web UI. In comparison, uptime in the command line is 20:36.

(Edit: put in the time instead of uptime :Q)

**Comment by phillxnet** [comment]
@haoto  Thanks for reporting. Nice find.

**Comment by schakrava** [comment]
This has been fixed recently in [https://github.com/rockstor/rockstor-core/commit/7a3b6571637797fc4af3bc08352856100639c8f0](url)
