### ISSUE TITLE
Not possible to schedule 30 min snapshots by the minute

### ISSUE THREAD

**Issue by vinima** [rockstor/rockstor-core#999]
30 min snapshots are only taken at 0 and 30 mins past the hour.  It is not possible to schedule it at any other time. The ability to schedule by minute appears for hourly snapshot and would be useful for 30 min snapshots also. 

![image](https://cloud.githubusercontent.com/assets/13106797/10953239/ed3a7976-82fb-11e5-9be1-9fe11fcaab2b.png)

![image](https://cloud.githubusercontent.com/assets/13106797/10953266/05f09004-82fc-11e5-9f79-b3ab3271563f.png)

**Comment by MFlyer** [comment]
@schakrava to be closed (my opinion) considering new extended tasks

Flyer

**Comment by schakrava** [comment]
You are right @MFlyer , thanks for your comment.
